## Análise Exploratória dos Dados Brutos

## Hemoprod Alagoas

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
import pandas as pd
import os
import numpy as np

# --- 1. Defina os caminhos para seus arquivos ---
# Ajuste os caminhos conforme a estrutura do seu projeto no notebook
dados_brutos_path = 'dados_brutos'
dicionario_path = 'dicionario_colunas_269.xlsx'
arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_AL.xlsx')
nome_planilha = 'HEMOPROD - ALAGOAS'

# --- 2. Carregue os dados e o dicionário ---
try:
    # Carrega o arquivo de dados
    hemoprod_al = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)
    print("Arquivo de dados carregado com sucesso.")
    print(f"Número de colunas original: {len(hemoprod_al.columns)}")

    # Carrega o arquivo de dicionário
    dicionario = pd.read_excel(dicionario_path)
    print("Arquivo de dicionário carregado com sucesso.")

    # --- 3. Limpeza Inicial dos Nomes das Colunas (ADICIONADO) ---
    # Mapeia as colunas, limpando espaços em branco no início e fim
    # e substituindo o caractere \xa0 (Non-breaking space) por um espaço normal.
    mapa_limpeza = {
        col: col.strip().replace('\xa0', ' ') 
        for col in hemoprod_al.columns
    }

    # Aplica a renomeação para limpar os nomes
    hemoprod_al = hemoprod_al.rename(columns=mapa_limpeza)
    print("Nomes das colunas do DataFrame limpos e padronizados (strip/\\xa0).")

    # --- 4. Crie o dicionário de mapeamento ---
    # Cria um dicionário no formato {'nome_original': 'nome_sql'} para uso no .rename()
    # NOTA: O 'nome_original' no dicionário TAMBÉM deve estar limpo para combinar.
    # Se o dicionário não estiver limpo, adicione a mesma limpeza aqui:
    dicionario['nome_original'] = dicionario['nome_original'].astype(str).str.strip().str.replace('\xa0', ' ')
    
    mapa_renomeacao = pd.Series(dicionario['nome_sql'].values, index=dicionario['nome_original']).to_dict()
    
    # Lista dos nomes de coluna no DataFrame atual APÓS a limpeza inicial
    colunas_atuais = set(hemoprod_al.columns)
    
    # Lista dos nomes originais de coluna no dicionário APÓS a limpeza (se aplicada)
    colunas_originais_dicionario = set(dicionario['nome_original'].tolist())
    
    # Lista dos nomes SQL (os desejados) no dicionário
    colunas_sql_desejadas = set(dicionario['nome_sql'].tolist())
    
    # --- 5. Renomeie as colunas com base no mapeamento (nome_original -> nome_sql) ---
    print("\n--- Processo de Renomeação ---")
    hemoprod_al.rename(columns=mapa_renomeacao, inplace=True)
    print("Colunas renomeadas com sucesso (apenas as que existiam no dicionário foram modificadas).")


   # --- 4. Inferir Tipos e Criar Mapeamento de Tipos ---
    
    # --- Lógica de Inferência customizada para 'Int64' ---
    tipos_inferidos = {}
    for col in hemoprod_al.columns:
        
        # 4.1. Tenta converter a coluna para o tipo que melhor representa seus dados (incluindo Int64/string/datetime)
        # O errors='ignore' é crucial para não falhar se a coluna não puder ser convertida
        coluna_convertida = pd.to_numeric(hemoprod_al[col], errors='coerce')
        
        # Se a conversão for bem-sucedida (não é totalmente NaN, nem totalmente string)
        if not coluna_convertida.isna().all() and coluna_convertida.dtype.kind in 'fi': # 'f' para float, 'i' para int
            
            # Se a coluna parecer um número, tentamos forçar para Int64
            # O .astype('Int64') usa o tipo inteiro que suporta NaN
            try:
                # Se for possível converter para Int64, use 'Int64'
                hemoprod_al[col] = hemoprod_al[col].astype('Int64')
                tipos_inferidos[col] = 'Int64'
            except Exception:
                # Se for numérico mas não puder ser Int64 (ex: float com muitas casas decimais), use 'float64'
                tipos_inferidos[col] = 'float64'
        
        # Verifica se é data/hora
        elif pd.api.types.is_datetime64_any_dtype(hemoprod_al[col]):
             tipos_inferidos[col] = 'datetime64[ns]'
             
        # Caso contrário, assume-se que é um texto/string
        else:
            tipos_inferidos[col] = 'object' # O padrão para string no pandas

    
    print("\nTipos de dados inferidos (amostra):")
    for i, (col, dtype) in enumerate(tipos_inferidos.items()):
        if i < 5:
            print(f"  {col}: {dtype}")
        if i == 5:
            print("  ...")
    
    # --- 5. Atualizar o DataFrame Dicionário ---
    
    # 5.1. Cria a coluna 'tipo_dados' no dicionário e preenche com os tipos inferidos
    dicionario['tipo_dados'] = dicionario['nome_sql'].map(tipos_inferidos)
    
    # 5.2. Trata colunas não encontradas no DataFrame de dados
    dicionario['tipo_dados'] = dicionario['tipo_dados'].fillna('object')
    
    print("\n--- Dicionário Atualizado ---")
    print("Coluna 'tipo_dados' criada com sucesso, com numéricos definidos como 'Int64' ou 'float64'.")
    
    # --- 6. Salvar o Dicionário Atualizado ---

    # Sugestão de novo caminho para salvar
    novo_dicionario_path = 'dicionario_colunas_269_COM_TIPOS_V2.xlsx'
    
    dicionario.to_excel(novo_dicionario_path, index=False)
    
    print(f"\n✅ Dicionário salvo com a nova coluna 'tipo_dados' em: {novo_dicionario_path}")
    print("\nPrimeiras linhas do dicionário atualizado:")
    display(dicionario.head())

    # --- 6. Análise de Colunas (Qualidade dos Dados) ---

    # 6.1. Colunas que não puderam ser renomeadas (existem no DF, mas não no 'nome_original' do dicionário)
    # Aqui usamos as colunas atuais ANTES da renomeação para ver o que sobrou.
    colunas_nao_mapeadas = [
        col for col in colunas_atuais 
        if col not in colunas_originais_dicionario
    ]

    print("-" * 30)
    print("Análise de Colunas do DataFrame (hemoprod_al):")
    print(f"Número de colunas não mapeadas: {len(colunas_nao_mapeadas)}")
    print(f"Colunas não mapeadas (manterão nome original): {colunas_nao_mapeadas}")
    
    # 6.2. Análise de Colunas Faltantes/A Mais (Comparação com 'nome_sql' desejado)
    colunas_apos_renomeacao = set(hemoprod_al.columns)
    
    colunas_faltantes = list(colunas_sql_desejadas - colunas_apos_renomeacao)
    colunas_a_mais = list(colunas_apos_renomeacao - colunas_sql_desejadas)

    print("-" * 30)
    print("Análise de Colunas (Comparação com a lista SQL DESEJADA):")
    print(f"Número de colunas FALTANTES: {len(colunas_faltantes)}")
    print(f"Colunas FALTANTES (deveriam estar, mas não estão): {colunas_faltantes}")
    print("-" * 30)
    print(f"Número de colunas A MAIS: {len(colunas_a_mais)}")
    print(f"Colunas A MAIS (estão no DF, mas não na lista SQL desejada): {colunas_a_mais}")
    print("-" * 30)

    # --- 7. Verifique o resultado ---
    print("\nInformações do DataFrame com as novas colunas:")
    hemoprod_al.info()
    
    print("\nAs 5 primeiras linhas com as novas colunas:")
    display(hemoprod_al.head())

except FileNotFoundError as e:
    print(f"\nErro de arquivo não encontrado: {e}")
except KeyError as e:
    print(f"\nErro de coluna não encontrada: {e}. Verifique se as colunas 'nome_original' e 'nome_sql' existem no seu arquivo de dicionário.")
except Exception as e:
    print(f"\nOcorreu um erro inesperado: {e}")

Arquivo de dados carregado com sucesso.
Número de colunas original: 269
Arquivo de dicionário carregado com sucesso.
Nomes das colunas do DataFrame limpos e padronizados (strip/\xa0).

--- Processo de Renomeação ---
Colunas renomeadas com sucesso (apenas as que existiam no dicionário foram modificadas).

Tipos de dados inferidos (amostra):
  id: Int64
  data_envio: object
  ultima_pagina: Int64
  idioma_inicial: object
  semente: Int64
  ...

--- Dicionário Atualizado ---
Coluna 'tipo_dados' criada com sucesso, com numéricos definidos como 'Int64' ou 'float64'.

✅ Dicionário salvo com a nova coluna 'tipo_dados' em: dicionario_colunas_269_COM_TIPOS_V2.xlsx

Primeiras linhas do dicionário atualizado:

,nome_original,nome_sql,comentario,tipo_dados
0,ID da resposta,id,Identificador único e chave primária da submis...,Int64
1,Data de envio,data_envio,Data e hora exatas do envio final do formulário.,object
2,Última página,ultima_pagina,Título da última página do formulário acessada...,Int64
3,Idioma inicial,idioma_inicial,Idioma selecionado no início do preenchimento ...,object
4,Semente,semente,Valor interno de semente/aleatorização (uso té...,Int64

------------------------------
Análise de Colunas do DataFrame (hemoprod_al):
Número de colunas não mapeadas: 0
Colunas não mapeadas (manterão nome original): []
------------------------------
Análise de Colunas (Comparação com a lista SQL DESEJADA):
Número de colunas FALTANTES: 0
Colunas FALTANTES (deveriam estar, mas não estão): []
------------------------------
Número de colunas A MAIS: 0
Colunas A MAIS (estão no DF, mas não na lista SQL desejada): []
------------------------------

Informações do DataFrame com as novas colunas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315 entries, 0 to 314
Columns: 269 entries, id to hemoprod_3_observacoes
dtypes: Int64(235), float64(16), object(18)
memory usage: 734.4+ KB

As 5 primeiras linhas com as novas colunas:

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,21,2024-07-03 09:12:00,4,pt-BR,<NA>,mC2pcyfb6aHYhhG,2024-07-03 09:00:00,2024-07-03 09:12:00,186.249.59.158,NaN,ORIGINAL,2024,Junho,NaN,"Delmiro Gouveia, Alagoas",Secretaria de Estado da Saúde - Hospital Regio...,Hospital Regional do Alto Sertão - HRAS,12200259000165,Agência Transfusional,Público,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,10,0,7,0,1,0,21,0,1,0,0,0,0,0,0,0,40,0,40,0,0,0,40,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,17,17,0,0,0,0,47,47,0,0,0,0,16,16,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,47,47,0,0,0,0,16,16,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,NaN
1,22,2024-07-03 18:36:00,4,pt-BR,<NA>,FPAwxbAGdnaP0uv,2024-07-03 18:21:00,2024-07-03 18:36:00,186.249.60.28,NaN,ORIGINAL,2024,Junho,NaN,"Maceió, Alagoas",Secretaria de Estado da Saúde - Hospital Metro...,HOSPITAL METROPOLITANO DE ALAGOAS,12200259000165,Agência Transfusional,Público,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,28,0,3,0,2,0,47,0,7,0,1,0,0,0,6,0,14,0,2,0,0,0,16,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,5,0,0,0,0,0,6,0,0,83,0,0,0,0,0,0,0,0,46,0,0,0,0,0,5,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,4,0,4,4,0,1,1,0,117,117,0,60,60,0,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,<NA>,<NA>,NaN
2,26,2024-07-05 18:21:55,4,pt-BR,5371664,VwcXLtA5rfFIUi9,2024-07-05 17:19:26,2024-07-05 18:21:55,206.42.47.96,NaN,ORIGINAL,2024,Junho,NaN,"Maceió, Alagoas",Banco de Sangue Oswaldo Calado - Hemopac,NaN,12181996000168,Unidade de Coleta e Transfusão,Privado-SUS,Rede de serviços,Agência Transfusional Unimed do Banco de Sangu...,NaN,NaN,88,19,163,37,0,0,131,41,52,5,68,10,180,19,71,37,0,0,55,24,196,32,1,28,29,2,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16,8,24,0,0,0,2,249,0,NaN,249.0,0,249.0,0,249.0,3,249.0,0,249.0,3,249.0,0,249.0,1,249.0,0,249.0,0,249.0,0,249.0,0,85,86,29,23,4,11,90,100,17,4,5,3,0,1,19,17,41,0,0,1,37,0,0,3,249.0,249,6,0,NaN,0,0,0,237,0,0,12,0,0,249,32,71,0,0,0,228,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,5,1,209,0,0,12,0,0,11,0,0,0,0,83,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,37,37,0,0,0,14,249,263,0,0,0,0,71,71,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,15,0,15,0,0,0,73,0,73,0,0,0,71,0,71,0,0,0,0,0,0,0,0,0,0,0,0,0,0,31,126,41,0,0,0,0,0,0,0,0,0,NaN
3,28,2024-07-07 18:21:00,4,pt-BR,<NA>,7qTz7fGLGpNNxUf,2024-07-07 17:40:00,2024-07-07 18:21:00,190.102.52.160,NaN,ORIGINAL,2024,Junho,NaN,"Arapiraca, Alagoas",Secretaria de Estado da Saúde - Unidade Emergê...,NaN,12200259000408,Agência Transfusional,Público,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,33,0,13,0,3,0,70,0,2,0,3,0,0,0,3,0,6,0,0,0,0,0,1,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,28,0,0,0,0,0,6,0,0,130,0,0,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,14,0,0,0,0,14,14,0,179,179,0,17,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,NaN
4,29,2024-07-07 18:39:39,4,pt-BR,1067738071,XpuFs3JEYKeGWPJ,2024-07-07 18:27:15,2024-07-07 18:39:39,190.102.52.160,NaN,ORIGINAL,2024,Junho,NaN,"Arapiraca, Alagoas",Centro Hospitalar Manoel André - Chama,NaN,471021000124,Agência Transfusional,Privado-SUS,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,68,0,20,0,3,0,82,0,2,0,0,0,0,0,26,0,29,0,6,0,29,1,5,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,6,0,0,0,0,0,20,0,0,203,0,0,65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3,0,0,0,0,1,5,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,7,0,0,0,0,14,14,0,204,204,0,65,65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,0,0,0,0,0,0,0,<NA>,<NA>,NaN

In [3]:
# ASSUME QUE AS VARIÁVEIS 'hemoprod_al', 'dicionario', 'colunas_a_mais', 
# 'colunas_faltantes' E 'colunas_sql_desejadas' EXISTEM DA CÉLULA ANTERIOR.

print("--- 6. PADRONIZAÇÃO DO ESQUEMA (Remoção, Adição e Reordenação) ---")

# 6.1. REMOVE as Colunas a Mais
if colunas_a_mais:
    # Verificação de segurança: Só tenta dropar colunas que estão realmente no DF
    colunas_para_dropar = [col for col in colunas_a_mais if col in hemoprod_al.columns]
    hemoprod_al.drop(columns=colunas_para_dropar, inplace=True)
    print(f"✅ {len(colunas_para_dropar)} colunas a mais removidas.")
else:
    print("Nenhuma coluna a mais para remover.")

# 6.2. ADICIONA as Colunas Faltantes
if colunas_faltantes:
    
    # Prepara o sub-dicionário apenas com as colunas faltantes (para tipos)
    dicionario_faltante = dicionario[dicionario['nome_sql'].isin(colunas_faltantes)]
    
    for col_sql in colunas_faltantes:
        
        # Adiciona a coluna com valor nulo (NaN)
        hemoprod_al[col_sql] = np.nan 

        # --- Lógica Opcional de Conversão de Tipo (Baseada na coluna 'tipo_dados' no dicionário) ---
        # Tenta encontrar o tipo no dicionário (apenas se a coluna 'tipo_dados' existir e não estiver vazia)
        if 'tipo_dados' in dicionario.columns:
            tipo_desejado_row = dicionario_faltante[dicionario_faltante['nome_sql'] == col_sql]
            
            if not tipo_desejado_row.empty:
                tipo_desejado = tipo_desejado_row['tipo_dados'].iloc[0].lower()

                # Converte para o tipo, se for reconhecido
                if 'int' in tipo_desejado or 'float' in tipo_desejado:
                    # Usa 'float64' para números que podem ter NaNs, para evitar erros de Pandas
                    hemoprod_al[col_sql] = hemoprod_al[col_sql].astype('float64') 
                elif 'string' in tipo_desejado or 'object' in tipo_desejado:
                    # Converte para 'object' (string)
                    hemoprod_al[col_sql] = hemoprod_al[col_sql].astype('object')
                 
    print(f"✅ {len(colunas_faltantes)} colunas faltantes adicionadas e preenchidas com NaN.")
else:
    print("Nenhuma coluna faltante para adicionar.")


# 6.3. Reordena as colunas (Para garantir a ordem padronizada do dicionário)
colunas_finais = dicionario['nome_sql'].tolist()
# Garante que só as colunas que realmente existem no DF (após drop/adição) sejam usadas na reordenação
colunas_finais_presentes = [col for col in colunas_finais if col in hemoprod_al.columns]

# Esta é a linha que reordena o DataFrame
hemoprod_al = hemoprod_al[colunas_finais_presentes]
print("✅ Colunas reordenadas para seguir a ordem do dicionário.")


# --- 7. Verifique o resultado Final ---
print("\n--- Resultado Final ---")
print(f"Número de colunas final: {len(hemoprod_al.columns)}")
print("Informações do DataFrame padronizado:")
hemoprod_al.info()

print("\nAs 5 primeiras linhas com as colunas padronizadas:")
display(hemoprod_al.head())

--- 6. PADRONIZAÇÃO DO ESQUEMA (Remoção, Adição e Reordenação) ---
Nenhuma coluna a mais para remover.
Nenhuma coluna faltante para adicionar.
✅ Colunas reordenadas para seguir a ordem do dicionário.

--- Resultado Final ---
Número de colunas final: 269
Informações do DataFrame padronizado:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315 entries, 0 to 314
Columns: 269 entries, id to hemoprod_3_observacoes
dtypes: Int64(235), float64(16), object(18)
memory usage: 734.4+ KB

As 5 primeiras linhas com as colunas padronizadas:

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,21,2024-07-03 09:12:00,4,pt-BR,<NA>,mC2pcyfb6aHYhhG,2024-07-03 09:00:00,2024-07-03 09:12:00,186.249.59.158,NaN,ORIGINAL,2024,Junho,NaN,"Delmiro Gouveia, Alagoas",Secretaria de Estado da Saúde - Hospital Regio...,Hospital Regional do Alto Sertão - HRAS,12200259000165,Agência Transfusional,Público,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,10,0,7,0,1,0,21,0,1,0,0,0,0,0,0,0,40,0,40,0,0,0,40,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,17,17,0,0,0,0,47,47,0,0,0,0,16,16,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,47,47,0,0,0,0,16,16,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,NaN
1,22,2024-07-03 18:36:00,4,pt-BR,<NA>,FPAwxbAGdnaP0uv,2024-07-03 18:21:00,2024-07-03 18:36:00,186.249.60.28,NaN,ORIGINAL,2024,Junho,NaN,"Maceió, Alagoas",Secretaria de Estado da Saúde - Hospital Metro...,HOSPITAL METROPOLITANO DE ALAGOAS,12200259000165,Agência Transfusional,Público,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,28,0,3,0,2,0,47,0,7,0,1,0,0,0,6,0,14,0,2,0,0,0,16,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,5,0,0,0,0,0,6,0,0,83,0,0,0,0,0,0,0,0,46,0,0,0,0,0,5,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,4,0,4,4,0,1,1,0,117,117,0,60,60,0,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,<NA>,<NA>,NaN
2,26,2024-07-05 18:21:55,4,pt-BR,5371664,VwcXLtA5rfFIUi9,2024-07-05 17:19:26,2024-07-05 18:21:55,206.42.47.96,NaN,ORIGINAL,2024,Junho,NaN,"Maceió, Alagoas",Banco de Sangue Oswaldo Calado - Hemopac,NaN,12181996000168,Unidade de Coleta e Transfusão,Privado-SUS,Rede de serviços,Agência Transfusional Unimed do Banco de Sangu...,NaN,NaN,88,19,163,37,0,0,131,41,52,5,68,10,180,19,71,37,0,0,55,24,196,32,1,28,29,2,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16,8,24,0,0,0,2,249,0,NaN,249.0,0,249.0,0,249.0,3,249.0,0,249.0,3,249.0,0,249.0,1,249.0,0,249.0,0,249.0,0,249.0,0,85,86,29,23,4,11,90,100,17,4,5,3,0,1,19,17,41,0,0,1,37,0,0,3,249.0,249,6,0,NaN,0,0,0,237,0,0,12,0,0,249,32,71,0,0,0,228,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,5,1,209,0,0,12,0,0,11,0,0,0,0,83,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,37,37,0,0,0,14,249,263,0,0,0,0,71,71,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,15,0,15,0,0,0,73,0,73,0,0,0,71,0,71,0,0,0,0,0,0,0,0,0,0,0,0,0,0,31,126,41,0,0,0,0,0,0,0,0,0,NaN
3,28,2024-07-07 18:21:00,4,pt-BR,<NA>,7qTz7fGLGpNNxUf,2024-07-07 17:40:00,2024-07-07 18:21:00,190.102.52.160,NaN,ORIGINAL,2024,Junho,NaN,"Arapiraca, Alagoas",Secretaria de Estado da Saúde - Unidade Emergê...,NaN,12200259000408,Agência Transfusional,Público,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,33,0,13,0,3,0,70,0,2,0,3,0,0,0,3,0,6,0,0,0,0,0,1,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,28,0,0,0,0,0,6,0,0,130,0,0,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,14,0,0,0,0,14,14,0,179,179,0,17,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,NaN
4,29,2024-07-07 18:39:39,4,pt-BR,1067738071,XpuFs3JEYKeGWPJ,2024-07-07 18:27:15,2024-07-07 18:39:39,190.102.52.160,NaN,ORIGINAL,2024,Junho,NaN,"Arapiraca, Alagoas",Centro Hospitalar Manoel André - Chama,NaN,471021000124,Agência Transfusional,Privado-SUS,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,68,0,20,0,3,0,82,0,2,0,0,0,0,0,26,0,29,0,6,0,29,1,5,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,6,0,0,0,0,0,20,0,0,203,0,0,65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3,0,0,0,0,1,5,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,7,0,0,0,0,14,14,0,204,204,0,65,65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,0,0,0,0,0,0,0,<NA>,<NA>,NaN

In [4]:
# --- 2. Defina as colunas para a chave e para ordenação ---
registros_antes = len(hemoprod_al)
print(f"Total de registros ANTES da remoção de duplicatas: {registros_antes}")
    

colunas_chave = [
        'cnpj', 
        'ano_referencia', 
        'periodo_referencia', 
        'razao_social_nome_fantasia'
    ]

coluna_data = 'data_envio'

# --- 3. Verifique se as colunas necessárias existem ---
colunas_necessarias = colunas_chave + [coluna_data]

if not all(col in hemoprod_al.columns for col in colunas_necessarias):
    print("\n--- ERRO ---")
    print("Uma ou mais colunas necessárias para a deduplicação não foram encontradas.")
    colunas_faltantes = [col for col in colunas_necessarias if col not in hemoprod_al.columns]
    print(f"Colunas necessárias: {colunas_necessarias}")
    print(f"Colunas faltantes no DataFrame: {colunas_faltantes}")
else:
    # --- 4. Prepare a coluna de data e ordene os dados ---
    # Converte a coluna 'data_envio' para datetime para garantir a ordenação correta.
    # 'errors='coerce'' transformará datas inválidas em NaT (Not a Time), que são tratadas como nulas.
    hemoprod_al[coluna_data] = pd.to_datetime(hemoprod_al[coluna_data], errors='coerce')

    # Ordena o DataFrame. Os registros com data de envio mais recente ficarão por último.
    print(f"\nOrdenando os dados por '{coluna_data}'...")
    hemoprod_al_ordenado = hemoprod_al.sort_values(by=coluna_data, ascending=True)

    # --- 5. Identifique e separe os registros duplicados e únicos ---
    # Em vez de usar drop_duplicates() diretamente, vamos usar duplicated()
    # para criar uma máscara booleana.
    # 'keep='last'' marca todas as ocorrências de uma chave como True, EXCETO a última (a mais recente).
    print(f"Identificando duplicatas com base na chave: {colunas_chave}...")
    mascara_duplicatas = hemoprod_al_ordenado.duplicated(subset=colunas_chave, keep='last')

    # O DataFrame de removidos conterá todas as linhas marcadas como True
    hemoprod_removidos = hemoprod_al_ordenado[mascara_duplicatas]
    
    # O DataFrame deduplicado conterá o INVERSO (~) da máscara (linhas marcadas como False)
    hemoprod_al_deduplicado = hemoprod_al_ordenado[~mascara_duplicatas]
    
    # Agora podemos contar os registros diretamente dos novos DataFrames
    registros_depois = len(hemoprod_al_deduplicado)
    registros_removidos = len(hemoprod_removidos) 
    
    # --- 6. Exiba o resultado ---
    print("\n--- Processo Concluído ---")
    print(f"Registros removidos: {registros_removidos}")
    print(f"Total de registros DEPOIS da remoção de duplicatas: {registros_depois}")

    # (Opcional) Exibe a amostra dos removidos
    print("\nAmostra dos dados REMOVIDOS (os mais antigos/duplicados):")
    display(hemoprod_removidos.head(10))

    # Você pode continuar a usar o DataFrame 'hemoprod_al_deduplicado' para suas análises
    print("\nAmostra dos dados únicos (os mais recentes para cada chave):")
    display(hemoprod_al_deduplicado.head(10))
    
    # Agora você tem o DataFrame 'hemoprod_removidos' salvo

Total de registros ANTES da remoção de duplicatas: 315

Ordenando os dados por 'data_envio'...
Identificando duplicatas com base na chave: ['cnpj', 'ano_referencia', 'periodo_referencia', 'razao_social_nome_fantasia']...

--- Processo Concluído ---
Registros removidos: 8
Total de registros DEPOIS da remoção de duplicatas: 307

Amostra dos dados REMOVIDOS (os mais antigos/duplicados):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
159,223,2025-03-13 18:07:11,4,pt-BR,1477628817,fukFXzEvovgFY3v,2025-03-13 17:00:24,2025-03-13 18:07:11,186.249.59.155,NaN,ORIGINAL,2025,Fevereiro,NaN,"Maceió, Alagoas",Hospital Geral do Estado Professor Oswaldo Bra...,NaN,12200259000246,Agência Transfusional,Público,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,63,0,24,0,10,0,124,0,25,0,1,0,2,0,12,0,40,0,3,0,0,0,47,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,43,0,0,0,0,0,155,0,0,230,4,0,0,0,0,2,0,0,0,0,0,0,0,0,59,0,0,0,0,1,0,6,0,0,0,0,4,3,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,20,0,0,0,0,0,187,0,0,89,0,0,0,0,0,2,0,0,0,0,0,0,0,0,53,0,0,0,0,0,0,0,0,0,0,3,3,0,44,44,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,0,0,0,0,0,1,0,<NA>,<NA>,NaN
186,254,2025-05-02 14:53:15,4,pt-BR,414284960,99bt2srUJ7EjuAb,2025-05-02 14:39:35,2025-05-02 14:53:15,201.33.41.54,NaN,ORIGINAL,2024,Abril,NaN,"São Miguel dos Campos, Alagoas",Santa Casa de Misericórdia de São Miguel dos C...,NaN,12737680000,Agência Transfusional,Privado-SUS,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,20,0,4,0,0,0,32,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,0,0,0,0,0,0,80,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,59,59,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,NaN
214,285,2025-06-04 14:30:57,4,pt-BR,1680333359,7ij8hzNGbS9VM6O,2025-06-04 13:59:41,2025-06-04 14:30:57,186.249.59.157,NaN,ORIGINAL,2025,Maio,NaN,"Arapiraca, Alagoas",Secretaria de Estado da Saúde - Hemocentro de ...,NaN,12200259000165,Hemocentro Regional,Público,Único serviço,NaN,NaN,NaN,221,77,1270,383,0,0,598,292,893,168,0,0,969,266,522,194,8,5,510,187,973,268,0,0,0,0,0,19,0,0,32,0,0,0,0,0,9,0,0,1,0,0,0,0,0,0,0,0,1,0,0,398,2,2,1,0,1986,0,NaN,1486.0,2,1486.0,1,1486.0,24,1486.0,5,1486.0,13,1486.0,9,1486.0,7,0.0,0,0.0,0,0.0,0,0.0,0,383,318,140,72,28,19,580,532,54,41,14,4,4,2,84,59,156,3,7,8,22,5,0,3,1486.0,1486,61,0,NaN,83,0,0,571,0,0,0,0,0,89,0,58,383,0,0,135,107,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,88,0,0,11,0,0,0,9,4,78,0,0,25,0,46,72,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,46,30,76,0,0,0,179,51,230,393,193,489,183,57,240,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
229,302,2025-07-02 12:59:32,4,pt-BR,687257106,D86bHnoNVySMI3w,2025-07-02 11:57:27,2025-07-02 12:59:32,189.52.187.82,NaN,ORIGINAL,2025,Junho,NaN,"Maceió, Alagoas",Fundação Hospital da Agroindústria do Açúcar -...,NaN,1229129000159,Unidade de Coleta e Transfusão,Privado-SUS,Único serviço,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0,9,0,3,0,2,0,27,0,0,0,2,0,1,0,0,0,5,0,0,0,0,0,4,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,4,0,38,38,0,30,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,NaN
252,328,2025-08-04 14:37:56,4,pt-BR,305008609,99bt2srUJ7EjuAb,2025-08-04 14:30:23,2025-08-04 14:37:56,190.15.107.82,NaN,ORIGINAL,2025,Julho,NaN,"São Miguel dos Campos, Alagoas",Santa Casa de Misericórdia de São Miguel dos C...,NaN,12737680000,Agência Transfusional,Privado-SUS,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,31,0,10,0,2,0,70,0,4,0,0,0,0,0,4,0,0,0,0,0,0,0,0,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,0,0,0,0,0,0,117,0,0,0,0,0,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,103,103,0,0,0,0,18,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,<NA>,<NA>,NaN
257,335,2025-08-06 08:21:33,4,pt-BR,804427324,D86bHnoNVySMI3w,2025-08-06 07:52:51,2025-08-06 08:21:33,189.52.187.82,NaN,ORIGINAL,2025,Julho,NaN,"Maceió, Alagoas",Fundação Hospital da Agroindústria do Açúcar -...,NaN,1229129000159,Unidade de Coleta e Transfusão,Privado,Único serviço,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0,11,0,1,0,0,0,13,0,0,0,4,0,0,0,2,0,4,0,0,0,0,0,3,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,0,0,31,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,26,26,0,31,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,26,26,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
297,380,2025-10-01 17:06:49,4,pt-BR,1946453061,99bt2srUJ7EjuAb,2025-10-01 16:55:56,2025-10-01 17:06:49,190.15.107.84,NaN,ORIGINAL,2025,Setembro,NaN,"São Miguel dos Campos, Alagoas",Santa Casa de Misericórdia de São Miguel dos C...,NaN,12737680000,Agência Transfusional,Privado-SUS,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,46,0,12,0,1,0,49,0,2,0,0,0,0,0,2,0,0,0,0,0,0,0,0,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,4,0,0,0,0,0,114,0,0,0,0,0,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,4,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,4,0,0,0,0,89,89,0,0,0,0,19,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,0,0,0,0,0,0,1,<NA>,<NA>,NaN

Amostra dos dados únicos (os mais recentes para cada chave):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,21,2024-07-03 09:12:00,4,pt-BR,<NA>,mC2pcyfb6aHYhhG,2024-07-03 09:00:00,2024-07-03 09:12:00,186.249.59.158,NaN,ORIGINAL,2024,Junho,NaN,"Delmiro Gouveia, Alagoas",Secretaria de Estado da Saúde - Hospital Regio...,Hospital Regional do Alto Sertão - HRAS,12200259000165,Agência Transfusional,Público,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,10,0,7,0,1,0,21,0,1,0,0,0,0,0,0,0,40,0,40,0,0,0,40,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,17,17,0,0,0,0,47,47,0,0,0,0,16,16,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,47,47,0,0,0,0,16,16,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,NaN
1,22,2024-07-03 18:36:00,4,pt-BR,<NA>,FPAwxbAGdnaP0uv,2024-07-03 18:21:00,2024-07-03 18:36:00,186.249.60.28,NaN,ORIGINAL,2024,Junho,NaN,"Maceió, Alagoas",Secretaria de Estado da Saúde - Hospital Metro...,HOSPITAL METROPOLITANO DE ALAGOAS,12200259000165,Agência Transfusional,Público,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,28,0,3,0,2,0,47,0,7,0,1,0,0,0,6,0,14,0,2,0,0,0,16,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,5,0,0,0,0,0,6,0,0,83,0,0,0,0,0,0,0,0,46,0,0,0,0,0,5,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,4,0,4,4,0,1,1,0,117,117,0,60,60,0,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,<NA>,<NA>,NaN
2,26,2024-07-05 18:21:55,4,pt-BR,5371664,VwcXLtA5rfFIUi9,2024-07-05 17:19:26,2024-07-05 18:21:55,206.42.47.96,NaN,ORIGINAL,2024,Junho,NaN,"Maceió, Alagoas",Banco de Sangue Oswaldo Calado - Hemopac,NaN,12181996000168,Unidade de Coleta e Transfusão,Privado-SUS,Rede de serviços,Agência Transfusional Unimed do Banco de Sangu...,NaN,NaN,88,19,163,37,0,0,131,41,52,5,68,10,180,19,71,37,0,0,55,24,196,32,1,28,29,2,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16,8,24,0,0,0,2,249,0,NaN,249.0,0,249.0,0,249.0,3,249.0,0,249.0,3,249.0,0,249.0,1,249.0,0,249.0,0,249.0,0,249.0,0,85,86,29,23,4,11,90,100,17,4,5,3,0,1,19,17,41,0,0,1,37,0,0,3,249.0,249,6,0,NaN,0,0,0,237,0,0,12,0,0,249,32,71,0,0,0,228,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,5,1,209,0,0,12,0,0,11,0,0,0,0,83,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,37,37,0,0,0,14,249,263,0,0,0,0,71,71,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,15,0,15,0,0,0,73,0,73,0,0,0,71,0,71,0,0,0,0,0,0,0,0,0,0,0,0,0,0,31,126,41,0,0,0,0,0,0,0,0,0,NaN
3,28,2024-07-07 18:21:00,4,pt-BR,<NA>,7qTz7fGLGpNNxUf,2024-07-07 17:40:00,2024-07-07 18:21:00,190.102.52.160,NaN,ORIGINAL,2024,Junho,NaN,"Arapiraca, Alagoas",Secretaria de Estado da Saúde - Unidade Emergê...,NaN,12200259000408,Agência Transfusional,Público,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,33,0,13,0,3,0,70,0,2,0,3,0,0,0,3,0,6,0,0,0,0,0,1,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,28,0,0,0,0,0,6,0,0,130,0,0,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,14,0,0,0,0,14,14,0,179,179,0,17,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,NaN
4,29,2024-07-07 18:39:39,4,pt-BR,1067738071,XpuFs3JEYKeGWPJ,2024-07-07 18:27:15,2024-07-07 18:39:39,190.102.52.160,NaN,ORIGINAL,2024,Junho,NaN,"Arapiraca, Alagoas",Centro Hospitalar Manoel André - Chama,NaN,471021000124,Agência Transfusional,Privado-SUS,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,68,0,20,0,3,0,82,0,2,0,0,0,0,0,26,0,29,0,6,0,29,1,5,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,6,0,0,0,0,0,20,0,0,203,0,0,65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3,0,0,0,0,1,5,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,7,0,0,0,0,14,14,0,204,204,0,65,65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,0,0,0,0,0,0,0,<NA>,<NA>,NaN
5,30,2024-07-08 09:37:00,4,pt-BR,<NA>,zdJC1Bv8XoRbUGn,2024-07-08 09:29:00,2024-07-08 09:37:00,2804:14d:1289:8bfb:b4fb:13c8:940e:35a9,NaN,RETIFICADORA,2024,Junho,NaN,"Maceió, Alagoas",Secretaria de Estado da Saúde - Hospital da Mu...,Hospital da Mulher Dra. Nise da Silveira,12200259000165,Agência Transfusional,Público,Único serviço,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,0,28,0,12,0,1,0,38,0,2,0,3,0,0,0,1,0,1,0,1,0,0,0,2,NaN,<NA>,<NA>,<NA>,NaN,0,0,0,0,0,0,0,0,0,0,14,1,0,94,11,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,0,0,110,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,<NA>,<NA>,NaN

In [5]:
hemoprod_al_deduplicado.to_excel('dados_processados/hemoprod_al.xlsx', index=False)

## Hemoprod Amazonas

In [20]:
import pandas as pd
import os

# --- 1. Defina os caminhos para seus arquivos ---
# Ajuste os caminhos conforme a estrutura do seu projeto no notebook
dados_brutos_path = 'dados_brutos'
dicionario_path = 'dicionario_colunas_269.xlsx'
arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_AM.xlsx')
nome_planilha = 'HEMOPROD - AMAZONAS'

try:
    # Carrega o arquivo de dados
    hemoprod_am = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)
    print("Arquivo de dados carregado com sucesso.")
    print(f"Número de colunas original: {len(hemoprod_am.columns)}")

    # Carrega o arquivo de dicionário
    dicionario = pd.read_excel(dicionario_path)
    print("Arquivo de dicionário carregado com sucesso.")

    # --- 3. Limpeza Inicial dos Nomes das Colunas (ADICIONADO) ---
    # Mapeia as colunas, limpando espaços em branco no início e fim
    # e substituindo o caractere \xa0 (Non-breaking space) por um espaço normal.
    mapa_limpeza = {
        col: col.strip().replace('\xa0', ' ') 
        for col in hemoprod_am.columns
    }

    # Aplica a renomeação para limpar os nomes
    hemoprod_am = hemoprod_am.rename(columns=mapa_limpeza)
    print("Nomes das colunas do DataFrame limpos e padronizados (strip/\\xa0).")

    # --- 4. Crie o dicionário de mapeamento ---
    # Cria um dicionário no formato {'nome_original': 'nome_sql'} para uso no .rename()
    # NOTA: O 'nome_original' no dicionário TAMBÉM deve estar limpo para combinar.
    # Se o dicionário não estiver limpo, adicione a mesma limpeza aqui:
    dicionario['nome_original'] = dicionario['nome_original'].astype(str).str.strip().str.replace('\xa0', ' ')
    
    mapa_renomeacao = pd.Series(dicionario['nome_sql'].values, index=dicionario['nome_original']).to_dict()
    
    # Lista dos nomes de coluna no DataFrame atual APÓS a limpeza inicial
    colunas_atuais = set(hemoprod_am.columns)
    
    # Lista dos nomes originais de coluna no dicionário APÓS a limpeza (se aplicada)
    colunas_originais_dicionario = set(dicionario['nome_original'].tolist())
    
    # Lista dos nomes SQL (os desejados) no dicionário
    colunas_sql_desejadas = set(dicionario['nome_sql'].tolist())
    
    # --- 5. Renomeie as colunas com base no mapeamento (nome_original -> nome_sql) ---
    print("\n--- Processo de Renomeação ---")
    hemoprod_am.rename(columns=mapa_renomeacao, inplace=True)
    print("Colunas renomeadas com sucesso (apenas as que existiam no dicionário foram modificadas).")


   # --- 4. Inferir Tipos e Criar Mapeamento de Tipos ---
    
    # --- Lógica de Inferência customizada para 'Int64' ---
    tipos_inferidos = {}
    for col in hemoprod_am.columns:
        
        # 4.1. Tenta converter a coluna para o tipo que melhor representa seus dados (incluindo Int64/string/datetime)
        # O errors='ignore' é crucial para não falhar se a coluna não puder ser convertida
        coluna_convertida = pd.to_numeric(hemoprod_am[col], errors='coerce')
        
        # Se a conversão for bem-sucedida (não é totalmente NaN, nem totalmente string)
        if not coluna_convertida.isna().all() and coluna_convertida.dtype.kind in 'fi': # 'f' para float, 'i' para int
            
            # Se a coluna parecer um número, tentamos forçar para Int64
            # O .astype('Int64') usa o tipo inteiro que suporta NaN
            try:
                # Se for possível converter para Int64, use 'Int64'
                hemoprod_am[col] = hemoprod_am[col].astype('Int64')
                tipos_inferidos[col] = 'Int64'
            except Exception:
                # Se for numérico mas não puder ser Int64 (ex: float com muitas casas decimais), use 'float64'
                tipos_inferidos[col] = 'float64'
        
        # Verifica se é data/hora
        elif pd.api.types.is_datetime64_any_dtype(hemoprod_am[col]):
             tipos_inferidos[col] = 'datetime64[ns]'
             
        # Caso contrário, assume-se que é um texto/string
        else:
            tipos_inferidos[col] = 'object' # O padrão para string no pandas

    
    print("\nTipos de dados inferidos (amostra):")
    for i, (col, dtype) in enumerate(tipos_inferidos.items()):
        if i < 5:
            print(f"  {col}: {dtype}")
        if i == 5:
            print("  ...")
    
    # --- 5. Atualizar o DataFrame Dicionário ---
    
    # 5.1. Cria a coluna 'tipo_dados' no dicionário e preenche com os tipos inferidos
    dicionario['tipo_dados'] = dicionario['nome_sql'].map(tipos_inferidos)
    
    # 5.2. Trata colunas não encontradas no DataFrame de dados
    dicionario['tipo_dados'] = dicionario['tipo_dados'].fillna('object')
    
    print("\n--- Dicionário Atualizado ---")
    print("Coluna 'tipo_dados' criada com sucesso, com numéricos definidos como 'Int64' ou 'float64'.")
    
    # --- 6. Salvar o Dicionário Atualizado ---

    # Sugestão de novo caminho para salvar
    # novo_dicionario_path = 'dicionario_colunas_269_COM_TIPOS_V3.xlsx'
    
    # dicionario.to_excel(novo_dicionario_path, index=False)
    
    print(f"\n✅ Dicionário salvo com a nova coluna 'tipo_dados' em: {novo_dicionario_path}")
    print("\nPrimeiras linhas do dicionário atualizado:")
    display(dicionario.head())

    # --- 6. Análise de Colunas (Qualidade dos Dados) ---

    # 6.1. Colunas que não puderam ser renomeadas (existem no DF, mas não no 'nome_original' do dicionário)
    # Aqui usamos as colunas atuais ANTES da renomeação para ver o que sobrou.
    colunas_nao_mapeadas = [
        col for col in colunas_atuais 
        if col not in colunas_originais_dicionario
    ]

    print("-" * 30)
    print("Análise de Colunas do DataFrame (hemoprod_am):")
    print(f"Número de colunas não mapeadas: {len(colunas_nao_mapeadas)}")
    print(f"Colunas não mapeadas (manterão nome original): {colunas_nao_mapeadas}")
    
    # 6.2. Análise de Colunas Faltantes/A Mais (Comparação com 'nome_sql' desejado)
    colunas_apos_renomeacao = set(hemoprod_am.columns)
    
    colunas_faltantes = list(colunas_sql_desejadas - colunas_apos_renomeacao)
    colunas_a_mais = list(colunas_apos_renomeacao - colunas_sql_desejadas)

    print("-" * 30)
    print("Análise de Colunas (Comparação com a lista SQL DESEJADA):")
    print(f"Número de colunas FALTANTES: {len(colunas_faltantes)}")
    print(f"Colunas FALTANTES (deveriam estar, mas não estão): {colunas_faltantes}")
    print("-" * 30)
    print(f"Número de colunas A MAIS: {len(colunas_a_mais)}")
    print(f"Colunas A MAIS (estão no DF, mas não na lista SQL desejada): {colunas_a_mais}")
    print("-" * 30)

    # --- 7. Verifique o resultado ---
    print("\nInformações do DataFrame com as novas colunas:")
    hemoprod_am.info()
    
    print("\nAs 5 primeiras linhas com as novas colunas:")
    display(hemoprod_am.head())

except FileNotFoundError as e:
    print(f"\nErro de arquivo não encontrado: {e}")
except KeyError as e:
    print(f"\nErro de coluna não encontrada: {e}. Verifique se as colunas 'nome_original' e 'nome_sql' existem no seu arquivo de dicionário.")
except Exception as e:
    print(f"\nOcorreu um erro inesperado: {e}")

Arquivo de dados carregado com sucesso.
Número de colunas original: 270
Arquivo de dicionário carregado com sucesso.
Nomes das colunas do DataFrame limpos e padronizados (strip/\xa0).

--- Processo de Renomeação ---
Colunas renomeadas com sucesso (apenas as que existiam no dicionário foram modificadas).

Tipos de dados inferidos (amostra):
  id: Int64
  data_envio: object
  ultima_pagina: Int64
  idioma_inicial: object
  semente: Int64
  ...

--- Dicionário Atualizado ---
Coluna 'tipo_dados' criada com sucesso, com numéricos definidos como 'Int64' ou 'float64'.

✅ Dicionário salvo com a nova coluna 'tipo_dados' em: dicionario_colunas_269_COM_TIPOS_V2.xlsx

Primeiras linhas do dicionário atualizado:

,nome_original,nome_sql,comentario,tipo_dados
0,ID da resposta,id,Identificador único e chave primária da submis...,Int64
1,Data de envio,data_envio,Data e hora exatas do envio final do formulário.,object
2,Última página,ultima_pagina,Título da última página do formulário acessada...,Int64
3,Idioma inicial,idioma_inicial,Idioma selecionado no início do preenchimento ...,object
4,Semente,semente,Valor interno de semente/aleatorização (uso té...,Int64

------------------------------
Análise de Colunas do DataFrame (hemoprod_am):
Número de colunas não mapeadas: 1
Colunas não mapeadas (manterão nome original): ['URL de referência']
------------------------------
Análise de Colunas (Comparação com a lista SQL DESEJADA):
Número de colunas FALTANTES: 0
Colunas FALTANTES (deveriam estar, mas não estão): []
------------------------------
Número de colunas A MAIS: 1
Colunas A MAIS (estão no DF, mas não na lista SQL desejada): ['URL de referência']
------------------------------

Informações do DataFrame com as novas colunas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Columns: 270 entries, id to hemoprod_3_observacoes
dtypes: Int64(229), float64(27), object(14)
memory usage: 74.8+ KB

As 5 primeiras linhas com as novas colunas:

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,URL de referência,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,5,2023-10-26 11:56:58,4,pt-BR,534226503,1vXXcXvg3W0RfaG,2023-10-26 09:36:21,2023-10-26 11:56:58,200.129.161.9,https://www.gov.br/,NaN,ORIGINAL,2023,Janeiro,NaN,"Manaus, Amazonas",Fundação de Hemotologia e Hemoterapia do Amazo...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2447,571,2788,874,0,3,1357,762,3878,686,0,0,3656,627,1579,821,0,0,2099,724,3136,724,69,492,561,40,17,57,3,1,4,2,0,2,24,8,32,6,1,7,4,0,4,0,0,0,2,0,2,477,302,779,25,0,0,0,5235,68,NaN,5199.0,2,5199.0,8,5199.0,55,5199.0,5,5199.0,44,5199.0,9,5199.0,4,0.0,0,0.0,0,0.0,0,0.0,0,1333.0,80,418,12,88,3,3092.0,142,89,1,26,0,3,0,207,2,325,3,3,10,488,9,3,10,1357.0,5199.0,127,13,NaN,5231.0,0,0,1770,0,20,0,0,0,4941.0,0,1292,0,0,0,3401.0,0,520,0,0,0,0,0,0,507,0,31,0,0,0,0,0,139,11,32,344,0,0,0,9,197,209,0,0,0,7,124,53,0,0,0,0,0,0,0,0,21,0,0,0,0,0,0,11,13,0,0,0,0,67,71,0,0,0,0,87,289,0,0,0,0,0,0,0,6,30,0,0,0,0,0,0,0,1064,26,0,0,0,0,5040,598,0,0,0,0,2202,0,0,0,0,0,0,0,0,425,0,0,0,0,0,65,1161,0,387,226,1,0,3,0,0,0,0,0,0,NaN
1,6,2023-10-26 12:54:31,4,pt-BR,1723372445,1vXXcXvg3W0RfaG,2023-10-26 12:27:08,2023-10-26 12:54:31,200.129.161.9,https://www.gov.br/,NaN,ORIGINAL,2023,Fevereiro,NaN,"Manaus, Amazonas",Fundação de Hemotologia e Hemoterapia do Amazo...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2386,651,2431,738,0,0,1342,765,3475,624,0,0,3352,632,1465,757,0,0,2029,730,2788,659,85,453,538,51,19,70,3,2,5,3,1,4,51,9,60,7,1,8,6,3,9,0,0,0,0,0,0,426,269,695,38,0,0,0,4817,69,NaN,4763.0,3,4763.0,4,4763.0,60,4763.0,8,4763.0,31,4763.0,12,4763.0,5,4763.0,0,0.0,0,0.0,0,0.0,0,1178.0,53,357,10,86,13,2846.0,151,79,0,22,0,4,0,211,0,316,0,1,14,448,11,1,14,1342.0,4763.0,123,13,NaN,4817.0,0,0,614,0,21,0,0,0,4229.0,0,461,0,0,0,3501.0,0,461,0,0,0,0,0,0,285,0,7,0,0,0,0,0,102,7,4,144,0,0,0,2,14,22,0,0,0,6,899,73,0,0,0,0,0,0,2,3,0,0,0,0,0,0,0,8,14,22,0,0,0,67,72,139,0,0,0,161,374,535,0,0,0,0,0,0,0,22,22,0,0,0,0,0,0,842,39,881,0,0,0,4774,640,5414,0,0,0,2072,0,2072,0,0,0,0,0,0,397,0,397,0,0,0,75,1223,0,308,180,2,0,2,0,0,0,0,0,0,NaN
2,9,2023-10-31 11:14:51,4,pt-BR,2072510604,1vXXcXvg3W0RfaG,2023-10-31 10:49:55,2023-10-31 11:14:51,200.129.161.9,https://www.gov.br/,NaN,ORIGINAL,2023,Março,NaN,"Manaus, Amazonas",Fundação Hospitalar de Hematologia e Hemoterap...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2281,620,3338,1012,0,0,1589,964,4030,668,0,0,3864,684,1755,948,0,0,2234,877,3385,755,75,582,657,34,10,44,0,0,0,2,0,2,26,7,33,3,0,3,3,0,3,0,0,0,1,0,1,540,349,889,29,0,0,0,5619,57,NaN,5496.0,5,5496.0,12,5496.0,74,5496.0,13,5496.0,71,5496.0,11,5496.0,4,5496.0,0,0.0,0,0.0,0,0.0,0,1343.0,66,405,12,100,8,3344.0,204,95,6,37,0,9,0,251,6,392,12,3,20,537,22,3,20,1589.0,5496.0,190,15,NaN,5634.0,0,0,1626,0,32,0,0,0,4757.0,0,1048,0,0,0,3644.0,0,484,0,0,0,0,0,0,644,0,0,0,0,0,0,0,155,5,1,195,0,0,0,8,2,28,0,0,0,10,519,159,0,0,0,0,0,0,0,9,2,0,0,0,0,0,0,4,4,8,0,0,0,137,69,206,0,0,0,240,716,956,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1035,32,1067,0,0,0,5202,679,5881,0,0,0,2233,0,2233,0,0,0,0,0,0,612,0,612,0,0,0,74,1668,0,446,187,5,0,1,0,0,0,0,0,0,NaN
3,10,2023-10-31 12:16:31,4,pt-BR,411593062,1vXXcXvg3W0RfaG,2023-10-31 11:17:44,2023-10-31 12:16:31,200.129.161.9,https://www.gov.br/,NaN,ORIGINAL,2023,Abril,NaN,"Manaus, Amazonas",Fundação Hospitalar de Hematologia e Hemoterap...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2839,617,3280,982,0,0,1756,921,4363,678,0,0,3985,579,2134,1020,0,0,2344,730,3775,869,82,640,722,40,15,55,1,4,5,0,0,0,17,7,24,12,3,15,5,0,5,0,0,0,4,0,4,418,351,769,94,0,0,0,6119,64,NaN,6076.0,5,6076.0,10,6076.0,78,6076.0,10,6076.0,56,6076.0,16,6076.0,10,6076.0,0,0.0,0,0.0,0,0.0,0,1550.0,62,494,12,119,7,3628.0,206,82,6,33,0,7,0,259,3,381,9,0,14,546,14,0,14,1759.0,6076.0,185,15,NaN,6119.0,0,0,1510,0,21,0,0,0,5299.0,0,966,0,0,0,4060.0,0,544,0,0,0,0,0,0,497,0,9,0,0,0,0,0,152,2,0,242,0,0,0,4,16,9,0,0,0,9,862,57,0,0,0,0,0,0,11,0,34,0,0,0,0,0,0,12,0,12,0,0,0,132,71,203,0,0,0,424,413,837,0,0,0,0,0,0,0,63,63,0,0,0,0,0,0,1086,32,1118,0,0,0,5087,585,5672,0,0,0,2161,0,2161,0,0,0,0,0,0,395,0,395,0,0,0,43,1699,0,276,172,2,0,1,0,0,1,0,0,0,NaN
4,11,2023-10-31 13:06:36,4,pt-BR,542798905,1vXXcXvg3W0RfaG,2023-10-31 12:19:45,2023-10-31 13:06:36,200.129.161.9,https://www.gov.br/,NaN,ORIGINAL,2023,Maio,NaN,"Manaus, Amazonas",Fundação Hospitalar de Hematologia e Hemoterap...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2297,597,3368,1048,0,0,1595,911,4070,734,0,0,3796,629,1869,1016,0,0,2368,801,3297,844,64,553,617,34,10,44,0,1,1,1,0,1,23,13,36,10,0,10,3,3,6,0,0,0,1,0,1,493,436,929,75,0,0,0,5665,84,NaN,5632.0,1,5632.0,11,5632.0,86,5632.0,11,5632.0,50,5632.0,10,5632.0,9,5632.0,0,0.0,0,0.0,0,0.0,0,1326.0,63,462,29,89,1,3179.0,188,97,7,29,0,5,0,272,1,403,8,6,10,516,20,6,10,1595.0,5632.0,178,3,NaN,5665.0,0,0,1594,0,25,0,0,0,4745.0,0,867,0,0,0,3383.0,0,560,0,0,0,0,0,0,493,0,0,0,0,0,0,0,75,8,0,214,0,0,0,9,35,13,0,0,0,2,465,50,0,0,0,0,0,0,5,0,8,0,0,0,0,0,0,4,3,7,0,0,0,123,78,201,0,0,0,205,427,632,0,0,0,0,0,0,0,21,21,0,0,0,0,0,0,953,33,986,0,0,0,5167,811,5978,0,0,0,2256,0,2256,0,0,0,0,0,0,439,0,439,0,0,0,59,1580,0,296,132,3,0,4,0,0,0,0,0,0,NaN

In [17]:
# ASSUME QUE AS VARIÁVEIS 'hemoprod_al', 'dicionario', 'colunas_a_mais', 
# 'colunas_faltantes' E 'colunas_sql_desejadas' EXISTEM DA CÉLULA ANTERIOR.

print("--- 6. PADRONIZAÇÃO DO ESQUEMA (Remoção, Adição e Reordenação) ---")

# 6.1. REMOVE as Colunas a Mais
if colunas_a_mais:
    # Verificação de segurança: Só tenta dropar colunas que estão realmente no DF
    colunas_para_dropar = [col for col in colunas_a_mais if col in hemoprod_al.columns]
    hemoprod_am.drop(columns=colunas_para_dropar, inplace=True)
    print(f"✅ {len(colunas_para_dropar)} colunas a mais removidas.")
else:
    print("Nenhuma coluna a mais para remover.")

# 6.2. ADICIONA as Colunas Faltantes
if colunas_faltantes:
    
    # Prepara o sub-dicionário apenas com as colunas faltantes (para tipos)
    dicionario_faltante = dicionario[dicionario['nome_sql'].isin(colunas_faltantes)]
    
    for col_sql in colunas_faltantes:
        
        # Adiciona a coluna com valor nulo (NaN)
        hemoprod_am[col_sql] = np.nan 

        # --- Lógica Opcional de Conversão de Tipo (Baseada na coluna 'tipo_dados' no dicionário) ---
        # Tenta encontrar o tipo no dicionário (apenas se a coluna 'tipo_dados' existir e não estiver vazia)
        if 'tipo_dados' in dicionario.columns:
            tipo_desejado_row = dicionario_faltante[dicionario_faltante['nome_sql'] == col_sql]
            
            if not tipo_desejado_row.empty:
                tipo_desejado = tipo_desejado_row['tipo_dados'].iloc[0].lower()

                # Converte para o tipo, se for reconhecido
                if 'int' in tipo_desejado or 'float' in tipo_desejado:
                    # Usa 'float64' para números que podem ter NaNs, para evitar erros de Pandas
                    hemoprod_am[col_sql] = hemoprod_am[col_sql].astype('float64') 
                elif 'string' in tipo_desejado or 'object' in tipo_desejado:
                    # Converte para 'object' (string)
                    hemoprod_am[col_sql] = hemoprod_am[col_sql].astype('object')
                 
    print(f"✅ {len(colunas_faltantes)} colunas faltantes adicionadas e preenchidas com NaN.")
else:
    print("Nenhuma coluna faltante para adicionar.")


# 6.3. Reordena as colunas (Para garantir a ordem padronizada do dicionário)
colunas_finais = dicionario['nome_sql'].tolist()
# Garante que só as colunas que realmente existem no DF (após drop/adição) sejam usadas na reordenação
colunas_finais_presentes = [col for col in colunas_finais if col in hemoprod_am.columns]

# Esta é a linha que reordena o DataFrame
hemoprod_am = hemoprod_am[colunas_finais_presentes]
print("✅ Colunas reordenadas para seguir a ordem do dicionário.")


# --- 7. Verifique o resultado Final ---
print("\n--- Resultado Final ---")
print(f"Número de colunas final: {len(hemoprod_am.columns)}")
print("Informações do DataFrame padronizado:")
hemoprod_am.info()

print("\nAs 5 primeiras linhas com as colunas padronizadas:")
display(hemoprod_am.head())

--- 6. PADRONIZAÇÃO DO ESQUEMA (Remoção, Adição e Reordenação) ---
✅ 0 colunas a mais removidas.
Nenhuma coluna faltante para adicionar.
✅ Colunas reordenadas para seguir a ordem do dicionário.

--- Resultado Final ---
Número de colunas final: 269
Informações do DataFrame padronizado:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Columns: 269 entries, id to hemoprod_3_observacoes
dtypes: Int64(229), float64(27), object(13)
memory usage: 74.5+ KB

As 5 primeiras linhas com as colunas padronizadas:

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,5,2023-10-26 11:56:58,4,pt-BR,534226503,1vXXcXvg3W0RfaG,2023-10-26 09:36:21,2023-10-26 11:56:58,200.129.161.9,NaN,ORIGINAL,2023,Janeiro,NaN,"Manaus, Amazonas",Fundação de Hemotologia e Hemoterapia do Amazo...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2447,571,2788,874,0,3,1357,762,3878,686,0,0,3656,627,1579,821,0,0,2099,724,3136,724,69,492,561,40,17,57,3,1,4,2,0,2,24,8,32,6,1,7,4,0,4,0,0,0,2,0,2,477,302,779,25,0,0,0,5235,68,NaN,5199.0,2,5199.0,8,5199.0,55,5199.0,5,5199.0,44,5199.0,9,5199.0,4,0.0,0,0.0,0,0.0,0,0.0,0,1333.0,80,418,12,88,3,3092.0,142,89,1,26,0,3,0,207,2,325,3,3,10,488,9,3,10,1357.0,5199.0,127,13,NaN,5231.0,0,0,1770,0,20,0,0,0,4941.0,0,1292,0,0,0,3401.0,0,520,0,0,0,0,0,0,507,0,31,0,0,0,0,0,139,11,32,344,0,0,0,9,197,209,0,0,0,7,124,53,0,0,0,0,0,0,0,0,21,0,0,0,0,0,0,11,13,0,0,0,0,67,71,0,0,0,0,87,289,0,0,0,0,0,0,0,6,30,0,0,0,0,0,0,0,1064,26,0,0,0,0,5040,598,0,0,0,0,2202,0,0,0,0,0,0,0,0,425,0,0,0,0,0,65,1161,0,387,226,1,0,3,0,0,0,0,0,0,NaN
1,6,2023-10-26 12:54:31,4,pt-BR,1723372445,1vXXcXvg3W0RfaG,2023-10-26 12:27:08,2023-10-26 12:54:31,200.129.161.9,NaN,ORIGINAL,2023,Fevereiro,NaN,"Manaus, Amazonas",Fundação de Hemotologia e Hemoterapia do Amazo...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2386,651,2431,738,0,0,1342,765,3475,624,0,0,3352,632,1465,757,0,0,2029,730,2788,659,85,453,538,51,19,70,3,2,5,3,1,4,51,9,60,7,1,8,6,3,9,0,0,0,0,0,0,426,269,695,38,0,0,0,4817,69,NaN,4763.0,3,4763.0,4,4763.0,60,4763.0,8,4763.0,31,4763.0,12,4763.0,5,4763.0,0,0.0,0,0.0,0,0.0,0,1178.0,53,357,10,86,13,2846.0,151,79,0,22,0,4,0,211,0,316,0,1,14,448,11,1,14,1342.0,4763.0,123,13,NaN,4817.0,0,0,614,0,21,0,0,0,4229.0,0,461,0,0,0,3501.0,0,461,0,0,0,0,0,0,285,0,7,0,0,0,0,0,102,7,4,144,0,0,0,2,14,22,0,0,0,6,899,73,0,0,0,0,0,0,2,3,0,0,0,0,0,0,0,8,14,22,0,0,0,67,72,139,0,0,0,161,374,535,0,0,0,0,0,0,0,22,22,0,0,0,0,0,0,842,39,881,0,0,0,4774,640,5414,0,0,0,2072,0,2072,0,0,0,0,0,0,397,0,397,0,0,0,75,1223,0,308,180,2,0,2,0,0,0,0,0,0,NaN
2,9,2023-10-31 11:14:51,4,pt-BR,2072510604,1vXXcXvg3W0RfaG,2023-10-31 10:49:55,2023-10-31 11:14:51,200.129.161.9,NaN,ORIGINAL,2023,Março,NaN,"Manaus, Amazonas",Fundação Hospitalar de Hematologia e Hemoterap...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2281,620,3338,1012,0,0,1589,964,4030,668,0,0,3864,684,1755,948,0,0,2234,877,3385,755,75,582,657,34,10,44,0,0,0,2,0,2,26,7,33,3,0,3,3,0,3,0,0,0,1,0,1,540,349,889,29,0,0,0,5619,57,NaN,5496.0,5,5496.0,12,5496.0,74,5496.0,13,5496.0,71,5496.0,11,5496.0,4,5496.0,0,0.0,0,0.0,0,0.0,0,1343.0,66,405,12,100,8,3344.0,204,95,6,37,0,9,0,251,6,392,12,3,20,537,22,3,20,1589.0,5496.0,190,15,NaN,5634.0,0,0,1626,0,32,0,0,0,4757.0,0,1048,0,0,0,3644.0,0,484,0,0,0,0,0,0,644,0,0,0,0,0,0,0,155,5,1,195,0,0,0,8,2,28,0,0,0,10,519,159,0,0,0,0,0,0,0,9,2,0,0,0,0,0,0,4,4,8,0,0,0,137,69,206,0,0,0,240,716,956,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1035,32,1067,0,0,0,5202,679,5881,0,0,0,2233,0,2233,0,0,0,0,0,0,612,0,612,0,0,0,74,1668,0,446,187,5,0,1,0,0,0,0,0,0,NaN
3,10,2023-10-31 12:16:31,4,pt-BR,411593062,1vXXcXvg3W0RfaG,2023-10-31 11:17:44,2023-10-31 12:16:31,200.129.161.9,NaN,ORIGINAL,2023,Abril,NaN,"Manaus, Amazonas",Fundação Hospitalar de Hematologia e Hemoterap...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2839,617,3280,982,0,0,1756,921,4363,678,0,0,3985,579,2134,1020,0,0,2344,730,3775,869,82,640,722,40,15,55,1,4,5,0,0,0,17,7,24,12,3,15,5,0,5,0,0,0,4,0,4,418,351,769,94,0,0,0,6119,64,NaN,6076.0,5,6076.0,10,6076.0,78,6076.0,10,6076.0,56,6076.0,16,6076.0,10,6076.0,0,0.0,0,0.0,0,0.0,0,1550.0,62,494,12,119,7,3628.0,206,82,6,33,0,7,0,259,3,381,9,0,14,546,14,0,14,1759.0,6076.0,185,15,NaN,6119.0,0,0,1510,0,21,0,0,0,5299.0,0,966,0,0,0,4060.0,0,544,0,0,0,0,0,0,497,0,9,0,0,0,0,0,152,2,0,242,0,0,0,4,16,9,0,0,0,9,862,57,0,0,0,0,0,0,11,0,34,0,0,0,0,0,0,12,0,12,0,0,0,132,71,203,0,0,0,424,413,837,0,0,0,0,0,0,0,63,63,0,0,0,0,0,0,1086,32,1118,0,0,0,5087,585,5672,0,0,0,2161,0,2161,0,0,0,0,0,0,395,0,395,0,0,0,43,1699,0,276,172,2,0,1,0,0,1,0,0,0,NaN
4,11,2023-10-31 13:06:36,4,pt-BR,542798905,1vXXcXvg3W0RfaG,2023-10-31 12:19:45,2023-10-31 13:06:36,200.129.161.9,NaN,ORIGINAL,2023,Maio,NaN,"Manaus, Amazonas",Fundação Hospitalar de Hematologia e Hemoterap...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2297,597,3368,1048,0,0,1595,911,4070,734,0,0,3796,629,1869,1016,0,0,2368,801,3297,844,64,553,617,34,10,44,0,1,1,1,0,1,23,13,36,10,0,10,3,3,6,0,0,0,1,0,1,493,436,929,75,0,0,0,5665,84,NaN,5632.0,1,5632.0,11,5632.0,86,5632.0,11,5632.0,50,5632.0,10,5632.0,9,5632.0,0,0.0,0,0.0,0,0.0,0,1326.0,63,462,29,89,1,3179.0,188,97,7,29,0,5,0,272,1,403,8,6,10,516,20,6,10,1595.0,5632.0,178,3,NaN,5665.0,0,0,1594,0,25,0,0,0,4745.0,0,867,0,0,0,3383.0,0,560,0,0,0,0,0,0,493,0,0,0,0,0,0,0,75,8,0,214,0,0,0,9,35,13,0,0,0,2,465,50,0,0,0,0,0,0,5,0,8,0,0,0,0,0,0,4,3,7,0,0,0,123,78,201,0,0,0,205,427,632,0,0,0,0,0,0,0,21,21,0,0,0,0,0,0,953,33,986,0,0,0,5167,811,5978,0,0,0,2256,0,2256,0,0,0,0,0,0,439,0,439,0,0,0,59,1580,0,296,132,3,0,4,0,0,0,0,0,0,NaN

In [9]:
#remover o url
hemoprod_am = hemoprod_am.drop(columns=['url'])

In [11]:
# --- 2. Defina as colunas para a chave e para ordenação ---
registros_antes = len(hemoprod_am)
print(f"Total de registros ANTES da remoção de duplicatas: {registros_antes}")
    

colunas_chave = [
        'cnpj', 
        'ano_referencia', 
        'periodo_referencia', 
        'razao_social_nome_fantasia'
    ]

coluna_data = 'data_envio'

# --- 3. Verifique se as colunas necessárias existem ---
colunas_necessarias = colunas_chave + [coluna_data]

if not all(col in hemoprod_am.columns for col in colunas_necessarias):
    print("\n--- ERRO ---")
    print("Uma ou mais colunas necessárias para a deduplicação não foram encontradas.")
    colunas_faltantes = [col for col in colunas_necessarias if col not in hemoprod_am.columns]
    print(f"Colunas necessárias: {colunas_necessarias}")
    print(f"Colunas faltantes no DataFrame: {colunas_faltantes}")
else:
    # --- 4. Prepare a coluna de data e ordene os dados ---
    # Converte a coluna 'data_envio' para datetime para garantir a ordenação correta.
    # 'errors='coerce'' transformará datas inválidas em NaT (Not a Time), que são tratadas como nulas.
    hemoprod_am[coluna_data] = pd.to_datetime(hemoprod_am[coluna_data], errors='coerce')

    # Ordena o DataFrame. Os registros com data de envio mais recente ficarão por último.
    print(f"\nOrdenando os dados por '{coluna_data}'...")
    hemoprod_am_ordenado = hemoprod_am.sort_values(by=coluna_data, ascending=True)

    # --- 5. Identifique e separe os registros duplicados e únicos ---
    # Em vez de usar drop_duplicates() diretamente, vamos usar duplicated()
    # para criar uma máscara booleana.
    # 'keep='last'' marca todas as ocorrências de uma chave como True, EXCETO a última (a mais recente).
    print(f"Identificando duplicatas com base na chave: {colunas_chave}...")
    mascara_duplicatas = hemoprod_am_ordenado.duplicated(subset=colunas_chave, keep='last')

    # O DataFrame de removidos conterá todas as linhas marcadas como True
    hemoprod_removidos = hemoprod_am_ordenado[mascara_duplicatas]
    
    # O DataFrame deduplicado conterá o INVERSO (~) da máscara (linhas marcadas como False)
    hemoprod_am_deduplicado = hemoprod_am_ordenado[~mascara_duplicatas]
    
    # Agora podemos contar os registros diretamente dos novos DataFrames
    registros_depois = len(hemoprod_am_deduplicado)
    registros_removidos = len(hemoprod_removidos) 
    
    # --- 6. Exiba o resultado ---
    print("\n--- Processo Concluído ---")
    print(f"Registros removidos: {registros_removidos}")
    print(f"Total de registros DEPOIS da remoção de duplicatas: {registros_depois}")

    # (Opcional) Exibe a amostra dos removidos
    print("\nAmostra dos dados REMOVIDOS (os mais antigos/duplicados):")
    display(hemoprod_removidos.head(10))

    # Você pode continuar a usar o DataFrame 'hemoprod_am_deduplicado' para suas análises
    print("\nAmostra dos dados únicos (os mais recentes para cada chave):")
    display(hemoprod_am_deduplicado.head(10))

    hemoprod_am.describe()
    
    # Agora você tem o DataFrame 'hemoprod_removidos' salvo

Total de registros ANTES da remoção de duplicatas: 32

Ordenando os dados por 'data_envio'...
Identificando duplicatas com base na chave: ['cnpj', 'ano_referencia', 'periodo_referencia', 'razao_social_nome_fantasia']...

--- Processo Concluído ---
Registros removidos: 0
Total de registros DEPOIS da remoção de duplicatas: 32

Amostra dos dados REMOVIDOS (os mais antigos/duplicados):

Empty DataFrame
Columns: [id, data_envio, ultima_pagina, idioma_inicial, semente, codigo_acesso, data_inicio, data_ultima_acao, ip, identificacao_dado, tipo_envio, ano_referencia, periodo_referencia, identificacao_estabelecimento, municipio, razao_social_nome_fantasia, razao_social_nome_fantasia_outros, cnpj, tipo_estabelecimento, natureza_estabelecimento, dados_informados_referem_se, rede_estabelecimento, cnes, endereco, triagem_clinica_total_doacao_espontanea_aptos, triagem_clinica_total_doacao_espontanea_inaptos, triagem_clinica_total_doacao_reposicao_aptos, triagem_clinica_total_doacao_reposicao_inaptos, triagem_clinica_total_doacao_autologa_aptos, triagem_clinica_total_doacao_autologa_inaptos, total_doador_primeira_vez_aptos, total_doador_primeira_vez_inaptos, total_doador_repeticao_aptos, total_doador_repeticao_inaptos, total_doador_esporadico_aptos, total_doador_esporadico_inaptos, total_doador_masculino_aptos, total_doador_masculino_inaptos, total_doador_feminino_aptos, total_doador_feminino_inaptos, total_doador_menor_de_18_anos_aptos, total_doador_menor_de_18_anos_inaptos, total_doador_18_ate_29_anos_aptos, total_doador_18_ate_29_anos_inaptos, total_doador_acima_de_29_anos_aptos, total_doador_acima_de_29_anos_inaptos, total_candidatos_inaptos_anemia_masculino, total_candidatos_inaptos_anemia_feminino, total_candidatos_inaptos_anemia_total, total_candidatos_inaptos_hipertensao_masculino, total_candidatos_inaptos_hipertensao_feminino, total_candidatos_inaptos_hipertensao_total, total_candidatos_inaptos_hipotensao_masculino, total_candidatos_inaptos_hipotensao_feminino, total_candidatos_inaptos_hipotensao_total, total_candidatos_inaptos_alcoolismo_masculino, total_candidatos_inaptos_alcoolismo_feminino, total_candidatos_inaptos_alcoolismo_total, total_candidatos_inaptos_comportamento_risco_dst_masculino, total_candidatos_inaptos_comportamento_risco_dst_feminino, total_candidatos_inaptos_comportamento_risco_dst_total, total_candidatos_inaptos_uso_drogas_masculino, total_candidatos_inaptos_uso_drogas_feminino, total_candidatos_inaptos_uso_drogas_total, total_candidatos_inaptos_hepatite_masculino, total_candidatos_inaptos_hepatite_feminino, total_candidatos_inaptos_hepatite_total, total_candidatos_inaptos_doenca_chagas_masculino, total_candidatos_inaptos_doenca_chagas_feminino, total_candidatos_inaptos_doenca_chagas_total, total_candidatos_inaptos_malaria_masculino, total_candidatos_inaptos_malaria_feminino, total_candidatos_inaptos_malaria_total, total_candidatos_inaptos_outras_masculino, total_candidatos_inaptos_outras_feminino, total_candidatos_inaptos_outras_total, coleta_total_candidatos_desistentes, total_interrupcoes_coleta_dificuldade_puncao_venosa, total_interrupcoes_coleta_reacao_vagal, total_interrupcoes_coleta_outros_motivos, total_coletas_sangue_total, total_coletas_aferese, hemoprod_1_observacoes, exames_triagem_doenca_doenca_chagas_amostras_testadas, exames_triagem_doenca_doenca_chagas_amostras_reagentes, exames_triagem_doenca_hiv_amostras_testadas, exames_triagem_doenca_hiv_amostras_reagentes, exames_triagem_doenca_sifilis_amostras_testadas, `exames_triagem_doenca_sifilis_amostras_reagentes, exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas, exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes, exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas, exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes, exames_triagem_doenca_hepatite_c_amostras_testadas, exames_triagem_doenca_hepatite_c_amostras_reagentes, exames_triagem_doenca_htlv_i_ii_amostras_testadas, exames_triagem_doenca_htlv_i_ii_amostras_reagentes, exames_triagem_doenca_malaria_amostras_testadas, exames_triagem_doenca_malaria_amostras_reagentes, exames_triagem_doenca_hbv_teste_nat_amostras_testadas, ...]
Index: []

Amostra dos dados únicos (os mais recentes para cada chave):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,5,2023-10-26 11:56:58,4,pt-BR,534226503,1vXXcXvg3W0RfaG,2023-10-26 09:36:21,2023-10-26 11:56:58,200.129.161.9,NaN,ORIGINAL,2023,Janeiro,NaN,"Manaus, Amazonas",Fundação de Hemotologia e Hemoterapia do Amazo...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2447,571,2788,874,0,3,1357,762,3878,686,0,0,3656,627,1579,821,0,0,2099,724,3136,724,69,492,561,40,17,57,3,1,4,2,0,2,24,8,32,6,1,7,4,0,4,0,0,0,2,0,2,477,302,779,25,0,0,0,5235,68,NaN,5199.0,2,5199.0,8,5199.0,55,5199.0,5,5199.0,44,5199.0,9,5199.0,4,0.0,0,0.0,0,0.0,0,0.0,0,1333.0,80,418,12,88,3,3092.0,142,89,1,26,0,3,0,207,2,325,3,3,10,488,9,3,10,1357.0,5199.0,127,13,NaN,5231.0,0,0,1770,0,20,0,0,0,4941.0,0,1292,0,0,0,3401.0,0,520,0,0,0,0,0,0,507,0,31,0,0,0,0,0,139,11,32,344,0,0,0,9,197,209,0,0,0,7,124,53,0,0,0,0,0,0,0,0,21,0,0,0,0,0,0,11,13,0,0,0,0,67,71,0,0,0,0,87,289,0,0,0,0,0,0,0,6,30,0,0,0,0,0,0,0,1064,26,0,0,0,0,5040,598,0,0,0,0,2202,0,0,0,0,0,0,0,0,425,0,0,0,0,0,65,1161,0,387,226,1,0,3,0,0,0,0,0,0,NaN
1,6,2023-10-26 12:54:31,4,pt-BR,1723372445,1vXXcXvg3W0RfaG,2023-10-26 12:27:08,2023-10-26 12:54:31,200.129.161.9,NaN,ORIGINAL,2023,Fevereiro,NaN,"Manaus, Amazonas",Fundação de Hemotologia e Hemoterapia do Amazo...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2386,651,2431,738,0,0,1342,765,3475,624,0,0,3352,632,1465,757,0,0,2029,730,2788,659,85,453,538,51,19,70,3,2,5,3,1,4,51,9,60,7,1,8,6,3,9,0,0,0,0,0,0,426,269,695,38,0,0,0,4817,69,NaN,4763.0,3,4763.0,4,4763.0,60,4763.0,8,4763.0,31,4763.0,12,4763.0,5,4763.0,0,0.0,0,0.0,0,0.0,0,1178.0,53,357,10,86,13,2846.0,151,79,0,22,0,4,0,211,0,316,0,1,14,448,11,1,14,1342.0,4763.0,123,13,NaN,4817.0,0,0,614,0,21,0,0,0,4229.0,0,461,0,0,0,3501.0,0,461,0,0,0,0,0,0,285,0,7,0,0,0,0,0,102,7,4,144,0,0,0,2,14,22,0,0,0,6,899,73,0,0,0,0,0,0,2,3,0,0,0,0,0,0,0,8,14,22,0,0,0,67,72,139,0,0,0,161,374,535,0,0,0,0,0,0,0,22,22,0,0,0,0,0,0,842,39,881,0,0,0,4774,640,5414,0,0,0,2072,0,2072,0,0,0,0,0,0,397,0,397,0,0,0,75,1223,0,308,180,2,0,2,0,0,0,0,0,0,NaN
2,9,2023-10-31 11:14:51,4,pt-BR,2072510604,1vXXcXvg3W0RfaG,2023-10-31 10:49:55,2023-10-31 11:14:51,200.129.161.9,NaN,ORIGINAL,2023,Março,NaN,"Manaus, Amazonas",Fundação Hospitalar de Hematologia e Hemoterap...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2281,620,3338,1012,0,0,1589,964,4030,668,0,0,3864,684,1755,948,0,0,2234,877,3385,755,75,582,657,34,10,44,0,0,0,2,0,2,26,7,33,3,0,3,3,0,3,0,0,0,1,0,1,540,349,889,29,0,0,0,5619,57,NaN,5496.0,5,5496.0,12,5496.0,74,5496.0,13,5496.0,71,5496.0,11,5496.0,4,5496.0,0,0.0,0,0.0,0,0.0,0,1343.0,66,405,12,100,8,3344.0,204,95,6,37,0,9,0,251,6,392,12,3,20,537,22,3,20,1589.0,5496.0,190,15,NaN,5634.0,0,0,1626,0,32,0,0,0,4757.0,0,1048,0,0,0,3644.0,0,484,0,0,0,0,0,0,644,0,0,0,0,0,0,0,155,5,1,195,0,0,0,8,2,28,0,0,0,10,519,159,0,0,0,0,0,0,0,9,2,0,0,0,0,0,0,4,4,8,0,0,0,137,69,206,0,0,0,240,716,956,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1035,32,1067,0,0,0,5202,679,5881,0,0,0,2233,0,2233,0,0,0,0,0,0,612,0,612,0,0,0,74,1668,0,446,187,5,0,1,0,0,0,0,0,0,NaN
3,10,2023-10-31 12:16:31,4,pt-BR,411593062,1vXXcXvg3W0RfaG,2023-10-31 11:17:44,2023-10-31 12:16:31,200.129.161.9,NaN,ORIGINAL,2023,Abril,NaN,"Manaus, Amazonas",Fundação Hospitalar de Hematologia e Hemoterap...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2839,617,3280,982,0,0,1756,921,4363,678,0,0,3985,579,2134,1020,0,0,2344,730,3775,869,82,640,722,40,15,55,1,4,5,0,0,0,17,7,24,12,3,15,5,0,5,0,0,0,4,0,4,418,351,769,94,0,0,0,6119,64,NaN,6076.0,5,6076.0,10,6076.0,78,6076.0,10,6076.0,56,6076.0,16,6076.0,10,6076.0,0,0.0,0,0.0,0,0.0,0,1550.0,62,494,12,119,7,3628.0,206,82,6,33,0,7,0,259,3,381,9,0,14,546,14,0,14,1759.0,6076.0,185,15,NaN,6119.0,0,0,1510,0,21,0,0,0,5299.0,0,966,0,0,0,4060.0,0,544,0,0,0,0,0,0,497,0,9,0,0,0,0,0,152,2,0,242,0,0,0,4,16,9,0,0,0,9,862,57,0,0,0,0,0,0,11,0,34,0,0,0,0,0,0,12,0,12,0,0,0,132,71,203,0,0,0,424,413,837,0,0,0,0,0,0,0,63,63,0,0,0,0,0,0,1086,32,1118,0,0,0,5087,585,5672,0,0,0,2161,0,2161,0,0,0,0,0,0,395,0,395,0,0,0,43,1699,0,276,172,2,0,1,0,0,1,0,0,0,NaN
4,11,2023-10-31 13:06:36,4,pt-BR,542798905,1vXXcXvg3W0RfaG,2023-10-31 12:19:45,2023-10-31 13:06:36,200.129.161.9,NaN,ORIGINAL,2023,Maio,NaN,"Manaus, Amazonas",Fundação Hospitalar de Hematologia e Hemoterap...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2297,597,3368,1048,0,0,1595,911,4070,734,0,0,3796,629,1869,1016,0,0,2368,801,3297,844,64,553,617,34,10,44,0,1,1,1,0,1,23,13,36,10,0,10,3,3,6,0,0,0,1,0,1,493,436,929,75,0,0,0,5665,84,NaN,5632.0,1,5632.0,11,5632.0,86,5632.0,11,5632.0,50,5632.0,10,5632.0,9,5632.0,0,0.0,0,0.0,0,0.0,0,1326.0,63,462,29,89,1,3179.0,188,97,7,29,0,5,0,272,1,403,8,6,10,516,20,6,10,1595.0,5632.0,178,3,NaN,5665.0,0,0,1594,0,25,0,0,0,4745.0,0,867,0,0,0,3383.0,0,560,0,0,0,0,0,0,493,0,0,0,0,0,0,0,75,8,0,214,0,0,0,9,35,13,0,0,0,2,465,50,0,0,0,0,0,0,5,0,8,0,0,0,0,0,0,4,3,7,0,0,0,123,78,201,0,0,0,205,427,632,0,0,0,0,0,0,0,21,21,0,0,0,0,0,0,953,33,986,0,0,0,5167,811,5978,0,0,0,2256,0,2256,0,0,0,0,0,0,439,0,439,0,0,0,59,1580,0,296,132,3,0,4,0,0,0,0,0,0,NaN
5,12,2023-10-31 13:36:54,4,pt-BR,320740727,1vXXcXvg3W0RfaG,2023-10-31 13:18:44,2023-10-31 13:36:54,200.129.161.9,NaN,ORIGINAL,2023,Junho,NaN,"Manaus, Amazonas",Fundação Hospitalar de Hematologia e Hemoterap...,NaN,63678320000115,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,2616,711,3026,934,0,0,1487,880,4155,765,0,0,3794,675,1848,970,0,0,2151,779,3491,866,114,579,693,44,9,53,0,2,2,2,0,2,25,9,34,8,0,8,3,1,4,0,0,0,3,1,4,476,369,845,110,0,0,0,5642,72,NaN,5611.0,0,5611.0,5,5611.0,77,5611.0,6,5611.0,53,5611.0,12,5611.0,12,5611.0,0,0.0,0,0.0,0,0.0,0,1268.0,44,378,14,95,1,3594.0,118,113,5,28,0,8,0,258,2,407,7,5,12,508,14,5,12,1487.0,5611.0,165,21,NaN,5642.0,0,0,1541,0,28,0,0,0,4695.0,0,949,0,0,0,3328.0,0,507,0,0,0,0,0,0,543,0,4,0,0,0,2,0,168,0,1,178,0,0,0,5,74,12,0,0,0,10,487,76,0,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,890,890,0,0,0,89,4283,4372,0,0,0,150,1782,1932,0,0,0,0,0,0,0,408,408,0,0,0,0,0,0,954,30,984,0,0,0,5090,677,5767,0,0,0,2497,0,2497,0,0,0,0,0,0,390,0,390,0,0,0,60,1162,0,355,178,0,0,2,0,0,0,0,0,0,NaN

In [13]:
hemoprod_am.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Columns: 269 entries, id to hemoprod_3_observacoes
dtypes: Int64(229), datetime64[ns](1), float64(27), object(12)
memory usage: 74.5+ KB

In [14]:
hemoprod_am_deduplicado.to_excel('dados_processados/hemoprod_am.xlsx', index=False)

## Hemoprod Amapa

In [19]:
import pandas as pd
import os

# --- 1. Defina os caminhos para seus arquivos ---
# Ajuste os caminhos conforme a estrutura do seu projeto no notebook
dados_brutos_path = 'dados_brutos'
dicionario_path = 'dicionario_colunas_269.xlsx'
arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_AP.xlsx')
nome_planilha = 'HEMOPROD - AMAPA'

try:
    # Carrega o arquivo de dados
    hemoprod_ap = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)
    print("Arquivo de dados carregado com sucesso.")
    print(f"Número de colunas original: {len(hemoprod_ap.columns)}")

    # Carrega o arquivo de dicionário
    dicionario = pd.read_excel(dicionario_path)
    print("Arquivo de dicionário carregado com sucesso.")

    # --- 3. Limpeza Inicial dos Nomes das Colunas (ADICIONADO) ---
    # Mapeia as colunas, limpando espaços em branco no início e fim
    # e substituindo o caractere \xa0 (Non-breaking space) por um espaço normal.
    mapa_limpeza = {
        col: col.strip().replace('\xa0', ' ') 
        for col in hemoprod_ap.columns
    }

    # Aplica a renomeação para limpar os nomes
    hemoprod_ap = hemoprod_ap.rename(columns=mapa_limpeza)
    print("Nomes das colunas do DataFrame limpos e padronizados (strip/\\xa0).")

    # --- 4. Crie o dicionário de mapeamento ---
    # Cria um dicionário no formato {'nome_original': 'nome_sql'} para uso no .rename()
    # NOTA: O 'nome_original' no dicionário TAMBÉM deve estar limpo para combinar.
    # Se o dicionário não estiver limpo, adicione a mesma limpeza aqui:
    dicionario['nome_original'] = dicionario['nome_original'].astype(str).str.strip().str.replace('\xa0', ' ')
    
    mapa_renomeacao = pd.Series(dicionario['nome_sql'].values, index=dicionario['nome_original']).to_dict()
    
    # Lista dos nomes de coluna no DataFrame atual APÓS a limpeza inicial
    colunas_atuais = set(hemoprod_ap.columns)
    
    # Lista dos nomes originais de coluna no dicionário APÓS a limpeza (se aplicada)
    colunas_originais_dicionario = set(dicionario['nome_original'].tolist())
    
    # Lista dos nomes SQL (os desejados) no dicionário
    colunas_sql_desejadas = set(dicionario['nome_sql'].tolist())
    
    # --- 5. Renomeie as colunas com base no mapeamento (nome_original -> nome_sql) ---
    print("\n--- Processo de Renomeação ---")
    hemoprod_ap.rename(columns=mapa_renomeacao, inplace=True)
    print("Colunas renomeadas com sucesso (apenas as que existiam no dicionário foram modificadas).")


   # --- 4. Inferir Tipos e Criar Mapeamento de Tipos ---
    
    # --- Lógica de Inferência customizada para 'Int64' ---
    tipos_inferidos = {}
    for col in hemoprod_ap.columns:
        
        # 4.1. Tenta converter a coluna para o tipo que melhor representa seus dados (incluindo Int64/string/datetime)
        # O errors='ignore' é crucial para não falhar se a coluna não puder ser convertida
        coluna_convertida = pd.to_numeric(hemoprod_ap[col], errors='coerce')
        
        # Se a conversão for bem-sucedida (não é totalmente NaN, nem totalmente string)
        if not coluna_convertida.isna().all() and coluna_convertida.dtype.kind in 'fi': # 'f' para float, 'i' para int
            
            # Se a coluna parecer um número, tentamos forçar para Int64
            # O .astype('Int64') usa o tipo inteiro que suporta NaN
            try:
                # Se for possível converter para Int64, use 'Int64'
                hemoprod_ap[col] = hemoprod_ap[col].astype('Int64')
                tipos_inferidos[col] = 'Int64'
            except Exception:
                # Se for numérico mas não puder ser Int64 (ex: float com muitas casas decimais), use 'float64'
                tipos_inferidos[col] = 'float64'
        
        # Verifica se é data/hora
        elif pd.api.types.is_datetime64_any_dtype(hemoprod_ap[col]):
             tipos_inferidos[col] = 'datetime64[ns]'
             
        # Caso contrário, assume-se que é um texto/string
        else:
            tipos_inferidos[col] = 'object' # O padrão para string no pandas

    
    print("\nTipos de dados inferidos (amostra):")
    for i, (col, dtype) in enumerate(tipos_inferidos.items()):
        if i < 5:
            print(f"  {col}: {dtype}")
        if i == 5:
            print("  ...")
    
    # --- 5. Atualizar o DataFrame Dicionário ---
    
    # 5.1. Cria a coluna 'tipo_dados' no dicionário e preenche com os tipos inferidos
    dicionario['tipo_dados'] = dicionario['nome_sql'].map(tipos_inferidos)
    
    # 5.2. Trata colunas não encontradas no DataFrame de dados
    dicionario['tipo_dados'] = dicionario['tipo_dados'].fillna('object')
    
    print("\n--- Dicionário Atualizado ---")
    print("Coluna 'tipo_dados' criada com sucesso, com numéricos definidos como 'Int64' ou 'float64'.")
    
    # --- 6. Salvar o Dicionário Atualizado ---

    # Sugestão de novo caminho para salvar
    # novo_dicionario_path = 'dicionario_colunas_269_COM_TIPOS_V3.xlsx'
    
    # dicionario.to_excel(novo_dicionario_path, index=False)
    
    print(f"\n✅ Dicionário salvo com a nova coluna 'tipo_dados' em: {novo_dicionario_path}")
    print("\nPrimeiras linhas do dicionário atualizado:")
    display(dicionario.head())

    # --- 6. Análise de Colunas (Qualidade dos Dados) ---

    # 6.1. Colunas que não puderam ser renomeadas (existem no DF, mas não no 'nome_original' do dicionário)
    # Aqui usamos as colunas atuais ANTES da renomeação para ver o que sobrou.
    colunas_nao_mapeadas = [
        col for col in colunas_atuais 
        if col not in colunas_originais_dicionario
    ]

    print("-" * 30)
    print("Análise de Colunas do DataFrame (hemoprod_ap):")
    print(f"Número de colunas não mapeadas: {len(colunas_nao_mapeadas)}")
    print(f"Colunas não mapeadas (manterão nome original): {colunas_nao_mapeadas}")
    
    # 6.2. Análise de Colunas Faltantes/A Mais (Comparação com 'nome_sql' desejado)
    colunas_apos_renomeacao = set(hemoprod_ap.columns)
    
    colunas_faltantes = list(colunas_sql_desejadas - colunas_apos_renomeacao)
    colunas_a_mais = list(colunas_apos_renomeacao - colunas_sql_desejadas)

    print("-" * 30)
    print("Análise de Colunas (Comparação com a lista SQL DESEJADA):")
    print(f"Número de colunas FALTANTES: {len(colunas_faltantes)}")
    print(f"Colunas FALTANTES (deveriam estar, mas não estão): {colunas_faltantes}")
    print("-" * 30)
    print(f"Número de colunas A MAIS: {len(colunas_a_mais)}")
    print(f"Colunas A MAIS (estão no DF, mas não na lista SQL desejada): {colunas_a_mais}")
    print("-" * 30)

    # --- 7. Verifique o resultado ---
    print("\nInformações do DataFrame com as novas colunas:")
    hemoprod_ap.info()
    
    print("\nAs 5 primeiras linhas com as novas colunas:")
    display(hemoprod_ap.head())

except FileNotFoundError as e:
    print(f"\nErro de arquivo não encontrado: {e}")
except KeyError as e:
    print(f"\nErro de coluna não encontrada: {e}. Verifique se as colunas 'nome_original' e 'nome_sql' existem no seu arquivo de dicionário.")
except Exception as e:
    print(f"\nOcorreu um erro inesperado: {e}")

Arquivo de dados carregado com sucesso.
Número de colunas original: 269
Arquivo de dicionário carregado com sucesso.
Nomes das colunas do DataFrame limpos e padronizados (strip/\xa0).

--- Processo de Renomeação ---
Colunas renomeadas com sucesso (apenas as que existiam no dicionário foram modificadas).

Tipos de dados inferidos (amostra):
  id: Int64
  data_envio: object
  ultima_pagina: Int64
  idioma_inicial: object
  semente: Int64
  ...

--- Dicionário Atualizado ---
Coluna 'tipo_dados' criada com sucesso, com numéricos definidos como 'Int64' ou 'float64'.

✅ Dicionário salvo com a nova coluna 'tipo_dados' em: dicionario_colunas_269_COM_TIPOS_V2.xlsx

Primeiras linhas do dicionário atualizado:

,nome_original,nome_sql,comentario,tipo_dados
0,ID da resposta,id,Identificador único e chave primária da submis...,Int64
1,Data de envio,data_envio,Data e hora exatas do envio final do formulário.,object
2,Última página,ultima_pagina,Título da última página do formulário acessada...,Int64
3,Idioma inicial,idioma_inicial,Idioma selecionado no início do preenchimento ...,object
4,Semente,semente,Valor interno de semente/aleatorização (uso té...,Int64

------------------------------
Análise de Colunas do DataFrame (hemoprod_ap):
Número de colunas não mapeadas: 0
Colunas não mapeadas (manterão nome original): []
------------------------------
Análise de Colunas (Comparação com a lista SQL DESEJADA):
Número de colunas FALTANTES: 0
Colunas FALTANTES (deveriam estar, mas não estão): []
------------------------------
Número de colunas A MAIS: 0
Colunas A MAIS (estão no DF, mas não na lista SQL desejada): []
------------------------------

Informações do DataFrame com as novas colunas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Columns: 269 entries, id to hemoprod_3_observacoes
dtypes: Int64(247), float64(8), object(14)
memory usage: 2.5+ KB

As 5 primeiras linhas com as novas colunas:

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,8,2025-06-16 13:29:53,4,pt-BR,1663392622,oQ8x1U42tODTlWA,2025-06-16 12:28:39,2025-06-16 13:29:53,177.84.201.126,NaN,RETIFICADORA,2024,Consolidado,NaN,"Macapá, Amapá",Secretaria de Estado de Saúde do Amapá - Insti...,NaN,1762561000190,Hemocentro Coordenador,Público,Rede de serviços,Instituto de Hematologia e Hemoterapia do Amap...,NaN,NaN,6228,1306,10187,2806,0,0,3712,2052,12693,2058,0,0,10078,1922,6338,2190,120,36,5180,1662,11117,2414,0,0,514,0,0,163,0,0,1,0,0,7,0,0,1071,0,0,18,0,0,6,0,0,0,0,0,6,0,0,2326,156,28,602,1120,16259,0,NaN,16168,23,16168,20,16168,142,16168,25,16168,118,16168,45,16168,20,16168,0,16168,2,16168,0,16168,15,3748,2539,1532,1037,244,166,9480,6449,319,209,104,9,27,2,773,525,42,501,16269,9262,3004,64,0,1435,2468,16168,410,216,NaN,410,0,0,15288,0,0,0,0,0,10,0,0,14614,0,0,0,0,0,0,0,0,0,0,0,810,0,0,8926,0,0,0,0,412,67,505,9974,0,0,0,0,0,0,17,50,912,0,0,0,0,0,0,0,0,0,0,0,26,0,644,3104,0,0,0,0,1192,1192,0,0,0,0,0,0,404,3173,3577,0,0,0,0,0,0,0,0,0,0,732,732,0,2236,2236,0,0,0,3806,0,0,0,0,0,0,0,0,13555,0,13555,0,0,0,0,0,0,0,0,0,1028,0,1028,4646,0,4646,0,0,0,1228,4034,0,0,0,0,0,0,2,0,0,NaN

In [ ]:
# hemoprod_ap.head()

,ID da resposta,Data de envio,Última página,Idioma inicial,Semente,Código de acesso,Data de início,Data da última ação,Endereço IP,IDENTIFICAÇÃO DO DADO,"Tipo de Informação Antes de responder ao formulário, declare o tipo de informação que será inserida.",Ano de referência,Período de referência,IDENTIFICAÇÃO DO ESTABELECIMENTO,Município,Razão Social - Nome Fantasia,Razão Social - Nome Fantasia [Outros],CNPJ,Tipo de estabelecimento,Natureza do estabelecimento,Os dados informados referem-se à um(a):,"Cite os estabelecimentos que compõem a rede Informe o Tipo de Estabelecimento, o Nome Fantasia e o Município de localização de cada um.",CNES - Cadastro Nacional de Estabelecimentos de Saúde,Endereço,2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Espontânea][Aptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Espontânea][Inaptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Reposição][Aptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Reposição][Inaptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Autóloga][Aptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Autóloga][Inaptos],2.2 Total de candidatos quanto ao tipo de doador [Primeira vez][Aptos],2.2 Total de candidatos quanto ao tipo de doador [Primeira vez][Inaptos],2.2 Total de candidatos quanto ao tipo de doador [Repetição][Aptos],2.2 Total de candidatos quanto ao tipo de doador [Repetição][Inaptos],2.2 Total de candidatos quanto ao tipo de doador [Esporádico][Aptos],2.2 Total de candidatos quanto ao tipo de doador [Esporádico][Inaptos],2.3 Total de candidatos quanto ao gênero do doador [Masculino][Aptos],2.3 Total de candidatos quanto ao gênero do doador [Masculino][Inaptos],2.3 Total de candidatos quanto ao gênero do doador [Feminino][Aptos],2.3 Total de candidatos quanto ao gênero do doador [Feminino][Inaptos],2.4 Total de candidatos quanto a idade do doador [Menor de 18 anos][Aptos],2.4 Total de candidatos quanto a idade do doador [Menor de 18 anos][Inaptos],2.4 Total de candidatos quanto a idade do doador [18 até 29 anos][Aptos],2.4 Total de candidatos quanto a idade do doador [18 até 29 anos][Inaptos],2.4 Total de candidatos quanto a idade do doador [Acima de 29 anos][Aptos],2.4 Total de candidatos quanto a idade do doador [Acima de 29 anos][Inaptos],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Anemia][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Anemia][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Anemia][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipertensão][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipertensão][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipertensão][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipotensão][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipotensão][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipotensão][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Alcoolismo][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Alcoolismo][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Alcoolismo][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Comportamento de risco para DST][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Comportamento de risco para DST][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Comportamento de risco para DST][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Uso de drogas][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Uso de drogas][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Uso de drogas][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hepatite][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hepatite][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hepatite][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Doença de Chagas][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Doença de Chagas][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Doença de Chagas][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Malária][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Malária][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Malária][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Outras][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Outras][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Outras][Total],3. Coleta 3.1 Total de candidatos desistentes,3.2 Total de interrupções na coleta por [Dificuldade de punção venosa],3.2 Total de interrupções na coleta por [Reação vagal],3.2 Total de interrupções na coleta por [Outros motivos],3.3 Total de coletas [Sangue total],3.3 Total de coletas [Por aférese],HEMOPROD_1 - Observações,4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Doença de Chagas][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Doença de Chagas][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Sífilis ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Sífilis ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - HBs Ag ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - HBs Ag ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - Anti HBc ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - Anti HBc ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite C][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite C][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HTLV I e II ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HTLV I e II ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Malária][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Malária][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HBV (Teste NAT)*][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HBV (Teste NAT)*][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HCV (Teste NAT)*][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HCV (Teste NAT)*][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV (Teste NAT)*][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV (Teste NAT)*][Amostras reagentes],4.2 Imunohematologia [A+][Doador],4.2 Imunohematologia [A+][Receptor],4.2 Imunohematologia [B+][Doador],4.2 Imunohematologia [B+][Receptor],4.2 Imunohematologia [AB+][Doador],4.2 Imunohematologia [AB+][Receptor],4.2 Imunohematologia [O+][Doador],4.2 Imunohematologia [O+][Receptor],4.2 Imunohematologia [A-][Doador],4.2 Imunohematologia [A-][Receptor],4.2 Imunohematologia [B-][Doador],4.2 Imunohematologia [B-][Receptor],4.2 Imunohematologia [AB-][Doador],4.2 Imunohematologia [AB-][Receptor],4.2 Imunohematologia [O-][Doador],4.2 Imunohematologia [O-][Receptor],4.2 Imunohematologia [Dfraco][Doador],4.2 Imunohematologia [Dfraco][Receptor],4.2 Imunohematologia [Pesquisa de anticorpo irregular positivo][Doador],4.2 Imunohematologia [Pesquisa de anticorpo irregular positivo][Receptor],4.2 Imunohematologia [Fenotipagem][Doador],4.2 Imunohematologia [Fenotipagem][Receptor],4.2 Imunohematologia [Combs Direto][Doador],4.2 Imunohematologia [Combs Direto][Receptor],4.3 Outros tipos de pesquisa [Pesquisa de HbS no doador],4.4 Inaptidão na triagem laboratorial [Total de bolsas testadas],4.4 Inaptidão na triagem laboratorial [Total de bolsas reagentes para 1 ou mais marcadores],5. Descarte de Bolsas 5.1 Descarte de bolsas [Total de bolsas descartadas por auto-exclusão],HEMOPROD_2 - Observações,6. Produção Hemoterápica 6.1(a) Entradas [Sangue total][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Sangue total][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Sangue total][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma Fresco Congelado][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma Fresco Congelado][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma Fresco Congelado][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma comum][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma comum][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma comum][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias sem buffy coat][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias sem buffy coat][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias sem buffy coat][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas de Aférese][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas de Aférese][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas de Aférese][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Leucócitos][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Leucócitos][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Leucócitos][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Crioprecipitado][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Crioprecipitado][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Crioprecipitado][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas sem buffy coat][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas sem buffy coat][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas sem buffy coat][Devolvidas],6.1(b) Perdas [Sangue total][Rompimento de Bolsa],6.1(b) Perdas [Sangue total][Validade],6.1(b) Perdas [Sangue total][Outros motivos],6.1(b) Perdas [Plasma Fresco Congelado][Rompimento de Bolsa],6.1(b) Perdas [Plasma Fresco Congelado][Validade],6.1(b) Perdas [Plasma Fresco Congelado][Outros motivos],6.1(b) Perdas [Plasma comum][Rompimento de Bolsa],6.1(b) Perdas [Plasma comum][Validade],6.1(b) Perdas [Plasma comum][Outros motivos],6.1(b) Perdas [Concentrado de Hemácias][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Hemácias][Validade],6.1(b) Perdas [Concentrado de Hemácias][Outros motivos],6.1(b) Perdas [Concentrado de Hemácias sem buffy coat][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Hemácias sem buffy coat][Validade],6.1(b) Perdas [Concentrado de Hemácias sem buffy coat][Outros motivos],6.1(b) Perdas [Concentrado de Plaquetas][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Plaquetas][Validade],6.1(b) Perdas [Concentrado de Plaquetas][Outros motivos],6.1(b) Perdas [Concentrado de Plaquetas de Aférese][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Plaquetas de Aférese][Validade],6.1(b) Perdas [Concentrado de Plaquetas de Aférese][Outros motivos],6.1(b) Perdas [Concentrado de Leucócitos][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Leucócitos][Validade],6.1(b) Perdas [Concentrado de Leucócitos][Outros motivos],6.1(b) Perdas [Crioprecipitado][Rompimento de Bolsa],6.1(b) Perdas [Crioprecipitado][Validade],6.1(b) Perdas [Crioprecipitado][Outros motivos],6.1(b) Perdas [Concentrado de Plaquetas sem buffy coat][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Plaquetas sem buffy coat][Validade],6.1(b) Perdas [Concentrado de Plaquetas sem buffy coat][Outros motivos],6.1(c) Tranfusões [Sangue total][Ambulatorial],6.1(c) Tranfusões [Sangue total][Hospitalar],6.1(c) Tranfusões [Sangue total][Total],6.1(c) Tranfusões [Plasma Fresco Congelado][Ambulatorial],6.1(c) Tranfusões [Plasma Fresco Congelado][Hospitalar],6.1(c) Tranfusões [Plasma Fresco Congelado][Total],6.1(c) Tranfusões [Plasma comum][Ambulatorial],6.1(c) Tranfusões [Plasma comum][Hospitalar],6.1(c) Tranfusões [Plasma comum][Total],6.1(c) Tranfusões [Concentrado de Hemácias][Ambulatorial],6.1(c) Tranfusões [Concentrado de Hemácias][Hospitalar],6.1(c) Tranfusões [Concentrado de Hemácias][Total],6.1(c) Tranfusões [Concentrado de Hemácias sem buffy coat][Ambulatorial],6.1(c) Tranfusões [Concentrado de Hemácias sem buffy coat][Hospitalar],6.1(c) Tranfusões [Concentrado de Hemácias sem buffy coat][Total],6.1(c) Tranfusões [Concentrado de Plaquetas][Ambulatorial],6.1(c) Tranfusões [Concentrado de Plaquetas][Hospitalar],6.1(c) Tranfusões [Concentrado de Plaquetas][Total],6.1(c) Tranfusões [Concentrado de Plaquetas de Aférese][Ambulatorial],6.1(c) Tranfusões [Concentrado de Plaquetas de Aférese][Hospitalar],6.1(c) Tranfusões [Concentrado de Plaquetas de Aférese][Total],6.1(c) Tranfusões [Concentrado de Leucócitos][Ambulatorial],6.1(c) Tranfusões [Concentrado de Leucócitos][Hospitalar],6.1(c) Tranfusões [Concentrado de Leucócitos][Total],6.1(c) Tranfusões [Crioprecipitado][Ambulatorial],6.1(c) Tranfusões [Crioprecipitado][Hospitalar],6.1(c) Tranfusões [Crioprecipitado][Total],6.1(c) Tranfusões [Concentrado de Plaquetas sem buffy coat][Ambulatorial],6.1(c) Tranfusões [Concentrado de Plaquetas sem buffy coat][Hospitalar],6.1(c) Tranfusões [Concentrado de Plaquetas sem buffy coat][Total],6.1(d) Distribuição para outros serviços [Sangue total][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Sangue total][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Sangue total][Total],6.1(d) Distribuição para outros serviços [Plasma Fresco Congelado][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma Fresco Congelado][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma Fresco Congelado][Total],6.1(d) Distribuição para outros serviços [Plasma comum][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma comum][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma comum][Total],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias][Total],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias sem buffy coat][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias sem buffy coat][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias sem buffy coat][Total],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas][Total],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas de Aférese][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas de Aférese][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas de Aférese][Total],6.1(d) Distribuição para outros serviços [Concentrado de Leucócitos][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Leucócitos][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Leucócitos][Total],6.1(d) Distribuição para outros serviços [Crioprecipitado][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Crioprecipitado][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Crioprecipitado][Total],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas sem buffy coat][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas sem buffy coat][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas sem buffy coat][Total],6.2 Procedimentos de modificação dos hemocomponentes [6.2.1 Lavagem],6.2 Procedimentos de modificação dos hemocomponentes [6.2.2 Irradiação],6.2 Procedimentos de modificação dos hemocomponentes [6.2.3(a) Filtração em Concentrado de Plaquetas],6.2 Procedimentos de modificação dos hemocomponentes [6.2.3(b) Filtração em Concentrado de Hemácias],6.2 Procedimentos de modificação dos hemocomponentes [6.2.4 Fracionamento pediátrico],7 Reações Transfusionais [Reação Febril não Hemolítica],7 Reações Transfusionais [Reação Hemolítica],7 Reações Transfusionais [Reação Alérgica],7 Reações Transfusionais [Choque Bacteriano],7 Reações Transfusionais [Alterações Metabólicas],7 Reações Transfusionais [Sobrecarga Volêmica],7 Reações Transfusionais [Outras reações ],8. Envio de Plasma para produção de hemoderivados [Plasma Fresco Congelado],8. Envio de Plasma para produção de hemoderivados [Plasma Comum],HEMOPROD_3 - Observações
0,8,2025-06-16 13:29:53,4,pt-BR,1663392622,oQ8x1U42tODTlWA,2025-06-16 12:28:39,2025-06-16 13:29:53,177.84.201.126,NaN,RETIFICADORA,2024,Consolidado,NaN,"Macapá, Amapá",Secretaria de Estado de Saúde do Amapá - Insti...,NaN,1762561000190,Hemocentro Coordenador,Público,Rede de serviços,Instituto de Hematologia e Hemoterapia do Amap...,NaN,NaN,6228,1306,10187,2806,0,0,3712,2052,12693,2058,0,0,10078,1922,6338,2190,120,36,5180,1662,11117,2414,0,0,514,0,0,163,0,0,1,0,0,7,0,0,1071,0,0,18,0,0,6,0,0,0,0,0,6,0,0,2326,156,28,602,1120,16259,0,NaN,16168,23,16168,20,16168,142,16168,25,16168,118,16168,45,16168,20,16168,0,16168,2,16168,0,16168,15,3748,2539,1532,1037,244,166,9480,6449,319,209,104,9,27,2,773,525,42,501,16269,9262,3004,64,0,1435,2468,16168,410,216,NaN,410,0,0,15288,0,0,0,0,0,10,0,0,14614,0,0,0,0,0,0,0,0,0,0,0,810,0,0,8926,0,0,0,0,412,67,505,9974,0,0,0,0,0,0,17,50,912,0,0,0,0,0,0,0,0,0,0,0,26,0,644,3104,0,0,0,0,1192,1192,0,0,0,0,0,0,404,3173,3577,0,0,0,0,0,0,0,0,0,0,732,732,0,2236,2236,0,0,0,3806,0,0,0,0,0,0,0,0,13555,0,13555,0,0,0,0,0,0,0,0,0,1028,0,1028,4646,0,4646,0,0,0,1228,4034,0,0,0,0,0,0,2,0,0,NaN

In [ ]:
# print("--- Nomes das Colunas (um por linha) ---")
# for coluna in hemoprod_ap.columns:
#     print(coluna + ",")

--- Nomes das Colunas (um por linha) ---
ID da resposta,
Data de envio,
Última página,
Idioma inicial,
Semente,
Código de acesso,
Data de início,
Data da última ação,
Endereço IP,
IDENTIFICAÇÃO DO DADO ,
Tipo de Informação  Antes de responder ao formulário, declare o tipo de informação que será inserida.  ,
Ano de referência ,
Período de referência,
IDENTIFICAÇÃO DO ESTABELECIMENTO ,
Município,
Razão Social - Nome Fantasia ,
Razão Social - Nome Fantasia  [Outros],
CNPJ,
Tipo de estabelecimento,
Natureza do estabelecimento,
Os dados informados referem-se à um(a): ,
Cite os estabelecimentos que compõem a rede  Informe o Tipo de Estabelecimento, o Nome Fantasia e o Município de localização de cada um. ,
CNES - Cadastro Nacional de Estabelecimentos de Saúde ,
Endereço,
2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Espontânea][Aptos],
2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Espontânea][Inaptos],
2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Reposição][Aptos],
2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Reposição][Inaptos],
2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Autóloga][Aptos],
2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Autóloga][Inaptos],
2.2 Total de candidatos quanto ao tipo de doador  [Primeira vez][Aptos],
2.2 Total de candidatos quanto ao tipo de doador  [Primeira vez][Inaptos],
2.2 Total de candidatos quanto ao tipo de doador  [Repetição][Aptos],
2.2 Total de candidatos quanto ao tipo de doador  [Repetição][Inaptos],
2.2 Total de candidatos quanto ao tipo de doador  [Esporádico][Aptos],
2.2 Total de candidatos quanto ao tipo de doador  [Esporádico][Inaptos],
2.3 Total de candidatos quanto ao gênero do doador  [Masculino][Aptos],
2.3 Total de candidatos quanto ao gênero do doador  [Masculino][Inaptos],
2.3 Total de candidatos quanto ao gênero do doador  [Feminino][Aptos],
2.3 Total de candidatos quanto ao gênero do doador  [Feminino][Inaptos],
2.4 Total de candidatos quanto a idade do doador  [Menor de 18 anos][Aptos],
2.4 Total de candidatos quanto a idade do doador  [Menor de 18 anos][Inaptos],
2.4 Total de candidatos quanto a idade do doador  [18 até 29 anos][Aptos],
2.4 Total de candidatos quanto a idade do doador  [18 até 29 anos][Inaptos],
2.4 Total de candidatos quanto a idade do doador  [Acima de 29 anos][Aptos],
2.4 Total de candidatos quanto a idade do doador  [Acima de 29 anos][Inaptos],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Anemia][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Anemia][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Anemia][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipertensão][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipertensão][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipertensão][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipotensão][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipotensão][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipotensão][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Alcoolismo][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Alcoolismo][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Alcoolismo][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Comportamento de risco para DST][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Comportamento de risco para DST][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Comportamento de risco para DST][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Uso de drogas][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Uso de drogas][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Uso de drogas][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hepatite][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hepatite][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hepatite][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Doença de Chagas][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Doença de Chagas][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Doença de Chagas][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Malária][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Malária][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Malária][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Outras][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Outras][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Outras][Total],
3. Coleta  3.1 Total de candidatos desistentes ,
3.2 Total de interrupções na coleta por [Dificuldade de punção venosa],
3.2 Total de interrupções na coleta por [Reação vagal],
3.2 Total de interrupções na coleta por [Outros motivos],
3.3 Total de coletas [Sangue total],
3.3 Total de coletas [Por aférese],
HEMOPROD_1 - Observações,
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Doença de Chagas][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Doença de Chagas][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HIV][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HIV][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Sífilis ][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Sífilis ][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite B - HBs Ag ][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite B - HBs Ag ][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite B - Anti HBc ][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite B - Anti HBc ][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite C][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite C][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HTLV I e II ][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HTLV I e II ][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Malária][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Malária][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HBV (Teste NAT)*][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HBV (Teste NAT)*][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HCV (Teste NAT)*][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HCV (Teste NAT)*][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HIV (Teste NAT)*][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HIV (Teste NAT)*][Amostras reagentes],
4.2 Imunohematologia [A+][Doador],
4.2 Imunohematologia [A+][Receptor],
4.2 Imunohematologia [B+][Doador],
4.2 Imunohematologia [B+][Receptor],
4.2 Imunohematologia [AB+][Doador],
4.2 Imunohematologia [AB+][Receptor],
4.2 Imunohematologia [O+][Doador],
4.2 Imunohematologia [O+][Receptor],
4.2 Imunohematologia [A-][Doador],
4.2 Imunohematologia [A-][Receptor],
4.2 Imunohematologia [B-][Doador],
4.2 Imunohematologia [B-][Receptor],
4.2 Imunohematologia [AB-][Doador],
4.2 Imunohematologia [AB-][Receptor],
4.2 Imunohematologia [O-][Doador],
4.2 Imunohematologia [O-][Receptor],
4.2 Imunohematologia [Dfraco][Doador],
4.2 Imunohematologia [Dfraco][Receptor],
4.2 Imunohematologia [Pesquisa de anticorpo irregular positivo][Doador],
4.2 Imunohematologia [Pesquisa de anticorpo irregular positivo][Receptor],
4.2 Imunohematologia [Fenotipagem][Doador],
4.2 Imunohematologia [Fenotipagem][Receptor],
4.2 Imunohematologia [Combs Direto][Doador],
4.2 Imunohematologia [Combs Direto][Receptor],
4.3 Outros tipos de pesquisa [Pesquisa de HbS no doador],
4.4 Inaptidão na triagem laboratorial [Total de bolsas testadas],
4.4 Inaptidão na triagem laboratorial [Total de bolsas reagentes para 1 ou mais marcadores],
5. Descarte de Bolsas  5.1 Descarte de bolsas  [Total de bolsas descartadas por auto-exclusão],
HEMOPROD_2 - Observações,
6. Produção Hemoterápica  6.1(a) Entradas   [Sangue total][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Sangue total][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Sangue total][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Plasma Fresco Congelado][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Plasma Fresco Congelado][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Plasma Fresco Congelado][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Plasma comum][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Plasma comum][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Plasma comum][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias sem buffy coat][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias sem buffy coat][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias sem buffy coat][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas de Aférese][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas de Aférese][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas de Aférese][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Leucócitos][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Leucócitos][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Leucócitos][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Crioprecipitado][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Crioprecipitado][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Crioprecipitado][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas sem buffy coat][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas sem buffy coat][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas sem buffy coat][Devolvidas],
6.1(b) Perdas  [Sangue total][Rompimento de Bolsa],
6.1(b) Perdas  [Sangue total][Validade],
6.1(b) Perdas  [Sangue total][Outros motivos],
6.1(b) Perdas  [Plasma Fresco Congelado][Rompimento de Bolsa],
6.1(b) Perdas  [Plasma Fresco Congelado][Validade],
6.1(b) Perdas  [Plasma Fresco Congelado][Outros motivos],
6.1(b) Perdas  [Plasma comum][Rompimento de Bolsa],
6.1(b) Perdas  [Plasma comum][Validade],
6.1(b) Perdas  [Plasma comum][Outros motivos],
6.1(b) Perdas  [Concentrado de Hemácias][Rompimento de Bolsa],
6.1(b) Perdas  [Concentrado de Hemácias][Validade],
6.1(b) Perdas  [Concentrado de Hemácias][Outros motivos],
6.1(b) Perdas  [Concentrado de Hemácias sem buffy coat][Rompimento de Bolsa],
6.1(b) Perdas  [Concentrado de Hemácias sem buffy coat][Validade],
6.1(b) Perdas  [Concentrado de Hemácias sem buffy coat][Outros motivos],
6.1(b) Perdas  [Concentrado de Plaquetas][Rompimento de Bolsa],
6.1(b) Perdas  [Concentrado de Plaquetas][Validade],
6.1(b) Perdas  [Concentrado de Plaquetas][Outros motivos],
6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Rompimento de Bolsa],
6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Validade],
6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Outros motivos],
6.1(b) Perdas  [Concentrado de Leucócitos][Rompimento de Bolsa],
6.1(b) Perdas  [Concentrado de Leucócitos][Validade],
6.1(b) Perdas  [Concentrado de Leucócitos][Outros motivos],
6.1(b) Perdas  [Crioprecipitado][Rompimento de Bolsa],
6.1(b) Perdas  [Crioprecipitado][Validade],
6.1(b) Perdas  [Crioprecipitado][Outros motivos],
6.1(b) Perdas  [Concentrado de Plaquetas sem buffy coat][Rompimento de Bolsa],
6.1(b) Perdas  [Concentrado de Plaquetas sem buffy coat][Validade],
6.1(b) Perdas  [Concentrado de Plaquetas sem buffy coat][Outros motivos],
6.1(c) Tranfusões  [Sangue total][Ambulatorial],
6.1(c) Tranfusões  [Sangue total][Hospitalar],
6.1(c) Tranfusões  [Sangue total][Total],
6.1(c) Tranfusões  [Plasma Fresco Congelado][Ambulatorial],
6.1(c) Tranfusões  [Plasma Fresco Congelado][Hospitalar],
6.1(c) Tranfusões  [Plasma Fresco Congelado][Total],
6.1(c) Tranfusões  [Plasma comum][Ambulatorial],
6.1(c) Tranfusões  [Plasma comum][Hospitalar],
6.1(c) Tranfusões  [Plasma comum][Total],
6.1(c) Tranfusões  [Concentrado de Hemácias][Ambulatorial],
6.1(c) Tranfusões  [Concentrado de Hemácias][Hospitalar],
6.1(c) Tranfusões  [Concentrado de Hemácias][Total],
6.1(c) Tranfusões  [Concentrado de Hemácias sem buffy coat][Ambulatorial],
6.1(c) Tranfusões  [Concentrado de Hemácias sem buffy coat][Hospitalar],
6.1(c) Tranfusões  [Concentrado de Hemácias sem buffy coat][Total],
6.1(c) Tranfusões  [Concentrado de Plaquetas][Ambulatorial],
6.1(c) Tranfusões  [Concentrado de Plaquetas][Hospitalar],
6.1(c) Tranfusões  [Concentrado de Plaquetas][Total],
6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Ambulatorial],
6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Hospitalar],
6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Total],
6.1(c) Tranfusões  [Concentrado de Leucócitos][Ambulatorial],
6.1(c) Tranfusões  [Concentrado de Leucócitos][Hospitalar],
6.1(c) Tranfusões  [Concentrado de Leucócitos][Total],
6.1(c) Tranfusões  [Crioprecipitado][Ambulatorial],
6.1(c) Tranfusões  [Crioprecipitado][Hospitalar],
6.1(c) Tranfusões  [Crioprecipitado][Total],
6.1(c) Tranfusões  [Concentrado de Plaquetas sem buffy coat][Ambulatorial],
6.1(c) Tranfusões  [Concentrado de Plaquetas sem buffy coat][Hospitalar],
6.1(c) Tranfusões  [Concentrado de Plaquetas sem buffy coat][Total],
6.1(d) Distribuição para outros serviços     [Sangue total][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Sangue total][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Sangue total][Total],
6.1(d) Distribuição para outros serviços     [Plasma Fresco Congelado][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Plasma Fresco Congelado][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Plasma Fresco Congelado][Total],
6.1(d) Distribuição para outros serviços     [Plasma comum][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Plasma comum][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Plasma comum][Total],
6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias][Total],
6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias sem buffy coat][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias sem buffy coat][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias sem buffy coat][Total],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas][Total],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas de Aférese][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas de Aférese][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas de Aférese][Total],
6.1(d) Distribuição para outros serviços     [Concentrado de Leucócitos][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Leucócitos][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Leucócitos][Total],
6.1(d) Distribuição para outros serviços     [Crioprecipitado][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Crioprecipitado][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Crioprecipitado][Total],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas sem buffy coat][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas sem buffy coat][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas sem buffy coat][Total],
6.2 Procedimentos de modificação dos hemocomponentes [6.2.1 Lavagem],
6.2 Procedimentos de modificação dos hemocomponentes [6.2.2 Irradiação],
6.2 Procedimentos de modificação dos hemocomponentes [6.2.3(a) Filtração em Concentrado de Plaquetas],
6.2 Procedimentos de modificação dos hemocomponentes [6.2.3(b) Filtração em Concentrado de Hemácias],
6.2 Procedimentos de modificação dos hemocomponentes [6.2.4 Fracionamento pediátrico],
7 Reações Transfusionais [Reação Febril não Hemolítica],
7 Reações Transfusionais [Reação Hemolítica],
7 Reações Transfusionais [Reação Alérgica],
7 Reações Transfusionais [Choque Bacteriano],
7 Reações Transfusionais [Alterações Metabólicas],
7 Reações Transfusionais [Sobrecarga Volêmica],
7 Reações Transfusionais [Outras reações ],
8. Envio de Plasma para produção de hemoderivados [Plasma Fresco Congelado],
8. Envio de Plasma para produção de hemoderivados [Plasma Comum],
HEMOPROD_3 - Observações,

In [18]:
import os
import pandas as pd

dados_brutos_path = 'dados_brutos'

arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_AP.xlsx')
nome_planilha = 'HEMOPROD - AMAPA'

dicionario_path_ap = ('./dicionario_colunas_269.xlsx')
# dicionario_path_ap = ('./dicionario_colunas_270.xlsx')

dicionario_ap = pd.read_excel(dicionario_path_ap, sheet_name='Sheet1')

# --- 2. Carregue os dados e o dicionário ---
try:
    # Carrega o arquivo de dados
    hemoprod_ap = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)
    print("Arquivo de dados carregado com sucesso.")
    print(f"Número de colunas original: {len(hemoprod_ap.columns)}")

    # Carrega o arquivo de dicionário
    dicionario = pd.read_excel(dicionario_path_ap)
    print("Arquivo de dicionário carregado com sucesso.")

    # --- 3. Extraia a lista de novos nomes ---
    # Pega os valores da coluna 'nome_sql' e converte para uma lista
    novos_nomes = dicionario['nome_sql'].tolist()
    print(f"Número de novos nomes no dicionário: {len(novos_nomes)}")

    # --- 4. Verificação de segurança (MUITO IMPORTANTE) ---
    # Garante que o número de colunas é o mesmo antes de renomear
    if len(hemoprod_ap.columns) == len(novos_nomes):
        print("\nO número de colunas corresponde. Renomeando...")
        
        # --- 5. Substitua os nomes das colunas ---
        # Esta é a linha principal que faz a substituição direta
        hemoprod_ap.columns = novos_nomes
        
        print("Colunas renomeadas com sucesso!")
        
        # --- 6. Verifique o resultado ---
        print("\nInformações do DataFrame com as novas colunas:")
        hemoprod_ap.info()
        
        print("\nAs 5 primeiras linhas com as novas colunas:")
        display(hemoprod_ap.head())

    else:
        # Mensagem de erro se o número de colunas for diferente
        print("\n--- ERRO ---")
        print("A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.")
        print(f"Colunas no arquivo de dados: {len(hemoprod_ap.columns)}")
        print(f"Nomes no dicionário: {len(novos_nomes)}")

except FileNotFoundError as e:
    print(f"\nErro de arquivo não encontrado: {e}")
except KeyError as e:
    print(f"\nErro de coluna não encontrada: {e}. Verifique se a coluna 'nome_sql' existe no seu arquivo de dicionário.")
except Exception as e:
    print(f"\nOcorreu um erro inesperado: {e}")

Arquivo de dados carregado com sucesso.
Número de colunas original: 269
Arquivo de dicionário carregado com sucesso.
Número de novos nomes no dicionário: 269

O número de colunas corresponde. Renomeando...
Colunas renomeadas com sucesso!

Informações do DataFrame com as novas colunas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Columns: 269 entries, id to hemoprod_3_observacoes
dtypes: float64(8), int64(247), object(14)
memory usage: 2.2+ KB

As 5 primeiras linhas com as novas colunas:

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,8,2025-06-16 13:29:53,4,pt-BR,1663392622,oQ8x1U42tODTlWA,2025-06-16 12:28:39,2025-06-16 13:29:53,177.84.201.126,NaN,RETIFICADORA,2024,Consolidado,NaN,"Macapá, Amapá",Secretaria de Estado de Saúde do Amapá - Insti...,NaN,1762561000190,Hemocentro Coordenador,Público,Rede de serviços,Instituto de Hematologia e Hemoterapia do Amap...,NaN,NaN,6228,1306,10187,2806,0,0,3712,2052,12693,2058,0,0,10078,1922,6338,2190,120,36,5180,1662,11117,2414,0,0,514,0,0,163,0,0,1,0,0,7,0,0,1071,0,0,18,0,0,6,0,0,0,0,0,6,0,0,2326,156,28,602,1120,16259,0,NaN,16168,23,16168,20,16168,142,16168,25,16168,118,16168,45,16168,20,16168,0,16168,2,16168,0,16168,15,3748,2539,1532,1037,244,166,9480,6449,319,209,104,9,27,2,773,525,42,501,16269,9262,3004,64,0,1435,2468,16168,410,216,NaN,410,0,0,15288,0,0,0,0,0,10,0,0,14614,0,0,0,0,0,0,0,0,0,0,0,810,0,0,8926,0,0,0,0,412,67,505,9974,0,0,0,0,0,0,17,50,912,0,0,0,0,0,0,0,0,0,0,0,26,0,644,3104,0,0,0,0,1192,1192,0,0,0,0,0,0,404,3173,3577,0,0,0,0,0,0,0,0,0,0,732,732,0,2236,2236,0,0,0,3806,0,0,0,0,0,0,0,0,13555,0,13555,0,0,0,0,0,0,0,0,0,1028,0,1028,4646,0,4646,0,0,0,1228,4034,0,0,0,0,0,0,2,0,0,NaN

In [26]:
# --- 2. Defina as colunas para a chave e para ordenação ---
registros_antes = len(hemoprod_ap)
print(f"Total de registros ANTES da remoção de duplicatas: {registros_antes}")
    

colunas_chave = [
        'cnpj', 
        'ano_referencia', 
        'periodo_referencia', 
        'razao_social_nome_fantasia'
    ]

coluna_data = 'data_envio'

# --- 3. Verifique se as colunas necessárias existem ---
colunas_necessarias = colunas_chave + [coluna_data]

if not all(col in hemoprod_ap.columns for col in colunas_necessarias):
    print("\n--- ERRO ---")
    print("Uma ou mais colunas necessárias para a deduplicação não foram encontradas.")
    colunas_faltantes = [col for col in colunas_necessarias if col not in hemoprod_ap.columns]
    print(f"Colunas necessárias: {colunas_necessarias}")
    print(f"Colunas faltantes no DataFrame: {colunas_faltantes}")
else:
    # --- 4. Prepare a coluna de data e ordene os dados ---
    # Converte a coluna 'data_envio' para datetime para garantir a ordenação correta.
    # 'errors='coerce'' transformará datas inválidas em NaT (Not a Time), que são tratadas como nulas.
    hemoprod_ap[coluna_data] = pd.to_datetime(hemoprod_ap[coluna_data], errors='coerce')

    # Ordena o DataFrame. Os registros com data de envio mais recente ficarão por último.
    print(f"\nOrdenando os dados por '{coluna_data}'...")
    hemoprod_ap_ordenado = hemoprod_ap.sort_values(by=coluna_data, ascending=True)

    # --- 5. Identifique e separe os registros duplicados e únicos ---
    # Em vez de usar drop_duplicates() diretamente, vamos usar duplicated()
    # para criar uma máscara booleana.
    # 'keep='last'' marca todas as ocorrências de uma chave como True, EXCETO a última (a mais recente).
    print(f"Identificando duplicatas com base na chave: {colunas_chave}...")
    mascara_duplicatas = hemoprod_ap_ordenado.duplicated(subset=colunas_chave, keep='last')

    # O DataFrame de removidos conterá todas as linhas marcadas como True
    hemoprod_removidos = hemoprod_ap_ordenado[mascara_duplicatas]
    
    # O DataFrame deduplicado conterá o INVERSO (~) da máscara (linhas marcadas como False)
    hemoprod_ap_deduplicado = hemoprod_ap_ordenado[~mascara_duplicatas]
    
    # Agora podemos contar os registros diretamente dos novos DataFrames
    registros_depois = len(hemoprod_ap_deduplicado)
    registros_removidos = len(hemoprod_removidos) 
    
    # --- 6. Exiba o resultado ---
    print("\n--- Processo Concluído ---")
    print(f"Registros removidos: {registros_removidos}")
    print(f"Total de registros DEPOIS da remoção de duplicatas: {registros_depois}")

    # (Opcional) Exibe a amostra dos removidos
    print("\nAmostra dos dados REMOVIDOS (os mais antigos/duplicados):")
    display(hemoprod_removidos.head(10))

    # Você pode continuar a usar o DataFrame 'hemoprod_ap_deduplicado' para suas análises
    print("\nAmostra dos dados únicos (os mais recentes para cada chave):")
    display(hemoprod_ap_deduplicado.head(10))
    
    # Agora você tem o DataFrame 'hemoprod_removidos' salvo

Total de registros ANTES da remoção de duplicatas: 1

Ordenando os dados por 'data_envio'...
Identificando duplicatas com base na chave: ['cnpj', 'ano_referencia', 'periodo_referencia', 'razao_social_nome_fantasia']...

--- Processo Concluído ---
Registros removidos: 0
Total de registros DEPOIS da remoção de duplicatas: 1

Amostra dos dados REMOVIDOS (os mais antigos/duplicados):

Empty DataFrame
Columns: [id, data_envio, ultima_pagina, idioma_inicial, semente, codigo_acesso, data_inicio, data_ultima_acao, ip, identificacao_dado, tipo_envio, ano_referencia, periodo_referencia, identificacao_estabelecimento, municipio, razao_social_nome_fantasia, razao_social_nome_fantasia_outros, cnpj, tipo_estabelecimento, natureza_estabelecimento, dados_informados_referem_se, rede_estabelecimento, cnes, endereco, triagem_clinica_total_doacao_espontanea_aptos, triagem_clinica_total_doacao_espontanea_inaptos, triagem_clinica_total_doacao_reposicao_aptos, triagem_clinica_total_doacao_reposicao_inaptos, triagem_clinica_total_doacao_autologa_aptos, triagem_clinica_total_doacao_autologa_inaptos, total_doador_primeira_vez_aptos, total_doador_primeira_vez_inaptos, total_doador_repeticao_aptos, total_doador_repeticao_inaptos, total_doador_esporadico_aptos, total_doador_esporadico_inaptos, total_doador_masculino_aptos, total_doador_masculino_inaptos, total_doador_feminino_aptos, total_doador_feminino_inaptos, total_doador_menor_de_18_anos_aptos, total_doador_menor_de_18_anos_inaptos, total_doador_18_ate_29_anos_aptos, total_doador_18_ate_29_anos_inaptos, total_doador_acima_de_29_anos_aptos, total_doador_acima_de_29_anos_inaptos, total_candidatos_inaptos_anemia_masculino, total_candidatos_inaptos_anemia_feminino, total_candidatos_inaptos_anemia_total, total_candidatos_inaptos_hipertensao_masculino, total_candidatos_inaptos_hipertensao_feminino, total_candidatos_inaptos_hipertensao_total, total_candidatos_inaptos_hipotensao_masculino, total_candidatos_inaptos_hipotensao_feminino, total_candidatos_inaptos_hipotensao_total, total_candidatos_inaptos_alcoolismo_masculino, total_candidatos_inaptos_alcoolismo_feminino, total_candidatos_inaptos_alcoolismo_total, total_candidatos_inaptos_comportamento_risco_dst_masculino, total_candidatos_inaptos_comportamento_risco_dst_feminino, total_candidatos_inaptos_comportamento_risco_dst_total, total_candidatos_inaptos_uso_drogas_masculino, total_candidatos_inaptos_uso_drogas_feminino, total_candidatos_inaptos_uso_drogas_total, total_candidatos_inaptos_hepatite_masculino, total_candidatos_inaptos_hepatite_feminino, total_candidatos_inaptos_hepatite_total, total_candidatos_inaptos_doenca_chagas_masculino, total_candidatos_inaptos_doenca_chagas_feminino, total_candidatos_inaptos_doenca_chagas_total, total_candidatos_inaptos_malaria_masculino, total_candidatos_inaptos_malaria_feminino, total_candidatos_inaptos_malaria_total, total_candidatos_inaptos_outras_masculino, total_candidatos_inaptos_outras_feminino, total_candidatos_inaptos_outras_total, coleta_total_candidatos_desistentes, total_interrupcoes_coleta_dificuldade_puncao_venosa, total_interrupcoes_coleta_reacao_vagal, total_interrupcoes_coleta_outros_motivos, total_coletas_sangue_total, total_coletas_aferese, hemoprod_1_observacoes, exames_triagem_doenca_doenca_chagas_amostras_testadas, exames_triagem_doenca_doenca_chagas_amostras_reagentes, exames_triagem_doenca_hiv_amostras_testadas, exames_triagem_doenca_hiv_amostras_reagentes, exames_triagem_doenca_sifilis_amostras_testadas, `exames_triagem_doenca_sifilis_amostras_reagentes, exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas, exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes, exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas, exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes, exames_triagem_doenca_hepatite_c_amostras_testadas, exames_triagem_doenca_hepatite_c_amostras_reagentes, exames_triagem_doenca_htlv_i_ii_amostras_testadas, exames_triagem_doenca_htlv_i_ii_amostras_reagentes, exames_triagem_doenca_malaria_amostras_testadas, exames_triagem_doenca_malaria_amostras_reagentes, exames_triagem_doenca_hbv_teste_nat_amostras_testadas, ...]
Index: []

Amostra dos dados únicos (os mais recentes para cada chave):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,8,2025-06-16 13:29:53,4,pt-BR,1663392622,oQ8x1U42tODTlWA,2025-06-16 12:28:39,2025-06-16 13:29:53,177.84.201.126,NaN,RETIFICADORA,2024,Consolidado,NaN,"Macapá, Amapá",Secretaria de Estado de Saúde do Amapá - Insti...,NaN,1762561000190,Hemocentro Coordenador,Público,Rede de serviços,Instituto de Hematologia e Hemoterapia do Amap...,NaN,NaN,6228,1306,10187,2806,0,0,3712,2052,12693,2058,0,0,10078,1922,6338,2190,120,36,5180,1662,11117,2414,0,0,514,0,0,163,0,0,1,0,0,7,0,0,1071,0,0,18,0,0,6,0,0,0,0,0,6,0,0,2326,156,28,602,1120,16259,0,NaN,16168,23,16168,20,16168,142,16168,25,16168,118,16168,45,16168,20,16168,0,16168,2,16168,0,16168,15,3748,2539,1532,1037,244,166,9480,6449,319,209,104,9,27,2,773,525,42,501,16269,9262,3004,64,0,1435,2468,16168,410,216,NaN,410,0,0,15288,0,0,0,0,0,10,0,0,14614,0,0,0,0,0,0,0,0,0,0,0,810,0,0,8926,0,0,0,0,412,67,505,9974,0,0,0,0,0,0,17,50,912,0,0,0,0,0,0,0,0,0,0,0,26,0,644,3104,0,0,0,0,1192,1192,0,0,0,0,0,0,404,3173,3577,0,0,0,0,0,0,0,0,0,0,732,732,0,2236,2236,0,0,0,3806,0,0,0,0,0,0,0,0,13555,0,13555,0,0,0,0,0,0,0,0,0,1028,0,1028,4646,0,4646,0,0,0,1228,4034,0,0,0,0,0,0,2,0,0,NaN

In [29]:
hemoprod_ap_deduplicado.to_excel('dados_processados/hemoprod_ap.xlsx', index=False)

## Hemoprod Bahia

In [14]:
arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_BA.xlsx')
nome_planilha = 'HEMOPROD - BAHIA'
hemoprod_ba = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)
print("Arquivo de dados carregado com sucesso.")
print(f"Número de colunas original: {len(hemoprod_ba.columns)}")

try:
    # Lê apenas o cabeçalho do arquivo original para obter os nomes das colunas
    # df_original = pd.read_excel(arquivo_dados_path, nrows=0)
    colunas_originais = hemoprod_ba.columns.tolist()

    # Cria um novo DataFrame para o dicionário
    dicionario_df = pd.DataFrame({
        'nome_original': colunas_originais,
        'nome_sql': ''  # Adiciona uma coluna vazia para os novos nomes
    })

    # Salva o DataFrame do dicionário em um novo arquivo Excel
    dicionario_df.to_excel('dicionario_ba.xlsx', index=False)

    print(f"Arquivo de dicionário dicionario.xlsx gerado com sucesso!")
    print(f"O arquivo contém {len(colunas_originais)} colunas originais.")
    print("Agora você pode preencher a coluna 'nome_sql' com os nomes desejados.")

except FileNotFoundError:
    print(f"Erro: O arquivo de dados '{arquivo_dados_path}' não foi encontrado.")
except Exception as e:
    print(f"Ocorreu um erro inesperado: {e}")

Arquivo de dados carregado com sucesso.
Número de colunas original: 269
Arquivo de dicionário dicionario.xlsx gerado com sucesso!
O arquivo contém 269 colunas originais.
Agora você pode preencher a coluna 'nome_sql' com os nomes desejados.

In [30]:
import os
import pandas as pd

dados_brutos_path = 'dados_brutos'

arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_BA.xlsx')
nome_planilha = 'HEMOPROD - BAHIA'

dicionario_path_ba = ('./dicionario_colunas_269.xlsx')
# dicionario_path_ap = ('./dicionario_colunas_270.xlsx')

dicionario_ba = pd.read_excel(dicionario_path_ba, sheet_name='Sheet1')

# --- 2. Carregue os dados e o dicionário ---
try:
    # Carrega o arquivo de dados
    hemoprod_ba = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)
    print("Arquivo de dados carregado com sucesso.")
    print(f"Número de colunas original: {len(hemoprod_ba.columns)}")

    # Carrega o arquivo de dicionário
    dicionario = pd.read_excel(dicionario_path_ba)
    print("Arquivo de dicionário carregado com sucesso.")

    # --- 3. Extraia a lista de novos nomes ---
    # Pega os valores da coluna 'nome_sql' e converte para uma lista
    novos_nomes = dicionario['nome_sql'].tolist()
    print(f"Número de novos nomes no dicionário: {len(novos_nomes)}")

    # --- 4. Verificação de segurança (MUITO IMPORTANTE) ---
    # Garante que o número de colunas é o mesmo antes de renomear
    if len(hemoprod_ba.columns) == len(novos_nomes):
        print("\nO número de colunas corresponde. Renomeando...")
        
        # --- 5. Substitua os nomes das colunas ---
        # Esta é a linha principal que faz a substituição direta
        hemoprod_ba.columns = novos_nomes
        
        print("Colunas renomeadas com sucesso!")
        
        # --- 6. Verifique o resultado ---
        print("\nInformações do DataFrame com as novas colunas:")
        hemoprod_ba.info()
        
        print("\nAs 5 primeiras linhas com as novas colunas:")
        display(hemoprod_ba.head())

    else:
        # Mensagem de erro se o número de colunas for diferente
        print("\n--- ERRO ---")
        print("A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.")
        print(f"Colunas no arquivo de dados: {len(hemoprod_ba.columns)}")
        print(f"Nomes no dicionário: {len(novos_nomes)}")

except FileNotFoundError as e:
    print(f"\nErro de arquivo não encontrado: {e}")
except KeyError as e:
    print(f"\nErro de coluna não encontrada: {e}. Verifique se a coluna 'nome_sql' existe no seu arquivo de dicionário.")
except Exception as e:
    print(f"\nOcorreu um erro inesperado: {e}")

Arquivo de dados carregado com sucesso.
Número de colunas original: 269
Arquivo de dicionário carregado com sucesso.
Número de novos nomes no dicionário: 269

O número de colunas corresponde. Renomeando...
Colunas renomeadas com sucesso!

Informações do DataFrame com as novas colunas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 975 entries, 0 to 974
Columns: 269 entries, id to hemoprod_3_observacoes
dtypes: float64(247), int64(4), object(18)
memory usage: 2.0+ MB

As 5 primeiras linhas com as novas colunas:

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,8,2023-06-23 10:10:16,4,pt-BR,2.080744e+09,HmkD8Fq6Obb0Spm,2023-06-23 09:53:53,2023-06-23 10:10:16,10.0.0.119,NaN,ORIGINAL,2023,Junho,NaN,"Paulo Afonso, Bahia",Fundação de Hemoterapia e Hematologia do Estad...,NaN,34306340000167,Unidade de Coleta e Transfusão,Público,Único serviço,NaN,NaN,NaN,72.0,7.0,169.0,27.0,0.0,0.0,141.0,24.0,100.0,10.0,0.0,0.0,124.0,13.0,117.0,21.0,0.0,3.0,85.0,9.0,156.0,22.0,1.0,5.0,6.0,3.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,15.0,24.0,1.0,9.0,0.0,1.0,230.0,0.0,NaN,197.0,1.0,197.0,5.0,197.0,6.0,197.0,0.0,197.0,4.0,197.0,1.0,197.0,0.0,197.0,0.0,197.0,4.0,197.0,1.0,197.0,5.0,49.0,37.0,18.0,16.0,1.0,2.0,81.0,47.0,7.0,5.0,2.0,0.0,1.0,0.0,11.0,5.0,21.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,197.0,197.0,16.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,230.0,0.0,0.0,230.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,230.0,0.0,1.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,112.0,112.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,A UNIDADE DESCARTA O PLASMA PRODUZIDO.
1,14,2023-07-03 10:51:45,4,pt-BR,1.347364e+09,7wrQGPKvZXmav1F,2023-07-03 10:28:12,2023-07-03 10:51:45,10.0.0.205,NaN,ORIGINAL,2023,Junho,NaN,"Salvador, Bahia",Hemato Serviços de Hemoterapia Ltda - AgênciaT...,NaN,13894995001952,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,67.0,0.0,16.0,0.0,2.0,0.0,37.0,0.0,9.0,0.0,0.0,0.0,1.0,0.0,8.0,0.0,18.0,0.0,5.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,"Por se tratar de uma agência transfusional, nã...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,202.0,1.0,0.0,0.0,0.0,0.0,234.0,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,81.0,81.0,0.0,0.0,0.0,0.0,71.0,71.0,0.0,9.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,15,2023-07-03 11:05:14,4,pt-BR,1.577556e+09,7wrQGPKvZXmav1F,2023-07-03 10:54:08,2023-07-03 11:05:14,10.0.0.81,NaN,ORIGINAL,2023,Junho,NaN,"Salvador, Bahia",Hemato Serviços de Hemoterapia Ltda - Hospital...,NaN,13894995002924,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,13.0,0.0,4.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,"Por se tratar de uma agência transfusional, nã...",0.0,0.0,0.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,94.0,5.0,0.0,0.0,0.0,0.0,10.0,5.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,35.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
3,16,2023-07-03 11:39:48,4,pt-BR,2.101298e+09,7wrQGPKvZXmav1F,2023-07-03 11:07:27,2023-07-03 11:39:48,10.0.0.155,NaN,ORIGINAL,2023,Junho,NaN,"Salvador, Bahia",Hemato Serviços de Hemoterapia Ltda - Hospital...,NaN,13894995002096,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,70.0,0.0,46.0,0.0,18.0,0.0,81.0,0.0,10.0,0.0,1.0,0.0,0.0,0.0,6.0,0.0,17.0,0.0,1.0,0.0,303.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,72.0,0.0,0.0,0.0,0.0,0.0,270.0,6.0,0.0,0.0,0.0,0.0,174.0,13.0,0.0,34.0,8.0,0.0,0.0,0.0,0.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,19.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,142.0,142.0,0.0,0.0,0.0,0.0,50.0,50.0,0.0,12.0,12.0,0.0,0.0,0.0,0.0,8.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,17,2023-07-03 11:53:51,4,pt-BR,1.447849e+09,7wrQGPKvZXmav1F,2023-07-03 11:40:45,2023-07-03 11:53:51,10.0.0.224,NaN,ORIGINAL,2023,Junho,NaN,"Salvador, Bahia",Hemato Serviços de Hemoterapia Ltda - Hospital...,NaN,13894995002177,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,48.0,0.0,4.0,0.0,1.0,0.0,30.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,26.0,0.0,0.0,0.0,0.0,0.0,152.0,33.0,0.0,0.0,0.0,0.0,36.0,10.0,0.0,22.0,11.0,0.0,0.0,0.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,8.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,7.0,0.0,0.0,0.0,0.0,24.0,24.0,0.0,0.0,0.0,0.0,7.0,7.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,12.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

In [31]:
# --- 2. Defina as colunas para a chave e para ordenação ---
registros_antes = len(hemoprod_ba)
print(f"Total de registros ANTES da remoção de duplicatas: {registros_antes}")
    

colunas_chave = [
        'cnpj', 
        'ano_referencia', 
        'periodo_referencia', 
        'razao_social_nome_fantasia'
    ]

coluna_data = 'data_envio'

# --- 3. Verifique se as colunas necessárias existem ---
colunas_necessarias = colunas_chave + [coluna_data]

if not all(col in hemoprod_ba.columns for col in colunas_necessarias):
    print("\n--- ERRO ---")
    print("Uma ou mais colunas necessárias para a deduplicação não foram encontradas.")
    colunas_faltantes = [col for col in colunas_necessarias if col not in hemoprod_ba.columns]
    print(f"Colunas necessárias: {colunas_necessarias}")
    print(f"Colunas faltantes no DataFrame: {colunas_faltantes}")
else:
    # --- 4. Prepare a coluna de data e ordene os dados ---
    # Converte a coluna 'data_envio' para datetime para garantir a ordenação correta.
    # 'errors='coerce'' transformará datas inválidas em NaT (Not a Time), que são tratadas como nulas.
    hemoprod_ba[coluna_data] = pd.to_datetime(hemoprod_ba[coluna_data], errors='coerce')

    # Ordena o DataFrame. Os registros com data de envio mais recente ficarão por último.
    print(f"\nOrdenando os dados por '{coluna_data}'...")
    hemoprod_ba_ordenado = hemoprod_ba.sort_values(by=coluna_data, ascending=True)

    # --- 5. Identifique e separe os registros duplicados e únicos ---
    # Em vez de usar drop_duplicates() diretamente, vamos usar duplicated()
    # para criar uma máscara booleana.
    # 'keep='last'' marca todas as ocorrências de uma chave como True, EXCETO a última (a mais recente).
    print(f"Identificando duplicatas com base na chave: {colunas_chave}...")
    mascara_duplicatas = hemoprod_ba_ordenado.duplicated(subset=colunas_chave, keep='last')

    # O DataFrame de removidos conterá todas as linhas marcadas como True
    hemoprod_removidos = hemoprod_ba_ordenado[mascara_duplicatas]
    
    # O DataFrame deduplicado conterá o INVERSO (~) da máscara (linhas marcadas como False)
    hemoprod_ba_deduplicado = hemoprod_ba_ordenado[~mascara_duplicatas]
    
    # Agora podemos contar os registros diretamente dos novos DataFrames
    registros_depois = len(hemoprod_ba_deduplicado)
    registros_removidos = len(hemoprod_removidos) 
    
    # --- 6. Exiba o resultado ---
    print("\n--- Processo Concluído ---")
    print(f"Registros removidos: {registros_removidos}")
    print(f"Total de registros DEPOIS da remoção de duplicatas: {registros_depois}")

    # (Opcional) Exibe a amostra dos removidos
    print("\nAmostra dos dados REMOVIDOS (os mais antigos/duplicados):")
    display(hemoprod_removidos.head(10))

    # Você pode continuar a usar o DataFrame 'hemoprod_ba_deduplicado' para suas análises
    print("\nAmostra dos dados únicos (os mais recentes para cada chave):")
    display(hemoprod_ba_deduplicado.head(10))
    
    # Agora você tem o DataFrame 'hemoprod_removidos' salvo

Total de registros ANTES da remoção de duplicatas: 975

Ordenando os dados por 'data_envio'...
Identificando duplicatas com base na chave: ['cnpj', 'ano_referencia', 'periodo_referencia', 'razao_social_nome_fantasia']...

--- Processo Concluído ---
Registros removidos: 267
Total de registros DEPOIS da remoção de duplicatas: 708

Amostra dos dados REMOVIDOS (os mais antigos/duplicados):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
15,35,2023-07-25 18:57:03,4,pt-BR,8.145631e+08,DzGNznkdlkYXGXd,2023-07-25 17:53:17,2023-07-25 18:57:03,10.0.1.142,NaN,RETIFICADORA,2023,Janeiro,NaN,"Salvador, Bahia",Fundação de Hemoterapia e Hematologia do Estad...,NaN,34306340000167,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,1070.0,298.0,985.0,293.0,0.0,0.0,587.0,286.0,1468.0,305.0,0.0,0.0,1242.0,293.0,813.0,298.0,8.0,4.0,605.0,221.0,1442.0,366.0,9.0,65.0,74.0,19.0,9.0,28.0,0.0,1.0,1.0,1.0,2.0,3.0,90.0,44.0,134.0,2.0,2.0,4.0,0.0,1.0,1.0,0.0,0.0,0.0,6.0,3.0,9.0,166.0,171.0,337.0,1.0,22.0,3.0,10.0,1957.0,62.0,NaN,2030.0,8.0,2030.0,6.0,2030.0,29.0,2030.0,2.0,2030.0,11.0,2030.0,6.0,2030.0,0.0,0.0,0.0,2030.0,1.0,2030.0,1.0,2030.0,3.0,510.0,268.0,236.0,164.0,89.0,44.0,973.0,502.0,63.0,29.0,31.0,9.0,11.0,2.0,130.0,32.0,235.0,1.0,2.0,59.0,942.0,300.0,18.0,268.0,2043.0,2030.0,58.0,0.0,Não é realizado voto de auto-exclusão.,0.0,1890.0,0.0,3823.0,0.0,0.0,0.0,0.0,0.0,1295.0,333.0,111.0,2528.0,60.0,0.0,1504.0,63.0,0.0,104.0,0.0,0.0,0.0,0.0,0.0,555.0,0.0,0.0,938.0,0.0,0.0,3.0,0.0,21.0,19.0,10.0,2489.0,0.0,0.0,0.0,0.0,10.0,65.0,1.0,12.0,73.0,1.0,174.0,194.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,102.0,133.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,252.0,0.0,252.0,5.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0,529.0,60.0,589.0,0.0,0.0,0.0,1182.0,317.0,1499.0,1735.0,767.0,2502.0,887.0,195.0,1082.0,109.0,0.0,109.0,0.0,0.0,0.0,467.0,11.0,478.0,484.0,142.0,626.0,3.0,104.0,30.0,1564.0,601.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,Irradiação realizada em serviço externo por co...
43,80,2023-08-29 10:07:51,4,pt-BR,5.958126e+08,imTjpvSprA4zOL8,2023-08-29 09:11:27,2023-08-29 10:07:51,10.0.1.142,NaN,ORIGINAL,2023,Janeiro,NaN,"Guanambi, Bahia",Fundação de Hemoterapia e Hematologia do Estad...,NaN,34306340000167,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,129.0,31.0,298.0,101.0,0.0,0.0,188.0,75.0,239.0,57.0,0.0,0.0,227.0,61.0,200.0,71.0,3.0,1.0,123.0,54.0,301.0,77.0,0.0,0.0,0.0,1.0,2.0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,19.0,16.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.0,52.0,93.0,0.0,0.0,9.0,3.0,415.0,0.0,NaN,389.0,1.0,389.0,1.0,389.0,4.0,389.0,0.0,389.0,5.0,389.0,0.0,389.0,1.0,0.0,0.0,389.0,0.0,389.0,0.0,389.0,0.0,117.0,60.0,44.0,17.0,7.0,12.0,185.0,89.0,22.0,4.0,1.0,1.0,1.0,1.0,30.0,9.0,54.0,15.0,1.0,5.0,48.0,18.0,0.0,5.0,407.0,389.0,11.0,0.0,NaN,0.0,0.0,0.0,0.0,26.0,0.0,405.0,0.0,0.0,336.0,0.0,19.0,69.0,7.0,3.0,69.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,405.0,0.0,1.0,11.0,0.0,0.0,0.0,1.0,31.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,2.0,17.0,0.0,0.0,0.0,71.0,245.0,316.0,15.0,75.0,90.0,19.0,14.0,33.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,69.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
45,82,2023-08-29 10:30:05,4,pt-BR,5.452058e+08,imTjpvSprA4zOL8,2023-08-29 10:12:30,2023-08-29 10:30:05,10.0.0.14,NaN,ORIGINAL,2023,Janeiro,NaN,"Guanambi, Bahia",Fundação de Hemoterapia e Hematologia do Estad...,NaN,34306340000167,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,129.0,31.0,298.0,101.0,0.0,0.0,188.0,75.0,239.0,57.0,0.0,0.0,227.0,61.0,200.0,71.0,3.0,1.0,123.0,54.0,301.0,77.0,0.0,0.0,0.0,1.0,2.0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,19.0,16.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.0,52.0,93.0,0.0,0.0,9.0,3.0,415.0,0.0,NaN,389.0,1.0,389.0,1.0,389.0,4.0,389.0,0.0,389.0,5.0,389.0,0.0,389.0,1.0,0.0,0.0,389.0,0.0,389.0,0.0,389.0,0.0,117.0,60.0,44.0,17.0,7.0,12.0,185.0,89.0,22.0,4.0,1.0,1.0,1.0,1.0,30.0,9.0,54.0,15.0,1.0,5.0,48.0,18.0,0.0,5.0,407.0,389.0,11.0,0.0,NaN,0.0,0.0,0.0,0.0,26.0,0.0,405.0,0.0,0.0,336.0,0.0,19.0,69.0,7.0,3.0,69.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,405.0,1.0,0.0,11.0,0.0,1.0,0.0,0.0,31.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,2.0,17.0,0.0,0.0,0.0,71.0,245.0,316.0,15.0,75.0,90.0,19.0,14.0,33.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,69.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
49,86,2023-08-29 11:04:52,4,pt-BR,2.571943e+08,imTjpvSprA4zOL8,2023-08-29 10:49:50,2023-08-29 11:04:52,10.0.1.165,NaN,ORIGINAL,2023,Fevereiro,NaN,"Guanambi, Bahia",Fundação de Hemoterapia e Hematologia do Estad...,NaN,34306340000167,Hemocentro Coordenador,Público,Único serviço,NaN,NaN,NaN,114.0,31.0,320.0,130.0,0.0,0.0,203.0,115.0,231.0,46.0,0.0,0.0,244.0,90.0,190.0,71.0,1.0,1.0,131.0,50.0,302.0,110.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,13.0,33.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,68.0,56.0,124.0,0.0,4.0,10.0,5.0,415.0,0.0,NaN,418.0,2.0,418.0,3.0,418.0,5.0,418.0,0.0,418.0,4.0,418.0,0.0,418.0,0.0,0.0,0.0,418.0,0.0,418.0,0.0,418.0,0.0,134.0,63.0,38.0,19.0,16.0,3.0,177.0,78.0,10.0,8.0,4.0,0.0,4.0,0.0,35.0,22.0,53.0,30.0,2.0,8.0,52.0,64.0,4.0,8.0,418.0,418.0,14.0,0.0,NaN,0.0,0.0,0.0,0.0,33.0,0.0,402.0,0.0,0.0,327.0,0.0,21.0,75.0,9.0,2.0,75.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,4.0,0.0,0.0,0.0,402.0,0.0,1.0,8.0,0.0,2.0,1.0,0.0,53.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,13.0,21.0,0.0,0.0,0.0,62.0,256.0,318.0,6.0,54.0,60.0,17.0,5.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,75.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

Amostra dos dados únicos (os mais recentes para cada chave):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,8,2023-06-23 10:10:16,4,pt-BR,2.080744e+09,HmkD8Fq6Obb0Spm,2023-06-23 09:53:53,2023-06-23 10:10:16,10.0.0.119,NaN,ORIGINAL,2023,Junho,NaN,"Paulo Afonso, Bahia",Fundação de Hemoterapia e Hematologia do Estad...,NaN,34306340000167,Unidade de Coleta e Transfusão,Público,Único serviço,NaN,NaN,NaN,72.0,7.0,169.0,27.0,0.0,0.0,141.0,24.0,100.0,10.0,0.0,0.0,124.0,13.0,117.0,21.0,0.0,3.0,85.0,9.0,156.0,22.0,1.0,5.0,6.0,3.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,15.0,24.0,1.0,9.0,0.0,1.0,230.0,0.0,NaN,197.0,1.0,197.0,5.0,197.0,6.0,197.0,0.0,197.0,4.0,197.0,1.0,197.0,0.0,197.0,0.0,197.0,4.0,197.0,1.0,197.0,5.0,49.0,37.0,18.0,16.0,1.0,2.0,81.0,47.0,7.0,5.0,2.0,0.0,1.0,0.0,11.0,5.0,21.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,197.0,197.0,16.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,230.0,0.0,0.0,230.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,230.0,0.0,1.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,112.0,112.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,A UNIDADE DESCARTA O PLASMA PRODUZIDO.
1,14,2023-07-03 10:51:45,4,pt-BR,1.347364e+09,7wrQGPKvZXmav1F,2023-07-03 10:28:12,2023-07-03 10:51:45,10.0.0.205,NaN,ORIGINAL,2023,Junho,NaN,"Salvador, Bahia",Hemato Serviços de Hemoterapia Ltda - AgênciaT...,NaN,13894995001952,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,67.0,0.0,16.0,0.0,2.0,0.0,37.0,0.0,9.0,0.0,0.0,0.0,1.0,0.0,8.0,0.0,18.0,0.0,5.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,"Por se tratar de uma agência transfusional, nã...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,202.0,1.0,0.0,0.0,0.0,0.0,234.0,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,81.0,81.0,0.0,0.0,0.0,0.0,71.0,71.0,0.0,9.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,15,2023-07-03 11:05:14,4,pt-BR,1.577556e+09,7wrQGPKvZXmav1F,2023-07-03 10:54:08,2023-07-03 11:05:14,10.0.0.81,NaN,ORIGINAL,2023,Junho,NaN,"Salvador, Bahia",Hemato Serviços de Hemoterapia Ltda - Hospital...,NaN,13894995002924,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,13.0,0.0,4.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,"Por se tratar de uma agência transfusional, nã...",0.0,0.0,0.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,94.0,5.0,0.0,0.0,0.0,0.0,10.0,5.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,35.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
3,16,2023-07-03 11:39:48,4,pt-BR,2.101298e+09,7wrQGPKvZXmav1F,2023-07-03 11:07:27,2023-07-03 11:39:48,10.0.0.155,NaN,ORIGINAL,2023,Junho,NaN,"Salvador, Bahia",Hemato Serviços de Hemoterapia Ltda - Hospital...,NaN,13894995002096,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,70.0,0.0,46.0,0.0,18.0,0.0,81.0,0.0,10.0,0.0,1.0,0.0,0.0,0.0,6.0,0.0,17.0,0.0,1.0,0.0,303.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,72.0,0.0,0.0,0.0,0.0,0.0,270.0,6.0,0.0,0.0,0.0,0.0,174.0,13.0,0.0,34.0,8.0,0.0,0.0,0.0,0.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,19.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,142.0,142.0,0.0,0.0,0.0,0.0,50.0,50.0,0.0,12.0,12.0,0.0,0.0,0.0,0.0,8.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,17,2023-07-03 11:53:51,4,pt-BR,1.447849e+09,7wrQGPKvZXmav1F,2023-07-03 11:40:45,2023-07-03 11:53:51,10.0.0.224,NaN,ORIGINAL,2023,Junho,NaN,"Salvador, Bahia",Hemato Serviços de Hemoterapia Ltda - Hospital...,NaN,13894995002177,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,48.0,0.0,4.0,0.0,1.0,0.0,30.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,26.0,0.0,0.0,0.0,0.0,0.0,152.0,33.0,0.0,0.0,0.0,0.0,36.0,10.0,0.0,22.0,11.0,0.0,0.0,0.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,8.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,7.0,0.0,0.0,0.0,0.0,24.0,24.0,0.0,0.0,0.0,0.0,7.0,7.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,12.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

In [32]:
hemoprod_ba_deduplicado.to_excel('dados_processados/hemoprod_ba.xlsx', index=False)

## Hemoprod Ceara

In [ ]:
import os
import pandas as pd

dados_brutos_path = 'dados_brutos'

arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_CE.xlsx')
nome_planilha = 'Planilha1'

dicionario_path_ce = ('./dicionario_colunas_269.xlsx')
# dicionario_path_ap = ('./dicionario_colunas_270.xlsx')

dicionario_ce = pd.read_excel(dicionario_path_ce, sheet_name='Sheet1')

# --- 2. Carregue os dados e o dicionário ---
try:
    # Carrega o arquivo de dados
    hemoprod_ce = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)
    print("Arquivo de dados carregado com sucesso.")
    print(f"Número de colunas original: {len(hemoprod_ce.columns)}")

    # Carrega o arquivo de dicionário
    dicionario = pd.read_excel(dicionario_path_ce)
    print("Arquivo de dicionário carregado com sucesso.")

    # --- 3. Extraia a lista de novos nomes ---
    # Pega os valores da coluna 'nome_sql' e converte para uma lista
    novos_nomes = dicionario['nome_sql'].tolist()
    print(f"Número de novos nomes no dicionário: {len(novos_nomes)}")

    # --- 4. Verificação de segurança (MUITO IMPORTANTE) ---
    # Garante que o número de colunas é o mesmo antes de renomear
    if len(hemoprod_ce.columns) == len(novos_nomes):
        print("\nO número de colunas corresponde. Renomeando...")
        
        # --- 5. Substitua os nomes das colunas ---
        # Esta é a linha principal que faz a substituição direta
        hemoprod_ce.columns = novos_nomes
        
        print("Colunas renomeadas com sucesso!")
        
        # --- 6. Verifique o resultado ---
        print("\nInformações do DataFrame com as novas colunas:")
        hemoprod_ce.info()
        
        print("\nAs 5 primeiras linhas com as novas colunas:")
        display(hemoprod_ce.head())

    else:
        # Mensagem de erro se o número de colunas for diferente
        print("\n--- ERRO ---")
        print("A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.")
        print(f"Colunas no arquivo de dados: {len(hemoprod_ce.columns)}")
        print(f"Nomes no dicionário: {len(novos_nomes)}")

except FileNotFoundError as e:
    print(f"\nErro de arquivo não encontrado: {e}")
except KeyError as e:
    print(f"\nErro de coluna não encontrada: {e}. Verifique se a coluna 'nome_sql' existe no seu arquivo de dicionário.")
except Exception as e:
    print(f"\nOcorreu um erro inesperado: {e}")

Arquivo de dados carregado com sucesso.
Número de colunas original: 269
Arquivo de dicionário carregado com sucesso.
Número de novos nomes no dicionário: 269

O número de colunas corresponde. Renomeando...
Colunas renomeadas com sucesso!

Informações do DataFrame com as novas colunas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228 entries, 0 to 227
Columns: 269 entries, id to hemoprod_3_observacoes
dtypes: datetime64[ns](3), float64(253), object(13)
memory usage: 479.3+ KB

As 5 primeiras linhas com as novas colunas:

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,8.0,2023-04-06 15:58:18,4.0,pt-BR,4.992114e+08,s16oIPSgdM8DdUr,2023-04-06 15:20:49,2023-04-06 15:58:18,10.0.113.219,NaN,ORIGINAL,2023.0,Março,NaN,"Fortaleza, Ceará",Fujisan Centro de Hemoterapia e Hematologia do...,NaN,7.871680e+12,Núcleo de Hemoterapia,Privado,Único serviço,NaN,NaN,NaN,483.0,104.0,1722.0,253.0,0.0,0.0,1173.0,225.0,544.0,47.0,488.0,85.0,1437.0,140.0,768.0,217.0,0.0,0.0,552.0,72.0,1647.0,284.0,0.0,0.0,0.0,2.0,0.0,2.0,1.0,4.0,5.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,133.0,212.0,345.0,7.0,10.0,3.0,9.0,2123.0,75.0,NaN,2111.0,3.0,2112.0,0.0,2111.0,27.0,2112.0,1.0,2112.0,12.0,2112.0,3.0,2112.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,646.0,430.0,162.0,81.0,59.0,34.0,906.0,561.0,133.0,37.0,40.0,7.0,11.0,6.0,148.0,61.0,337.0,66.0,0.0,30.0,142.0,0.0,0.0,1.0,862.0,2185.0,50.0,0.0,NaN,0.0,0.0,0.0,1947.0,315.0,9.0,441.0,0.0,0.0,2103.0,2307.0,1094.0,0.0,0.0,0.0,1853.0,343.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,340.0,453.0,10.0,0.0,0.0,0.0,0.0,0.0,22.0,3.0,21.0,1278.0,0.0,0.0,439.0,0.0,49.0,65.0,0.0,0.0,0.0,0.0,134.0,132.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,107.0,126.0,233.0,0.0,0.0,0.0,302.0,733.0,1035.0,0.0,0.0,0.0,242.0,574.0,816.0,0.0,0.0,0.0,0.0,0.0,0.0,160.0,78.0,238.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0,215.0,77.0,2.0,82.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
1,9.0,2023-04-13 16:24:27,4.0,pt-BR,1.541636e+09,s16oIPSgdM8DdUr,2023-04-13 15:49:43,2023-04-13 16:24:27,10.0.113.219,NaN,ORIGINAL,2023.0,Janeiro,NaN,"Fortaleza, Ceará",Fujisan Centro de Hemoterapia e Hematologia do...,NaN,7.871680e+12,Núcleo de Hemoterapia,Privado,Único serviço,NaN,NaN,NaN,358.0,38.0,1257.0,181.0,0.0,0.0,864.0,140.0,535.0,47.0,216.0,32.0,1103.0,79.0,512.0,140.0,0.0,0.0,461.0,66.0,1144.0,152.0,0.0,0.0,0.0,6.0,0.0,6.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,71.0,137.0,208.0,7.0,8.0,1.0,6.0,1545.0,62.0,NaN,1458.0,3.0,1458.0,2.0,1458.0,15.0,1458.0,1.0,1458.0,9.0,1458.0,2.0,1458.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,462.0,342.0,115.0,78.0,37.0,35.0,618.0,489.0,102.0,29.0,15.0,11.0,1.0,0.0,104.0,51.0,226.0,60.0,3.0,21.0,91.0,5.0,0.0,0.0,549.0,1604.0,42.0,0.0,NaN,0.0,0.0,0.0,1377.0,263.0,4.0,392.0,72.0,0.0,1532.0,2049.0,857.0,0.0,0.0,0.0,1298.0,199.0,31.0,0.0,0.0,0.0,0.0,0.0,0.0,534.0,344.0,1.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,5.0,740.0,0.0,34.0,222.0,0.0,23.0,47.0,0.0,0.0,0.0,0.0,136.0,91.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,81.0,117.0,198.0,54.0,0.0,54.0,258.0,616.0,874.0,0.0,0.0,0.0,164.0,368.0,532.0,0.0,0.0,0.0,0.0,0.0,0.0,126.0,113.0,239.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39.0,213.0,45.0,5.0,58.0,2.0,0.0,6.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
2,10.0,2023-04-14 11:50:10,4.0,pt-BR,6.238845e+08,s16oIPSgdM8DdUr,2023-04-14 11:13:36,2023-04-14 11:50:10,10.0.0.195,NaN,ORIGINAL,2023.0,Fevereiro,NaN,"Fortaleza, Ceará",Fujisan Centro de Hemoterapia e Hematologia do...,NaN,7.871680e+12,Núcleo de Hemoterapia,Privado,Único serviço,NaN,NaN,NaN,563.0,66.0,1292.0,205.0,0.0,0.0,959.0,187.0,505.0,38.0,391.0,46.0,1207.0,101.0,648.0,170.0,0.0,0.0,480.0,64.0,1366.0,206.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,98.0,169.0,267.0,5.0,6.0,0.0,5.0,1788.0,62.0,NaN,1951.0,1.0,1951.0,1.0,1951.0,20.0,1951.0,0.0,1951.0,14.0,1951.0,2.0,1951.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,604.0,358.0,159.0,74.0,48.0,27.0,873.0,469.0,83.0,35.0,21.0,4.0,5.0,1.0,161.0,46.0,271.0,51.0,2.0,18.0,123.0,5.0,0.0,0.0,777.0,1848.0,52.0,0.0,NaN,0.0,0.0,0.0,1664.0,264.0,7.0,340.0,0.0,0.0,1776.0,2015.0,897.0,0.0,0.0,0.0,1580.0,235.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,585.0,380.0,12.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0,24.0,992.0,0.0,28.0,294.0,0.0,17.0,67.0,0.0,0.0,0.0,0.0,418.0,105.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,62.0,140.0,202.0,0.0,0.0,0.0,262.0,596.0,858.0,0.0,0.0,0.0,134.0,367.0,501.0,0.0,0.0,0.0,0.0,0.0,0.0,67.0,169.0,236.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,197.0,57.0,1.0,78.0,2.0,0.0,5.0,0.0,0.0,0.0,2.0,0.0,0.0,NaN
3,11.0,2023-05-08 13:07:37,4.0,pt-BR,1.913022e+08,s16oIPSgdM8DdUr,2023-05-08 12:47:48,2023-05-08 13:07:37,10.0.52.31,NaN,ORIGINAL,2023.0,Abril,NaN,"Fortaleza, Ceará",Fujisan Centro de Hemoterapia e Hematologia do...,NaN,7.871680e+12,Núcleo de Hemoterapia,Privado,Único serviço,NaN,NaN,NaN,564.0,67.0,1393.0,284.0,0.0,0.0,1099.0,249.0,514.0,41.0,344.0,61.0,1351.0,150.0,606.0,201.0,0.0,0.0,599.0,99.0,1348.0,250.0,0.0,0.0,0.0,4.0,1.0,5.0,1.0,5.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,143.0,195.0,338.0,8.0,10.0,1.0,9.0,1876.0,73.0,NaN,1991.0,2.0,1991.0,2.0,1991.0,17.0,1991.0,1.0,1990.0,11.0,1991.0,6.0,1991.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,580.0,343.0,209.0,87.0,92.0,46.0,842.0,490.0,80.0,39.0,35.0,9.0,9.0,1.0,145.0,45.0,275.0,66.0,0.0,22.0,111.0,0.0,0.0,1.0,810.0,1939.0,51.0,0.0,NaN,0.0,0.0,0.0,1626.0,305.0,2.0,485.0,138.0,0.0,1839.0,2035.0,846.0,0.0,0.0,0.0,1622.0,259.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,430.0,278.0,8.0,0.0,0.0,0.0,1.0,0.0,38.0,1.0,14.0,1313.0,0.0,7.0,427.0,0.0,144.0,91.0,0.0,0.0,0.0,0.0,120.0,211.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,75.0,133.0,208.0,136.0,0.0,136.0,248.0,685.0,933.0,0.0,0.0,0.0,158.0,405.0,563.0,0.0,0.0,0.0,0.0,0.0,0.0,76.0,126.0,202.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,202.0,39.0,0.0,85.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [40]:
# --- 2. Defina as colunas para a chave e para ordenação ---
registros_antes = len(hemoprod_ce)
print(f"Total de registros ANTES da remoção de duplicatas: {registros_antes}")
    

colunas_chave = [
        'cnpj', 
        'ano_referencia', 
        'periodo_referencia', 
        'razao_social_nome_fantasia'
    ]

coluna_data = 'data_envio'

# --- 3. Verifique se as colunas necessárias existem ---
colunas_necessarias = colunas_chave + [coluna_data]

if not all(col in hemoprod_ce.columns for col in colunas_necessarias):
    print("\n--- ERRO ---")
    print("Uma ou mais colunas necessárias para a deduplicação não foram encontradas.")
    colunas_faltantes = [col for col in colunas_necessarias if col not in hemoprod_ce.columns]
    print(f"Colunas necessárias: {colunas_necessarias}")
    print(f"Colunas faltantes no DataFrame: {colunas_faltantes}")
else:
    # --- 4. Prepare a coluna de data e ordene os dados ---
    # Converte a coluna 'data_envio' para datetime para garantir a ordenação correta.
    # 'errors='coerce'' transformará datas inválidas em NaT (Not a Time), que são tratadas como nulas.
    hemoprod_ce[coluna_data] = pd.to_datetime(hemoprod_ce[coluna_data], errors='coerce')

    # Ordena o DataFrame. Os registros com data de envio mais recente ficarão por último.
    print(f"\nOrdenando os dados por '{coluna_data}'...")
    hemoprod_ce_ordenado = hemoprod_ce.sort_values(by=coluna_data, ascending=True)

    # --- 5. Identifique e separe os registros duplicados e únicos ---
    # Em vez de usar drop_duplicates() diretamente, vamos usar duplicated()
    # para criar uma máscara booleana.
    # 'keep='last'' marca todas as ocorrências de uma chave como True, EXCETO a última (a mais recente).
    print(f"Identificando duplicatas com cese na chave: {colunas_chave}...")
    mascara_duplicatas = hemoprod_ce_ordenado.duplicated(subset=colunas_chave, keep='last')

    # O DataFrame de removidos conterá todas as linhas marcadas como True
    hemoprod_removidos = hemoprod_ce_ordenado[mascara_duplicatas]
    
    # O DataFrame deduplicado conterá o INVERSO (~) da máscara (linhas marcadas como False)
    hemoprod_ce_deduplicado = hemoprod_ce_ordenado[~mascara_duplicatas]
    
    # Agora podemos contar os registros diretamente dos novos DataFrames
    registros_depois = len(hemoprod_ce_deduplicado)
    registros_removidos = len(hemoprod_removidos) 
    
    # --- 6. Exice o resultado ---
    print("\n--- Processo Concluído ---")
    print(f"Registros removidos: {registros_removidos}")
    print(f"Total de registros DEPOIS da remoção de duplicatas: {registros_depois}")

    # (Opcional) Exibe a amostra dos removidos
    print("\nAmostra dos dados REMOVIDOS (os mais antigos/duplicados):")
    display(hemoprod_removidos.head(10))

    # Você pode continuar a usar o DataFrame 'hemoprod_ce_deduplicado' para suas análises
    print("\nAmostra dos dados únicos (os mais recentes para cada chave):")
    display(hemoprod_ce_deduplicado.head(10))
    
    # Agora você tem o DataFrame 'hemoprod_removidos' salvo

Total de registros ANTES da remoção de duplicatas: 228

Ordenando os dados por 'data_envio'...
Identificando duplicatas com cese na chave: ['cnpj', 'ano_referencia', 'periodo_referencia', 'razao_social_nome_fantasia']...

--- Processo Concluído ---
Registros removidos: 162
Total de registros DEPOIS da remoção de duplicatas: 66

Amostra dos dados REMOVIDOS (os mais antigos/duplicados):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
170,180.0,2025-02-24 18:44:45,4.0,pt-BR,1.426538e+09,Qg5Ni6JhOAJCeU3,2025-02-24 18:17:55,2025-02-24 18:44:45,189.90.161.242,NaN,ORIGINAL,2025.0,Janeiro,NaN,"Fortaleza, Ceará",Secretaria de Estado de Saúde do Ceará - Centr...,NaN,7.954570e+12,Hemocentro Coordenador,Público,Rede de serviços,HEMOCENTRO COORDENADOR FORTALEZA,NaN,NaN,10387.0,2596.0,178.0,36.0,0.0,0.0,2324.0,1190.0,5529.0,712.0,2712.0,730.0,5950.0,1206.0,4615.0,1426.0,109.0,40.0,4729.0,1355.0,5727.0,1237.0,28.0,363.0,391.0,9.0,15.0,24.0,63.0,26.0,89.0,8.0,0.0,8.0,468.0,250.0,718.0,98.0,114.0,212.0,2.0,1.0,3.0,5.0,1.0,6.0,0.0,0.0,0.0,548.0,717.0,1265.0,95.0,816.0,133.0,314.0,10368.0,150.0,NaN,10518.0,6.0,10518.0,7.0,10518.0,62.0,10518.0,18.0,10518.0,26.0,10518.0,1.0,10518.0,13.0,10518.0,0.0,10518.0,0.0,10518.0,0.0,10518.0,3.0,3312.0,1491.0,899.0,426.0,271.0,156.0,4849.0,2039.0,383.0,154.0,106.0,30.0,38.0,7.0,677.0,231.0,1204.0,0.0,58.0,537.0,7009.0,549.0,387.0,326.0,3772.0,10518.0,136.0,9.0,NaN,192.0,0.0,0.0,10046.0,226.0,51.0,0.0,0.0,0.0,146.0,0.0,0.0,9901.0,1101.0,552.0,0.0,0.0,0.0,300.0,3.0,0.0,0.0,0.0,0.0,1070.0,56.0,19.0,1495.0,394.0,78.0,7.0,0.0,268.0,39.0,77.0,1263.0,2.0,27.0,80.0,0.0,0.0,0.0,9.0,926.0,649.0,0.0,0.0,0.0,0.0,164.0,165.0,0.0,0.0,0.0,3.0,62.0,38.0,10.0,444.0,1277.0,0.0,1.0,1.0,169.0,1358.0,1527.0,0.0,0.0,0.0,0.0,0.0,0.0,822.0,7290.0,8112.0,0.0,0.0,0.0,30.0,162.0,192.0,0.0,0.0,0.0,0.0,359.0,359.0,102.0,789.0,891.0,2.0,2.0,4.0,2259.0,228.0,2487.0,0.0,0.0,0.0,0.0,0.0,0.0,12791.0,1965.0,14756.0,0.0,0.0,0.0,391.0,14.0,405.0,0.0,0.0,0.0,740.0,93.0,833.0,1661.0,175.0,1836.0,0.0,3276.0,1709.0,9966.0,4950.0,37.0,0.0,16.0,0.0,0.0,0.0,21.0,4434.0,1055.0,NaN
183,185.0,2025-03-20 15:08:49,4.0,pt-BR,4.062604e+08,Qg5Ni6JhOAJCeU3,2025-03-20 13:47:35,2025-03-20 15:08:49,189.90.161.242,NaN,RETIFICADORA,2025.0,Janeiro,NaN,"Fortaleza, Ceará",Secretaria de Estado de Saúde do Ceará - Centr...,NaN,7.954570e+12,Hemocentro Coordenador,Público,Rede de serviços,HEMOCENTRO COORDENADOR FORTALEZA,NaN,NaN,10387.0,2596.0,178.0,36.0,0.0,0.0,2324.0,1190.0,5529.0,712.0,2712.0,730.0,5950.0,1206.0,4615.0,1426.0,109.0,40.0,4729.0,1355.0,5727.0,1237.0,28.0,363.0,391.0,9.0,15.0,24.0,63.0,26.0,89.0,8.0,0.0,8.0,468.0,250.0,718.0,98.0,114.0,212.0,2.0,1.0,3.0,5.0,1.0,6.0,0.0,0.0,0.0,548.0,717.0,1265.0,95.0,118.0,131.0,77.0,10368.0,150.0,NaN,10518.0,6.0,10518.0,7.0,10518.0,62.0,10518.0,18.0,10518.0,26.0,10518.0,1.0,10518.0,13.0,10518.0,0.0,10518.0,0.0,10518.0,0.0,10518.0,3.0,3312.0,1491.0,899.0,426.0,271.0,156.0,4849.0,2111.0,383.0,154.0,106.0,30.0,38.0,7.0,677.0,231.0,1204.0,0.0,58.0,358.0,7009.0,549.0,387.0,326.0,3772.0,10518.0,136.0,9.0,NaN,192.0,0.0,0.0,10046.0,226.0,51.0,0.0,0.0,0.0,146.0,0.0,0.0,9901.0,1101.0,552.0,0.0,0.0,0.0,300.0,3.0,0.0,0.0,0.0,0.0,1070.0,56.0,19.0,1495.0,394.0,78.0,7.0,0.0,268.0,39.0,77.0,1263.0,2.0,27.0,80.0,0.0,0.0,0.0,9.0,926.0,649.0,0.0,0.0,0.0,0.0,164.0,165.0,0.0,0.0,0.0,3.0,62.0,38.0,10.0,444.0,1277.0,0.0,1.0,1.0,169.0,1358.0,1527.0,0.0,0.0,0.0,0.0,0.0,0.0,822.0,7290.0,8112.0,0.0,0.0,0.0,30.0,162.0,192.0,0.0,0.0,0.0,0.0,359.0,359.0,102.0,789.0,891.0,2.0,2.0,4.0,2259.0,228.0,2487.0,0.0,0.0,0.0,0.0,0.0,0.0,12791.0,1965.0,14756.0,0.0,0.0,0.0,391.0,14.0,405.0,0.0,0.0,0.0,740.0,93.0,833.0,1661.0,175.0,1836.0,0.0,3276.0,1709.0,9966.0,4950.0,37.0,0.0,16.0,0.0,0.0,0.0,21.0,4434.0,1055.0,NaN
11,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HEMOCENTRO REGIONAL DE IGUATU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HEMOCENTRO REGIONAL DE CRATO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HEMOCENTRO REGIONAL DE QUIXADÁ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Amostra dos dados únicos (os mais recentes para cada chave):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,8.0,2023-04-06 15:58:18,4.0,pt-BR,4.992114e+08,s16oIPSgdM8DdUr,2023-04-06 15:20:49,2023-04-06 15:58:18,10.0.113.219,NaN,ORIGINAL,2023.0,Março,NaN,"Fortaleza, Ceará",Fujisan Centro de Hemoterapia e Hematologia do...,NaN,7.871680e+12,Núcleo de Hemoterapia,Privado,Único serviço,NaN,NaN,NaN,483.0,104.0,1722.0,253.0,0.0,0.0,1173.0,225.0,544.0,47.0,488.0,85.0,1437.0,140.0,768.0,217.0,0.0,0.0,552.0,72.0,1647.0,284.0,0.0,0.0,0.0,2.0,0.0,2.0,1.0,4.0,5.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,133.0,212.0,345.0,7.0,10.0,3.0,9.0,2123.0,75.0,NaN,2111.0,3.0,2112.0,0.0,2111.0,27.0,2112.0,1.0,2112.0,12.0,2112.0,3.0,2112.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,646.0,430.0,162.0,81.0,59.0,34.0,906.0,561.0,133.0,37.0,40.0,7.0,11.0,6.0,148.0,61.0,337.0,66.0,0.0,30.0,142.0,0.0,0.0,1.0,862.0,2185.0,50.0,0.0,NaN,0.0,0.0,0.0,1947.0,315.0,9.0,441.0,0.0,0.0,2103.0,2307.0,1094.0,0.0,0.0,0.0,1853.0,343.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,340.0,453.0,10.0,0.0,0.0,0.0,0.0,0.0,22.0,3.0,21.0,1278.0,0.0,0.0,439.0,0.0,49.0,65.0,0.0,0.0,0.0,0.0,134.0,132.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,107.0,126.0,233.0,0.0,0.0,0.0,302.0,733.0,1035.0,0.0,0.0,0.0,242.0,574.0,816.0,0.0,0.0,0.0,0.0,0.0,0.0,160.0,78.0,238.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0,215.0,77.0,2.0,82.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
1,9.0,2023-04-13 16:24:27,4.0,pt-BR,1.541636e+09,s16oIPSgdM8DdUr,2023-04-13 15:49:43,2023-04-13 16:24:27,10.0.113.219,NaN,ORIGINAL,2023.0,Janeiro,NaN,"Fortaleza, Ceará",Fujisan Centro de Hemoterapia e Hematologia do...,NaN,7.871680e+12,Núcleo de Hemoterapia,Privado,Único serviço,NaN,NaN,NaN,358.0,38.0,1257.0,181.0,0.0,0.0,864.0,140.0,535.0,47.0,216.0,32.0,1103.0,79.0,512.0,140.0,0.0,0.0,461.0,66.0,1144.0,152.0,0.0,0.0,0.0,6.0,0.0,6.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,71.0,137.0,208.0,7.0,8.0,1.0,6.0,1545.0,62.0,NaN,1458.0,3.0,1458.0,2.0,1458.0,15.0,1458.0,1.0,1458.0,9.0,1458.0,2.0,1458.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,462.0,342.0,115.0,78.0,37.0,35.0,618.0,489.0,102.0,29.0,15.0,11.0,1.0,0.0,104.0,51.0,226.0,60.0,3.0,21.0,91.0,5.0,0.0,0.0,549.0,1604.0,42.0,0.0,NaN,0.0,0.0,0.0,1377.0,263.0,4.0,392.0,72.0,0.0,1532.0,2049.0,857.0,0.0,0.0,0.0,1298.0,199.0,31.0,0.0,0.0,0.0,0.0,0.0,0.0,534.0,344.0,1.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,5.0,740.0,0.0,34.0,222.0,0.0,23.0,47.0,0.0,0.0,0.0,0.0,136.0,91.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,81.0,117.0,198.0,54.0,0.0,54.0,258.0,616.0,874.0,0.0,0.0,0.0,164.0,368.0,532.0,0.0,0.0,0.0,0.0,0.0,0.0,126.0,113.0,239.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39.0,213.0,45.0,5.0,58.0,2.0,0.0,6.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
2,10.0,2023-04-14 11:50:10,4.0,pt-BR,6.238845e+08,s16oIPSgdM8DdUr,2023-04-14 11:13:36,2023-04-14 11:50:10,10.0.0.195,NaN,ORIGINAL,2023.0,Fevereiro,NaN,"Fortaleza, Ceará",Fujisan Centro de Hemoterapia e Hematologia do...,NaN,7.871680e+12,Núcleo de Hemoterapia,Privado,Único serviço,NaN,NaN,NaN,563.0,66.0,1292.0,205.0,0.0,0.0,959.0,187.0,505.0,38.0,391.0,46.0,1207.0,101.0,648.0,170.0,0.0,0.0,480.0,64.0,1366.0,206.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,98.0,169.0,267.0,5.0,6.0,0.0,5.0,1788.0,62.0,NaN,1951.0,1.0,1951.0,1.0,1951.0,20.0,1951.0,0.0,1951.0,14.0,1951.0,2.0,1951.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,604.0,358.0,159.0,74.0,48.0,27.0,873.0,469.0,83.0,35.0,21.0,4.0,5.0,1.0,161.0,46.0,271.0,51.0,2.0,18.0,123.0,5.0,0.0,0.0,777.0,1848.0,52.0,0.0,NaN,0.0,0.0,0.0,1664.0,264.0,7.0,340.0,0.0,0.0,1776.0,2015.0,897.0,0.0,0.0,0.0,1580.0,235.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,585.0,380.0,12.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0,24.0,992.0,0.0,28.0,294.0,0.0,17.0,67.0,0.0,0.0,0.0,0.0,418.0,105.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,62.0,140.0,202.0,0.0,0.0,0.0,262.0,596.0,858.0,0.0,0.0,0.0,134.0,367.0,501.0,0.0,0.0,0.0,0.0,0.0,0.0,67.0,169.0,236.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,197.0,57.0,1.0,78.0,2.0,0.0,5.0,0.0,0.0,0.0,2.0,0.0,0.0,NaN
3,11.0,2023-05-08 13:07:37,4.0,pt-BR,1.913022e+08,s16oIPSgdM8DdUr,2023-05-08 12:47:48,2023-05-08 13:07:37,10.0.52.31,NaN,ORIGINAL,2023.0,Abril,NaN,"Fortaleza, Ceará",Fujisan Centro de Hemoterapia e Hematologia do...,NaN,7.871680e+12,Núcleo de Hemoterapia,Privado,Único serviço,NaN,NaN,NaN,564.0,67.0,1393.0,284.0,0.0,0.0,1099.0,249.0,514.0,41.0,344.0,61.0,1351.0,150.0,606.0,201.0,0.0,0.0,599.0,99.0,1348.0,250.0,0.0,0.0,0.0,4.0,1.0,5.0,1.0,5.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,143.0,195.0,338.0,8.0,10.0,1.0,9.0,1876.0,73.0,NaN,1991.0,2.0,1991.0,2.0,1991.0,17.0,1991.0,1.0,1990.0,11.0,1991.0,6.0,1991.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,580.0,343.0,209.0,87.0,92.0,46.0,842.0,490.0,80.0,39.0,35.0,9.0,9.0,1.0,145.0,45.0,275.0,66.0,0.0,22.0,111.0,0.0,0.0,1.0,810.0,1939.0,51.0,0.0,NaN,0.0,0.0,0.0,1626.0,305.0,2.0,485.0,138.0,0.0,1839.0,2035.0,846.0,0.0,0.0,0.0,1622.0,259.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,430.0,278.0,8.0,0.0,0.0,0.0,1.0,0.0,38.0,1.0,14.0,1313.0,0.0,7.0,427.0,0.0,144.0,91.0,0.0,0.0,0.0,0.0,120.0,211.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,75.0,133.0,208.0,136.0,0.0,136.0,248.0,685.0,933.0,0.0,0.0,0.0,158.0,405.0,563.0,0.0,0.0,0.0,0.0,0.0,0.0,76.0,126.0,202.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,202.0,39.0,0.0,85.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [41]:
hemoprod_ce_deduplicado.to_excel('dados_processados/hemoprod_ce.xlsx', index=False)

## Hemoprod Distrito Federal

In [42]:
import os
import pandas as pd

dados_brutos_path = 'dados_brutos'

arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_DF.xlsx')
nome_planilha = 'HEMOPROD - DISTRITOFEDERAL'

dicionario_path_df = ('./dicionario_colunas_269.xlsx')
# dicionario_path_ap = ('./dicionario_colunas_270.xlsx')

dicionario_df = pd.read_excel(dicionario_path_df, sheet_name='Sheet1')

# --- 2. Carregue os dados e o dicionário ---
try:
    # Carrega o arquivo de dados
    hemoprod_df = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)
    print("Arquivo de dados carregado com sucesso.")
    print(f"Número de colunas original: {len(hemoprod_df.columns)}")

    # Carrega o arquivo de dicionário
    dicionario = pd.read_excel(dicionario_path_df)
    print("Arquivo de dicionário carregado com sucesso.")

    # --- 3. Extraia a lista de novos nomes ---
    # Pega os valores da coluna 'nome_sql' e converte para uma lista
    novos_nomes = dicionario['nome_sql'].tolist()
    print(f"Número de novos nomes no dicionário: {len(novos_nomes)}")

    # --- 4. Verificação de segurança (MUITO IMPORTANTE) ---
    # Garante que o número de colunas é o mesmo antes de renomear
    if len(hemoprod_df.columns) == len(novos_nomes):
        print("\nO número de colunas corresponde. Renomeando...")
        
        # --- 5. Substitua os nomes das colunas ---
        # Esta é a linha principal que faz a substituição direta
        hemoprod_df.columns = novos_nomes
        
        print("Colunas renomeadas com sucesso!")
        
        # --- 6. Verifique o resultado ---
        print("\nInformações do DataFrame com as novas colunas:")
        hemoprod_df.info()
        
        print("\nAs 5 primeiras linhas com as novas colunas:")
        display(hemoprod_df.head())

    else:
        # Mensagem de erro se o número de colunas for diferente
        print("\n--- ERRO ---")
        print("A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.")
        print(f"Colunas no arquivo de dados: {len(hemoprod_df.columns)}")
        print(f"Nomes no dicionário: {len(novos_nomes)}")

except FileNotFoundError as e:
    print(f"\nErro de arquivo não encontrado: {e}")
except KeyError as e:
    print(f"\nErro de coluna não encontrada: {e}. Verifique se a coluna 'nome_sql' existe no seu arquivo de dicionário.")
except Exception as e:
    print(f"\nOcorreu um erro inesperado: {e}")

Arquivo de dados carregado com sucesso.
Número de colunas original: 269
Arquivo de dicionário carregado com sucesso.
Número de novos nomes no dicionário: 269

O número de colunas corresponde. Renomeando...
Colunas renomeadas com sucesso!

Informações do DataFrame com as novas colunas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Columns: 269 entries, id to hemoprod_3_observacoes
dtypes: float64(250), int64(4), object(15)
memory usage: 386.8+ KB

As 5 primeiras linhas com as novas colunas:

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,11,2023-05-10 11:29:00,4,pt-BR,NaN,rPK9T4H3U3oa2a9,2023-05-10 11:01:00,2023-05-10 11:29:00,10.0.0.30,NaN,ORIGINAL,2023,Abril,NaN,"Brasília, Distrito Federal",Grupo Gestor de Serviços em Hemoterapia (GSH) ...,GSH - AT HOSPITAL SANTA LUZIA,8397078001841,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,43.0,0.0,20.0,0.0,11.0,0.0,82.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,15.0,0.0,15.0,0.0,4.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,23.0,175.0,11.0,0.0,0.0,0.0,23.0,196.0,19.0,3.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,4.0,3.0,0.0,0.0,0.0,1.0,2.0,5.0,0.0,0.0,0.0,0.0,73.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,7.0,116.0,123.0,0.0,0.0,0.0,0.0,63.0,63.0,3.0,11.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,10.0,0.0,0.0,0.0,94.0,0.0,94.0,0.0,0.0,0.0,78.0,0.0,78.0,6.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,82.0,77.0,221.0,36.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,12,2023-05-10 12:22:00,4,pt-BR,NaN,MIXePx6p2p5vAoy,2023-05-10 12:03:00,2023-05-10 12:22:00,10.0.4.36,NaN,ORIGINAL,2023,Abril,NaN,"Brasília, Distrito Federal",Grupo Gestor de Serviços em Hemoterapia (GSH) ...,GSH - AT HOSPITAL SANTA HELENA,8397078002066,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,34.0,0.0,13.0,0.0,2.0,0.0,38.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0,11.0,0.0,19.0,0.0,1.0,21.0,27.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,261.0,25.0,0.0,0.0,0.0,0.0,146.0,19.0,0.0,8.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,19.0,6.0,0.0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,10.0,0.0,0.0,0.0,4.0,104.0,108.0,0.0,0.0,0.0,0.0,42.0,42.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,10.0,0.0,0.0,0.0,219.0,0.0,219.0,0.0,0.0,0.0,109.0,0.0,109.0,8.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67.0,49.0,196.0,5.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN
2,14,2023-05-15 12:56:00,4,pt-BR,NaN,WZ4ZIXCj3uWhwAH,2023-05-15 12:04:00,2023-05-15 12:56:00,10.0.3.242,NaN,ORIGINAL,2023,Abril,NaN,"Brasília, Distrito Federal",Grupo Gestor de Serviços em Hemoterapia (GSH) ...,AT HOSPITAL SANTA LÚCIA SUL,8397078003,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,89.0,0.0,24.0,0.0,7.0,0.0,151.0,0.0,27.0,0.0,17.0,0.0,2.0,0.0,9.0,0.0,55.0,0.0,17.0,0.0,17.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,31.0,0.0,0.0,0.0,0.0,45.0,268.0,24.0,0.0,0.0,0.0,20.0,159.0,14.0,0.0,14.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,2.0,0.0,0.0,0.0,0.0,5.0,10.0,0.0,0.0,0.0,0.0,19.0,7.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,55.0,55.0,0.0,0.0,0.0,0.0,270.0,270.0,0.0,0.0,0.0,0.0,116.0,116.0,0.0,10.0,10.0,0.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,162.0,0.0,162.0,0.0,0.0,0.0,80.0,0.0,80.0,0.0,0.0,0.0,35.0,0.0,35.0,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,154.0,89.0,480.0,44.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN
3,15,2023-05-15 14:31:00,4,pt-BR,NaN,iehHllaeyrYagiU,2023-05-15 14:10:00,2023-05-15 14:31:00,10.0.51.170,NaN,ORIGINAL,2023,Abril,NaN,"Brasília, Distrito Federal",Grupo Gestor de Serviços em Hemoterapia (GSH) ...,BANCO DE SANGUE BRASÍLIA - GRUPO GSH,9397078002490,Unidade de Coleta,Privado,Único serviço,NaN,NaN,NaN,247.0,33.0,288.0,78.0,1.0,0.0,344.0,94.0,175.0,16.0,17.0,1.0,296.0,69.0,240.0,42.0,0.0,0.0,174.0,30.0,362.0,81.0,0.0,1.0,1.0,5.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,4.0,18.0,4.0,6.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.0,54.0,100.0,0.0,13.0,0.0,3.0,542.0,63.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16,2023-05-15 16:23:00,4,pt-BR,NaN,1aorcIMzUajACtF,2023-05-15 14:42:00,2023-05-15 16:23:00,10.0.0.84,NaN,ORIGINAL,2023,Abril,NaN,"Brasília, Distrito Federal",Grupo Gestor de Serviços em Hemoterapia (GSH) ...,AT Hosipital Santa Lucia Norte - Brasilia,8397078003038,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,59.0,0.0,7.0,0.0,3.0,0.0,103.0,0.0,12.0,0.0,2.0,0.0,0.0,0.0,4.0,0.0,18.0,0.0,5.0,0.0,6.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,208.0,10.0,0.0,0.0,0.0,0.0,102.0,0.0,0.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,1.0,24.0,3.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,150.0,150.0,0.0,0.0,0.0,0.0,70.0,70.0,0.0,11.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57.0,85.0,311.0,6.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

In [43]:
# --- 2. Defina as colunas para a chave e para ordenação ---
registros_antes = len(hemoprod_df)
print(f"Total de registros ANTES da remoção de duplicatas: {registros_antes}")
    

colunas_chave = [
        'cnpj', 
        'ano_referencia', 
        'periodo_referencia', 
        'razao_social_nome_fantasia'
    ]

coluna_data = 'data_envio'

# --- 3. Verifique se as colunas necessárias existem ---
colunas_necessarias = colunas_chave + [coluna_data]

if not all(col in hemoprod_df.columns for col in colunas_necessarias):
    print("\n--- ERRO ---")
    print("Uma ou mais colunas necessárias para a deduplicação não foram encontradas.")
    colunas_faltantes = [col for col in colunas_necessarias if col not in hemoprod_df.columns]
    print(f"Colunas necessárias: {colunas_necessarias}")
    print(f"Colunas faltantes no DataFrame: {colunas_faltantes}")
else:
    # --- 4. Prepare a coluna de data e ordene os dados ---
    # Converte a coluna 'data_envio' para datetime para garantir a ordenação correta.
    # 'errors='coerce'' transformará datas inválidas em NaT (Not a Time), que são tratadas como nulas.
    hemoprod_df[coluna_data] = pd.to_datetime(hemoprod_df[coluna_data], errors='coerce')

    # Ordena o DataFrame. Os registros com data de envio mais recente ficarão por último.
    print(f"\nOrdenando os dados por '{coluna_data}'...")
    hemoprod_df_ordenado = hemoprod_df.sort_values(by=coluna_data, ascending=True)

    # --- 5. Identifique e separe os registros duplicados e únicos ---
    # Em vez de usar drop_duplicates() diretamente, vamos usar duplicated()
    # para criar uma máscara booleana.
    # 'keep='last'' marca todas as ocorrências de uma chave como True, EXCETO a última (a mais recente).
    print(f"Identificando duplicatas com cese na chave: {colunas_chave}...")
    mascara_duplicatas = hemoprod_df_ordenado.duplicated(subset=colunas_chave, keep='last')

    # O DataFrame de removidos conterá todas as linhas marcadas como True
    hemoprod_removidos = hemoprod_df_ordenado[mascara_duplicatas]
    
    # O DataFrame deduplicado conterá o INVERSO (~) da máscara (linhas marcadas como False)
    hemoprod_df_deduplicado = hemoprod_df_ordenado[~mascara_duplicatas]
    
    # Agora podemos contar os registros diretamente dos novos DataFrames
    registros_depois = len(hemoprod_df_deduplicado)
    registros_removidos = len(hemoprod_removidos) 
    
    # --- 6. Exice o resultado ---
    print("\n--- Processo Concluído ---")
    print(f"Registros removidos: {registros_removidos}")
    print(f"Total de registros DEPOIS da remoção de duplicatas: {registros_depois}")

    # (Opcional) Exibe a amostra dos removidos
    print("\nAmostra dos dados REMOVIDOS (os mais antigos/duplicados):")
    display(hemoprod_removidos.head(10))

    # Você pode continuar a usar o DataFrame 'hemoprod_ce_deduplicado' para suas análises
    print("\nAmostra dos dados únicos (os mais recentes para cada chave):")
    display(hemoprod_df_deduplicado.head(10))
    
    # Agora você tem o DataFrame 'hemoprod_removidos' salvo

Total de registros ANTES da remoção de duplicatas: 184

Ordenando os dados por 'data_envio'...
Identificando duplicatas com cese na chave: ['cnpj', 'ano_referencia', 'periodo_referencia', 'razao_social_nome_fantasia']...

--- Processo Concluído ---
Registros removidos: 1
Total de registros DEPOIS da remoção de duplicatas: 183

Amostra dos dados REMOVIDOS (os mais antigos/duplicados):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
166,214,2025-07-11 15:42:42,4,pt-BR,1.813328e+09,x2aCGP57HelTDzN,2025-07-11 15:28:30,2025-07-11 15:42:42,164.163.2.146,NaN,ORIGINAL,2025,Julho,NaN,"Brasília, Distrito Federal",Grupo Gestor de Serviços em Hemoterapia (GSH) ...,NaN,8397078003038,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,42.0,0.0,14.0,0.0,3.0,0.0,118.0,0.0,5.0,0.0,10.0,0.0,2.0,0.0,10.0,0.0,27.0,0.0,5.0,0.0,6.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,257.0,20.0,0.0,0.0,0.0,0.0,118.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,11.0,0.0,0.0,0.0,0.0,165.0,165.0,0.0,0.0,0.0,0.0,55.0,55.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,0.0,17.0,0.0,0.0,0.0,91.0,0.0,91.0,0.0,0.0,0.0,28.0,0.0,28.0,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

Amostra dos dados únicos (os mais recentes para cada chave):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,11,2023-05-10 11:29:00,4,pt-BR,NaN,rPK9T4H3U3oa2a9,2023-05-10 11:01:00,2023-05-10 11:29:00,10.0.0.30,NaN,ORIGINAL,2023,Abril,NaN,"Brasília, Distrito Federal",Grupo Gestor de Serviços em Hemoterapia (GSH) ...,GSH - AT HOSPITAL SANTA LUZIA,8397078001841,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,43.0,0.0,20.0,0.0,11.0,0.0,82.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,15.0,0.0,15.0,0.0,4.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,23.0,175.0,11.0,0.0,0.0,0.0,23.0,196.0,19.0,3.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,4.0,3.0,0.0,0.0,0.0,1.0,2.0,5.0,0.0,0.0,0.0,0.0,73.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,7.0,116.0,123.0,0.0,0.0,0.0,0.0,63.0,63.0,3.0,11.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,10.0,0.0,0.0,0.0,94.0,0.0,94.0,0.0,0.0,0.0,78.0,0.0,78.0,6.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,82.0,77.0,221.0,36.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,12,2023-05-10 12:22:00,4,pt-BR,NaN,MIXePx6p2p5vAoy,2023-05-10 12:03:00,2023-05-10 12:22:00,10.0.4.36,NaN,ORIGINAL,2023,Abril,NaN,"Brasília, Distrito Federal",Grupo Gestor de Serviços em Hemoterapia (GSH) ...,GSH - AT HOSPITAL SANTA HELENA,8397078002066,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,34.0,0.0,13.0,0.0,2.0,0.0,38.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0,11.0,0.0,19.0,0.0,1.0,21.0,27.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,261.0,25.0,0.0,0.0,0.0,0.0,146.0,19.0,0.0,8.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,19.0,6.0,0.0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,10.0,0.0,0.0,0.0,4.0,104.0,108.0,0.0,0.0,0.0,0.0,42.0,42.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,10.0,0.0,0.0,0.0,219.0,0.0,219.0,0.0,0.0,0.0,109.0,0.0,109.0,8.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67.0,49.0,196.0,5.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN
2,14,2023-05-15 12:56:00,4,pt-BR,NaN,WZ4ZIXCj3uWhwAH,2023-05-15 12:04:00,2023-05-15 12:56:00,10.0.3.242,NaN,ORIGINAL,2023,Abril,NaN,"Brasília, Distrito Federal",Grupo Gestor de Serviços em Hemoterapia (GSH) ...,AT HOSPITAL SANTA LÚCIA SUL,8397078003,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,89.0,0.0,24.0,0.0,7.0,0.0,151.0,0.0,27.0,0.0,17.0,0.0,2.0,0.0,9.0,0.0,55.0,0.0,17.0,0.0,17.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,31.0,0.0,0.0,0.0,0.0,45.0,268.0,24.0,0.0,0.0,0.0,20.0,159.0,14.0,0.0,14.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,2.0,0.0,0.0,0.0,0.0,5.0,10.0,0.0,0.0,0.0,0.0,19.0,7.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,55.0,55.0,0.0,0.0,0.0,0.0,270.0,270.0,0.0,0.0,0.0,0.0,116.0,116.0,0.0,10.0,10.0,0.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,162.0,0.0,162.0,0.0,0.0,0.0,80.0,0.0,80.0,0.0,0.0,0.0,35.0,0.0,35.0,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,154.0,89.0,480.0,44.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN
3,15,2023-05-15 14:31:00,4,pt-BR,NaN,iehHllaeyrYagiU,2023-05-15 14:10:00,2023-05-15 14:31:00,10.0.51.170,NaN,ORIGINAL,2023,Abril,NaN,"Brasília, Distrito Federal",Grupo Gestor de Serviços em Hemoterapia (GSH) ...,BANCO DE SANGUE BRASÍLIA - GRUPO GSH,9397078002490,Unidade de Coleta,Privado,Único serviço,NaN,NaN,NaN,247.0,33.0,288.0,78.0,1.0,0.0,344.0,94.0,175.0,16.0,17.0,1.0,296.0,69.0,240.0,42.0,0.0,0.0,174.0,30.0,362.0,81.0,0.0,1.0,1.0,5.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,4.0,18.0,4.0,6.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.0,54.0,100.0,0.0,13.0,0.0,3.0,542.0,63.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16,2023-05-15 16:23:00,4,pt-BR,NaN,1aorcIMzUajACtF,2023-05-15 14:42:00,2023-05-15 16:23:00,10.0.0.84,NaN,ORIGINAL,2023,Abril,NaN,"Brasília, Distrito Federal",Grupo Gestor de Serviços em Hemoterapia (GSH) ...,AT Hosipital Santa Lucia Norte - Brasilia,8397078003038,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,59.0,0.0,7.0,0.0,3.0,0.0,103.0,0.0,12.0,0.0,2.0,0.0,0.0,0.0,4.0,0.0,18.0,0.0,5.0,0.0,6.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,208.0,10.0,0.0,0.0,0.0,0.0,102.0,0.0,0.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,1.0,24.0,3.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,150.0,150.0,0.0,0.0,0.0,0.0,70.0,70.0,0.0,11.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57.0,85.0,311.0,6.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

In [44]:
hemoprod_df_deduplicado.to_excel('dados_processados/hemoprod_df.xlsx', index=False)

## Hemoprod Espirito Santo

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
import os
import pandas as pd

dados_brutos_path = 'dados_brutos'

arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_ES.xlsx')
nome_planilha = 'HEMOPROD - ESPIRITOSANTO'

dicionario_path_es = ('./dicionario_colunas_269.xlsx')
# dicionario_path_ap = ('./dicionario_colunas_270.xlsx')

dicionario_es = pd.read_excel(dicionario_path_es, sheet_name='Sheet1')

# --- 2. Carregue os dados e o dicionário ---
try:
    # Carrega o arquivo de dados
    hemoprod_es = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)
    print("Arquivo de dados carregado com sucesso.")
    print(f"Número de colunas original: {len(hemoprod_es.columns)}")

    # Carrega o arquivo de dicionário
    dicionario = pd.read_excel(dicionario_path_es)
    print("Arquivo de dicionário carregado com sucesso.")

    # --- 3. Extraia a lista de novos nomes ---
    # Pega os valores da coluna 'nome_sql' e converte para uma lista
    novos_nomes = dicionario['nome_sql'].tolist()
    print(f"Número de novos nomes no dicionário: {len(novos_nomes)}")

    # --- 4. Verificação de segurança (MUITO IMPORTANTE) ---
    # Garante que o número de colunas é o mesmo antes de renomear
    if len(hemoprod_es.columns) == len(novos_nomes):
        print("\nO número de colunas corresponde. Renomeando...")
        
        # --- 5. Substitua os nomes das colunas ---
        # Esta é a linha principal que faz a substituição direta
        hemoprod_es.columns = novos_nomes
        
        print("Colunas renomeadas com sucesso!")
        
        # --- 6. Verifique o resultado ---
        print("\nInformações do DataFrame com as novas colunas:")
        hemoprod_es.info()
        
        print("\nAs 5 primeiras linhas com as novas colunas:")
        display(hemoprod_es.head())

    else:
        # Mensagem de erro se o número de colunas for diferente
        print("\n--- ERRO ---")
        print("A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.")
        print(f"Colunas no arquivo de dados: {len(hemoprod_es.columns)}")
        print(f"Nomes no dicionário: {len(novos_nomes)}")

except FileNotFoundError as e:
    print(f"\nErro de arquivo não encontrado: {e}")
except KeyError as e:
    print(f"\nErro de coluna não encontrada: {e}. Verifique se a coluna 'nome_sql' existe no seu arquivo de dicionário.")
except Exception as e:
    print(f"\nOcorreu um erro inesperado: {e}")

Arquivo de dados carregado com sucesso.
Número de colunas original: 257
Arquivo de dicionário carregado com sucesso.
Número de novos nomes no dicionário: 270

--- ERRO ---
A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.
Colunas no arquivo de dados: 257
Nomes no dicionário: 270

In [51]:
arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_CE.xlsx')
nome_planilha = 'Planilha1'
hemoprod_ce1 = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)

colunas_padrao = set(hemoprod_ce1.columns)
colunas_estado = set(hemoprod_es.columns)

colunas_faltantes = list(colunas_padrao - colunas_estado)

colunas_a_mais = list(colunas_estado - colunas_padrao)

print(f"Número de colunas faltantes: {len(colunas_faltantes)}")
print(f"Colunas faltantes (a serem adicionadas): {colunas_faltantes}")
print("-" * 30)
print(f"Número de colunas a mais: {len(colunas_a_mais)}")
print(f"Colunas a mais (a serem dropadas): {colunas_a_mais}")

Número de colunas faltantes: 15
Colunas faltantes (a serem adicionadas): ['6. Produção Hemoterápica  6.1(a) Entradas\xa0  [Concentrado de Plaquetas de Aférese][Recebidas]', 'Cite os estabelecimentos que compõem a rede  Informe o Tipo de Estabelecimento, o Nome Fantasia\xa0e o Município de localização de cada um. ', '6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Outros motivos]', 'Ano de referência\xa0 ', '6. Produção Hemoterápica  6.1(a) Entradas\xa0  [Concentrado de Plaquetas de Aférese][Devolvidas]', '6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Validade]', '6.1(d) Distribuição para outros serviços  \xa0  [Concentrado de Plaquetas de Aférese][Total]', '6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Total]', '6.1(d) Distribuição para outros serviços  \xa0  [Concentrado de Plaquetas de Aférese][Com exame pré-transfusional ]', '6. Produção Hemoterápica  6.1(a) Entradas\xa0  [Concentrado de Plaquetas de Aférese][Produzidas]', '6.1(d) Distribuição para outros serviços  \xa0  [Concentrado de Plaquetas de Aférese][Sem exame pré-transfusional ]', '6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Hospitalar]', '6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Rompimento de Bolsa]', 'Os dados informados referem-se à um(a): ', '6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Ambulatorial]']
------------------------------
Número de colunas a mais: 3
Colunas a mais (a serem dropadas): ['Período de referência [Outros]', 'Município [Outros]', 'URL de referência']

In [52]:
colunas_a_mais = ['Período de referência [Outros]', 'Município [Outros]', 'URL de referência']

# Conta quantos valores *não são nulos* em cada uma dessas colunas
contagem_nao_nulos = hemoprod_es[colunas_a_mais].count()

print("Contagem de valores NÃO-NULOS (preenchidos) por coluna:")
print(contagem_nao_nulos)

Contagem de valores NÃO-NULOS (preenchidos) por coluna:
Período de referência [Outros]     19
Município [Outros]                  0
URL de referência                 610
dtype: int64

In [53]:
if colunas_a_mais:
    hemoprod_es = hemoprod_es.drop(columns=colunas_a_mais, errors='ignore')
    print(f"Colunas a mais removidas: {colunas_a_mais}")
else:
    print("Nenhuma coluna para remover.")

# 2. ADICIONAR as colunas faltantes e preenchê-las com zero (0)
for coluna in colunas_faltantes:
    # Cria a nova coluna no hemoprod_es preenchida com 0
    hemoprod_es[coluna] = 0

print(f"Colunas faltantes adicionadas e zeradas: {colunas_faltantes}")

# 3. REORDENAR as colunas do hemoprod_es na mesma ordem do df_padrao
# A lista de colunas do df_padrao agora é o nosso gabarito final
ordem_padrao = hemoprod_ce1.columns.tolist()

# Reorganiza as colunas do hemoprod_es
hemoprod_es = hemoprod_es[ordem_padrao]

print("-" * 50)
print("Processo concluído:")
print(f"Total de colunas após o ajuste: {len(hemoprod_es.columns)}")
print("A ordem das colunas no df_estado agora corresponde à ordem do df_padrao.")

Colunas a mais removidas: ['Período de referência [Outros]', 'Município [Outros]', 'URL de referência']
Colunas faltantes adicionadas e zeradas: ['6. Produção Hemoterápica  6.1(a) Entradas\xa0  [Concentrado de Plaquetas de Aférese][Recebidas]', 'Cite os estabelecimentos que compõem a rede  Informe o Tipo de Estabelecimento, o Nome Fantasia\xa0e o Município de localização de cada um. ', '6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Outros motivos]', 'Ano de referência\xa0 ', '6. Produção Hemoterápica  6.1(a) Entradas\xa0  [Concentrado de Plaquetas de Aférese][Devolvidas]', '6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Validade]', '6.1(d) Distribuição para outros serviços  \xa0  [Concentrado de Plaquetas de Aférese][Total]', '6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Total]', '6.1(d) Distribuição para outros serviços  \xa0  [Concentrado de Plaquetas de Aférese][Com exame pré-transfusional ]', '6. Produção Hemoterápica  6.1(a) Entradas\xa0  [Concentrado de Plaquetas de Aférese][Produzidas]', '6.1(d) Distribuição para outros serviços  \xa0  [Concentrado de Plaquetas de Aférese][Sem exame pré-transfusional ]', '6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Hospitalar]', '6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Rompimento de Bolsa]', 'Os dados informados referem-se à um(a): ', '6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Ambulatorial]']
--------------------------------------------------
Processo concluído:
Total de colunas após o ajuste: 269
A ordem das colunas no df_estado agora corresponde à ordem do df_padrao.

In [54]:
# Mapeia as colunas, limpando espaços em branco no início e fim
# e substituindo o caractere \xa0 por um espaço normal.
novos_nomes = {col: col.strip().replace('\xa0', ' ') for col in hemoprod_es.columns}

# Aplica a renomeação
hemoprod_es = hemoprod_es.rename(columns=novos_nomes)

print("Nomes das colunas limpos e padronizados.")

Nomes das colunas limpos e padronizados.

In [55]:
# Nomes das colunas após a limpeza (ajuste se a coluna original tiver nome diferente)
coluna_periodo_limpa = 'Período de referência'
coluna_ano_limpa = 'Ano de referência' # Ou apenas 'Ano de referencia'

# Nota: Certifique-se de que a sua coluna original do período esteja na ordem correta,
# caso contrário, a lógica de reordenação no final fará o trabalho.

# 1. Criar ou sobrescrever a coluna 'Ano de referencia' (limpa)
# O split divide a string e o str[1] pega o ano
hemoprod_es[coluna_ano_limpa] = hemoprod_es[coluna_periodo_limpa].astype(str).str.split('/').str[1]

# 2. Atualizar a coluna original 'Período de referência' (para ter só o mês)
# O split divide a string e o str[0] pega o mês
hemoprod_es[coluna_periodo_limpa] = hemoprod_es[coluna_periodo_limpa].astype(str).str.split('/').str[0]

print("Separação de mês e ano concluída nas colunas limpas.")
print(hemoprod_es[[coluna_periodo_limpa, coluna_ano_limpa]].head())

Separação de mês e ano concluída nas colunas limpas.
  Período de referência Ano de referência
0               Outubro              2022
1               Outubro              2022
2               Outubro              2022
3               Outubro              2022
4              Novembro              2022

In [56]:
set(hemoprod_es.columns)

{'2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Autóloga][Aptos]',
 '2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Autóloga][Inaptos]',
 '2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Espontânea][Aptos]',
 '2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Espontânea][Inaptos]',
 '2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Reposição][Aptos]',
 '2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Reposição][Inaptos]',
 '2.2 Total de candidatos quanto ao tipo de doador  [Esporádico][Aptos]',
 '2.2 Total de candidatos quanto ao tipo de doador  [Esporádico][Inaptos]',
 '2.2 Total de candidatos quanto ao tipo de doador  [Primeira vez][Aptos]',
 '2.2 Total de candidatos quanto ao tipo de doador  [Primeira vez][Inaptos]',
 '2.2 Total de candidatos quanto ao tipo de doador  [Repetição][Aptos]',
 '2.2 Total de candidatos quanto ao tipo de doador  [Repetição][Inaptos]',
 '2.3 Total de candidatos quanto ao gênero do doador  [Feminino][Aptos]',
 '2.3 Total de candidatos quanto ao gênero do doador  [Feminino][Inaptos]',
 '2.3 Total de candidatos quanto ao gênero do doador  [Masculino][Aptos]',
 '2.3 Total de candidatos quanto ao gênero do doador  [Masculino][Inaptos]',
 '2.4 Total de candidatos quanto a idade do doador  [18 até 29 anos][Aptos]',
 '2.4 Total de candidatos quanto a idade do doador  [18 até 29 anos][Inaptos]',
 '2.4 Total de candidatos quanto a idade do doador  [Acima de 29 anos][Aptos]',
 '2.4 Total de candidatos quanto a idade do doador  [Acima de 29 anos][Inaptos]',
 '2.4 Total de candidatos quanto a idade do doador  [Menor de 18 anos][Aptos]',
 '2.4 Total de candidatos quanto a idade do doador  [Menor de 18 anos][Inaptos]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Alcoolismo][Feminino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Alcoolismo][Masculino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Alcoolismo][Total]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Anemia][Feminino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Anemia][Masculino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Anemia][Total]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Comportamento de risco para DST][Feminino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Comportamento de risco para DST][Masculino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Comportamento de risco para DST][Total]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Doença de Chagas][Feminino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Doença de Chagas][Masculino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Doença de Chagas][Total]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hepatite][Feminino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hepatite][Masculino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hepatite][Total]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipertensão][Feminino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipertensão][Masculino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipertensão][Total]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipotensão][Feminino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipotensão][Masculino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipotensão][Total]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Malária][Feminino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Malária][Masculino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Malária][Total]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Outras][Feminino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Outras][Masculino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Outras][Total]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Uso de drogas][Feminino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Uso de drogas][Masculino]',
 '2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Uso de drogas][Total]',
 '3. Coleta  3.1 Total de candidatos desistentes',
 '3.2 Total de interrupções na coleta por [Dificuldade de punção venosa]',
 '3.2 Total de interrupções na coleta por [Outros motivos]',
 '3.2 Total de interrupções na coleta por [Reação vagal]',
 '3.3 Total de coletas [Por aférese]',
 '3.3 Total de coletas [Sangue total]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Doença de Chagas][Amostras reagentes]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Doença de Chagas][Amostras testadas]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HBV (Teste NAT)*][Amostras reagentes]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HBV (Teste NAT)*][Amostras testadas]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HCV (Teste NAT)*][Amostras reagentes]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HCV (Teste NAT)*][Amostras testadas]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HIV (Teste NAT)*][Amostras reagentes]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HIV (Teste NAT)*][Amostras testadas]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HIV][Amostras reagentes]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HIV][Amostras testadas]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HTLV I e II ][Amostras reagentes]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HTLV I e II ][Amostras testadas]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite B - Anti HBc ][Amostras reagentes]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite B - Anti HBc ][Amostras testadas]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite B - HBs Ag ][Amostras reagentes]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite B - HBs Ag ][Amostras testadas]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite C][Amostras reagentes]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite C][Amostras testadas]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Malária][Amostras reagentes]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Malária][Amostras testadas]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Sífilis ][Amostras reagentes]',
 '4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Sífilis ][Amostras testadas]',
 '4.2 Imunohematologia [A+][Doador]',
 '4.2 Imunohematologia [A+][Receptor]',
 '4.2 Imunohematologia [A-][Doador]',
 '4.2 Imunohematologia [A-][Receptor]',
 '4.2 Imunohematologia [AB+][Doador]',
 '4.2 Imunohematologia [AB+][Receptor]',
 '4.2 Imunohematologia [AB-][Doador]',
 '4.2 Imunohematologia [AB-][Receptor]',
 '4.2 Imunohematologia [B+][Doador]',
 '4.2 Imunohematologia [B+][Receptor]',
 '4.2 Imunohematologia [B-][Doador]',
 '4.2 Imunohematologia [B-][Receptor]',
 '4.2 Imunohematologia [Combs Direto][Doador]',
 '4.2 Imunohematologia [Combs Direto][Receptor]',
 '4.2 Imunohematologia [Dfraco][Doador]',
 '4.2 Imunohematologia [Dfraco][Receptor]',
 '4.2 Imunohematologia [Fenotipagem][Doador]',
 '4.2 Imunohematologia [Fenotipagem][Receptor]',
 '4.2 Imunohematologia [O+][Doador]',
 '4.2 Imunohematologia [O+][Receptor]',
 '4.2 Imunohematologia [O-][Doador]',
 '4.2 Imunohematologia [O-][Receptor]',
 '4.2 Imunohematologia [Pesquisa de anticorpo irregular positivo][Doador]',
 '4.2 Imunohematologia [Pesquisa de anticorpo irregular positivo][Receptor]',
 '4.3 Outros tipos de pesquisa [Pesquisa de HbS no doador]',
 '4.4 Inaptidão na triagem laboratorial [Total de bolsas reagentes para 1 ou mais marcadores]',
 '4.4 Inaptidão na triagem laboratorial [Total de bolsas testadas]',
 '5. Descarte de Bolsas  5.1 Descarte de bolsas  [Total de bolsas descartadas por auto-exclusão]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias sem buffy coat][Devolvidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias sem buffy coat][Produzidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias sem buffy coat][Recebidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias][Devolvidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias][Produzidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias][Recebidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Leucócitos][Devolvidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Leucócitos][Produzidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Leucócitos][Recebidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas de Aférese][Devolvidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas de Aférese][Produzidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas de Aférese][Recebidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas sem buffy coat][Devolvidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas sem buffy coat][Produzidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas sem buffy coat][Recebidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas][Devolvidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas][Produzidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas][Recebidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Crioprecipitado][Devolvidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Crioprecipitado][Produzidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Crioprecipitado][Recebidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Plasma Fresco Congelado][Devolvidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Plasma Fresco Congelado][Produzidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Plasma Fresco Congelado][Recebidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Plasma comum][Devolvidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Plasma comum][Produzidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Plasma comum][Recebidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Sangue total][Devolvidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Sangue total][Produzidas]',
 '6. Produção Hemoterápica  6.1(a) Entradas   [Sangue total][Recebidas]',
 '6.1(b) Perdas  [Concentrado de Hemácias sem buffy coat][Outros motivos]',
 '6.1(b) Perdas  [Concentrado de Hemácias sem buffy coat][Rompimento de Bolsa]',
 '6.1(b) Perdas  [Concentrado de Hemácias sem buffy coat][Validade]',
 '6.1(b) Perdas  [Concentrado de Hemácias][Outros motivos]',
 '6.1(b) Perdas  [Concentrado de Hemácias][Rompimento de Bolsa]',
 '6.1(b) Perdas  [Concentrado de Hemácias][Validade]',
 '6.1(b) Perdas  [Concentrado de Leucócitos][Outros motivos]',
 '6.1(b) Perdas  [Concentrado de Leucócitos][Rompimento de Bolsa]',
 '6.1(b) Perdas  [Concentrado de Leucócitos][Validade]',
 '6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Outros motivos]',
 '6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Rompimento de Bolsa]',
 '6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Validade]',
 '6.1(b) Perdas  [Concentrado de Plaquetas sem buffy coat][Outros motivos]',
 '6.1(b) Perdas  [Concentrado de Plaquetas sem buffy coat][Rompimento de Bolsa]',
 '6.1(b) Perdas  [Concentrado de Plaquetas sem buffy coat][Validade]',
 '6.1(b) Perdas  [Concentrado de Plaquetas][Outros motivos]',
 '6.1(b) Perdas  [Concentrado de Plaquetas][Rompimento de Bolsa]',
 '6.1(b) Perdas  [Concentrado de Plaquetas][Validade]',
 '6.1(b) Perdas  [Crioprecipitado][Outros motivos]',
 '6.1(b) Perdas  [Crioprecipitado][Rompimento de Bolsa]',
 '6.1(b) Perdas  [Crioprecipitado][Validade]',
 '6.1(b) Perdas  [Plasma Fresco Congelado][Outros motivos]',
 '6.1(b) Perdas  [Plasma Fresco Congelado][Rompimento de Bolsa]',
 '6.1(b) Perdas  [Plasma Fresco Congelado][Validade]',
 '6.1(b) Perdas  [Plasma comum][Outros motivos]',
 '6.1(b) Perdas  [Plasma comum][Rompimento de Bolsa]',
 '6.1(b) Perdas  [Plasma comum][Validade]',
 '6.1(b) Perdas  [Sangue total][Outros motivos]',
 '6.1(b) Perdas  [Sangue total][Rompimento de Bolsa]',
 '6.1(b) Perdas  [Sangue total][Validade]',
 '6.1(c) Tranfusões  [Concentrado de Hemácias sem buffy coat][Ambulatorial]',
 '6.1(c) Tranfusões  [Concentrado de Hemácias sem buffy coat][Hospitalar]',
 '6.1(c) Tranfusões  [Concentrado de Hemácias sem buffy coat][Total]',
 '6.1(c) Tranfusões  [Concentrado de Hemácias][Ambulatorial]',
 '6.1(c) Tranfusões  [Concentrado de Hemácias][Hospitalar]',
 '6.1(c) Tranfusões  [Concentrado de Hemácias][Total]',
 '6.1(c) Tranfusões  [Concentrado de Leucócitos][Ambulatorial]',
 '6.1(c) Tranfusões  [Concentrado de Leucócitos][Hospitalar]',
 '6.1(c) Tranfusões  [Concentrado de Leucócitos][Total]',
 '6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Ambulatorial]',
 '6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Hospitalar]',
 '6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Total]',
 '6.1(c) Tranfusões  [Concentrado de Plaquetas sem buffy coat][Ambulatorial]',
 '6.1(c) Tranfusões  [Concentrado de Plaquetas sem buffy coat][Hospitalar]',
 '6.1(c) Tranfusões  [Concentrado de Plaquetas sem buffy coat][Total]',
 '6.1(c) Tranfusões  [Concentrado de Plaquetas][Ambulatorial]',
 '6.1(c) Tranfusões  [Concentrado de Plaquetas][Hospitalar]',
 '6.1(c) Tranfusões  [Concentrado de Plaquetas][Total]',
 '6.1(c) Tranfusões  [Crioprecipitado][Ambulatorial]',
 '6.1(c) Tranfusões  [Crioprecipitado][Hospitalar]',
 '6.1(c) Tranfusões  [Crioprecipitado][Total]',
 '6.1(c) Tranfusões  [Plasma Fresco Congelado][Ambulatorial]',
 '6.1(c) Tranfusões  [Plasma Fresco Congelado][Hospitalar]',
 '6.1(c) Tranfusões  [Plasma Fresco Congelado][Total]',
 '6.1(c) Tranfusões  [Plasma comum][Ambulatorial]',
 '6.1(c) Tranfusões  [Plasma comum][Hospitalar]',
 '6.1(c) Tranfusões  [Plasma comum][Total]',
 '6.1(c) Tranfusões  [Sangue total][Ambulatorial]',
 '6.1(c) Tranfusões  [Sangue total][Hospitalar]',
 '6.1(c) Tranfusões  [Sangue total][Total]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias sem buffy coat][Com exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias sem buffy coat][Sem exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias sem buffy coat][Total]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias][Com exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias][Sem exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias][Total]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Leucócitos][Com exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Leucócitos][Sem exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Leucócitos][Total]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas de Aférese][Com exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas de Aférese][Sem exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas de Aférese][Total]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas sem buffy coat][Com exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas sem buffy coat][Sem exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas sem buffy coat][Total]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas][Com exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas][Sem exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas][Total]',
 '6.1(d) Distribuição para outros serviços     [Crioprecipitado][Com exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Crioprecipitado][Sem exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Crioprecipitado][Total]',
 '6.1(d) Distribuição para outros serviços     [Plasma Fresco Congelado][Com exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Plasma Fresco Congelado][Sem exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Plasma Fresco Congelado][Total]',
 '6.1(d) Distribuição para outros serviços     [Plasma comum][Com exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Plasma comum][Sem exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Plasma comum][Total]',
 '6.1(d) Distribuição para outros serviços     [Sangue total][Com exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Sangue total][Sem exame pré-transfusional ]',
 '6.1(d) Distribuição para outros serviços     [Sangue total][Total]',
 '6.2 Procedimentos de modificação dos hemocomponentes [6.2.1 Lavagem]',
 '6.2 Procedimentos de modificação dos hemocomponentes [6.2.2 Irradiação]',
 '6.2 Procedimentos de modificação dos hemocomponentes [6.2.3(a) Filtração em Concentrado de Plaquetas]',
 '6.2 Procedimentos de modificação dos hemocomponentes [6.2.3(b) Filtração em Concentrado de Hemácias]',
 '6.2 Procedimentos de modificação dos hemocomponentes [6.2.4 Fracionamento pediátrico]',
 '7 Reações Transfusionais [Alterações Metabólicas]',
 '7 Reações Transfusionais [Choque Bacteriano]',
 '7 Reações Transfusionais [Outras reações ]',
 '7 Reações Transfusionais [Reação Alérgica]',
 '7 Reações Transfusionais [Reação Febril não Hemolítica]',
 '7 Reações Transfusionais [Reação Hemolítica]',
 '7 Reações Transfusionais [Sobrecarga Volêmica]',
 '8. Envio de Plasma para produção de hemoderivados [Plasma Comum]',
 '8. Envio de Plasma para produção de hemoderivados [Plasma Fresco Congelado]',
 'Ano de referência',
 'CNES - Cadastro Nacional de Estabelecimentos de Saúde',
 'CNPJ',
 'Cite os estabelecimentos que compõem a rede  Informe o Tipo de Estabelecimento, o Nome Fantasia e o Município de localização de cada um.',
 'Código de acesso',
 'Data da última ação',
 'Data de envio',
 'Data de início',
 'Endereço',
 'Endereço IP',
 'HEMOPROD_1 - Observações',
 'HEMOPROD_2 - Observações',
 'HEMOPROD_3 - Observações',
 'ID da resposta',
 'IDENTIFICAÇÃO DO DADO',
 'IDENTIFICAÇÃO DO ESTABELECIMENTO',
 'Idioma inicial',
 'Município',
 'Natureza do estabelecimento',
 'Os dados informados referem-se à um(a):',
 'Período de referência',
 'Razão Social - Nome Fantasia',
 'Razão Social - Nome Fantasia  [Outros]',
 'Semente',

In [57]:
hemoprod_es.head()

,ID da resposta,Data de envio,Última página,Idioma inicial,Semente,Código de acesso,Data de início,Data da última ação,Endereço IP,IDENTIFICAÇÃO DO DADO,"Tipo de Informação Antes de responder ao formulário, declare o tipo de informação que será inserida.",Ano de referência,Período de referência,IDENTIFICAÇÃO DO ESTABELECIMENTO,Município,Razão Social - Nome Fantasia,Razão Social - Nome Fantasia [Outros],CNPJ,Tipo de estabelecimento,Natureza do estabelecimento,Os dados informados referem-se à um(a):,"Cite os estabelecimentos que compõem a rede Informe o Tipo de Estabelecimento, o Nome Fantasia e o Município de localização de cada um.",CNES - Cadastro Nacional de Estabelecimentos de Saúde,Endereço,2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Espontânea][Aptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Espontânea][Inaptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Reposição][Aptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Reposição][Inaptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Autóloga][Aptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Autóloga][Inaptos],2.2 Total de candidatos quanto ao tipo de doador [Primeira vez][Aptos],2.2 Total de candidatos quanto ao tipo de doador [Primeira vez][Inaptos],2.2 Total de candidatos quanto ao tipo de doador [Repetição][Aptos],2.2 Total de candidatos quanto ao tipo de doador [Repetição][Inaptos],2.2 Total de candidatos quanto ao tipo de doador [Esporádico][Aptos],2.2 Total de candidatos quanto ao tipo de doador [Esporádico][Inaptos],2.3 Total de candidatos quanto ao gênero do doador [Masculino][Aptos],2.3 Total de candidatos quanto ao gênero do doador [Masculino][Inaptos],2.3 Total de candidatos quanto ao gênero do doador [Feminino][Aptos],2.3 Total de candidatos quanto ao gênero do doador [Feminino][Inaptos],2.4 Total de candidatos quanto a idade do doador [Menor de 18 anos][Aptos],2.4 Total de candidatos quanto a idade do doador [Menor de 18 anos][Inaptos],2.4 Total de candidatos quanto a idade do doador [18 até 29 anos][Aptos],2.4 Total de candidatos quanto a idade do doador [18 até 29 anos][Inaptos],2.4 Total de candidatos quanto a idade do doador [Acima de 29 anos][Aptos],2.4 Total de candidatos quanto a idade do doador [Acima de 29 anos][Inaptos],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Anemia][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Anemia][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Anemia][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipertensão][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipertensão][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipertensão][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipotensão][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipotensão][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipotensão][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Alcoolismo][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Alcoolismo][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Alcoolismo][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Comportamento de risco para DST][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Comportamento de risco para DST][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Comportamento de risco para DST][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Uso de drogas][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Uso de drogas][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Uso de drogas][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hepatite][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hepatite][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hepatite][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Doença de Chagas][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Doença de Chagas][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Doença de Chagas][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Malária][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Malária][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Malária][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Outras][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Outras][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Outras][Total],3. Coleta 3.1 Total de candidatos desistentes,3.2 Total de interrupções na coleta por [Dificuldade de punção venosa],3.2 Total de interrupções na coleta por [Reação vagal],3.2 Total de interrupções na coleta por [Outros motivos],3.3 Total de coletas [Sangue total],3.3 Total de coletas [Por aférese],HEMOPROD_1 - Observações,4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Doença de Chagas][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Doença de Chagas][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Sífilis ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Sífilis ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - HBs Ag ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - HBs Ag ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - Anti HBc ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - Anti HBc ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite C][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite C][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HTLV I e II ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HTLV I e II ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Malária][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Malária][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HBV (Teste NAT)*][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HBV (Teste NAT)*][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HCV (Teste NAT)*][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HCV (Teste NAT)*][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV (Teste NAT)*][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV (Teste NAT)*][Amostras reagentes],4.2 Imunohematologia [A+][Doador],4.2 Imunohematologia [A+][Receptor],4.2 Imunohematologia [B+][Doador],4.2 Imunohematologia [B+][Receptor],4.2 Imunohematologia [AB+][Doador],4.2 Imunohematologia [AB+][Receptor],4.2 Imunohematologia [O+][Doador],4.2 Imunohematologia [O+][Receptor],4.2 Imunohematologia [A-][Doador],4.2 Imunohematologia [A-][Receptor],4.2 Imunohematologia [B-][Doador],4.2 Imunohematologia [B-][Receptor],4.2 Imunohematologia [AB-][Doador],4.2 Imunohematologia [AB-][Receptor],4.2 Imunohematologia [O-][Doador],4.2 Imunohematologia [O-][Receptor],4.2 Imunohematologia [Dfraco][Doador],4.2 Imunohematologia [Dfraco][Receptor],4.2 Imunohematologia [Pesquisa de anticorpo irregular positivo][Doador],4.2 Imunohematologia [Pesquisa de anticorpo irregular positivo][Receptor],4.2 Imunohematologia [Fenotipagem][Doador],4.2 Imunohematologia [Fenotipagem][Receptor],4.2 Imunohematologia [Combs Direto][Doador],4.2 Imunohematologia [Combs Direto][Receptor],4.3 Outros tipos de pesquisa [Pesquisa de HbS no doador],4.4 Inaptidão na triagem laboratorial [Total de bolsas testadas],4.4 Inaptidão na triagem laboratorial [Total de bolsas reagentes para 1 ou mais marcadores],5. Descarte de Bolsas 5.1 Descarte de bolsas [Total de bolsas descartadas por auto-exclusão],HEMOPROD_2 - Observações,6. Produção Hemoterápica 6.1(a) Entradas [Sangue total][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Sangue total][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Sangue total][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma Fresco Congelado][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma Fresco Congelado][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma Fresco Congelado][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma comum][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma comum][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma comum][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias sem buffy coat][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias sem buffy coat][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias sem buffy coat][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas de Aférese][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas de Aférese][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas de Aférese][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Leucócitos][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Leucócitos][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Leucócitos][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Crioprecipitado][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Crioprecipitado][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Crioprecipitado][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas sem buffy coat][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas sem buffy coat][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas sem buffy coat][Devolvidas],6.1(b) Perdas [Sangue total][Rompimento de Bolsa],6.1(b) Perdas [Sangue total][Validade],6.1(b) Perdas [Sangue total][Outros motivos],6.1(b) Perdas [Plasma Fresco Congelado][Rompimento de Bolsa],6.1(b) Perdas [Plasma Fresco Congelado][Validade],6.1(b) Perdas [Plasma Fresco Congelado][Outros motivos],6.1(b) Perdas [Plasma comum][Rompimento de Bolsa],6.1(b) Perdas [Plasma comum][Validade],6.1(b) Perdas [Plasma comum][Outros motivos],6.1(b) Perdas [Concentrado de Hemácias][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Hemácias][Validade],6.1(b) Perdas [Concentrado de Hemácias][Outros motivos],6.1(b) Perdas [Concentrado de Hemácias sem buffy coat][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Hemácias sem buffy coat][Validade],6.1(b) Perdas [Concentrado de Hemácias sem buffy coat][Outros motivos],6.1(b) Perdas [Concentrado de Plaquetas][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Plaquetas][Validade],6.1(b) Perdas [Concentrado de Plaquetas][Outros motivos],6.1(b) Perdas [Concentrado de Plaquetas de Aférese][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Plaquetas de Aférese][Validade],6.1(b) Perdas [Concentrado de Plaquetas de Aférese][Outros motivos],6.1(b) Perdas [Concentrado de Leucócitos][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Leucócitos][Validade],6.1(b) Perdas [Concentrado de Leucócitos][Outros motivos],6.1(b) Perdas [Crioprecipitado][Rompimento de Bolsa],6.1(b) Perdas [Crioprecipitado][Validade],6.1(b) Perdas [Crioprecipitado][Outros motivos],6.1(b) Perdas [Concentrado de Plaquetas sem buffy coat][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Plaquetas sem buffy coat][Validade],6.1(b) Perdas [Concentrado de Plaquetas sem buffy coat][Outros motivos],6.1(c) Tranfusões [Sangue total][Ambulatorial],6.1(c) Tranfusões [Sangue total][Hospitalar],6.1(c) Tranfusões [Sangue total][Total],6.1(c) Tranfusões [Plasma Fresco Congelado][Ambulatorial],6.1(c) Tranfusões [Plasma Fresco Congelado][Hospitalar],6.1(c) Tranfusões [Plasma Fresco Congelado][Total],6.1(c) Tranfusões [Plasma comum][Ambulatorial],6.1(c) Tranfusões [Plasma comum][Hospitalar],6.1(c) Tranfusões [Plasma comum][Total],6.1(c) Tranfusões [Concentrado de Hemácias][Ambulatorial],6.1(c) Tranfusões [Concentrado de Hemácias][Hospitalar],6.1(c) Tranfusões [Concentrado de Hemácias][Total],6.1(c) Tranfusões [Concentrado de Hemácias sem buffy coat][Ambulatorial],6.1(c) Tranfusões [Concentrado de Hemácias sem buffy coat][Hospitalar],6.1(c) Tranfusões [Concentrado de Hemácias sem buffy coat][Total],6.1(c) Tranfusões [Concentrado de Plaquetas][Ambulatorial],6.1(c) Tranfusões [Concentrado de Plaquetas][Hospitalar],6.1(c) Tranfusões [Concentrado de Plaquetas][Total],6.1(c) Tranfusões [Concentrado de Plaquetas de Aférese][Ambulatorial],6.1(c) Tranfusões [Concentrado de Plaquetas de Aférese][Hospitalar],6.1(c) Tranfusões [Concentrado de Plaquetas de Aférese][Total],6.1(c) Tranfusões [Concentrado de Leucócitos][Ambulatorial],6.1(c) Tranfusões [Concentrado de Leucócitos][Hospitalar],6.1(c) Tranfusões [Concentrado de Leucócitos][Total],6.1(c) Tranfusões [Crioprecipitado][Ambulatorial],6.1(c) Tranfusões [Crioprecipitado][Hospitalar],6.1(c) Tranfusões [Crioprecipitado][Total],6.1(c) Tranfusões [Concentrado de Plaquetas sem buffy coat][Ambulatorial],6.1(c) Tranfusões [Concentrado de Plaquetas sem buffy coat][Hospitalar],6.1(c) Tranfusões [Concentrado de Plaquetas sem buffy coat][Total],6.1(d) Distribuição para outros serviços [Sangue total][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Sangue total][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Sangue total][Total],6.1(d) Distribuição para outros serviços [Plasma Fresco Congelado][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma Fresco Congelado][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma Fresco Congelado][Total],6.1(d) Distribuição para outros serviços [Plasma comum][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma comum][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma comum][Total],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias][Total],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias sem buffy coat][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias sem buffy coat][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias sem buffy coat][Total],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas][Total],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas de Aférese][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas de Aférese][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas de Aférese][Total],6.1(d) Distribuição para outros serviços [Concentrado de Leucócitos][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Leucócitos][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Leucócitos][Total],6.1(d) Distribuição para outros serviços [Crioprecipitado][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Crioprecipitado][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Crioprecipitado][Total],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas sem buffy coat][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas sem buffy coat][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas sem buffy coat][Total],6.2 Procedimentos de modificação dos hemocomponentes [6.2.1 Lavagem],6.2 Procedimentos de modificação dos hemocomponentes [6.2.2 Irradiação],6.2 Procedimentos de modificação dos hemocomponentes [6.2.3(a) Filtração em Concentrado de Plaquetas],6.2 Procedimentos de modificação dos hemocomponentes [6.2.3(b) Filtração em Concentrado de Hemácias],6.2 Procedimentos de modificação dos hemocomponentes [6.2.4 Fracionamento pediátrico],7 Reações Transfusionais [Reação Febril não Hemolítica],7 Reações Transfusionais [Reação Hemolítica],7 Reações Transfusionais [Reação Alérgica],7 Reações Transfusionais [Choque Bacteriano],7 Reações Transfusionais [Alterações Metabólicas],7 Reações Transfusionais [Sobrecarga Volêmica],7 Reações Transfusionais [Outras reações ],8. Envio de Plasma para produção de hemoderivados [Plasma Fresco Congelado],8. Envio de Plasma para produção de hemoderivados [Plasma Comum],HEMOPROD_3 - Observações
0,15,2022-11-28 11:00:00,4,pt-BR,NaN,vxvDL62C5ez3TbL,2022-11-28 10:49:00,2022-11-28 11:00:00,10.0.11.157,NaN,ORIGINAL,2022,Outubro,NaN,"Serra, Espírito Santo",Hemomed Medicina Transfusional Ltda - Hospital...,NaN,5.674518e+12,Agência Transfusional,Público,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,107.0,0.0,41.0,0.0,9.0,0.0,178.0,0.0,6.0,0.0,1.0,0.0,3.0,0.0,27.0,0.0,10.0,0.0,4.0,0.0,140.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,68.0,0.0,0.0,0.0,0.0,0.0,244.0,182.0,0.0,0.0,0.0,0.0,76.0,1.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0,0.0,0.0,0.0,0.0,2.0,73.0,0.0,0.0,0.0,0.0,18.0,31.0,0,0,0,0.0,0.0,0.0,0.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74.0,74.0,0.0,0.0,0.0,0.0,273.0,273.0,0.0,0.0,0.0,0.0,45.0,45.0,0,0,0,0.0,0.0,0.0,0.0,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,7.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,13.0,16.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN

In [19]:
hemoprod_es.head()

,ID da resposta,Data de envio,Última página,Idioma inicial,Semente,Código de acesso,Data de início,Data da última ação,Endereço IP,IDENTIFICAÇÃO DO DADO,"Tipo de Informação Antes de responder ao formulário, declare o tipo de informação que será inserida.",Ano de referência,Período de referência,IDENTIFICAÇÃO DO ESTABELECIMENTO,Município,Razão Social - Nome Fantasia,Razão Social - Nome Fantasia [Outros],CNPJ,Tipo de estabelecimento,Natureza do estabelecimento,Os dados informados referem-se à um(a):,"Cite os estabelecimentos que compõem a rede Informe o Tipo de Estabelecimento, o Nome Fantasia e o Município de localização de cada um.",CNES - Cadastro Nacional de Estabelecimentos de Saúde,Endereço,2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Espontânea][Aptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Espontânea][Inaptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Reposição][Aptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Reposição][Inaptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Autóloga][Aptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Autóloga][Inaptos],2.2 Total de candidatos quanto ao tipo de doador [Primeira vez][Aptos],2.2 Total de candidatos quanto ao tipo de doador [Primeira vez][Inaptos],2.2 Total de candidatos quanto ao tipo de doador [Repetição][Aptos],2.2 Total de candidatos quanto ao tipo de doador [Repetição][Inaptos],2.2 Total de candidatos quanto ao tipo de doador [Esporádico][Aptos],2.2 Total de candidatos quanto ao tipo de doador [Esporádico][Inaptos],2.3 Total de candidatos quanto ao gênero do doador [Masculino][Aptos],2.3 Total de candidatos quanto ao gênero do doador [Masculino][Inaptos],2.3 Total de candidatos quanto ao gênero do doador [Feminino][Aptos],2.3 Total de candidatos quanto ao gênero do doador [Feminino][Inaptos],2.4 Total de candidatos quanto a idade do doador [Menor de 18 anos][Aptos],2.4 Total de candidatos quanto a idade do doador [Menor de 18 anos][Inaptos],2.4 Total de candidatos quanto a idade do doador [18 até 29 anos][Aptos],2.4 Total de candidatos quanto a idade do doador [18 até 29 anos][Inaptos],2.4 Total de candidatos quanto a idade do doador [Acima de 29 anos][Aptos],2.4 Total de candidatos quanto a idade do doador [Acima de 29 anos][Inaptos],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Anemia][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Anemia][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Anemia][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipertensão][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipertensão][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipertensão][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipotensão][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipotensão][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipotensão][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Alcoolismo][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Alcoolismo][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Alcoolismo][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Comportamento de risco para DST][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Comportamento de risco para DST][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Comportamento de risco para DST][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Uso de drogas][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Uso de drogas][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Uso de drogas][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hepatite][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hepatite][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hepatite][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Doença de Chagas][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Doença de Chagas][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Doença de Chagas][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Malária][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Malária][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Malária][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Outras][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Outras][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Outras][Total],3. Coleta 3.1 Total de candidatos desistentes,3.2 Total de interrupções na coleta por [Dificuldade de punção venosa],3.2 Total de interrupções na coleta por [Reação vagal],3.2 Total de interrupções na coleta por [Outros motivos],3.3 Total de coletas [Sangue total],3.3 Total de coletas [Por aférese],HEMOPROD_1 - Observações,4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Doença de Chagas][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Doença de Chagas][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Sífilis ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Sífilis ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - HBs Ag ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - HBs Ag ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - Anti HBc ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - Anti HBc ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite C][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite C][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HTLV I e II ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HTLV I e II ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Malária][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Malária][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HBV (Teste NAT)*][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HBV (Teste NAT)*][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HCV (Teste NAT)*][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HCV (Teste NAT)*][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV (Teste NAT)*][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV (Teste NAT)*][Amostras reagentes],4.2 Imunohematologia [A+][Doador],4.2 Imunohematologia [A+][Receptor],4.2 Imunohematologia [B+][Doador],4.2 Imunohematologia [B+][Receptor],4.2 Imunohematologia [AB+][Doador],4.2 Imunohematologia [AB+][Receptor],4.2 Imunohematologia [O+][Doador],4.2 Imunohematologia [O+][Receptor],4.2 Imunohematologia [A-][Doador],4.2 Imunohematologia [A-][Receptor],4.2 Imunohematologia [B-][Doador],4.2 Imunohematologia [B-][Receptor],4.2 Imunohematologia [AB-][Doador],4.2 Imunohematologia [AB-][Receptor],4.2 Imunohematologia [O-][Doador],4.2 Imunohematologia [O-][Receptor],4.2 Imunohematologia [Dfraco][Doador],4.2 Imunohematologia [Dfraco][Receptor],4.2 Imunohematologia [Pesquisa de anticorpo irregular positivo][Doador],4.2 Imunohematologia [Pesquisa de anticorpo irregular positivo][Receptor],4.2 Imunohematologia [Fenotipagem][Doador],4.2 Imunohematologia [Fenotipagem][Receptor],4.2 Imunohematologia [Combs Direto][Doador],4.2 Imunohematologia [Combs Direto][Receptor],4.3 Outros tipos de pesquisa [Pesquisa de HbS no doador],4.4 Inaptidão na triagem laboratorial [Total de bolsas testadas],4.4 Inaptidão na triagem laboratorial [Total de bolsas reagentes para 1 ou mais marcadores],5. Descarte de Bolsas 5.1 Descarte de bolsas [Total de bolsas descartadas por auto-exclusão],HEMOPROD_2 - Observações,6. Produção Hemoterápica 6.1(a) Entradas [Sangue total][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Sangue total][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Sangue total][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma Fresco Congelado][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma Fresco Congelado][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma Fresco Congelado][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma comum][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma comum][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma comum][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias sem buffy coat][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias sem buffy coat][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias sem buffy coat][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas de Aférese][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas de Aférese][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas de Aférese][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Leucócitos][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Leucócitos][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Leucócitos][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Crioprecipitado][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Crioprecipitado][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Crioprecipitado][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas sem buffy coat][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas sem buffy coat][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas sem buffy coat][Devolvidas],6.1(b) Perdas [Sangue total][Rompimento de Bolsa],6.1(b) Perdas [Sangue total][Validade],6.1(b) Perdas [Sangue total][Outros motivos],6.1(b) Perdas [Plasma Fresco Congelado][Rompimento de Bolsa],6.1(b) Perdas [Plasma Fresco Congelado][Validade],6.1(b) Perdas [Plasma Fresco Congelado][Outros motivos],6.1(b) Perdas [Plasma comum][Rompimento de Bolsa],6.1(b) Perdas [Plasma comum][Validade],6.1(b) Perdas [Plasma comum][Outros motivos],6.1(b) Perdas [Concentrado de Hemácias][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Hemácias][Validade],6.1(b) Perdas [Concentrado de Hemácias][Outros motivos],6.1(b) Perdas [Concentrado de Hemácias sem buffy coat][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Hemácias sem buffy coat][Validade],6.1(b) Perdas [Concentrado de Hemácias sem buffy coat][Outros motivos],6.1(b) Perdas [Concentrado de Plaquetas][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Plaquetas][Validade],6.1(b) Perdas [Concentrado de Plaquetas][Outros motivos],6.1(b) Perdas [Concentrado de Plaquetas de Aférese][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Plaquetas de Aférese][Validade],6.1(b) Perdas [Concentrado de Plaquetas de Aférese][Outros motivos],6.1(b) Perdas [Concentrado de Leucócitos][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Leucócitos][Validade],6.1(b) Perdas [Concentrado de Leucócitos][Outros motivos],6.1(b) Perdas [Crioprecipitado][Rompimento de Bolsa],6.1(b) Perdas [Crioprecipitado][Validade],6.1(b) Perdas [Crioprecipitado][Outros motivos],6.1(b) Perdas [Concentrado de Plaquetas sem buffy coat][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Plaquetas sem buffy coat][Validade],6.1(b) Perdas [Concentrado de Plaquetas sem buffy coat][Outros motivos],6.1(c) Tranfusões [Sangue total][Ambulatorial],6.1(c) Tranfusões [Sangue total][Hospitalar],6.1(c) Tranfusões [Sangue total][Total],6.1(c) Tranfusões [Plasma Fresco Congelado][Ambulatorial],6.1(c) Tranfusões [Plasma Fresco Congelado][Hospitalar],6.1(c) Tranfusões [Plasma Fresco Congelado][Total],6.1(c) Tranfusões [Plasma comum][Ambulatorial],6.1(c) Tranfusões [Plasma comum][Hospitalar],6.1(c) Tranfusões [Plasma comum][Total],6.1(c) Tranfusões [Concentrado de Hemácias][Ambulatorial],6.1(c) Tranfusões [Concentrado de Hemácias][Hospitalar],6.1(c) Tranfusões [Concentrado de Hemácias][Total],6.1(c) Tranfusões [Concentrado de Hemácias sem buffy coat][Ambulatorial],6.1(c) Tranfusões [Concentrado de Hemácias sem buffy coat][Hospitalar],6.1(c) Tranfusões [Concentrado de Hemácias sem buffy coat][Total],6.1(c) Tranfusões [Concentrado de Plaquetas][Ambulatorial],6.1(c) Tranfusões [Concentrado de Plaquetas][Hospitalar],6.1(c) Tranfusões [Concentrado de Plaquetas][Total],6.1(c) Tranfusões [Concentrado de Plaquetas de Aférese][Ambulatorial],6.1(c) Tranfusões [Concentrado de Plaquetas de Aférese][Hospitalar],6.1(c) Tranfusões [Concentrado de Plaquetas de Aférese][Total],6.1(c) Tranfusões [Concentrado de Leucócitos][Ambulatorial],6.1(c) Tranfusões [Concentrado de Leucócitos][Hospitalar],6.1(c) Tranfusões [Concentrado de Leucócitos][Total],6.1(c) Tranfusões [Crioprecipitado][Ambulatorial],6.1(c) Tranfusões [Crioprecipitado][Hospitalar],6.1(c) Tranfusões [Crioprecipitado][Total],6.1(c) Tranfusões [Concentrado de Plaquetas sem buffy coat][Ambulatorial],6.1(c) Tranfusões [Concentrado de Plaquetas sem buffy coat][Hospitalar],6.1(c) Tranfusões [Concentrado de Plaquetas sem buffy coat][Total],6.1(d) Distribuição para outros serviços [Sangue total][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Sangue total][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Sangue total][Total],6.1(d) Distribuição para outros serviços [Plasma Fresco Congelado][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma Fresco Congelado][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma Fresco Congelado][Total],6.1(d) Distribuição para outros serviços [Plasma comum][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma comum][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma comum][Total],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias][Total],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias sem buffy coat][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias sem buffy coat][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias sem buffy coat][Total],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas][Total],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas de Aférese][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas de Aférese][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas de Aférese][Total],6.1(d) Distribuição para outros serviços [Concentrado de Leucócitos][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Leucócitos][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Leucócitos][Total],6.1(d) Distribuição para outros serviços [Crioprecipitado][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Crioprecipitado][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Crioprecipitado][Total],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas sem buffy coat][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas sem buffy coat][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas sem buffy coat][Total],6.2 Procedimentos de modificação dos hemocomponentes [6.2.1 Lavagem],6.2 Procedimentos de modificação dos hemocomponentes [6.2.2 Irradiação],6.2 Procedimentos de modificação dos hemocomponentes [6.2.3(a) Filtração em Concentrado de Plaquetas],6.2 Procedimentos de modificação dos hemocomponentes [6.2.3(b) Filtração em Concentrado de Hemácias],6.2 Procedimentos de modificação dos hemocomponentes [6.2.4 Fracionamento pediátrico],7 Reações Transfusionais [Reação Febril não Hemolítica],7 Reações Transfusionais [Reação Hemolítica],7 Reações Transfusionais [Reação Alérgica],7 Reações Transfusionais [Choque Bacteriano],7 Reações Transfusionais [Alterações Metabólicas],7 Reações Transfusionais [Sobrecarga Volêmica],7 Reações Transfusionais [Outras reações ],8. Envio de Plasma para produção de hemoderivados [Plasma Fresco Congelado],8. Envio de Plasma para produção de hemoderivados [Plasma Comum],HEMOPROD_3 - Observações,Ano de referencia
0,15,2022-11-28 11:00:00,4,pt-BR,NaN,vxvDL62C5ez3TbL,2022-11-28 10:49:00,2022-11-28 11:00:00,10.0.11.157,NaN,ORIGINAL,0,Outubro,NaN,"Serra, Espírito Santo",Hemomed Medicina Transfusional Ltda - Hospital...,NaN,5.674518e+12,Agência Transfusional,Público,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,107.0,0.0,41.0,0.0,9.0,0.0,178.0,0.0,6.0,0.0,1.0,0.0,3.0,0.0,27.0,0.0,10.0,0.0,4.0,0.0,140.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,68.0,0.0,0.0,0.0,0.0,0.0,244.0,182.0,0.0,0.0,0.0,0.0,76.0,1.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0,0.0,0.0,0.0,0.0,2.0,73.0,0.0,0.0,0.0,0.0,18.0,31.0,0,0,0,0.0,0.0,0.0,0.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74.0,74.0,0.0,0.0,0.0,0.0,273.0,273.0,0.0,0.0,0.0,0.0,45.0,45.0,0,0,0,0.0,0.0,0.0,0.0,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,7.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,13.0,16.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,2022

In [61]:
# Carrega o arquivo de dicionário
dicionario_path_es = ('./dicionario_colunas_269.xlsx')
dicionario = pd.read_excel(dicionario_path_es)
print("Arquivo de dicionário carregado com sucesso.")

# --- 3. Extraia a lista de novos nomes ---
# Pega os valores da coluna 'nome_sql' e converte para uma lista
novos_nomes = dicionario['nome_sql'].tolist()
print(f"Número de novos nomes no dicionário: {len(novos_nomes)}")

# --- 4. Verificação de segurança (MUITO IMPORTANTE) ---
# Garante que o número de colunas é o mesmo antes de renomear
if len(hemoprod_es.columns) == len(novos_nomes):
    print("\nO número de colunas corresponde. Renomeando...")
    
    # --- 5. Substitua os nomes das colunas ---
    # Esta é a linha principal que faz a substituição direta
    hemoprod_es.columns = novos_nomes
    
    print("Colunas renomeadas com sucesso!")
    
    # --- 6. Verifique o resultado ---
    print("\nInformações do DataFrame com as novas colunas:")
    hemoprod_es.info()
    
    print("\nAs 5 primeiras linhas com as novas colunas:")
    display(hemoprod_es.head())

else:
    # Mensagem de erro se o número de colunas for diferente
    print("\n--- ERRO ---")
    print("A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.")
    print(f"Colunas no arquivo de dados: {len(hemoprod_es.columns)}")
    print(f"Nomes no dicionário: {len(novos_nomes)}")

Arquivo de dicionário carregado com sucesso.
Número de novos nomes no dicionário: 269

O número de colunas corresponde. Renomeando...
Colunas renomeadas com sucesso!

Informações do DataFrame com as novas colunas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1827 entries, 0 to 1826
Columns: 269 entries, id to hemoprod_3_observacoes
dtypes: float64(237), int64(16), object(16)
memory usage: 3.7+ MB

As 5 primeiras linhas com as novas colunas:

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,15,2022-11-28 11:00:00,4,pt-BR,NaN,vxvDL62C5ez3TbL,2022-11-28 10:49:00,2022-11-28 11:00:00,10.0.11.157,NaN,ORIGINAL,2022,Outubro,NaN,"Serra, Espírito Santo",Hemomed Medicina Transfusional Ltda - Hospital...,NaN,5.674518e+12,Agência Transfusional,Público,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,107.0,0.0,41.0,0.0,9.0,0.0,178.0,0.0,6.0,0.0,1.0,0.0,3.0,0.0,27.0,0.0,10.0,0.0,4.0,0.0,140.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,68.0,0.0,0.0,0.0,0.0,0.0,244.0,182.0,0.0,0.0,0.0,0.0,76.0,1.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0,0.0,0.0,0.0,0.0,2.0,73.0,0.0,0.0,0.0,0.0,18.0,31.0,0,0,0,0.0,0.0,0.0,0.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74.0,74.0,0.0,0.0,0.0,0.0,273.0,273.0,0.0,0.0,0.0,0.0,45.0,45.0,0,0,0,0.0,0.0,0.0,0.0,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,7.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,13.0,16.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN
1,16,2022-11-28 11:20:00,4,pt-BR,NaN,Sgje9tqyifI28Jl,2022-11-28 10:54:00,2022-11-28 11:20:00,10.0.0.216,NaN,ORIGINAL,2022,Outubro,NaN,"Vitória, Espírito Santo",Pronto Socorro Milena Gottardi,NaN,2.708061e+13,Agência Transfusional,Público,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,41.0,0.0,24.0,0.0,5.0,0.0,80.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,1.0,0.0,9.0,0.0,12.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,149.0,0.0,0.0,0.0,0.0,0.0,206.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,61.0,49.0,110.0,0.0,0.0,0.0,26.0,112.0,138.0,0,0,0,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,3.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,115.0,3.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,17,2022-11-28 11:09:00,4,pt-BR,NaN,vxvDL62C5ez3TbL,2022-11-28 11:04:00,2022-11-28 11:09:00,10.0.0.216,NaN,ORIGINAL,2022,Outubro,NaN,"Serra, Espírito Santo",Hemomed Medicina Transfusional Ltda - Hospital...,NaN,5.674518e+12,Agência Transfusional,Privado,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,5.0,0.0,0.0,0.0,45.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,7.0,0.0,14.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,7.0,2.0,0.0,0.0,0.0,0.0,118.0,46.0,0.0,0.0,0.0,0.0,40.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,8.0,2.0,0.0,0.0,0.0,0.0,7.0,1.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,78.0,78.0,0.0,0.0,0.0,0.0,9.0,9.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
3,20,2022-11-30 13:53:00,4,pt-BR,NaN,z6fJe1OkT46z0Yn,2022-11-30 13:38:00,2022-11-30 13:53:00,10.0.7.253,NaN,ORIGINAL,2022,Outubro,NaN,"Colatina, Espírito Santo",Casa de Saúde Santa Maria,NaN,2.749061e+13,Agência Transfusional,Privado-SUS,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,4.0,2.0,1.0,3.0,1.0,8.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,17.0,17.0,0.0,0.0,0.0,0.0,10.0,10.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,22,2022-12-01 09:57:00,4,pt-BR,NaN,VSR5a1w4grp1UkS,2022-12-01 09:43:00,2022-12-01 09:57:00,10.0.11.127,NaN,ORIGINAL,2022,Novembro,NaN,"Venda Nova do Imigrante, Espírito Santo",Associação Social Filantrópica Hospital Padre ...,NaN,2.744380e+13,Agência Transfusional,Privado-SUS,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,2.0,0.0,0.0,15.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,47.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,11.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

In [62]:
print("--- Nomes das Colunas (um por linha) ---")
for coluna in hemoprod_es.columns:
    print(coluna + ",")

--- Nomes das Colunas (um por linha) ---
id,
data_envio,
ultima_pagina,
idioma_inicial,
semente,
codigo_acesso,
data_inicio,
data_ultima_acao,
ip,
identificacao_dado,
tipo_envio,
ano_referencia,
periodo_referencia,
identificacao_estabelecimento,
municipio,
razao_social_nome_fantasia,
razao_social_nome_fantasia_outros,
cnpj,
tipo_estabelecimento,
natureza_estabelecimento,
dados_informados_referem_se,
rede_estabelecimento,
cnes,
endereco,
triagem_clinica_total_doacao_espontanea_aptos,
triagem_clinica_total_doacao_espontanea_inaptos,
triagem_clinica_total_doacao_reposicao_aptos,
triagem_clinica_total_doacao_reposicao_inaptos,
triagem_clinica_total_doacao_autologa_aptos,
triagem_clinica_total_doacao_autologa_inaptos,
total_doador_primeira_vez_aptos,
total_doador_primeira_vez_inaptos,
total_doador_repeticao_aptos,
total_doador_repeticao_inaptos,
total_doador_esporadico_aptos,
total_doador_esporadico_inaptos,
total_doador_masculino_aptos,
total_doador_masculino_inaptos,
total_doador_feminino_aptos,
total_doador_feminino_inaptos,
total_doador_menor_de_18_anos_aptos,
total_doador_menor_de_18_anos_inaptos,
total_doador_18_ate_29_anos_aptos,
total_doador_18_ate_29_anos_inaptos,
total_doador_acima_de_29_anos_aptos,
total_doador_acima_de_29_anos_inaptos,
total_candidatos_inaptos_anemia_masculino,
total_candidatos_inaptos_anemia_feminino,
total_candidatos_inaptos_anemia_total,
total_candidatos_inaptos_hipertensao_masculino,
total_candidatos_inaptos_hipertensao_feminino,
total_candidatos_inaptos_hipertensao_total,
total_candidatos_inaptos_hipotensao_masculino,
total_candidatos_inaptos_hipotensao_feminino,
total_candidatos_inaptos_hipotensao_total,
total_candidatos_inaptos_alcoolismo_masculino,
total_candidatos_inaptos_alcoolismo_feminino,
total_candidatos_inaptos_alcoolismo_total,
total_candidatos_inaptos_comportamento_risco_dst_masculino,
total_candidatos_inaptos_comportamento_risco_dst_feminino,
total_candidatos_inaptos_comportamento_risco_dst_total,
total_candidatos_inaptos_uso_drogas_masculino,
total_candidatos_inaptos_uso_drogas_feminino,
total_candidatos_inaptos_uso_drogas_total,
total_candidatos_inaptos_hepatite_masculino,
total_candidatos_inaptos_hepatite_feminino,
total_candidatos_inaptos_hepatite_total,
total_candidatos_inaptos_doenca_chagas_masculino,
total_candidatos_inaptos_doenca_chagas_feminino,
total_candidatos_inaptos_doenca_chagas_total,
total_candidatos_inaptos_malaria_masculino,
total_candidatos_inaptos_malaria_feminino,
total_candidatos_inaptos_malaria_total,
total_candidatos_inaptos_outras_masculino,
total_candidatos_inaptos_outras_feminino,
total_candidatos_inaptos_outras_total,
coleta_total_candidatos_desistentes,
total_interrupcoes_coleta_dificuldade_puncao_venosa,
total_interrupcoes_coleta_reacao_vagal,
total_interrupcoes_coleta_outros_motivos,
total_coletas_sangue_total,
total_coletas_aferese,
hemoprod_1_observacoes,
exames_triagem_doenca_doenca_chagas_amostras_testadas,
exames_triagem_doenca_doenca_chagas_amostras_reagentes,
exames_triagem_doenca_hiv_amostras_testadas,
exames_triagem_doenca_hiv_amostras_reagentes,
exames_triagem_doenca_sifilis_amostras_testadas,
`exames_triagem_doenca_sifilis_amostras_reagentes,
exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,
exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,
exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,
exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,
exames_triagem_doenca_hepatite_c_amostras_testadas,
exames_triagem_doenca_hepatite_c_amostras_reagentes,
exames_triagem_doenca_htlv_i_ii_amostras_testadas,
exames_triagem_doenca_htlv_i_ii_amostras_reagentes,
exames_triagem_doenca_malaria_amostras_testadas,
exames_triagem_doenca_malaria_amostras_reagentes,
exames_triagem_doenca_hbv_teste_nat_amostras_testadas,
exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,
exames_triagem_doenca_hcv_teste_nat_amostras_testadas,
exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,
exames_triagem_doenca_hiv_teste_nat_amostras_testadas,
exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,
imunohematologia_a_positivo_doador,
imunohematologia_a_positivo_receptor,
imunohematologia_b_positivo_doador,
imunohematologia_b_positivo_receptor,
imunohematologia_ab_positivo_doador,
imunohematologia_ab_positivo_receptor,
imunohematologia_o_positivo_doador,
imunohematologia_o_positivo_receptor,
imunohematologia_a_negativo_doador,
imunohematologia_a_negativo_receptor,
imunohematologia_b_negativo_doador,
imunohematologia_b_negativo_receptor,
imunohematologia_ab_negativo_doador,
imunohematologia_ab_negativo_receptor,
imunohematologia_o_negativo_doador,
imunohematologia_o_negativo_receptor,
imunohematologia_dfraco_doador,
imunohematologia_dfraco_receptor,
imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,
imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,
imunohematologia_fenotipagem_doador,
imunohematologia_fenotipagem_receptor,
imunohematologia_combs_direto_doador,
imunohematologia_combs_direto_receptor,
outros_tipos_pesquisa_pesquisa_hbs_doador,
inaptidao_triagem_laboratorial_total_bolsas_testadas,
inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,
descarte_bolsas_total_bolsas_descartadas_auto_exclusao,
hemoprod_2_observacoes,
producao_hemoterapica_entradas_sangue_total_produzidas,
producao_hemoterapica_entradas_sangue_total_recebidas,
producao_hemoterapica_entradas_sangue_total_devolvidas,
producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,
producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,
producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,
producao_hemoterapica_entradas_plasma_comum_produzidas,
producao_hemoterapica_entradas_plasma_comum_recebidas,
producao_hemoterapica_entradas_plasma_comum_devolvidas,
producao_hemoterapica_entradas_concentrado_hemacias_produzidas,
producao_hemoterapica_entradas_concentrado_hemacias_recebidas,
producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,
producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,
producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,
producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,
producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,
producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,
producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,
producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,
producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,
producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,
producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,
producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,
producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,
producao_hemoterapica_entradas_crioprecipitado_produzidas,
producao_hemoterapica_entradas_crioprecipitado_recebidas,
producao_hemoterapica_entradas_crioprecipitado_devolvidas,
producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,
producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,
producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,
perdas_sangue_total_rompimento_de_bolsa,
perdas_sangue_total_validade,
perdas_sangue_total_outros_motivos,
perdas_plasma_fresco_congelado_rompimento_de_bolsa,
perdas_plasma_fresco_congelado_validade,
perdas_plasma_fresco_congelado_outros_motivos,
perdas_plasma_comum_rompimento_de_bolsa,
perdas_plasma_comum_validade,
perdas_plasma_comum_outros_motivos,
perdas_concentrado_de_hemacias_rompimento_de_bolsa,
perdas_concentrado_de_hemacias_validade,
perdas_concentrado_de_hemacias_outros_motivos,
perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,
perdas_concentrado_de_hemacias_sem_buffy_coat_validade,
perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,
perdas_concentrado_de_plaquetas_rompimento_de_bolsa,
perdas_concentrado_de_plaquetas_validade,
perdas_concentrado_de_plaquetas_outros_motivos,
perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,
perdas_concentrado_de_plaquetas_de_aferese_validade,
perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,
perdas_concentrado_de_leucocitos_rompimento_de_bolsa,
perdas_concentrado_de_leucocitos_validade,
perdas_concentrado_de_leucocitos_outros_motivos,
perdas_crioprecipitado_rompimento_de_bolsa,
perdas_crioprecipitado_validade,
perdas_crioprecipitado_outros_motivos,
perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,
perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,
perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,
tranfusoes_sangue_total_ambulatorial,
tranfusoes_sangue_total_hospitalar,
tranfusoes_sangue_total_total,
tranfusoes_plasma_fresco_congelado_ambulatorial,
tranfusoes_plasma_fresco_congelado_hospitalar,
tranfusoes_plasma_fresco_congelado_total,
tranfusoes_plasma_comum_ambulatorial,
tranfusoes_plasma_comum_hospitalar,
tranfusoes_plasma_comum_total,
tranfusoes_concentrado_de_hemacias_ambulatorial,
tranfusoes_concentrado_de_hemacias_hospitalar,
tranfusoes_concentrado_de_hemacias_total,
tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,
tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,
tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,
tranfusoes_concentrado_de_plaquetas_ambulatorial,
tranfusoes_concentrado_de_plaquetas_hospitalar,
tranfusoes_concentrado_de_plaquetas_total,
tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,
tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,
tranfusoes_concentrado_de_plaquetas_de_aferese_total,
tranfusoes_concentrado_de_leucocitos_ambulatorial,
tranfusoes_concentrado_de_leucocitos_hospitalar,
tranfusoes_concentrado_de_leucocitos_total,
tranfusoes_crioprecipitado_ambulatorial,
tranfusoes_crioprecipitado_hospitalar,
tranfusoes_crioprecipitado_total,
tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,
tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,
tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,
distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,
distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,
distribuicao_para_outros_servicos_sangue_total_total,
distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,
distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,
distribuicao_para_outros_servicos_plasma_fresco_congelado_total,
distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,
distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,
distribuicao_para_outros_servicos_plasma_comum_total,
distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,
distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,
distribuicao_para_outros_servicos_concentrado_de_hemacias_total,
distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,
distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,
distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,
distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,
distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,
distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,
distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,
distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,
distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,
distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,
distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,
distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,
distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,
distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,
distribuicao_para_outros_servicos_crioprecipitado_total,
distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,
distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,
distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,
procedimentos_de_modificacao_dos_hemocomponentes_lavagem,
procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,
procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,
procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,
procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,
reacoes_transfusionais_reacao_febril_nao_hemolitica,
reacoes_transfusionais_reacao_hemolitica,
reacoes_transfusionais_reacao_alergica,
reacoes_transfusionais_choque_bacteriano,
reacoes_transfusionais_alteracoes_metabolicas,
reacoes_transfusionais_sobrecarga_volemica,
reacoes_transfusionais_outras_reacoes,
envio_plasma_producao_hemoderivados_plasma_fresco_congelado,
envio_plasma_producao_hemoderivados_plasma_comum,
hemoprod_3_observacoes,

In [63]:
import numpy as np
import pandas as pd

# Suponha que esta é a sua lista de colunas que devem ser vazias, e não 0
colunas_para_vazias = [
    'dados_informados_referem_se',
    'rede_estabelecimento',
    
]

# Itera sobre cada coluna na lista
for coluna in colunas_para_vazias:
    # Verifica se a coluna existe no DataFrame antes de tentar fazer a substituição
    if coluna in hemoprod_es.columns:
        # Substitui todos os valores '0' por pd.NA (valor ausente/vazio)
        hemoprod_es[coluna] = hemoprod_es[coluna].replace(0, pd.NA)
        print(f"Coluna '{coluna}' corrigida: 0 substituído por pd.NA.")
    else:
        print(f"Atenção: Coluna '{coluna}' não encontrada no DataFrame.")

print("\nSubstituição concluída.")

Coluna 'dados_informados_referem_se' corrigida: 0 substituído por pd.NA.
Coluna 'rede_estabelecimento' corrigida: 0 substituído por pd.NA.

Substituição concluída.

In [67]:
# Coluna a ser verificada (já limpa e separada)
coluna_mes = 'periodo_referencia'

# O padrão Regex r'.*\d+.*' verifica se a string contém UM OU MAIS dígitos (0-9)
# O .str.contains() retorna True ou False para cada linha
registros_com_numero = hemoprod_es[coluna_mes].astype(str).str.contains(r'\d+', na=False)

# 1. Contar quantos registros têm números
total_com_numero = registros_com_numero.sum()

print(f"Total de registros na coluna '{coluna_mes}' que contêm números: {total_com_numero}")

if total_com_numero > 0:
    print("-" * 50)
    print("Amostra dos registros que contêm números:")
    
    # 2. Exibir os registros com problema (as 5 primeiras ocorrências)
    linhas_problema = hemoprod_es[registros_com_numero]
    print(linhas_problema[[coluna_mes]].head(55))
    
    # Opcional: Se você quiser ver a linha inteira para entender o contexto
    # print(linhas_problema.head())
    
else:
    print("Nenhum registro encontrado com números na coluna de meses. Os dados parecem limpos.")

Total de registros na coluna 'periodo_referencia' que contêm números: 53
--------------------------------------------------
Amostra dos registros que contêm números:
    periodo_referencia
46    Consolidado 2022
55    Consolidado 2022
57    Consolidado 2022
58    Consolidado 2022
61    Consolidado 2022
66    Consolidado 2022
70    Consolidado 2022
72    Consolidado 2022
80    Consolidado 2022
81    Consolidado 2022
91    Consolidado 2022
94    Consolidado 2022
95    Consolidado 2022
98    Consolidado 2022
103   Consolidado 2022
106   Consolidado 2022
107   Consolidado 2022
108   Consolidado 2022
109   Consolidado 2022
110   Consolidado 2022
111   Consolidado 2022
112   Consolidado 2022
115   Consolidado 2022
116   Consolidado 2022
117   Consolidado 2022
118   Consolidado 2022
119   Consolidado 2022
120   Consolidado 2022
121   Consolidado 2022
122   Consolidado 2022
123   Consolidado 2022
126   Consolidado 2022
127   Consolidado 2022
128   Consolidado 2022
129   Consolidado 2022
130   Consolidado 2022
131   Consolidado 2022
133   Consolidado 2022
134   Consolidado 2022
148   Consolidado 2022
154   Consolidado 2022
155   Consolidado 2022
156   Consolidado 2022
160   Consolidado 2022
163   Consolidado 2022
175   Consolidado 2022
195   Consolidado 2022
204   Consolidado 2022
205   Consolidado 2022
223   Consolidado 2022
292   Consolidado 2022
293   Consolidado 2022
300   Consolidado 2022

In [68]:
import pandas as pd
import numpy as np
# Colunas a serem corrigidas
coluna_periodo = 'periodo_referencia'
coluna_ano = 'ano_referencia'

# 1. Identificar as linhas onde o período ainda contém o ano (e assumimos que é um caso de "Consolidado XXXX")
# Regex para encontrar qualquer texto seguido por 4 dígitos (o ano)
filtro_consolidado = hemoprod_es[coluna_periodo].astype(str).str.contains(r'\d{4}', na=False)

if filtro_consolidado.any():
    print(f"Encontrados {filtro_consolidado.sum()} registros que precisam de correção manual.")
    
    # 2. Extrair o Ano (4 dígitos consecutivos)
    # A função extract() é ideal para isso
    ano_extraido = hemoprod_es.loc[filtro_consolidado, coluna_periodo].str.extract(r'(\d{4})', expand=False)
    
    # 3. Preencher a coluna 'Ano de referencia' com o valor extraído
    hemoprod_es.loc[filtro_consolidado, coluna_ano] = ano_extraido
    
    # 4. Limpar a coluna 'Período de referência'
    # Remove os 4 dígitos e qualquer espaço antes ou depois deles, deixando apenas o texto como "Consolidado"
    hemoprod_es.loc[filtro_consolidado, coluna_periodo] = (
        hemoprod_es.loc[filtro_consolidado, coluna_periodo]
                 .str.replace(r'\s*\d{4}', '', regex=True) # Remove o ano e espaços
                 .str.strip() # Remove qualquer espaço residual no início/fim
    )
    
    print("Correção aplicada com sucesso.")
    print("-" * 50)
    print("Amostra dos registros corrigidos:")
    # Mostrar as 5 primeiras linhas que foram corrigidas
    print(hemoprod_es.loc[filtro_consolidado, [coluna_periodo, coluna_ano]].head())

else:
    print("Nenhum caso de período que ainda contenha o ano foi encontrado. O DataFrame está limpo.")

Encontrados 53 registros que precisam de correção manual.
Correção aplicada com sucesso.
--------------------------------------------------
Amostra dos registros corrigidos:
   periodo_referencia ano_referencia
46        Consolidado           2022
55        Consolidado           2022
57        Consolidado           2022
58        Consolidado           2022
61        Consolidado           2022

In [69]:
# --- 2. Defina as colunas para a chave e para ordenação ---
registros_antes = len(hemoprod_es)
print(f"Total de registros ANTES da remoção de duplicatas: {registros_antes}")
    

colunas_chave = [
        'cnpj', 
        'ano_referencia', 
        'periodo_referencia', 
        'razao_social_nome_fantasia'
    ]

coluna_data = 'data_envio'

# --- 3. Verifique se as colunas necessárias existem ---
colunas_necessarias = colunas_chave + [coluna_data]

if not all(col in hemoprod_es.columns for col in colunas_necessarias):
    print("\n--- ERRO ---")
    print("Uma ou mais colunas necessárias para a deduplicação não foram encontradas.")
    colunas_faltantes = [col for col in colunas_necessarias if col not in hemoprod_es.columns]
    print(f"Colunas necessárias: {colunas_necessarias}")
    print(f"Colunas faltantes no DataFrame: {colunas_faltantes}")
else:
    # --- 4. Prepare a coluna de data e ordene os dados ---
    # Converte a coluna 'data_envio' para datetime para garantir a ordenação correta.
    # 'errors='coerce'' transformará datas inválidas em NaT (Not a Time), que são tratadas como nulas.
    hemoprod_es[coluna_data] = pd.to_datetime(hemoprod_es[coluna_data], errors='coerce')

    # Ordena o DataFrame. Os registros com data de envio mais recente ficarão por último.
    print(f"\nOrdenando os dados por '{coluna_data}'...")
    hemoprod_es_ordenado = hemoprod_es.sort_values(by=coluna_data, ascending=True)

    # --- 5. Identifique e separe os registros duplicados e únicos ---
    # Em vez de usar drop_duplicates() diretamente, vamos usar duplicated()
    # para criar uma máscara booleana.
    # 'keep='last'' marca todas as ocorrências de uma chave como True, EXCETO a última (a mais recente).
    print(f"Identificando duplicatas com cese na chave: {colunas_chave}...")
    mascara_duplicatas = hemoprod_es_ordenado.duplicated(subset=colunas_chave, keep='last')

    # O DataFrame de removidos conterá todas as linhas marcadas como True
    hemoprod_removidos = hemoprod_es_ordenado[mascara_duplicatas]
    
    # O DataFrame deduplicado conterá o INVERSO (~) da máscara (linhas marcadas como False)
    hemoprod_es_deduplicado = hemoprod_es_ordenado[~mascara_duplicatas]
    
    # Agora podemos contar os registros diretamente dos novos DataFrames
    registros_depois = len(hemoprod_es_deduplicado)
    registros_removidos = len(hemoprod_removidos) 
    
    # --- 6. Exice o resultado ---
    print("\n--- Processo Concluído ---")
    print(f"Registros removidos: {registros_removidos}")
    print(f"Total de registros DEPOIS da remoção de duplicatas: {registros_depois}")

    # (Opcional) Exibe a amostra dos removidos
    print("\nAmostra dos dados REMOVIDOS (os mais antigos/duplicados):")
    display(hemoprod_removidos.head(10))

    # Você pode continuar a usar o DataFrame 'hemoprod_ce_deduplicado' para suas análises
    print("\nAmostra dos dados únicos (os mais recentes para cada chave):")
    display(hemoprod_es_deduplicado.head(10))
    
    # Agora você tem o DataFrame 'hemoprod_removidos' salvo

Total de registros ANTES da remoção de duplicatas: 1827

Ordenando os dados por 'data_envio'...
Identificando duplicatas com cese na chave: ['cnpj', 'ano_referencia', 'periodo_referencia', 'razao_social_nome_fantasia']...

--- Processo Concluído ---
Registros removidos: 83
Total de registros DEPOIS da remoção de duplicatas: 1744

Amostra dos dados REMOVIDOS (os mais antigos/duplicados):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
23,58,2022-12-13 14:32:00,4,pt-BR,NaN,4LWfMHVP36HzcXG,2022-12-13 13:30:00,2022-12-13 14:32:00,10.0.0.213,NaN,ORIGINAL,2022,Novembro,NaN,"São Mateus, Espírito Santo",Secretaria de Estado da Saúde do Espírito Sant...,NaN,2.708061e+13,Hemocentro Regional,Público,<NA>,<NA>,NaN,NaN,190.0,44.0,93.0,21.0,0.0,0.0,110.0,29.0,104.0,6.0,69.0,7.0,152.0,23.0,131.0,42.0,2.0,0.0,78.0,22.0,203.0,43.0,1.0,8.0,9.0,3.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,5.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,27.0,45.0,0.0,1.0,0.0,0.0,282.0,0.0,NaN,282.0,0.0,282.0,0.0,282.0,0.0,0.0,0.0,282.0,0.0,282.0,0.0,282.0,0.0,0.0,0.0,282.0,0.0,282.0,0.0,282.0,0.0,72.0,0.0,34.0,0.0,4.0,0.0,123.0,0.0,9.0,0.0,3.0,0.0,1.0,0.0,36.0,0.0,49.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,282.0,282.0,0.0,0.0,NaN,282.0,0.0,0.0,55.0,0.0,0.0,218.0,0.0,0.0,273.0,1.0,14.0,0.0,0.0,0.0,122.0,1.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,218.0,0.0,4.0,24.0,0.0,0.0,0.0,0.0,15.0,13.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,0.0,22.0,0.0,0.0,0.0,263.0,0.0,263.0,0.0,0.0,0.0,103.0,0.0,103.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,62.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
29,65,2022-12-14 14:36:00,4,pt-BR,NaN,upC3Y7lQmhhIeqY,2022-12-14 14:21:00,2022-12-14 14:36:00,10.0.0.38,NaN,ORIGINAL,2022,Novembro,NaN,"Vila Velha, Espírito Santo",Hemomed Medicina Transfusional Ltda - Hospital...,NaN,5.674518e+12,Agência Transfusional,Público,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Não obtem resultados para imuno hemato,0.0,0.0,0.0,0.0,50.0,0.0,0.0,0.0,0.0,0.0,236.0,218.0,0.0,0.0,0.0,0.0,262.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,0.0,0.0,68.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,19.0,34.0,0.0,0.0,4.0,49.0,179.0,28.0,0.0,0.0,0.0,15.0,150.0,165.0,0,0,0,0.0,0.0,0.0,7.0,13.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,6.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN
55,104,2023-01-06 14:18:00,4,pt-BR,NaN,upC3Y7lQmhhIeqY,2023-01-06 13:49:00,2023-01-06 14:18:00,10.0.0.38,NaN,ORIGINAL,2022,Consolidado,NaN,"Vila Velha, Espírito Santo",Hemomed Medicina Transfusional Ltda - Hospital...,NaN,5.674518e+12,Agência Transfusional,Privado,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,104.0,0.0,46.0,0.0,13.0,0.0,170.0,0.0,20.0,0.0,1.0,0.0,0.0,0.0,30.0,0.0,26.0,0.0,13.0,0.0,77.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,70.0,0.0,0.0,0.0,0.0,0.0,324.0,236.0,0.0,0.0,0.0,0.0,406.0,15.0,0,0,0,0.0,0.0,0.0,0.0,35.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.0,17.0,63.0,0.0,0.0,0.0,85.0,234.0,319.0,0.0,0.0,0.0,132.0,220.0,352.0,0,0,0,0.0,0.0,0.0,10.0,14.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.0,28.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
74,126,2023-01-10 10:50:00,4,pt-BR,NaN,jIrWf3pgMmwH9DC,2023-01-10 10:25:00,2023-01-10 10:50:00,10.0.0.51,NaN,ORIGINAL,2022,Dezembro,NaN,"Vitória, Espírito Santo",Secretaria de Estado da Saúde do Espírito Sant...,NaN,1.708061e+13,Hemocentro Coordenador,Público,<NA>,<NA>,NaN,NaN,1485.0,535.0,540.0,150.0,0.0,0.0,635.0,220.0,1390.0,465.0,0.0,0.0,1268.0,265.0,757.0,420.0,0.0,0.0,619.0,272.0,1406.0,413.0,0.0,0.0,218.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,116.0,0.0,0.0,4.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,324.0,0.0,37.0,15.0,16.0,1883.0,74.0,NaN,4800.0,0.0,4800.0,1.0,4800.0,55.0,4800.0,3.0,4800.0,64.0,4800.0,1.0,4800.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,994.0,15.0,355.0,0.0,118.0,0.0,1447.0,53.0,159.0,11.0,41.0,0.0,18.0,0.0,317.0,7.0,535.0,18.0,19.0,60.0,541.0,32.0,0.0,48.0,3449.0,4800.0,125.0,16.0,NaN,0.0,0.0,0.0,1932.0,0.0,0.0,0.0,0.0,0.0,2282.0,54.0,3.0,0.0,0.0,0.0,1712.0,0.0,9.0,0,0,0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,0.0,0.0,1683.0,0.0,0.0,0.0,3.0,111.0,190.0,0.0,0.0,0.0,0.0,103.0,468.0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,389.0,0.0,389.0,0.0,0.0,0.0,1891.0,144.0,2035.0,0.0,0.0,0.0,1204.0,4.0,1208.0,0,0,0,0.0,0.0,0.0,51.0,0.0,51.0,0.0,0.0,0.0,0.0,605.0,0.0,1047.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
120,193,2023-01-30 11:48:54,4,pt-BR,1.112983e+09,JOMetCb5zt7woLp,2023-01-30 11:35:10,2023-01-30 11:48:54,10.0.95.255,NaN,ORIGINAL,2022,Consolidado,NaN,"Guaçuí, Espírito Santo",Santa Casa de Misericordia de Guaçuí,NaN,2.768618e+13,Agência Transfusional,Privado-SUS,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,18.0,13.0,12.0,1.0,1.0,24.0,33.0,0.0,0.0,2.0,1.0,2.0,1.0,12.0,6.0,0.0,8.0,0.0,72.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Nos doadores coloquei as bolsas de CH que rece...,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,77.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,11.0,55.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

Amostra dos dados únicos (os mais recentes para cada chave):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,15,2022-11-28 11:00:00,4,pt-BR,NaN,vxvDL62C5ez3TbL,2022-11-28 10:49:00,2022-11-28 11:00:00,10.0.11.157,NaN,ORIGINAL,2022,Outubro,NaN,"Serra, Espírito Santo",Hemomed Medicina Transfusional Ltda - Hospital...,NaN,5.674518e+12,Agência Transfusional,Público,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,107.0,0.0,41.0,0.0,9.0,0.0,178.0,0.0,6.0,0.0,1.0,0.0,3.0,0.0,27.0,0.0,10.0,0.0,4.0,0.0,140.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,68.0,0.0,0.0,0.0,0.0,0.0,244.0,182.0,0.0,0.0,0.0,0.0,76.0,1.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0,0.0,0.0,0.0,0.0,2.0,73.0,0.0,0.0,0.0,0.0,18.0,31.0,0,0,0,0.0,0.0,0.0,0.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74.0,74.0,0.0,0.0,0.0,0.0,273.0,273.0,0.0,0.0,0.0,0.0,45.0,45.0,0,0,0,0.0,0.0,0.0,0.0,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,7.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,13.0,16.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN
2,17,2022-11-28 11:09:00,4,pt-BR,NaN,vxvDL62C5ez3TbL,2022-11-28 11:04:00,2022-11-28 11:09:00,10.0.0.216,NaN,ORIGINAL,2022,Outubro,NaN,"Serra, Espírito Santo",Hemomed Medicina Transfusional Ltda - Hospital...,NaN,5.674518e+12,Agência Transfusional,Privado,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,5.0,0.0,0.0,0.0,45.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,7.0,0.0,14.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,7.0,2.0,0.0,0.0,0.0,0.0,118.0,46.0,0.0,0.0,0.0,0.0,40.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,8.0,2.0,0.0,0.0,0.0,0.0,7.0,1.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,78.0,78.0,0.0,0.0,0.0,0.0,9.0,9.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,16,2022-11-28 11:20:00,4,pt-BR,NaN,Sgje9tqyifI28Jl,2022-11-28 10:54:00,2022-11-28 11:20:00,10.0.0.216,NaN,ORIGINAL,2022,Outubro,NaN,"Vitória, Espírito Santo",Pronto Socorro Milena Gottardi,NaN,2.708061e+13,Agência Transfusional,Público,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,41.0,0.0,24.0,0.0,5.0,0.0,80.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,1.0,0.0,9.0,0.0,12.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,149.0,0.0,0.0,0.0,0.0,0.0,206.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,61.0,49.0,110.0,0.0,0.0,0.0,26.0,112.0,138.0,0,0,0,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,3.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,115.0,3.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
3,20,2022-11-30 13:53:00,4,pt-BR,NaN,z6fJe1OkT46z0Yn,2022-11-30 13:38:00,2022-11-30 13:53:00,10.0.7.253,NaN,ORIGINAL,2022,Outubro,NaN,"Colatina, Espírito Santo",Casa de Saúde Santa Maria,NaN,2.749061e+13,Agência Transfusional,Privado-SUS,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,4.0,2.0,1.0,3.0,1.0,8.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,17.0,17.0,0.0,0.0,0.0,0.0,10.0,10.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,22,2022-12-01 09:57:00,4,pt-BR,NaN,VSR5a1w4grp1UkS,2022-12-01 09:43:00,2022-12-01 09:57:00,10.0.11.127,NaN,ORIGINAL,2022,Novembro,NaN,"Venda Nova do Imigrante, Espírito Santo",Associação Social Filantrópica Hospital Padre ...,NaN,2.744380e+13,Agência Transfusional,Privado-SUS,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,2.0,0.0,0.0,15.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,47.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,11.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

In [70]:
hemoprod_es_deduplicado.to_excel('dados_processados/hemoprod_es.xlsx', index=False)

## Hemoprod Goiás

In [83]:
import os
import pandas as pd

dados_brutos_path = 'dados_brutos'

arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_GO.xlsx')
nome_planilha = 'HEMOPROD - GOIAS'

dicionario_path_go = ('./dicionario_colunas_269.xlsx')
# dicionario_path_ap = ('./dicionario_colunas_270.xlsx')

dicionario_go = pd.read_excel(dicionario_path_go, sheet_name='Sheet1')

# --- 2. Carregue os dados e o dicionário ---
try:
    # Carrega o arquivo de dados
    hemoprod_go = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)
    print("Arquivo de dados carregado com sucesso.")
    print(f"Número de colunas original: {len(hemoprod_go.columns)}")

    # Carrega o arquivo de dicionário
    dicionario = pd.read_excel(dicionario_path_go)
    print("Arquivo de dicionário carregado com sucesso.")

    # --- 3. Extraia a lista de novos nomes ---
    # Pega os valores da coluna 'nome_sql' e converte para uma lista
    novos_nomes = dicionario['nome_sql'].tolist()
    print(f"Número de novos nomes no dicionário: {len(novos_nomes)}")

    # --- 4. Verificação de segurança (MUITO IMPORTANTE) ---
    # Garante que o número de colunas é o mesmo antes de renomear
    if len(hemoprod_go.columns) == len(novos_nomes):
        print("\nO número de colunas corresponde. Renomeando...")
        
        # --- 5. Substitua os nomes das colunas ---
        # Esta é a linha principal que faz a substituição direta
        hemoprod_go.columns = novos_nomes
        
        print("Colunas renomeadas com sucesso!")
        
        # --- 6. Verifique o resultado ---
        print("\nInformações do DataFrame com as novas colunas:")
        hemoprod_go.info()
        
        print("\nAs 5 primeiras linhas com as novas colunas:")
        display(hemoprod_go.head())

    else:
        # Mensagem de erro se o número de colunas for diferente
        print("\n--- ERRO ---")
        print("A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.")
        print(f"Colunas no arquivo de dados: {len(hemoprod_go.columns)}")
        print(f"Nomes no dicionário: {len(novos_nomes)}")

except FileNotFoundError as e:
    print(f"\nErro de arquivo não encontrado: {e}")
except KeyError as e:
    print(f"\nErro de coluna não encontrada: {e}. Verifique se a coluna 'nome_sql' existe no seu arquivo de dicionário.")
except Exception as e:
    print(f"\nOcorreu um erro inesperado: {e}")

Arquivo de dados carregado com sucesso.
Número de colunas original: 257
Arquivo de dicionário carregado com sucesso.
Número de novos nomes no dicionário: 269

--- ERRO ---
A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.
Colunas no arquivo de dados: 257
Nomes no dicionário: 269

In [89]:
arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_CE.xlsx')
nome_planilha = 'Planilha1'
hemoprod_ce1 = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)

colunas_padrao = set(hemoprod_ce1.columns)
colunas_estado = set(hemoprod_go.columns)

colunas_faltantes = list(colunas_padrao - colunas_estado)

colunas_a_mais = list(colunas_estado - colunas_padrao)

print(f"Número de colunas faltantes: {len(colunas_faltantes)}")
print(f"Colunas faltantes (a serem adicionadas): {colunas_faltantes}")
print("-" * 30)
print(f"Número de colunas a mais: {len(colunas_a_mais)}")
print(f"Colunas a mais (a serem dropadas): {colunas_a_mais}")

Número de colunas faltantes: 0
Colunas faltantes (a serem adicionadas): []
------------------------------
Número de colunas a mais: 0
Colunas a mais (a serem dropadas): []

In [88]:
import os
import pandas as pd
import numpy as np # Adicionado para usar pd.NA

# --- Assumindo que você já carregou os DataFrames e calculou as listas ---
# hemoprod_ce1 (DataFrame Padrão)
# hemoprod_es (DataFrame do Estado)
# colunas_padrao, colunas_estado, colunas_faltantes, colunas_a_mais

# Nomes das colunas problemáticas
COLUNA_ERRADA = 'Ano de referência '  # A coluna que está 'a mais'
COLUNA_CORRETA = 'Ano de referência\xa0 ' # A coluna que está 'faltando'

# 1. TRATAMENTO DA COLUNA 'ANO DE REFERÊNCIA': RENOMEAR EM VEZ DE DROPAR/ADICIONAR

# if COLUNA_ERRADA in colunas_a_mais and COLUNA_CORRETA in colunas_faltantes:
#     # 1.1. Renomear a coluna no DataFrame do estado (preservando os dados)
#     hemoprod_go = hemoprod_go.rename(columns={COLUNA_ERRADA: COLUNA_CORRETA})
    
#     print(f"COLUNA RENOMEADA: '{COLUNA_ERRADA.strip()}' -> '{COLUNA_CORRETA.strip()}'")
    
#     # 1.2. Remover as colunas tratadas das listas de faltantes e a mais
#     colunas_a_mais.remove(COLUNA_ERRADA)
#     colunas_faltantes.remove(COLUNA_CORRETA)
    
#     print("A coluna de Ano de Referência foi removida das listas de ajuste.")
# else:
#     # Caso os nomes não correspondam ou a coluna não esteja nas listas (improvável, mas seguro)
#     print("A coluna de Ano de Referência não foi tratada por renomeação. Prosseguindo com drop/adição.")


# # 2. CONTINUAR com as colunas restantes: DROP e ADIÇÃO

print("\n--- INICIANDO DROP E ADIÇÃO ---")

# 2.1. DROP das colunas A MAIS restantes
if colunas_a_mais:
    # Observe que COLUNA_ERRADA não está mais aqui
    hemoprod_go = hemoprod_go.drop(columns=colunas_a_mais, errors='ignore')
    print(f"Colunas a mais (restantes) removidas: {colunas_a_mais}")
else:
    print("Nenhuma coluna a mais restante para remover.")


# 2.2. ADICIONAR as colunas FALTANTES restantes e preenchê-las com zero (0)
# A coluna COLUNA_CORRETA também não está mais aqui
colunas_de_texto_para_vazias = ['Os dados informados referem-se à um(a):'] # Adicione outras colunas de texto aqui, se houver

for coluna in colunas_faltantes:
    if coluna in colunas_de_texto_para_vazias:
        # Cria a nova coluna preenchida com valor ausente (pd.NA)
        hemoprod_go[coluna] = pd.NA
    else:
        # Cria a nova coluna preenchida com 0
        hemoprod_go[coluna] = 0

print(f"Colunas faltantes (restantes) adicionadas: {colunas_faltantes}")


# 3. REORDENAR as colunas do hemoprod_go na mesma ordem do padrão
ordem_padrao = hemoprod_ce1.columns.tolist()

# Reorganiza as colunas do hemoprod_go
hemoprod_go = hemoprod_go[ordem_padrao]

print("-" * 50)
print("Processo concluído:")
print(f"Total de colunas após o ajuste: {len(hemoprod_go.columns)}")
print("A ordem das colunas agora corresponde à ordem do hemoprod_ce1.")

--- INICIANDO DROP E ADIÇÃO ---
Nenhuma coluna a mais restante para remover.
Colunas faltantes (restantes) adicionadas: ['6. Produção Hemoterápica  6.1(a) Entradas\xa0  [Concentrado de Plaquetas de Aférese][Recebidas]', '6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Outros motivos]', '6. Produção Hemoterápica  6.1(a) Entradas\xa0  [Concentrado de Plaquetas de Aférese][Devolvidas]', '6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Validade]', '6.1(d) Distribuição para outros serviços  \xa0  [Concentrado de Plaquetas de Aférese][Total]', '6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Total]', '6.1(d) Distribuição para outros serviços  \xa0  [Concentrado de Plaquetas de Aférese][Com exame pré-transfusional ]', '6. Produção Hemoterápica  6.1(a) Entradas\xa0  [Concentrado de Plaquetas de Aférese][Produzidas]', '6.1(d) Distribuição para outros serviços  \xa0  [Concentrado de Plaquetas de Aférese][Sem exame pré-transfusional ]', '6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Hospitalar]', '6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Rompimento de Bolsa]', '6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Ambulatorial]']
--------------------------------------------------
Processo concluído:
Total de colunas após o ajuste: 269
A ordem das colunas agora corresponde à ordem do hemoprod_ce1.

In [90]:
# Mapeia as colunas, limpando espaços em branco no início e fim
# e substituindo o caractere \xa0 por um espaço normal.
novos_nomes = {col: col.strip().replace('\xa0', ' ') for col in hemoprod_go.columns}

# Aplica a renomeação
hemoprod_go = hemoprod_go.rename(columns=novos_nomes)

print("Nomes das colunas limpos e padronizados.")

Nomes das colunas limpos e padronizados.

In [91]:
print("--- Nomes das Colunas (um por linha) ---")
for coluna in hemoprod_go.columns:
    print(coluna + ",")

--- Nomes das Colunas (um por linha) ---
ID da resposta,
Data de envio,
Última página,
Idioma inicial,
Semente,
Código de acesso,
Data de início,
Data da última ação,
Endereço IP,
IDENTIFICAÇÃO DO DADO,
Tipo de Informação  Antes de responder ao formulário, declare o tipo de informação que será inserida.,
Ano de referência,
Período de referência,
IDENTIFICAÇÃO DO ESTABELECIMENTO,
Município,
Razão Social - Nome Fantasia,
Razão Social - Nome Fantasia  [Outros],
CNPJ,
Tipo de estabelecimento,
Natureza do estabelecimento,
Os dados informados referem-se à um(a):,
Cite os estabelecimentos que compõem a rede  Informe o Tipo de Estabelecimento, o Nome Fantasia e o Município de localização de cada um.,
CNES - Cadastro Nacional de Estabelecimentos de Saúde,
Endereço,
2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Espontânea][Aptos],
2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Espontânea][Inaptos],
2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Reposição][Aptos],
2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Reposição][Inaptos],
2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Autóloga][Aptos],
2. Triagem Clínica  2.1 Total de candidatos quanto ao tipo de doação  [Autóloga][Inaptos],
2.2 Total de candidatos quanto ao tipo de doador  [Primeira vez][Aptos],
2.2 Total de candidatos quanto ao tipo de doador  [Primeira vez][Inaptos],
2.2 Total de candidatos quanto ao tipo de doador  [Repetição][Aptos],
2.2 Total de candidatos quanto ao tipo de doador  [Repetição][Inaptos],
2.2 Total de candidatos quanto ao tipo de doador  [Esporádico][Aptos],
2.2 Total de candidatos quanto ao tipo de doador  [Esporádico][Inaptos],
2.3 Total de candidatos quanto ao gênero do doador  [Masculino][Aptos],
2.3 Total de candidatos quanto ao gênero do doador  [Masculino][Inaptos],
2.3 Total de candidatos quanto ao gênero do doador  [Feminino][Aptos],
2.3 Total de candidatos quanto ao gênero do doador  [Feminino][Inaptos],
2.4 Total de candidatos quanto a idade do doador  [Menor de 18 anos][Aptos],
2.4 Total de candidatos quanto a idade do doador  [Menor de 18 anos][Inaptos],
2.4 Total de candidatos quanto a idade do doador  [18 até 29 anos][Aptos],
2.4 Total de candidatos quanto a idade do doador  [18 até 29 anos][Inaptos],
2.4 Total de candidatos quanto a idade do doador  [Acima de 29 anos][Aptos],
2.4 Total de candidatos quanto a idade do doador  [Acima de 29 anos][Inaptos],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Anemia][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Anemia][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Anemia][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipertensão][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipertensão][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipertensão][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipotensão][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipotensão][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hipotensão][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Alcoolismo][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Alcoolismo][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Alcoolismo][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Comportamento de risco para DST][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Comportamento de risco para DST][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Comportamento de risco para DST][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Uso de drogas][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Uso de drogas][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Uso de drogas][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hepatite][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hepatite][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Hepatite][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Doença de Chagas][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Doença de Chagas][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Doença de Chagas][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Malária][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Malária][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Malária][Total],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Outras][Masculino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Outras][Feminino],
2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero  [Outras][Total],
3. Coleta  3.1 Total de candidatos desistentes,
3.2 Total de interrupções na coleta por [Dificuldade de punção venosa],
3.2 Total de interrupções na coleta por [Reação vagal],
3.2 Total de interrupções na coleta por [Outros motivos],
3.3 Total de coletas [Sangue total],
3.3 Total de coletas [Por aférese],
HEMOPROD_1 - Observações,
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Doença de Chagas][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Doença de Chagas][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HIV][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HIV][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Sífilis ][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Sífilis ][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite B - HBs Ag ][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite B - HBs Ag ][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite B - Anti HBc ][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite B - Anti HBc ][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite C][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Hepatite C][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HTLV I e II ][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HTLV I e II ][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Malária][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [Malária][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HBV (Teste NAT)*][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HBV (Teste NAT)*][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HCV (Teste NAT)*][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HCV (Teste NAT)*][Amostras reagentes],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HIV (Teste NAT)*][Amostras testadas],
4. Exames Realizados  4.1 Triagem de doenças transmissíveis pelo sangue  [HIV (Teste NAT)*][Amostras reagentes],
4.2 Imunohematologia [A+][Doador],
4.2 Imunohematologia [A+][Receptor],
4.2 Imunohematologia [B+][Doador],
4.2 Imunohematologia [B+][Receptor],
4.2 Imunohematologia [AB+][Doador],
4.2 Imunohematologia [AB+][Receptor],
4.2 Imunohematologia [O+][Doador],
4.2 Imunohematologia [O+][Receptor],
4.2 Imunohematologia [A-][Doador],
4.2 Imunohematologia [A-][Receptor],
4.2 Imunohematologia [B-][Doador],
4.2 Imunohematologia [B-][Receptor],
4.2 Imunohematologia [AB-][Doador],
4.2 Imunohematologia [AB-][Receptor],
4.2 Imunohematologia [O-][Doador],
4.2 Imunohematologia [O-][Receptor],
4.2 Imunohematologia [Dfraco][Doador],
4.2 Imunohematologia [Dfraco][Receptor],
4.2 Imunohematologia [Pesquisa de anticorpo irregular positivo][Doador],
4.2 Imunohematologia [Pesquisa de anticorpo irregular positivo][Receptor],
4.2 Imunohematologia [Fenotipagem][Doador],
4.2 Imunohematologia [Fenotipagem][Receptor],
4.2 Imunohematologia [Combs Direto][Doador],
4.2 Imunohematologia [Combs Direto][Receptor],
4.3 Outros tipos de pesquisa [Pesquisa de HbS no doador],
4.4 Inaptidão na triagem laboratorial [Total de bolsas testadas],
4.4 Inaptidão na triagem laboratorial [Total de bolsas reagentes para 1 ou mais marcadores],
5. Descarte de Bolsas  5.1 Descarte de bolsas  [Total de bolsas descartadas por auto-exclusão],
HEMOPROD_2 - Observações,
6. Produção Hemoterápica  6.1(a) Entradas   [Sangue total][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Sangue total][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Sangue total][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Plasma Fresco Congelado][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Plasma Fresco Congelado][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Plasma Fresco Congelado][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Plasma comum][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Plasma comum][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Plasma comum][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias sem buffy coat][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias sem buffy coat][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Hemácias sem buffy coat][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas de Aférese][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas de Aférese][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas de Aférese][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Leucócitos][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Leucócitos][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Leucócitos][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Crioprecipitado][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Crioprecipitado][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Crioprecipitado][Devolvidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas sem buffy coat][Produzidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas sem buffy coat][Recebidas],
6. Produção Hemoterápica  6.1(a) Entradas   [Concentrado de Plaquetas sem buffy coat][Devolvidas],
6.1(b) Perdas  [Sangue total][Rompimento de Bolsa],
6.1(b) Perdas  [Sangue total][Validade],
6.1(b) Perdas  [Sangue total][Outros motivos],
6.1(b) Perdas  [Plasma Fresco Congelado][Rompimento de Bolsa],
6.1(b) Perdas  [Plasma Fresco Congelado][Validade],
6.1(b) Perdas  [Plasma Fresco Congelado][Outros motivos],
6.1(b) Perdas  [Plasma comum][Rompimento de Bolsa],
6.1(b) Perdas  [Plasma comum][Validade],
6.1(b) Perdas  [Plasma comum][Outros motivos],
6.1(b) Perdas  [Concentrado de Hemácias][Rompimento de Bolsa],
6.1(b) Perdas  [Concentrado de Hemácias][Validade],
6.1(b) Perdas  [Concentrado de Hemácias][Outros motivos],
6.1(b) Perdas  [Concentrado de Hemácias sem buffy coat][Rompimento de Bolsa],
6.1(b) Perdas  [Concentrado de Hemácias sem buffy coat][Validade],
6.1(b) Perdas  [Concentrado de Hemácias sem buffy coat][Outros motivos],
6.1(b) Perdas  [Concentrado de Plaquetas][Rompimento de Bolsa],
6.1(b) Perdas  [Concentrado de Plaquetas][Validade],
6.1(b) Perdas  [Concentrado de Plaquetas][Outros motivos],
6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Rompimento de Bolsa],
6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Validade],
6.1(b) Perdas  [Concentrado de Plaquetas de Aférese][Outros motivos],
6.1(b) Perdas  [Concentrado de Leucócitos][Rompimento de Bolsa],
6.1(b) Perdas  [Concentrado de Leucócitos][Validade],
6.1(b) Perdas  [Concentrado de Leucócitos][Outros motivos],
6.1(b) Perdas  [Crioprecipitado][Rompimento de Bolsa],
6.1(b) Perdas  [Crioprecipitado][Validade],
6.1(b) Perdas  [Crioprecipitado][Outros motivos],
6.1(b) Perdas  [Concentrado de Plaquetas sem buffy coat][Rompimento de Bolsa],
6.1(b) Perdas  [Concentrado de Plaquetas sem buffy coat][Validade],
6.1(b) Perdas  [Concentrado de Plaquetas sem buffy coat][Outros motivos],
6.1(c) Tranfusões  [Sangue total][Ambulatorial],
6.1(c) Tranfusões  [Sangue total][Hospitalar],
6.1(c) Tranfusões  [Sangue total][Total],
6.1(c) Tranfusões  [Plasma Fresco Congelado][Ambulatorial],
6.1(c) Tranfusões  [Plasma Fresco Congelado][Hospitalar],
6.1(c) Tranfusões  [Plasma Fresco Congelado][Total],
6.1(c) Tranfusões  [Plasma comum][Ambulatorial],
6.1(c) Tranfusões  [Plasma comum][Hospitalar],
6.1(c) Tranfusões  [Plasma comum][Total],
6.1(c) Tranfusões  [Concentrado de Hemácias][Ambulatorial],
6.1(c) Tranfusões  [Concentrado de Hemácias][Hospitalar],
6.1(c) Tranfusões  [Concentrado de Hemácias][Total],
6.1(c) Tranfusões  [Concentrado de Hemácias sem buffy coat][Ambulatorial],
6.1(c) Tranfusões  [Concentrado de Hemácias sem buffy coat][Hospitalar],
6.1(c) Tranfusões  [Concentrado de Hemácias sem buffy coat][Total],
6.1(c) Tranfusões  [Concentrado de Plaquetas][Ambulatorial],
6.1(c) Tranfusões  [Concentrado de Plaquetas][Hospitalar],
6.1(c) Tranfusões  [Concentrado de Plaquetas][Total],
6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Ambulatorial],
6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Hospitalar],
6.1(c) Tranfusões  [Concentrado de Plaquetas de Aférese][Total],
6.1(c) Tranfusões  [Concentrado de Leucócitos][Ambulatorial],
6.1(c) Tranfusões  [Concentrado de Leucócitos][Hospitalar],
6.1(c) Tranfusões  [Concentrado de Leucócitos][Total],
6.1(c) Tranfusões  [Crioprecipitado][Ambulatorial],
6.1(c) Tranfusões  [Crioprecipitado][Hospitalar],
6.1(c) Tranfusões  [Crioprecipitado][Total],
6.1(c) Tranfusões  [Concentrado de Plaquetas sem buffy coat][Ambulatorial],
6.1(c) Tranfusões  [Concentrado de Plaquetas sem buffy coat][Hospitalar],
6.1(c) Tranfusões  [Concentrado de Plaquetas sem buffy coat][Total],
6.1(d) Distribuição para outros serviços     [Sangue total][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Sangue total][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Sangue total][Total],
6.1(d) Distribuição para outros serviços     [Plasma Fresco Congelado][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Plasma Fresco Congelado][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Plasma Fresco Congelado][Total],
6.1(d) Distribuição para outros serviços     [Plasma comum][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Plasma comum][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Plasma comum][Total],
6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias][Total],
6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias sem buffy coat][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias sem buffy coat][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Hemácias sem buffy coat][Total],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas][Total],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas de Aférese][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas de Aférese][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas de Aférese][Total],
6.1(d) Distribuição para outros serviços     [Concentrado de Leucócitos][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Leucócitos][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Leucócitos][Total],
6.1(d) Distribuição para outros serviços     [Crioprecipitado][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Crioprecipitado][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Crioprecipitado][Total],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas sem buffy coat][Sem exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas sem buffy coat][Com exame pré-transfusional ],
6.1(d) Distribuição para outros serviços     [Concentrado de Plaquetas sem buffy coat][Total],
6.2 Procedimentos de modificação dos hemocomponentes [6.2.1 Lavagem],
6.2 Procedimentos de modificação dos hemocomponentes [6.2.2 Irradiação],
6.2 Procedimentos de modificação dos hemocomponentes [6.2.3(a) Filtração em Concentrado de Plaquetas],
6.2 Procedimentos de modificação dos hemocomponentes [6.2.3(b) Filtração em Concentrado de Hemácias],
6.2 Procedimentos de modificação dos hemocomponentes [6.2.4 Fracionamento pediátrico],
7 Reações Transfusionais [Reação Febril não Hemolítica],
7 Reações Transfusionais [Reação Hemolítica],
7 Reações Transfusionais [Reação Alérgica],
7 Reações Transfusionais [Choque Bacteriano],
7 Reações Transfusionais [Alterações Metabólicas],
7 Reações Transfusionais [Sobrecarga Volêmica],
7 Reações Transfusionais [Outras reações ],
8. Envio de Plasma para produção de hemoderivados [Plasma Fresco Congelado],
8. Envio de Plasma para produção de hemoderivados [Plasma Comum],
HEMOPROD_3 - Observações,

In [92]:
hemoprod_go.head()

,ID da resposta,Data de envio,Última página,Idioma inicial,Semente,Código de acesso,Data de início,Data da última ação,Endereço IP,IDENTIFICAÇÃO DO DADO,"Tipo de Informação Antes de responder ao formulário, declare o tipo de informação que será inserida.",Ano de referência,Período de referência,IDENTIFICAÇÃO DO ESTABELECIMENTO,Município,Razão Social - Nome Fantasia,Razão Social - Nome Fantasia [Outros],CNPJ,Tipo de estabelecimento,Natureza do estabelecimento,Os dados informados referem-se à um(a):,"Cite os estabelecimentos que compõem a rede Informe o Tipo de Estabelecimento, o Nome Fantasia e o Município de localização de cada um.",CNES - Cadastro Nacional de Estabelecimentos de Saúde,Endereço,2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Espontânea][Aptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Espontânea][Inaptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Reposição][Aptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Reposição][Inaptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Autóloga][Aptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Autóloga][Inaptos],2.2 Total de candidatos quanto ao tipo de doador [Primeira vez][Aptos],2.2 Total de candidatos quanto ao tipo de doador [Primeira vez][Inaptos],2.2 Total de candidatos quanto ao tipo de doador [Repetição][Aptos],2.2 Total de candidatos quanto ao tipo de doador [Repetição][Inaptos],2.2 Total de candidatos quanto ao tipo de doador [Esporádico][Aptos],2.2 Total de candidatos quanto ao tipo de doador [Esporádico][Inaptos],2.3 Total de candidatos quanto ao gênero do doador [Masculino][Aptos],2.3 Total de candidatos quanto ao gênero do doador [Masculino][Inaptos],2.3 Total de candidatos quanto ao gênero do doador [Feminino][Aptos],2.3 Total de candidatos quanto ao gênero do doador [Feminino][Inaptos],2.4 Total de candidatos quanto a idade do doador [Menor de 18 anos][Aptos],2.4 Total de candidatos quanto a idade do doador [Menor de 18 anos][Inaptos],2.4 Total de candidatos quanto a idade do doador [18 até 29 anos][Aptos],2.4 Total de candidatos quanto a idade do doador [18 até 29 anos][Inaptos],2.4 Total de candidatos quanto a idade do doador [Acima de 29 anos][Aptos],2.4 Total de candidatos quanto a idade do doador [Acima de 29 anos][Inaptos],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Anemia][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Anemia][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Anemia][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipertensão][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipertensão][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipertensão][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipotensão][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipotensão][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hipotensão][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Alcoolismo][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Alcoolismo][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Alcoolismo][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Comportamento de risco para DST][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Comportamento de risco para DST][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Comportamento de risco para DST][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Uso de drogas][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Uso de drogas][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Uso de drogas][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hepatite][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hepatite][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Hepatite][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Doença de Chagas][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Doença de Chagas][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Doença de Chagas][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Malária][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Malária][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Malária][Total],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Outras][Masculino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Outras][Feminino],2.5 Total de candidatos inaptos por motivo de inaptidão e por gênero [Outras][Total],3. Coleta 3.1 Total de candidatos desistentes,3.2 Total de interrupções na coleta por [Dificuldade de punção venosa],3.2 Total de interrupções na coleta por [Reação vagal],3.2 Total de interrupções na coleta por [Outros motivos],3.3 Total de coletas [Sangue total],3.3 Total de coletas [Por aférese],HEMOPROD_1 - Observações,4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Doença de Chagas][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Doença de Chagas][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Sífilis ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Sífilis ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - HBs Ag ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - HBs Ag ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - Anti HBc ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite B - Anti HBc ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite C][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Hepatite C][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HTLV I e II ][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HTLV I e II ][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Malária][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [Malária][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HBV (Teste NAT)*][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HBV (Teste NAT)*][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HCV (Teste NAT)*][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HCV (Teste NAT)*][Amostras reagentes],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV (Teste NAT)*][Amostras testadas],4. Exames Realizados 4.1 Triagem de doenças transmissíveis pelo sangue [HIV (Teste NAT)*][Amostras reagentes],4.2 Imunohematologia [A+][Doador],4.2 Imunohematologia [A+][Receptor],4.2 Imunohematologia [B+][Doador],4.2 Imunohematologia [B+][Receptor],4.2 Imunohematologia [AB+][Doador],4.2 Imunohematologia [AB+][Receptor],4.2 Imunohematologia [O+][Doador],4.2 Imunohematologia [O+][Receptor],4.2 Imunohematologia [A-][Doador],4.2 Imunohematologia [A-][Receptor],4.2 Imunohematologia [B-][Doador],4.2 Imunohematologia [B-][Receptor],4.2 Imunohematologia [AB-][Doador],4.2 Imunohematologia [AB-][Receptor],4.2 Imunohematologia [O-][Doador],4.2 Imunohematologia [O-][Receptor],4.2 Imunohematologia [Dfraco][Doador],4.2 Imunohematologia [Dfraco][Receptor],4.2 Imunohematologia [Pesquisa de anticorpo irregular positivo][Doador],4.2 Imunohematologia [Pesquisa de anticorpo irregular positivo][Receptor],4.2 Imunohematologia [Fenotipagem][Doador],4.2 Imunohematologia [Fenotipagem][Receptor],4.2 Imunohematologia [Combs Direto][Doador],4.2 Imunohematologia [Combs Direto][Receptor],4.3 Outros tipos de pesquisa [Pesquisa de HbS no doador],4.4 Inaptidão na triagem laboratorial [Total de bolsas testadas],4.4 Inaptidão na triagem laboratorial [Total de bolsas reagentes para 1 ou mais marcadores],5. Descarte de Bolsas 5.1 Descarte de bolsas [Total de bolsas descartadas por auto-exclusão],HEMOPROD_2 - Observações,6. Produção Hemoterápica 6.1(a) Entradas [Sangue total][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Sangue total][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Sangue total][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma Fresco Congelado][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma Fresco Congelado][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma Fresco Congelado][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma comum][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma comum][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Plasma comum][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias sem buffy coat][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias sem buffy coat][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Hemácias sem buffy coat][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas de Aférese][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas de Aférese][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas de Aférese][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Leucócitos][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Leucócitos][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Leucócitos][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Crioprecipitado][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Crioprecipitado][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Crioprecipitado][Devolvidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas sem buffy coat][Produzidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas sem buffy coat][Recebidas],6. Produção Hemoterápica 6.1(a) Entradas [Concentrado de Plaquetas sem buffy coat][Devolvidas],6.1(b) Perdas [Sangue total][Rompimento de Bolsa],6.1(b) Perdas [Sangue total][Validade],6.1(b) Perdas [Sangue total][Outros motivos],6.1(b) Perdas [Plasma Fresco Congelado][Rompimento de Bolsa],6.1(b) Perdas [Plasma Fresco Congelado][Validade],6.1(b) Perdas [Plasma Fresco Congelado][Outros motivos],6.1(b) Perdas [Plasma comum][Rompimento de Bolsa],6.1(b) Perdas [Plasma comum][Validade],6.1(b) Perdas [Plasma comum][Outros motivos],6.1(b) Perdas [Concentrado de Hemácias][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Hemácias][Validade],6.1(b) Perdas [Concentrado de Hemácias][Outros motivos],6.1(b) Perdas [Concentrado de Hemácias sem buffy coat][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Hemácias sem buffy coat][Validade],6.1(b) Perdas [Concentrado de Hemácias sem buffy coat][Outros motivos],6.1(b) Perdas [Concentrado de Plaquetas][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Plaquetas][Validade],6.1(b) Perdas [Concentrado de Plaquetas][Outros motivos],6.1(b) Perdas [Concentrado de Plaquetas de Aférese][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Plaquetas de Aférese][Validade],6.1(b) Perdas [Concentrado de Plaquetas de Aférese][Outros motivos],6.1(b) Perdas [Concentrado de Leucócitos][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Leucócitos][Validade],6.1(b) Perdas [Concentrado de Leucócitos][Outros motivos],6.1(b) Perdas [Crioprecipitado][Rompimento de Bolsa],6.1(b) Perdas [Crioprecipitado][Validade],6.1(b) Perdas [Crioprecipitado][Outros motivos],6.1(b) Perdas [Concentrado de Plaquetas sem buffy coat][Rompimento de Bolsa],6.1(b) Perdas [Concentrado de Plaquetas sem buffy coat][Validade],6.1(b) Perdas [Concentrado de Plaquetas sem buffy coat][Outros motivos],6.1(c) Tranfusões [Sangue total][Ambulatorial],6.1(c) Tranfusões [Sangue total][Hospitalar],6.1(c) Tranfusões [Sangue total][Total],6.1(c) Tranfusões [Plasma Fresco Congelado][Ambulatorial],6.1(c) Tranfusões [Plasma Fresco Congelado][Hospitalar],6.1(c) Tranfusões [Plasma Fresco Congelado][Total],6.1(c) Tranfusões [Plasma comum][Ambulatorial],6.1(c) Tranfusões [Plasma comum][Hospitalar],6.1(c) Tranfusões [Plasma comum][Total],6.1(c) Tranfusões [Concentrado de Hemácias][Ambulatorial],6.1(c) Tranfusões [Concentrado de Hemácias][Hospitalar],6.1(c) Tranfusões [Concentrado de Hemácias][Total],6.1(c) Tranfusões [Concentrado de Hemácias sem buffy coat][Ambulatorial],6.1(c) Tranfusões [Concentrado de Hemácias sem buffy coat][Hospitalar],6.1(c) Tranfusões [Concentrado de Hemácias sem buffy coat][Total],6.1(c) Tranfusões [Concentrado de Plaquetas][Ambulatorial],6.1(c) Tranfusões [Concentrado de Plaquetas][Hospitalar],6.1(c) Tranfusões [Concentrado de Plaquetas][Total],6.1(c) Tranfusões [Concentrado de Plaquetas de Aférese][Ambulatorial],6.1(c) Tranfusões [Concentrado de Plaquetas de Aférese][Hospitalar],6.1(c) Tranfusões [Concentrado de Plaquetas de Aférese][Total],6.1(c) Tranfusões [Concentrado de Leucócitos][Ambulatorial],6.1(c) Tranfusões [Concentrado de Leucócitos][Hospitalar],6.1(c) Tranfusões [Concentrado de Leucócitos][Total],6.1(c) Tranfusões [Crioprecipitado][Ambulatorial],6.1(c) Tranfusões [Crioprecipitado][Hospitalar],6.1(c) Tranfusões [Crioprecipitado][Total],6.1(c) Tranfusões [Concentrado de Plaquetas sem buffy coat][Ambulatorial],6.1(c) Tranfusões [Concentrado de Plaquetas sem buffy coat][Hospitalar],6.1(c) Tranfusões [Concentrado de Plaquetas sem buffy coat][Total],6.1(d) Distribuição para outros serviços [Sangue total][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Sangue total][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Sangue total][Total],6.1(d) Distribuição para outros serviços [Plasma Fresco Congelado][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma Fresco Congelado][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma Fresco Congelado][Total],6.1(d) Distribuição para outros serviços [Plasma comum][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma comum][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Plasma comum][Total],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias][Total],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias sem buffy coat][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias sem buffy coat][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Hemácias sem buffy coat][Total],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas][Total],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas de Aférese][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas de Aférese][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas de Aférese][Total],6.1(d) Distribuição para outros serviços [Concentrado de Leucócitos][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Leucócitos][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Leucócitos][Total],6.1(d) Distribuição para outros serviços [Crioprecipitado][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Crioprecipitado][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Crioprecipitado][Total],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas sem buffy coat][Sem exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas sem buffy coat][Com exame pré-transfusional ],6.1(d) Distribuição para outros serviços [Concentrado de Plaquetas sem buffy coat][Total],6.2 Procedimentos de modificação dos hemocomponentes [6.2.1 Lavagem],6.2 Procedimentos de modificação dos hemocomponentes [6.2.2 Irradiação],6.2 Procedimentos de modificação dos hemocomponentes [6.2.3(a) Filtração em Concentrado de Plaquetas],6.2 Procedimentos de modificação dos hemocomponentes [6.2.3(b) Filtração em Concentrado de Hemácias],6.2 Procedimentos de modificação dos hemocomponentes [6.2.4 Fracionamento pediátrico],7 Reações Transfusionais [Reação Febril não Hemolítica],7 Reações Transfusionais [Reação Hemolítica],7 Reações Transfusionais [Reação Alérgica],7 Reações Transfusionais [Choque Bacteriano],7 Reações Transfusionais [Alterações Metabólicas],7 Reações Transfusionais [Sobrecarga Volêmica],7 Reações Transfusionais [Outras reações ],8. Envio de Plasma para produção de hemoderivados [Plasma Fresco Congelado],8. Envio de Plasma para produção de hemoderivados [Plasma Comum],HEMOPROD_3 - Observações
0,2,2023-04-06 10:24:01,4,pt-BR,8.032299e+08,7ViMrEUwxtMPA2q,2023-04-06 09:41:19,2023-04-06 10:24:01,10.0.0.186,NaN,ORIGINAL,2023,Março,NaN,"Goiânia, Goiás",Associação de Combate ao Câncer em Goiás - Hos...,NaN,1.585595e+11,Núcleo de Hemoterapia,Público,Único serviço,NaN,NaN,NaN,408.0,79.0,363.0,71.0,0.0,0.0,460.0,106.0,291.0,40.0,20.0,4.0,472.0,64.0,299.0,86.0,2.0,2.0,228.0,50.0,541.0,98.0,5.0,1.0,26.0,0.0,2.0,2.0,1.0,2.0,3.0,0.0,0.0,0.0,3.0,0.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,64.0,86.0,150.0,16.0,0.0,3.0,0.0,700.0,71.0,NaN,771.0,0.0,771.0,0.0,771.0,10.0,771.0,0.0,771.0,8.0,771.0,0.0,771.0,0.0,0.0,0.0,771.0,0.0,771.0,0.0,771.0,0.0,248,262,82,48,13,46,327,277,33,10,13,8,2,0,55,25,0,0,2,17,101,58,0,0,15.0,771.0,18.0,0.0,NaN,16,0,0,695,0,0,0,0,0,698,54,0,0,0,0,333,16,0,0,0,0,0,0,0,53,0,0,165,25,0,0,0,16,4,5,630,0,0,0,1,48,76,0,0,0,0,10,56,0,0,0,0,0,0,1,2,23,0,1,23,0,0,0,0,114,114,0,0,0,194,408,602,0,0,0,19,256,278,0,0,0,0,0,0,0,95,95,4,152,156,0,0,0,6,0,6,0,0,0,2,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1227,126,90,56,1,0,2,0,0,1,0,0.0,0.0,NaN

In [93]:
# Carrega o arquivo de dicionário
dicionario_path_go = ('./dicionario_colunas_269.xlsx')
dicionario = pd.read_excel(dicionario_path_go)
print("Arquivo de dicionário carregado com sucesso.")

# --- 3. Extraia a lista de novos nomes ---
# Pega os valores da coluna 'nome_sql' e converte para uma lista
novos_nomes = dicionario['nome_sql'].tolist()
print(f"Número de novos nomes no dicionário: {len(novos_nomes)}")

# --- 4. Verificação de segurança (MUITO IMPORTANTE) ---
# Garante que o número de colunas é o mesmo antes de renomear
if len(hemoprod_go.columns) == len(novos_nomes):
    print("\nO número de colunas corresponde. Renomeando...")
    
    # --- 5. Substitua os nomes das colunas ---
    # Esta é a linha principal que faz a substituição direta
    hemoprod_go.columns = novos_nomes
    
    print("Colunas renomeadas com sucesso!")
    
    # --- 6. Verifique o resultado ---
    print("\nInformações do DataFrame com as novas colunas:")
    hemoprod_go.info()
    
    print("\nAs 5 primeiras linhas com as novas colunas:")
    display(hemoprod_go.head())

else:
    # Mensagem de erro se o número de colunas for diferente
    print("\n--- ERRO ---")
    print("A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.")
    print(f"Colunas no arquivo de dados: {len(hemoprod_go.columns)}")
    print(f"Nomes no dicionário: {len(novos_nomes)}")

Arquivo de dicionário carregado com sucesso.
Número de novos nomes no dicionário: 269

O número de colunas corresponde. Renomeando...
Colunas renomeadas com sucesso!

Informações do DataFrame com as novas colunas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474 entries, 0 to 473
Columns: 269 entries, id to hemoprod_3_observacoes
dtypes: float64(92), int64(159), object(18)
memory usage: 996.3+ KB

As 5 primeiras linhas com as novas colunas:

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,2,2023-04-06 10:24:01,4,pt-BR,8.032299e+08,7ViMrEUwxtMPA2q,2023-04-06 09:41:19,2023-04-06 10:24:01,10.0.0.186,NaN,ORIGINAL,2023,Março,NaN,"Goiânia, Goiás",Associação de Combate ao Câncer em Goiás - Hos...,NaN,1.585595e+11,Núcleo de Hemoterapia,Público,Único serviço,NaN,NaN,NaN,408.0,79.0,363.0,71.0,0.0,0.0,460.0,106.0,291.0,40.0,20.0,4.0,472.0,64.0,299.0,86.0,2.0,2.0,228.0,50.0,541.0,98.0,5.0,1.0,26.0,0.0,2.0,2.0,1.0,2.0,3.0,0.0,0.0,0.0,3.0,0.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,64.0,86.0,150.0,16.0,0.0,3.0,0.0,700.0,71.0,NaN,771.0,0.0,771.0,0.0,771.0,10.0,771.0,0.0,771.0,8.0,771.0,0.0,771.0,0.0,0.0,0.0,771.0,0.0,771.0,0.0,771.0,0.0,248,262,82,48,13,46,327,277,33,10,13,8,2,0,55,25,0,0,2,17,101,58,0,0,15.0,771.0,18.0,0.0,NaN,16,0,0,695,0,0,0,0,0,698,54,0,0,0,0,333,16,0,0,0,0,0,0,0,53,0,0,165,25,0,0,0,16,4,5,630,0,0,0,1,48,76,0,0,0,0,10,56,0,0,0,0,0,0,1,2,23,0,1,23,0,0,0,0,114,114,0,0,0,194,408,602,0,0,0,19,256,278,0,0,0,0,0,0,0,95,95,4,152,156,0,0,0,6,0,6,0,0,0,2,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1227,126,90,56,1,0,2,0,0,1,0,0.0,0.0,NaN
1,4,2023-04-10 16:13:24,4,pt-BR,8.612602e+08,do26zwKaqbdfirs,2023-04-10 15:42:31,2023-04-10 16:13:24,10.0.0.186,NaN,ORIGINAL,2023,Março,NaN,"Goiânia, Goiás",Instituto Goiano de Oncologia e Hemoterapia - ...,NaN,1.277573e+12,Unidade de Coleta e Transfusão,Privado,Único serviço,NaN,NaN,NaN,362.0,22.0,794.0,38.0,0.0,0.0,371.0,37.0,785.0,23.0,0.0,0.0,677.0,28.0,479.0,32.0,7.0,1.0,412.0,16.0,737.0,43.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0,28.0,55.0,0.0,2.0,2.0,67.0,1050.0,35.0,NaN,1154.0,0.0,1154.0,0.0,1154.0,25.0,1154.0,0.0,1154.0,16.0,1154.0,16.0,1154.0,0.0,1154.0,0.0,1154.0,0.0,1154.0,0.0,1154.0,0.0,321,213,101,63,35,19,453,288,78,23,23,10,6,1,137,43,246,31,2,7,16,2,0,3,7.0,1154.0,48.0,1.0,NaN,16,0,0,1075,4,0,1,0,0,1075,7,0,0,0,0,12,40,0,0,0,0,0,0,0,119,0,0,0,0,0,0,0,16,8,2,807,0,0,0,6,135,49,0,0,0,0,137,26,0,0,0,0,0,0,8,7,2,0,0,0,0,0,0,0,220,220,0,0,0,91,1252,1343,0,0,0,29,325,354,0,0,0,0,0,0,0,131,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,9,0,0,0,0,10,10,0,0,0,0,0,0,0,0,0,0,0,0,19,83,44,542,144,1,2,0,0,0,0,0,0.0,0.0,NaN
2,5,2023-04-11 16:26:17,4,pt-BR,1.403820e+09,CIYBY7ylc1zXzre,2023-04-11 15:51:51,2023-04-11 16:26:17,10.0.113.219,NaN,ORIGINAL,2023,Março,NaN,"Goiânia, Goiás",Santa Casa de Misericódia de Goiania - Santa C...,NaN,1.619790e+12,Unidade de Coleta e Transfusão,Privado-SUS,Único serviço,NaN,NaN,NaN,254.0,118.0,0.0,0.0,0.0,0.0,190.0,99.0,28.0,7.0,36.0,14.0,190.0,65.0,64.0,55.0,0.0,1.0,82.0,41.0,172.0,78.0,9.0,24.0,33.0,18.0,8.0,26.0,0.0,0.0,0.0,3.0,0.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31.0,26.0,57.0,3.0,0.0,1.0,0.0,0.0,0.0,NaN,251.0,0.0,251.0,1.0,251.0,7.0,251.0,0.0,51.0,5.0,251.0,1.0,251.0,0.0,0.0,0.0,251.0,1.0,251.0,0.0,251.0,0.0,80,42,27,23,6,1,118,30,6,1,5,5,0,0,5,8,0,0,0,2,0,0,0,0,6.0,251.0,19.0,0.0,NaN,0,0,0,245,0,0,0,0,0,245,4,0,0,0,0,143,0,0,0,0,0,0,0,0,34,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,18,0,0,0,2,0,24,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,26,26,0,0,0,12,108,120,0,0,0,0,54,54,0,0,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,51,35,0,0,0,0,0,0,0,0,0.0,0.0,NaN
3,7,2023-04-22 20:12:00,4,pt-BR,NaN,4GNr9cQ99c7Jrbk,2023-04-22 18:34:00,2023-04-22 20:12:00,10.0.1.33,NaN,ORIGINAL,2023,Janeiro,NaN,"Goiânia, Goiás",Instituto de Hemoterapia de Goiânia (IHG) - Ce...,CENTRO DE HEMOTERAPIA DE GOIÂNIA,3.341398e+12,Unidade de Coleta e Transfusão,Privado-SUS,Único serviço,NaN,NaN,NaN,189.0,16.0,410.0,37.0,0.0,0.0,350.0,38.0,153.0,5.0,96.0,10.0,348.0,23.0,251.0,30.0,7.0,0.0,172.0,12.0,420.0,41.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,21.0,29.0,50.0,1.0,4.0,1.0,16.0,572.0,5.0,NaN,583.0,0.0,583.0,0.0,583.0,3.0,583.0,0.0,583.0,5.0,583.0,0.0,583.0,0.0,0.0,0.0,583.0,1.0,583.0,0.0,583.0,0.0,192,85,64,34,15,14,237,112,37,14,5,5,1,1,32,7,75,0,1,8,75,0,0,0,583.0,583.0,6.0,0.0,NaN,2,0,0,570,0,0,0,0,0,570,67,0,0,0,0,312,47,0,0,0,0,0,0,0,83,0,0,0,0,0,0,0,2,0,0,281,0,0,83,0,8,23,0,0,0,2,49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,52,0,0,0,0,36,351,0,0,0,0,0,136,0,0,0,0,0,0,0,0,28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,13,7,147,37,0,0,0,0,0,0,0,0.0,0.0,NaN
4,8,2023-05-09 09:11:08,4,pt-BR,7.651788e+08,CIYBY7ylc1zXzre,2023-05-09 08:43:08,2023-05-09 09:11:08,10.0.0.47,NaN,ORIGINAL,2023,Abril,NaN,"Goiânia, Goiás",Santa Casa de Misericódia de Goiania - Santa C...,NaN,1.619790e+12,Unidade de Coleta e Transfusão,Privado-SUS,Único serviço,NaN,NaN,NaN,239.0,112.0,0.0,0.0,0.0,0.0,185.0,98.0,24.0,7.0,39.0,10.0,174.0,61.0,74.0,54.0,3.0,0.0,77.0,30.0,168.0,85.0,12.0,24.0,36.0,12.0,6.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,22.0,54.0,4.0,0.0,3.0,1.0,248.0,0.0,NaN,258.0,0.0,258.0,0.0,258.0,3.0,258.0,0.0,258.0,4.0,258.0,1.0,258.0,0.0,0.0,0.0,258.0,0.0,258.0,0.0,258.0,0.0,79,32,27,23,10,2,103,48,14,3,4,0,0,0,21,9,0,0,1,1,0,0,0,1,3.0,258.0,11.0,0.0,NaN,0,0,0,250,0,0,0,0,0,250,0,0,0,0,0,114,22,0,0,0,0,0,0,0,49,0,0,0,0,0,0,0,0,0,0,5,0,0,105,0,0,12,0,0,0,0,0,20,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0,0,39,39,0,0,0,24,167,191,0,0,0,0,98,0,0,0,0,0,0,0,0,39,39,0,0,0,0,0,0,0,39,39,0,0,0,0,191,191,0,0,0,0,98,98,0,0,0,0,0,0,0,39,39,0,0,0,0,0,9,24,0,0,0,0,0,0,0,0,0.0,0.0,NaN

In [95]:
hemoprod_go.describe()

,id,ultima_pagina,semente,identificacao_dado,ano_referencia,identificacao_estabelecimento,cnpj,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum
count,474.000000,474.0,4.630000e+02,0.0,474.000000,0.0,4.740000e+02,0.0,0.0,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.00000,454.000000,454.000000,454.0,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,454.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,454.000000,454.000000,454.000000,454.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.0,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.0,474.0,474.0,474.0,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.0,474.0,474.0,474.0,474.0,474.0,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.0,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.0,474.0,474.0,474.0,474.0,474.0,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.0,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.00000,474.0,474.0,474.0,474.000000,474.0,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.000000,474.0,474.0,474.000000,474.000000,454.000000,454.000000
mean,292.487342,4.0,1.116554e+09,NaN,2023.921941,NaN,7.126499e+12,NaN,NaN,437.460352,63.162996,181.024229,20.248899,0.555066,0.022026,247.420705,46.385463,224.784141,17.885463,146.504405,19.059471,358.614537,37.506608,260.112335,45.839207,7.914097,1.929515,223.204846,32.211454,390.196035,51.969163,1.378855,11.041850,12.449339,2.044053,0.938326,2.980176,0.255507,0.834802,1.088106,0.268722,0.068282,0.330396,3.654185,1.129956,4.665198,0.185022,0.028634,0.211454,0.055066,0.03304,0.085903,0.006608,0.0,0.006608,0.378855,0.268722,0.643172,29.030837,31.517621,60.654185,5.196035,3.341410,0.830396,4.759912,586.814978,24.088106,693.112335,0.803965,699.385463,0.997797,699.385463,9.916300,699.385463,0.753304,698.944934,5.061674,699.387665,1.491189,699.385463,1.328194,76.077093,0.002203,692.354626,0.138767,692.354626,0.044053,692.288546,0.370044,203.689873,88.289030,65.565401,28.139241,21.466245,8.476793,285.748945,121.476793,30.251055,12.592827,9.436709,3.177215,3.002110,1.027426,48.088608,16.377637,78.797468,12.158228,4.626582,10.050633,40.641350,18.592827,0.280591,5.732068,550.414097,700.986784,25.116740,1.522026,22.822785,0.002110,0.151899,477.373418,26.983122,6.082278,70.029536,0.0,0.137131,541.907173,71.154008,31.879747,11.529536,0.772152,0.029536,210.951477,25.240506,1.704641,0.0,0.0,0.0,0.0,0.037975,0.004219,42.400844,5.873418,0.611814,22.727848,5.048523,0.299578,0.594937,0.021097,18.044304,5.227848,11.928270,288.327004,0.016878,0.031646,63.242616,1.400844,36.168776,40.329114,0.012658,0.643460,0.721519,1.797468,79.299578,37.016878,0.0,0.0,0.0,0.0,0.0,0.0,0.464135,1.255274,2.158228,0.044304,9.377637,3.229958,0.337553,0.708861,1.046414,0.862869,28.580169,31.318565,0.0,0.670886,0.670886,27.419831,151.428270,174.845992,0.227848,1.166667,11.183544,3.402954,37.472574,40.926160,0.0,0.0,0.0,0.0,0.0,0.0,0.542194,12.533755,14.493671,1.658228,8.151899,11.689873,0.027426,0.0,0.027426,53.407173,25.607595,79.052743,1.875527,0.253165,3.637131,219.533755,184.620253,403.993671,3.430380,9.786920,13.217300,41.082278,35.689873,76.49789,0.0,0.0,0.0,0.054852,0.0,0.151899,19.191983,11.434599,30.873418,6.390295,4.436709,11.723629,2.886076,123.006329,19.795359,166.485232,33.042194,0.303797,0.010549,0.331224,0.0,0.0,0.040084,0.130802,57.583700,11.418502
std,164.757561,0.0,6.098059e+08,NaN,0.804469,NaN,1.196518e+13,NaN,NaN,597.295710,105.918457,273.361944,31.746612,2.505677,0.381063,265.123157,59.800432,229.227279,21.246168,262.457933,41.386388,376.002001,48.668484,298.475284,64.252971,49.802605,9.684168,260.815269,48.075403,409.927177,74.915487,2.243872,16.735588,18.143184,3.355704,1.755643,4.703299,0.758122,1.935272,2.373732,0.723640,0.321706,0.866905,8.193669,2.933152,10.629950,0.540742,0.179697,0.604801,0.237831,0.20211,0.331062,0.104851,0.0,0.104851,1.378515,1.268758,2.425123,37.083152,44.803209,80.728317,35.525060,5.408701,2.246381,10.401311,637.803530,91.768839,1573.586785,2.173264,1572.196453,2.892098,1572.196453,24.311573,1572.196453,2.405095,1572.350380,11.156154,1572.196705,4.651061,1572.196453,4.648363,275.577925,0.046932,1572.921049,0.484319,1572.921049,0.235479,1572.922915,1.022736,471.577169,82.133025,152.733753,26.784190,49.349810,9.676834,663.212397,110.958521,68.937376,13.588518,22.705701,4.085532,6.834033,2.914077,112.076068,18.584554,208.048613,17.949726,29.938588,21.776143,85.859355,34.348617,1.120331,12.440384,1586.865405,1571.934057,106.579477,3.834685,55.493197,0.045932,1.738182,435.569853,86.416023,52.550183,225.017132,0.0,2.494852,609.047730,132.233247,57.184249,93.207492,13.221434,0.467973,230.644918,47.144252,6.833051,0.0,0.0,0.0,0.0,0.826767,0.091863,64.344833,17.759279,3.426848,73.216062,13.146265,1.257081,1.709461,0.297235,27.976133,10.015146,50.126975,264.747174,0.194344,0.432617,195.674553,8.302403,57.790803,47.920888,0.171574,6.513078,5.608669,21.265987,90.116456,84.093196,0.0,0.0,0.0,0.0,0.0,0.0,3.457960,6.596833,5.552200,0.312088,27.703252,14.814993,7.349043,15.432991,22.782035,10.251807,57.789467,62.879846,0.0,10.488155,10.488155,54.558645,264.258211,299.516113,4.960604,23.736656,92.406824,8.620252,76.850479,80.895966,0.0,0.0,0.0,0.0,0.0,0.0,5.386079,31.186066,36.531503,6.888516,28.989648,39.543468,0.597110,0.0,0.597110,89.556299,43.319234,109.880405,19.351410,3.183474,32.748694,502.861146,220.334676,660.478219,28.853725,79.396608,107.758388,100.629370,75.928410,144.61858,0.0,0.0,0.0,1.194220,0.0,2.424794,49.205431,28.116884,61.274594,22.205974,16.742080,35.063060,8.194497,279.801391,49.686398,224.517573,59.179863,0.796734,0.121193,0.941186,0.0,0.0,0.206851,0.499239,225.251002,59.234381

In [96]:
# --- 2. Defina as colunas para a chave e para ordenação ---
registros_antes = len(hemoprod_go)
print(f"Total de registros ANTES da remoção de duplicatas: {registros_antes}")
    

colunas_chave = [
        'cnpj', 
        'ano_referencia', 
        'periodo_referencia', 
        'razao_social_nome_fantasia'
    ]

coluna_data = 'data_envio'

# --- 3. Verifique se as colunas necessárias existem ---
colunas_necessarias = colunas_chave + [coluna_data]

if not all(col in hemoprod_go.columns for col in colunas_necessarias):
    print("\n--- ERRO ---")
    print("Uma ou mais colunas necessárias para a deduplicação não foram encontradas.")
    colunas_faltantes = [col for col in colunas_necessarias if col not in hemoprod_go.columns]
    print(f"Colunas necessárias: {colunas_necessarias}")
    print(f"Colunas faltantes no DataFrame: {colunas_faltantes}")
else:
    # --- 4. Prepare a coluna de data e ordene os dados ---
    # Converte a coluna 'data_envio' para datetime para garantir a ordenação correta.
    # 'errors='coerce'' transformará datas inválidas em NaT (Not a Time), que são tratadas como nulas.
    hemoprod_go[coluna_data] = pd.to_datetime(hemoprod_go[coluna_data], errors='coerce')

    # Ordena o DataFrame. Os registros com data de envio mais recente ficarão por último.
    print(f"\nOrdenando os dados por '{coluna_data}'...")
    hemoprod_go_ordenado = hemoprod_go.sort_values(by=coluna_data, ascending=True)

    # --- 5. Identifique e separe os registros duplicados e únicos ---
    # Em vez de usar drop_duplicates() diretamente, vamos usar duplicated()
    # para criar uma máscara booleana.
    # 'keep='last'' marca todas as ocorrências de uma chave como True, EXCETO a última (a mais recente).
    print(f"Identificando duplicatas com cese na chave: {colunas_chave}...")
    mascara_duplicatas = hemoprod_go_ordenado.duplicated(subset=colunas_chave, keep='last')

    # O DataFrame de removidos conterá todas as linhas marcadas como True
    hemoprod_removidos = hemoprod_go_ordenado[mascara_duplicatas]
    
    # O DataFrame deduplicado conterá o INVERSO (~) da máscara (linhas marcadas como False)
    hemoprod_go_deduplicado = hemoprod_go_ordenado[~mascara_duplicatas]
    
    # Agora podemos contar os registros diretamente dos novos DataFrames
    registros_depois = len(hemoprod_go_deduplicado)
    registros_removidos = len(hemoprod_removidos) 
    
    # --- 6. Exice o resultado ---
    print("\n--- Processo Concluído ---")
    print(f"Registros removidos: {registros_removidos}")
    print(f"Total de registros DEPOIS da remoção de duplicatas: {registros_depois}")

    # (Opcional) Exibe a amostra dos removidos
    print("\nAmostra dos dados REMOVIDOS (os mais antigos/duplicados):")
    display(hemoprod_removidos.head(10))

    # Você pode continuar a usar o DataFrame 'hemoprod_ce_deduplicado' para suas análises
    print("\nAmostra dos dados únicos (os mais recentes para cada chave):")
    display(hemoprod_go_deduplicado.head(10))
    
    # Agora você tem o DataFrame 'hemoprod_removidos' salvo

Total de registros ANTES da remoção de duplicatas: 474

Ordenando os dados por 'data_envio'...
Identificando duplicatas com cese na chave: ['cnpj', 'ano_referencia', 'periodo_referencia', 'razao_social_nome_fantasia']...

--- Processo Concluído ---
Registros removidos: 3
Total de registros DEPOIS da remoção de duplicatas: 471

Amostra dos dados REMOVIDOS (os mais antigos/duplicados):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
342,423,2025-02-11 10:29:48,4,pt-BR,2.018850e+09,VHGGYmZQaVu2QZx,2025-02-11 10:20:27,2025-02-11 10:29:48,177.107.46.75,NaN,ORIGINAL,2025,Janeiro,NaN,"Iporá, Goiás",Fundo Municipal de Saúde - Unidade de Coleta e...,NaN,2.529964e+12,Unidade de Coleta e Transfusão,Público,Único serviço,NaN,NaN,NaN,163.0,34.0,1.0,0.0,0.0,0.0,19.0,12.0,127.0,19.0,18.0,3.0,111.0,21.0,53.0,13.0,4.0,1.0,43.0,15.0,117.0,18.0,0.0,5.0,5.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0,8.0,27.0,1.0,5.0,0.0,0.0,158.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,14,0,4,0,2,0,13,0,3,0,1,0,0,0,0,0,4,0,2,12,1,0,2,0.0,0.0,0.0,0.0,NaN,6,0,0,135,0,0,17,0,0,152,32,0,0,0,0,32,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,13,72,0,0,17,0,43,37,0,0,0,0,15,26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,3,0,0,0,0,45,69,0,0,0,0,0,4,0,0,0,0,0,0,0,0,10,0,0,0,0,0,0,51,0,0,0,0,0,0,0,0,0.0,0.0,NaN
408,503,2025-06-11 14:35:08,4,pt-BR,1.463516e+09,VHGGYmZQaVu2QZx,2025-06-11 14:30:12,2025-06-11 14:35:08,177.107.46.75,NaN,ORIGINAL,2025,Maio,NaN,"Jataí, Goiás",Empresa Transfusional do Entorno Ltda - Hemoce...,NaN,2.529964e+12,Hemocentro Regional,Público,Único serviço,NaN,NaN,NaN,381.0,65.0,14.0,1.0,0.0,0.0,124.0,30.0,124.0,11.0,147.0,25.0,210.0,18.0,185.0,48.0,6.0,1.0,153.0,29.0,236.0,36.0,1.0,20.0,21.0,0.0,1.0,1.0,0.0,2.0,2.0,1.0,0.0,1.0,2.0,2.0,4.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,1.0,0.0,12.0,380.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,91,0,23,0,19,0,95,0,12,0,5,0,1,0,16,0,0,0,5,59,8,0,1,0.0,0.0,0.0,0.0,NaN,14,0,0,374,0,0,3,0,0,377,35,0,0,0,0,226,2,0,0,0,0,0,0,0,15,0,0,0,0,0,0,0,9,1,0,302,0,0,0,0,7,21,0,0,0,0,130,35,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,42,25,67,0,0,0,101,262,363,0,0,0,9,48,57,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,98,0,0,0,0,0,0,0,0,0.0,0.0,NaN
434,535,2025-08-12 09:11:35,4,pt-BR,2.003715e+09,VHGGYmZQaVu2QZx,2025-08-12 09:00:19,2025-08-12 09:11:35,201.55.104.209,NaN,ORIGINAL,2025,Julho,NaN,"Catalão, Goiás",Fundo Municipal de Saúde - Hemocentro Regional...,NaN,2.529964e+12,Hemocentro Regional,Público,Único serviço,NaN,NaN,NaN,260.0,14.0,1.0,0.0,0.0,0.0,87.0,6.0,115.0,3.0,59.0,5.0,127.0,6.0,134.0,8.0,3.0,0.0,79.0,3.0,179.0,11.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,5.0,11.0,0.0,3.0,0.0,0.0,258.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,42,0,18,0,3,0,58,0,8,0,0,0,0,0,3,0,13,0,10,0,7,0,0,0.0,0.0,0.0,0.0,NaN,11,0,0,247,0,0,0,0,0,247,28,0,0,0,0,140,27,0,0,0,0,0,0,0,58,0,0,0,4,0,0,0,11,0,2,146,0,0,0,0,109,2,0,0,0,0,120,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40,11,51,0,0,0,47,205,252,0,0,0,0,19,19,0,0,0,0,0,0,0,16,16,0,0,0,0,0,0,68,8,0,0,0,0,0,0,0,0.0,0.0,NaN

Amostra dos dados únicos (os mais recentes para cada chave):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,2,2023-04-06 10:24:01,4,pt-BR,8.032299e+08,7ViMrEUwxtMPA2q,2023-04-06 09:41:19,2023-04-06 10:24:01,10.0.0.186,NaN,ORIGINAL,2023,Março,NaN,"Goiânia, Goiás",Associação de Combate ao Câncer em Goiás - Hos...,NaN,1.585595e+11,Núcleo de Hemoterapia,Público,Único serviço,NaN,NaN,NaN,408.0,79.0,363.0,71.0,0.0,0.0,460.0,106.0,291.0,40.0,20.0,4.0,472.0,64.0,299.0,86.0,2.0,2.0,228.0,50.0,541.0,98.0,5.0,1.0,26.0,0.0,2.0,2.0,1.0,2.0,3.0,0.0,0.0,0.0,3.0,0.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,64.0,86.0,150.0,16.0,0.0,3.0,0.0,700.0,71.0,NaN,771.0,0.0,771.0,0.0,771.0,10.0,771.0,0.0,771.0,8.0,771.0,0.0,771.0,0.0,0.0,0.0,771.0,0.0,771.0,0.0,771.0,0.0,248,262,82,48,13,46,327,277,33,10,13,8,2,0,55,25,0,0,2,17,101,58,0,0,15.0,771.0,18.0,0.0,NaN,16,0,0,695,0,0,0,0,0,698,54,0,0,0,0,333,16,0,0,0,0,0,0,0,53,0,0,165,25,0,0,0,16,4,5,630,0,0,0,1,48,76,0,0,0,0,10,56,0,0,0,0,0,0,1,2,23,0,1,23,0,0,0,0,114,114,0,0,0,194,408,602,0,0,0,19,256,278,0,0,0,0,0,0,0,95,95,4,152,156,0,0,0,6,0,6,0,0,0,2,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1227,126,90,56,1,0,2,0,0,1,0,0.0,0.0,NaN
1,4,2023-04-10 16:13:24,4,pt-BR,8.612602e+08,do26zwKaqbdfirs,2023-04-10 15:42:31,2023-04-10 16:13:24,10.0.0.186,NaN,ORIGINAL,2023,Março,NaN,"Goiânia, Goiás",Instituto Goiano de Oncologia e Hemoterapia - ...,NaN,1.277573e+12,Unidade de Coleta e Transfusão,Privado,Único serviço,NaN,NaN,NaN,362.0,22.0,794.0,38.0,0.0,0.0,371.0,37.0,785.0,23.0,0.0,0.0,677.0,28.0,479.0,32.0,7.0,1.0,412.0,16.0,737.0,43.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0,28.0,55.0,0.0,2.0,2.0,67.0,1050.0,35.0,NaN,1154.0,0.0,1154.0,0.0,1154.0,25.0,1154.0,0.0,1154.0,16.0,1154.0,16.0,1154.0,0.0,1154.0,0.0,1154.0,0.0,1154.0,0.0,1154.0,0.0,321,213,101,63,35,19,453,288,78,23,23,10,6,1,137,43,246,31,2,7,16,2,0,3,7.0,1154.0,48.0,1.0,NaN,16,0,0,1075,4,0,1,0,0,1075,7,0,0,0,0,12,40,0,0,0,0,0,0,0,119,0,0,0,0,0,0,0,16,8,2,807,0,0,0,6,135,49,0,0,0,0,137,26,0,0,0,0,0,0,8,7,2,0,0,0,0,0,0,0,220,220,0,0,0,91,1252,1343,0,0,0,29,325,354,0,0,0,0,0,0,0,131,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,9,0,0,0,0,10,10,0,0,0,0,0,0,0,0,0,0,0,0,19,83,44,542,144,1,2,0,0,0,0,0,0.0,0.0,NaN
2,5,2023-04-11 16:26:17,4,pt-BR,1.403820e+09,CIYBY7ylc1zXzre,2023-04-11 15:51:51,2023-04-11 16:26:17,10.0.113.219,NaN,ORIGINAL,2023,Março,NaN,"Goiânia, Goiás",Santa Casa de Misericódia de Goiania - Santa C...,NaN,1.619790e+12,Unidade de Coleta e Transfusão,Privado-SUS,Único serviço,NaN,NaN,NaN,254.0,118.0,0.0,0.0,0.0,0.0,190.0,99.0,28.0,7.0,36.0,14.0,190.0,65.0,64.0,55.0,0.0,1.0,82.0,41.0,172.0,78.0,9.0,24.0,33.0,18.0,8.0,26.0,0.0,0.0,0.0,3.0,0.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31.0,26.0,57.0,3.0,0.0,1.0,0.0,0.0,0.0,NaN,251.0,0.0,251.0,1.0,251.0,7.0,251.0,0.0,51.0,5.0,251.0,1.0,251.0,0.0,0.0,0.0,251.0,1.0,251.0,0.0,251.0,0.0,80,42,27,23,6,1,118,30,6,1,5,5,0,0,5,8,0,0,0,2,0,0,0,0,6.0,251.0,19.0,0.0,NaN,0,0,0,245,0,0,0,0,0,245,4,0,0,0,0,143,0,0,0,0,0,0,0,0,34,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,18,0,0,0,2,0,24,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,26,26,0,0,0,12,108,120,0,0,0,0,54,54,0,0,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,51,35,0,0,0,0,0,0,0,0,0.0,0.0,NaN
3,7,2023-04-22 20:12:00,4,pt-BR,NaN,4GNr9cQ99c7Jrbk,2023-04-22 18:34:00,2023-04-22 20:12:00,10.0.1.33,NaN,ORIGINAL,2023,Janeiro,NaN,"Goiânia, Goiás",Instituto de Hemoterapia de Goiânia (IHG) - Ce...,CENTRO DE HEMOTERAPIA DE GOIÂNIA,3.341398e+12,Unidade de Coleta e Transfusão,Privado-SUS,Único serviço,NaN,NaN,NaN,189.0,16.0,410.0,37.0,0.0,0.0,350.0,38.0,153.0,5.0,96.0,10.0,348.0,23.0,251.0,30.0,7.0,0.0,172.0,12.0,420.0,41.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,21.0,29.0,50.0,1.0,4.0,1.0,16.0,572.0,5.0,NaN,583.0,0.0,583.0,0.0,583.0,3.0,583.0,0.0,583.0,5.0,583.0,0.0,583.0,0.0,0.0,0.0,583.0,1.0,583.0,0.0,583.0,0.0,192,85,64,34,15,14,237,112,37,14,5,5,1,1,32,7,75,0,1,8,75,0,0,0,583.0,583.0,6.0,0.0,NaN,2,0,0,570,0,0,0,0,0,570,67,0,0,0,0,312,47,0,0,0,0,0,0,0,83,0,0,0,0,0,0,0,2,0,0,281,0,0,83,0,8,23,0,0,0,2,49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,52,0,0,0,0,36,351,0,0,0,0,0,136,0,0,0,0,0,0,0,0,28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,13,7,147,37,0,0,0,0,0,0,0,0.0,0.0,NaN
4,8,2023-05-09 09:11:08,4,pt-BR,7.651788e+08,CIYBY7ylc1zXzre,2023-05-09 08:43:08,2023-05-09 09:11:08,10.0.0.47,NaN,ORIGINAL,2023,Abril,NaN,"Goiânia, Goiás",Santa Casa de Misericódia de Goiania - Santa C...,NaN,1.619790e+12,Unidade de Coleta e Transfusão,Privado-SUS,Único serviço,NaN,NaN,NaN,239.0,112.0,0.0,0.0,0.0,0.0,185.0,98.0,24.0,7.0,39.0,10.0,174.0,61.0,74.0,54.0,3.0,0.0,77.0,30.0,168.0,85.0,12.0,24.0,36.0,12.0,6.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,22.0,54.0,4.0,0.0,3.0,1.0,248.0,0.0,NaN,258.0,0.0,258.0,0.0,258.0,3.0,258.0,0.0,258.0,4.0,258.0,1.0,258.0,0.0,0.0,0.0,258.0,0.0,258.0,0.0,258.0,0.0,79,32,27,23,10,2,103,48,14,3,4,0,0,0,21,9,0,0,1,1,0,0,0,1,3.0,258.0,11.0,0.0,NaN,0,0,0,250,0,0,0,0,0,250,0,0,0,0,0,114,22,0,0,0,0,0,0,0,49,0,0,0,0,0,0,0,0,0,0,5,0,0,105,0,0,12,0,0,0,0,0,20,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0,0,39,39,0,0,0,24,167,191,0,0,0,0,98,0,0,0,0,0,0,0,0,39,39,0,0,0,0,0,0,0,39,39,0,0,0,0,191,191,0,0,0,0,98,98,0,0,0,0,0,0,0,39,39,0,0,0,0,0,9,24,0,0,0,0,0,0,0,0,0.0,0.0,NaN
5,9,2023-05-11 09:12:10,4,pt-BR,1.511861e+09,do26zwKaqbdfirs,2023-05-11 08:39:15,2023-05-11 09:12:10,10.0.0.30,NaN,ORIGINAL,2023,Abril,NaN,"Goiânia, Goiás",Instituto Goiano de Oncologia e Hemoterapia - ...,NaN,1.277573e+12,Unidade de Coleta e Transfusão,Privado,Único serviço,NaN,NaN,NaN,393.0,21.0,984.0,49.0,0.0,0.0,567.0,32.0,810.0,29.0,0.0,0.0,801.0,26.0,576.0,35.0,9.0,0.0,524.0,22.0,844.0,39.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,29.0,53.0,0.0,10.0,0.0,70.0,1343.0,33.0,NaN,1375.0,0.0,1375.0,4.0,1375.0,28.0,1375.0,1.0,1375.0,17.0,1375.0,2.0,1375.0,1.0,1375.0,0.0,1375.0,1.0,1375.0,1.0,1375.0,2.0,455,189,143,76,42,14,534,288,81,31,18,7,4,4,97,8,201,31,1,6,17,0,0,0,14.0,1381.0,58.0,2.0,NaN,48,0,0,1279,0,0,0,0,0,1401,8,0,0,0,0,587,0,0,0,0,0,0,0,0,123,0,0,0,0,0,1,0,45,17,0,1013,0,0,0,8,20,81,0,0,0,0,172,20,0,0,0,0,0,0,3,2,3,0,0,0,0,0,0,2,256,258,0,0,0,75,1206,1281,0,0,0,22,322,344,0,0,0,0,0,0,0,63,63,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,6,20,0,0,0,0,0,0,0,0,0,0,0,0,20,87,41,469,178,0,0,1,0,0,0,0,0.0,0.0,NaN

In [97]:
hemoprod_go_deduplicado.to_excel('dados_processados/hemoprod_go.xlsx', index=False)

## Hemoprod Hemominas

In [98]:
import os
import pandas as pd

dados_brutos_path = 'dados_brutos'

arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_Hemominas.xlsx')
nome_planilha = 'HEMOPROD - HEMOMINAS'

dicionario_path_hm = ('./dicionario_colunas_269.xlsx')
# dicionario_path_ap = ('./dicionario_colunas_270.xlsx')

dicionario_hm = pd.read_excel(dicionario_path_hm, sheet_name='Sheet1')

# --- 2. Carregue os dados e o dicionário ---
try:
    # Carrega o arquivo de dados
    hemoprod_hm = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)
    print("Arquivo de dados carregado com sucesso.")
    print(f"Número de colunas original: {len(hemoprod_hm.columns)}")

    # Carrega o arquivo de dicionário
    dicionario = pd.read_excel(dicionario_path_hm)
    print("Arquivo de dicionário carregado com sucesso.")

    # --- 3. Extraia a lista de novos nomes ---
    # Pega os valores da coluna 'nome_sql' e converte para uma lista
    novos_nomes = dicionario['nome_sql'].tolist()
    print(f"Número de novos nomes no dicionário: {len(novos_nomes)}")

    # --- 4. Verificação de segurança (MUITO IMPORTANTE) ---
    # Garante que o número de colunas é o mesmo antes de renomear
    if len(hemoprod_hm.columns) == len(novos_nomes):
        print("\nO número de colunas corresponde. Renomeando...")
        
        # --- 5. Substitua os nomes das colunas ---
        # Esta é a linha principal que faz a substituição direta
        hemoprod_hm.columns = novos_nomes
        
        print("Colunas renomeadas com sucesso!")
        
        # --- 6. Verifique o resultado ---
        print("\nInformações do DataFrame com as novas colunas:")
        hemoprod_hm.info()
        
        print("\nAs 5 primeiras linhas com as novas colunas:")
        display(hemoprod_hm.head())

    else:
        # Mensagem de erro se o número de colunas for diferente
        print("\n--- ERRO ---")
        print("A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.")
        print(f"Colunas no arquivo de dados: {len(hemoprod_hm.columns)}")
        print(f"Nomes no dicionário: {len(novos_nomes)}")

except FileNotFoundError as e:
    print(f"\nErro de arquivo não encontrado: {e}")
except KeyError as e:
    print(f"\nErro de coluna não encontrada: {e}. Verifique se a coluna 'nome_sql' existe no seu arquivo de dicionário.")
except Exception as e:
    print(f"\nOcorreu um erro inesperado: {e}")

Arquivo de dados carregado com sucesso.
Número de colunas original: 270
Arquivo de dicionário carregado com sucesso.
Número de novos nomes no dicionário: 269

--- ERRO ---
A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.
Colunas no arquivo de dados: 270
Nomes no dicionário: 269

In [99]:
arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_CE.xlsx')
nome_planilha = 'Planilha1'
hemoprod_ce1 = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)

colunas_padrao = set(hemoprod_ce1.columns)
colunas_estado = set(hemoprod_hm.columns)

colunas_faltantes = list(colunas_padrao - colunas_estado)

colunas_a_mais = list(colunas_estado - colunas_padrao)

print(f"Número de colunas faltantes: {len(colunas_faltantes)}")
print(f"Colunas faltantes (a serem adicionadas): {colunas_faltantes}")
print("-" * 30)
print(f"Número de colunas a mais: {len(colunas_a_mais)}")
print(f"Colunas a mais (a serem dropadas): {colunas_a_mais}")

Número de colunas faltantes: 0
Colunas faltantes (a serem adicionadas): []
------------------------------
Número de colunas a mais: 1
Colunas a mais (a serem dropadas): ['Município [Outros]']

In [100]:

print("\n--- INICIANDO DROP E ADIÇÃO ---")

# 2.1. DROP das colunas A MAIS restantes
if colunas_a_mais:
    # Observe que COLUNA_ERRADA não está mais aqui
    hemoprod_hm = hemoprod_hm.drop(columns=colunas_a_mais, errors='ignore')
    print(f"Colunas a mais (restantes) removidas: {colunas_a_mais}")
else:
    print("Nenhuma coluna a mais restante para remover.")


# 2.2. ADICIONAR as colunas FALTANTES restantes e preenchê-las com zero (0)
# A coluna COLUNA_CORRETA também não está mais aqui
colunas_de_texto_para_vazias = ['Os dados informados referem-se à um(a):'] # Adicione outras colunas de texto aqui, se houver

for coluna in colunas_faltantes:
    if coluna in colunas_de_texto_para_vazias:
        # Cria a nova coluna preenchida com valor ausente (pd.NA)
        hemoprod_hm[coluna] = pd.NA
    else:
        # Cria a nova coluna preenchida com 0
        hemoprod_hm[coluna] = 0

print(f"Colunas faltantes (restantes) adicionadas: {colunas_faltantes}")


# 3. REORDENAR as colunas do hemoprod_hm na mesma ordem do padrão
ordem_padrao = hemoprod_ce1.columns.tolist()

# Reorganiza as colunas do hemoprod_hm
hemoprod_hm = hemoprod_hm[ordem_padrao]

print("-" * 50)
print("Processo concluído:")
print(f"Total de colunas após o ajuste: {len(hemoprod_hm.columns)}")
print("A ordem das colunas agora corresponde à ordem do hemoprod_ce1.")

--- INICIANDO DROP E ADIÇÃO ---
Colunas a mais (restantes) removidas: ['Município [Outros]']
Colunas faltantes (restantes) adicionadas: []
--------------------------------------------------
Processo concluído:
Total de colunas após o ajuste: 269
A ordem das colunas agora corresponde à ordem do hemoprod_ce1.

In [101]:
 # Carrega o arquivo de dicionário
dicionario = pd.read_excel(dicionario_path_hm)
print("Arquivo de dicionário carregado com sucesso.")

# --- 3. Extraia a lista de novos nomes ---
# Pega os valores da coluna 'nome_sql' e converte para uma lista
novos_nomes = dicionario['nome_sql'].tolist()
print(f"Número de novos nomes no dicionário: {len(novos_nomes)}")

# --- 4. Verificação de segurança (MUITO IMPORTANTE) ---
# Garante que o número de colunas é o mesmo antes de renomear
if len(hemoprod_hm.columns) == len(novos_nomes):
    print("\nO número de colunas corresponde. Renomeando...")
    
    # --- 5. Substitua os nomes das colunas ---
    # Esta é a linha principal que faz a substituição direta
    hemoprod_hm.columns = novos_nomes
    
    print("Colunas renomeadas com sucesso!")
    
    # --- 6. Verifique o resultado ---
    print("\nInformações do DataFrame com as novas colunas:")
    hemoprod_hm.info()
    
    print("\nAs 5 primeiras linhas com as novas colunas:")
    display(hemoprod_hm.head())

else:
    # Mensagem de erro se o número de colunas for diferente
    print("\n--- ERRO ---")
    print("A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.")
    print(f"Colunas no arquivo de dados: {len(hemoprod_hm.columns)}")
    print(f"Nomes no dicionário: {len(novos_nomes)}")

Arquivo de dicionário carregado com sucesso.
Número de novos nomes no dicionário: 269

O número de colunas corresponde. Renomeando...
Colunas renomeadas com sucesso!

Informações do DataFrame com as novas colunas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Columns: 269 entries, id to hemoprod_3_observacoes
dtypes: float64(26), int64(231), object(12)
memory usage: 1.9+ MB

As 5 primeiras linhas com as novas colunas:

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Janeiro,B3013,"BELO HORIZONTE, MG",HEMOCENTRO DE BELO HORIZONTE ...,'HEMOCENTRO DE BELO HORIZONTE' ...,,Hemocentro Coordenador,Público,Único serviço,NaN,4034325,"ALAMEDA EZEQUIEL DIAS, 321 - SANTA EFIGENIA ...",1676,384,1064,239,0,0,549,249,1166,150,1025,224,1428,275,1312,348,44,15,923,247,1773,361,3,55,58,9,7,16,2,8,10,2,0,2,92,64,156,2,0,2,1,1,2,0,0,0,14,5,19,150,208,358,3,0,0,7,2647,84,NaN,2710,5,2710,2,2710,15,2710,1,2710,9,2710,6,2710,1,0,0,2710,0,2710,0,2710,0,761,254,283,84,76,27,1168,329,121,44,40,13,9,7,255,48,425,1,2713,830,57,120,0,203,845,2710,38,0,NaN,49,0,0,2543,1435,118,0,0,0,2665,9202,369,2458,3853,174,69,3938,0,NaN,NaN,NaN,2448,0,434,245,563,0,0,0,0,0,0,98,208,1,7995,0,0,0,7,2,482,6,2,285,0,2,64,NaN,NaN,NaN,316,94,1916,21,0,20,0,0,0,0,0,0,5,0,5,0,0,0,255,0,255,0,0,0,1,0,1,NaN,NaN,NaN,34,0,34,0,0,0,0,0,0,0,0,0,2115,8,2123,0,0,0,6783,251,7034,3507,98,3605,154,0,154,NaN,NaN,NaN,8000,13,8013,824,0,824,0,0,0,0,863,0,2083,946,0,0,0,0,0,0,0,0,0,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Janeiro,B3192,"PATOS DE MINAS, MG",HEMOMINAS PATOS DE MINAS ...,'HEMOCENTRO DE BELO HORIZONTE' ...,19.904.440/0001-00,Núcleo de Hemoterapia,Público,Único serviço,NaN,2191415,"RUA MAJOR GOTE, 1255 - CENTRO ...",380,76,198,40,0,0,113,36,290,40,175,40,312,34,266,82,10,3,190,46,378,67,0,32,32,0,0,0,0,0,0,0,0,0,5,6,11,0,0,0,0,0,0,0,0,0,3,0,3,26,44,70,0,0,0,0,578,0,NaN,576,0,576,0,576,0,576,0,576,1,576,1,576,0,0,0,576,0,576,0,576,0,187,73,35,41,15,10,240,124,25,19,6,5,2,0,66,20,99,0,576,265,14,0,0,3,136,576,2,0,NaN,2,0,0,416,108,3,157,0,0,576,593,39,573,508,36,216,117,0,NaN,NaN,NaN,0,0,0,0,48,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,0,0,8,0,0,28,NaN,NaN,NaN,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,20,0,20,0,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,87,43,130,0,0,0,298,344,642,291,268,559,49,39,88,NaN,NaN,NaN,15,10,25,47,0,47,0,0,0,0,0,1,0,17,0,0,0,0,0,0,0,0,0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Janeiro,B3193,"DIAMANTINA, MG",HEMONUCLEO DE DIAMANTINA ...,'HEMOCENTRO DE BELO HORIZONTE' ...,03.129.874/0001-31,Núcleo de Hemoterapia,Público,Único serviço,NaN,2761327,"RUA RUA DA GLORIA, 469, FUNDOS - CENTRO ...",79,25,148,44,0,0,72,23,90,21,65,25,124,35,103,34,4,3,73,26,150,40,0,4,4,1,1,2,1,1,2,0,0,0,13,6,19,0,0,0,0,0,0,0,0,0,0,0,0,20,22,42,0,0,0,5,222,0,NaN,222,0,222,0,222,2,222,0,222,2,222,0,222,0,0,0,222,0,222,0,222,0,63,46,20,19,5,3,99,46,5,11,2,0,1,0,27,16,35,0,222,141,4,0,0,0,77,222,4,0,NaN,4,0,0,218,21,0,0,0,0,218,265,94,0,1,2,103,108,3,NaN,NaN,NaN,0,0,0,34,31,0,0,0,0,0,0,4,0,0,168,0,0,12,0,0,20,0,0,0,0,2,48,NaN,NaN,NaN,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,5,0,5,0,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,9,6,15,0,0,0,145,116,261,0,2,2,16,64,80,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,21,7,0,0,0,0,0,0,0,0,0,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Janeiro,B3194,"POUSO ALEGRE, MG",HEMOMINAS POUSO ALEGRE ...,'HEMOCENTRO DE BELO HORIZONTE' ...,,Hemocentro Regional,Público,Único serviço,NaN,2761416,"RUA COMENDADOR JOSE GARCIA, 825 - CENTRO ...",350,115,919,307,0,0,312,222,467,75,490,125,744,231,525,191,13,12,387,157,869,253,3,13,16,4,0,4,0,1,1,7,0,7,65,37,102,1,1,2,0,0,0,0,0,0,1,2,3,150,137,287,4,0,0,3,1262,0,NaN,1254,1,1254,1,1254,11,1254,0,1254,6,1254,2,1254,1,0,0,1254,0,1254,1,1254,1,369,30,102,15,33,1,559,37,65,9,18,2,3,0,107,5,189,0,1256,90,13,0,0,8,356,1254,20,0,NaN,32,0,0,1204,277,10,0,0,0,1230,2502,101,1195,2285,87,1195,2181,95,NaN,NaN,NaN,0,0,0,0,132,8,0,0,0,0,0,0,0,0,13,0,0,0,0,0,41,0,0,31,0,25,698,NaN,NaN,NaN,0,0,0,0,0,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,135,0,135,0,0,0,1228,121,1349,1073,117,1190,473,35,508,NaN,NaN,NaN,0,0,0,9,0,9,0,0,0,0,0,0,37,23,0,0,0,0,0,0,0,0,0,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Janeiro,B3195,"MONTES CLAROS, MG",HEMOMINAS MONTES CLAROS ...,'HEMOCENTRO DE BELO HORIZONTE' ...,17.217.985/0034-72,Hemocentro Regional,Público,Único serviço,NaN,2218933,"RUA URBINO VIANA, 640 - VILA GUILHERMINA ...",442,108,775,184,0,0,279,126,525,74,413,92,631,132,586,160,19,2,433,132,765,158,6,27,33,3,4,7,0,0,0,0,0,0,47,30,77,0,1,1,0,1,1,2,3,5,0,1,1,74,93,167,3,0,0,8,1196,13,NaN,1202,4,1202,1,1202,10,1202,0,1202,5,1202,4,1202,0,0,0,1202,0,1202,0,1202,1,349,29,93,12,21,2,593,53,48,0,14,0,5,0,81,5,149,0,1204,101,20,0,0,0,330,1202,22,0,NaN,17,0,0,1150,523,4,1,0,0,1191,1286,25,597,577,10,1142,1057,24,NaN,NaN,NaN,0,0,0,116,116,1,0,0,0,0,0,16,10,0,738,0,0,1,0,2,82,0,1,37,2,1,497,NaN,NaN,NaN,0,0,0,1,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,192,0,192,0,0,0,1160,0,1160,482,0,482,528,0,528,NaN,NaN,NaN,16,0,16,170,0,170,0,0,0,0,0,0,57,0,0,0,0,0,0,0,0,0,0,NaN

In [102]:
# --- 2. Defina as colunas para a chave e para ordenação ---
registros_antes = len(hemoprod_hm)
print(f"Total de registros ANTES da remoção de duplicatas: {registros_antes}")
    

colunas_chave = [
        'cnpj', 
        'ano_referencia', 
        'periodo_referencia', 
        'razao_social_nome_fantasia'
    ]

coluna_data = 'data_envio'

# --- 3. Verifique se as colunas necessárias existem ---
colunas_necessarias = colunas_chave + [coluna_data]

if not all(col in hemoprod_hm.columns for col in colunas_necessarias):
    print("\n--- ERRO ---")
    print("Uma ou mais colunas necessárias para a deduplicação não foram encontradas.")
    colunas_faltantes = [col for col in colunas_necessarias if col not in hemoprod_hm.columns]
    print(f"Colunas necessárias: {colunas_necessarias}")
    print(f"Colunas faltantes no DataFrame: {colunas_faltantes}")
else:
    # --- 4. Prepare a coluna de data e ordene os dados ---
    # Converte a coluna 'data_envio' para datetime para garantir a ordenação correta.
    # 'errors='coerce'' transformará datas inválidas em NaT (Not a Time), que são tratadas como nulas.
    hemoprod_hm[coluna_data] = pd.to_datetime(hemoprod_hm[coluna_data], errors='coerce')

    # Ordena o DataFrame. Os registros com data de envio mais recente ficarão por último.
    print(f"\nOrdenando os dados por '{coluna_data}'...")
    hemoprod_hm_ordenado = hemoprod_hm.sort_values(by=coluna_data, ascending=True)

    # --- 5. Identifique e separe os registros duplicados e únicos ---
    # Em vez de usar drop_duplicates() diretamente, vamos usar duplicated()
    # para criar uma máscara booleana.
    # 'keep='last'' marca todas as ocorrências de uma chave como True, EXCETO a última (a mais recente).
    print(f"Identificando duplicatas com cese na chave: {colunas_chave}...")
    mascara_duplicatas = hemoprod_hm_ordenado.duplicated(subset=colunas_chave, keep='last')

    # O DataFrame de removidos conterá todas as linhas marcadas como True
    hemoprod_removidos = hemoprod_hm_ordenado[mascara_duplicatas]
    
    # O DataFrame deduplicado conterá o INVERSO (~) da máscara (linhas marcadas como False)
    hemoprod_hm_deduplicado = hemoprod_hm_ordenado[~mascara_duplicatas]
    
    # Agora podemos contar os registros diretamente dos novos DataFrames
    registros_depois = len(hemoprod_hm_deduplicado)
    registros_removidos = len(hemoprod_removidos) 
    
    # --- 6. Exice o resultado ---
    print("\n--- Processo Concluído ---")
    print(f"Registros removidos: {registros_removidos}")
    print(f"Total de registros DEPOIS da remoção de duplicatas: {registros_depois}")

    # (Opcional) Exibe a amostra dos removidos
    print("\nAmostra dos dados REMOVIDOS (os mais antigos/duplicados):")
    display(hemoprod_removidos.head(10))

    # Você pode continuar a usar o DataFrame 'hemoprod_ce_deduplicado' para suas análises
    print("\nAmostra dos dados únicos (os mais recentes para cada chave):")
    display(hemoprod_hm_deduplicado.head(10))
    
    # Agora você tem o DataFrame 'hemoprod_removidos' salvo

Total de registros ANTES da remoção de duplicatas: 930

Ordenando os dados por 'data_envio'...
Identificando duplicatas com cese na chave: ['cnpj', 'ano_referencia', 'periodo_referencia', 'razao_social_nome_fantasia']...

--- Processo Concluído ---
Registros removidos: 0
Total de registros DEPOIS da remoção de duplicatas: 930

Amostra dos dados REMOVIDOS (os mais antigos/duplicados):

Empty DataFrame
Columns: [id, data_envio, ultima_pagina, idioma_inicial, semente, codigo_acesso, data_inicio, data_ultima_acao, ip, identificacao_dado, tipo_envio, ano_referencia, periodo_referencia, identificacao_estabelecimento, municipio, razao_social_nome_fantasia, razao_social_nome_fantasia_outros, cnpj, tipo_estabelecimento, natureza_estabelecimento, dados_informados_referem_se, rede_estabelecimento, cnes, endereco, triagem_clinica_total_doacao_espontanea_aptos, triagem_clinica_total_doacao_espontanea_inaptos, triagem_clinica_total_doacao_reposicao_aptos, triagem_clinica_total_doacao_reposicao_inaptos, triagem_clinica_total_doacao_autologa_aptos, triagem_clinica_total_doacao_autologa_inaptos, total_doador_primeira_vez_aptos, total_doador_primeira_vez_inaptos, total_doador_repeticao_aptos, total_doador_repeticao_inaptos, total_doador_esporadico_aptos, total_doador_esporadico_inaptos, total_doador_masculino_aptos, total_doador_masculino_inaptos, total_doador_feminino_aptos, total_doador_feminino_inaptos, total_doador_menor_de_18_anos_aptos, total_doador_menor_de_18_anos_inaptos, total_doador_18_ate_29_anos_aptos, total_doador_18_ate_29_anos_inaptos, total_doador_acima_de_29_anos_aptos, total_doador_acima_de_29_anos_inaptos, total_candidatos_inaptos_anemia_masculino, total_candidatos_inaptos_anemia_feminino, total_candidatos_inaptos_anemia_total, total_candidatos_inaptos_hipertensao_masculino, total_candidatos_inaptos_hipertensao_feminino, total_candidatos_inaptos_hipertensao_total, total_candidatos_inaptos_hipotensao_masculino, total_candidatos_inaptos_hipotensao_feminino, total_candidatos_inaptos_hipotensao_total, total_candidatos_inaptos_alcoolismo_masculino, total_candidatos_inaptos_alcoolismo_feminino, total_candidatos_inaptos_alcoolismo_total, total_candidatos_inaptos_comportamento_risco_dst_masculino, total_candidatos_inaptos_comportamento_risco_dst_feminino, total_candidatos_inaptos_comportamento_risco_dst_total, total_candidatos_inaptos_uso_drogas_masculino, total_candidatos_inaptos_uso_drogas_feminino, total_candidatos_inaptos_uso_drogas_total, total_candidatos_inaptos_hepatite_masculino, total_candidatos_inaptos_hepatite_feminino, total_candidatos_inaptos_hepatite_total, total_candidatos_inaptos_doenca_chagas_masculino, total_candidatos_inaptos_doenca_chagas_feminino, total_candidatos_inaptos_doenca_chagas_total, total_candidatos_inaptos_malaria_masculino, total_candidatos_inaptos_malaria_feminino, total_candidatos_inaptos_malaria_total, total_candidatos_inaptos_outras_masculino, total_candidatos_inaptos_outras_feminino, total_candidatos_inaptos_outras_total, coleta_total_candidatos_desistentes, total_interrupcoes_coleta_dificuldade_puncao_venosa, total_interrupcoes_coleta_reacao_vagal, total_interrupcoes_coleta_outros_motivos, total_coletas_sangue_total, total_coletas_aferese, hemoprod_1_observacoes, exames_triagem_doenca_doenca_chagas_amostras_testadas, exames_triagem_doenca_doenca_chagas_amostras_reagentes, exames_triagem_doenca_hiv_amostras_testadas, exames_triagem_doenca_hiv_amostras_reagentes, exames_triagem_doenca_sifilis_amostras_testadas, `exames_triagem_doenca_sifilis_amostras_reagentes, exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas, exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes, exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas, exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes, exames_triagem_doenca_hepatite_c_amostras_testadas, exames_triagem_doenca_hepatite_c_amostras_reagentes, exames_triagem_doenca_htlv_i_ii_amostras_testadas, exames_triagem_doenca_htlv_i_ii_amostras_reagentes, exames_triagem_doenca_malaria_amostras_testadas, exames_triagem_doenca_malaria_amostras_reagentes, exames_triagem_doenca_hbv_teste_nat_amostras_testadas, ...]
Index: []

Amostra dos dados únicos (os mais recentes para cada chave):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Janeiro,B3013,"BELO HORIZONTE, MG",HEMOCENTRO DE BELO HORIZONTE ...,'HEMOCENTRO DE BELO HORIZONTE' ...,,Hemocentro Coordenador,Público,Único serviço,NaN,4034325,"ALAMEDA EZEQUIEL DIAS, 321 - SANTA EFIGENIA ...",1676,384,1064,239,0,0,549,249,1166,150,1025,224,1428,275,1312,348,44,15,923,247,1773,361,3,55,58,9,7,16,2,8,10,2,0,2,92,64,156,2,0,2,1,1,2,0,0,0,14,5,19,150,208,358,3,0,0,7,2647,84,NaN,2710,5,2710,2,2710,15,2710,1,2710,9,2710,6,2710,1,0,0,2710,0,2710,0,2710,0,761,254,283,84,76,27,1168,329,121,44,40,13,9,7,255,48,425,1,2713,830,57,120,0,203,845,2710,38,0,NaN,49,0,0,2543,1435,118,0,0,0,2665,9202,369,2458,3853,174,69,3938,0,NaN,NaN,NaN,2448,0,434,245,563,0,0,0,0,0,0,98,208,1,7995,0,0,0,7,2,482,6,2,285,0,2,64,NaN,NaN,NaN,316,94,1916,21,0,20,0,0,0,0,0,0,5,0,5,0,0,0,255,0,255,0,0,0,1,0,1,NaN,NaN,NaN,34,0,34,0,0,0,0,0,0,0,0,0,2115,8,2123,0,0,0,6783,251,7034,3507,98,3605,154,0,154,NaN,NaN,NaN,8000,13,8013,824,0,824,0,0,0,0,863,0,2083,946,0,0,0,0,0,0,0,0,0,NaN
1,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Janeiro,B3192,"PATOS DE MINAS, MG",HEMOMINAS PATOS DE MINAS ...,'HEMOCENTRO DE BELO HORIZONTE' ...,19.904.440/0001-00,Núcleo de Hemoterapia,Público,Único serviço,NaN,2191415,"RUA MAJOR GOTE, 1255 - CENTRO ...",380,76,198,40,0,0,113,36,290,40,175,40,312,34,266,82,10,3,190,46,378,67,0,32,32,0,0,0,0,0,0,0,0,0,5,6,11,0,0,0,0,0,0,0,0,0,3,0,3,26,44,70,0,0,0,0,578,0,NaN,576,0,576,0,576,0,576,0,576,1,576,1,576,0,0,0,576,0,576,0,576,0,187,73,35,41,15,10,240,124,25,19,6,5,2,0,66,20,99,0,576,265,14,0,0,3,136,576,2,0,NaN,2,0,0,416,108,3,157,0,0,576,593,39,573,508,36,216,117,0,NaN,NaN,NaN,0,0,0,0,48,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,0,0,8,0,0,28,NaN,NaN,NaN,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,20,0,20,0,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,87,43,130,0,0,0,298,344,642,291,268,559,49,39,88,NaN,NaN,NaN,15,10,25,47,0,47,0,0,0,0,0,1,0,17,0,0,0,0,0,0,0,0,0,NaN
2,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Janeiro,B3193,"DIAMANTINA, MG",HEMONUCLEO DE DIAMANTINA ...,'HEMOCENTRO DE BELO HORIZONTE' ...,03.129.874/0001-31,Núcleo de Hemoterapia,Público,Único serviço,NaN,2761327,"RUA RUA DA GLORIA, 469, FUNDOS - CENTRO ...",79,25,148,44,0,0,72,23,90,21,65,25,124,35,103,34,4,3,73,26,150,40,0,4,4,1,1,2,1,1,2,0,0,0,13,6,19,0,0,0,0,0,0,0,0,0,0,0,0,20,22,42,0,0,0,5,222,0,NaN,222,0,222,0,222,2,222,0,222,2,222,0,222,0,0,0,222,0,222,0,222,0,63,46,20,19,5,3,99,46,5,11,2,0,1,0,27,16,35,0,222,141,4,0,0,0,77,222,4,0,NaN,4,0,0,218,21,0,0,0,0,218,265,94,0,1,2,103,108,3,NaN,NaN,NaN,0,0,0,34,31,0,0,0,0,0,0,4,0,0,168,0,0,12,0,0,20,0,0,0,0,2,48,NaN,NaN,NaN,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,5,0,5,0,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,9,6,15,0,0,0,145,116,261,0,2,2,16,64,80,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,21,7,0,0,0,0,0,0,0,0,0,NaN
3,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Janeiro,B3194,"POUSO ALEGRE, MG",HEMOMINAS POUSO ALEGRE ...,'HEMOCENTRO DE BELO HORIZONTE' ...,,Hemocentro Regional,Público,Único serviço,NaN,2761416,"RUA COMENDADOR JOSE GARCIA, 825 - CENTRO ...",350,115,919,307,0,0,312,222,467,75,490,125,744,231,525,191,13,12,387,157,869,253,3,13,16,4,0,4,0,1,1,7,0,7,65,37,102,1,1,2,0,0,0,0,0,0,1,2,3,150,137,287,4,0,0,3,1262,0,NaN,1254,1,1254,1,1254,11,1254,0,1254,6,1254,2,1254,1,0,0,1254,0,1254,1,1254,1,369,30,102,15,33,1,559,37,65,9,18,2,3,0,107,5,189,0,1256,90,13,0,0,8,356,1254,20,0,NaN,32,0,0,1204,277,10,0,0,0,1230,2502,101,1195,2285,87,1195,2181,95,NaN,NaN,NaN,0,0,0,0,132,8,0,0,0,0,0,0,0,0,13,0,0,0,0,0,41,0,0,31,0,25,698,NaN,NaN,NaN,0,0,0,0,0,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,135,0,135,0,0,0,1228,121,1349,1073,117,1190,473,35,508,NaN,NaN,NaN,0,0,0,9,0,9,0,0,0,0,0,0,37,23,0,0,0,0,0,0,0,0,0,NaN
4,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Janeiro,B3195,"MONTES CLAROS, MG",HEMOMINAS MONTES CLAROS ...,'HEMOCENTRO DE BELO HORIZONTE' ...,17.217.985/0034-72,Hemocentro Regional,Público,Único serviço,NaN,2218933,"RUA URBINO VIANA, 640 - VILA GUILHERMINA ...",442,108,775,184,0,0,279,126,525,74,413,92,631,132,586,160,19,2,433,132,765,158,6,27,33,3,4,7,0,0,0,0,0,0,47,30,77,0,1,1,0,1,1,2,3,5,0,1,1,74,93,167,3,0,0,8,1196,13,NaN,1202,4,1202,1,1202,10,1202,0,1202,5,1202,4,1202,0,0,0,1202,0,1202,0,1202,1,349,29,93,12,21,2,593,53,48,0,14,0,5,0,81,5,149,0,1204,101,20,0,0,0,330,1202,22,0,NaN,17,0,0,1150,523,4,1,0,0,1191,1286,25,597,577,10,1142,1057,24,NaN,NaN,NaN,0,0,0,116,116,1,0,0,0,0,0,16,10,0,738,0,0,1,0,2,82,0,1,37,2,1,497,NaN,NaN,NaN,0,0,0,1,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,192,0,192,0,0,0,1160,0,1160,482,0,482,528,0,528,NaN,NaN,NaN,16,0,16,170,0,170,0,0,0,0,0,0,57,0,0,0,0,0,0,0,0,0,0,NaN
5,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Janeiro,B3196,"PONTE NOVA, MG",HEMOMINAS PONTE NOVA ...,'HEMOCENTRO DE BELO HORIZONTE' ...,,Hemocentro Regional,Público,Único serviço,NaN,2206641,"RUA CARLOS GOMES, 17 - ESPLANADA ...",135,25,304,52,0,0,74,22,230,26,135,29,270,31,169,46,5,0,117,31,317,46,4,27,31,0,0,0,0,0,0,0,0,0,12,3,15,0,0,0,0,0,0,0,0,0,0,0,0,15,16,31,0,0,0,13,426,0,NaN,425,2,425,2,425,3,425,0,425,1,425,0,425,0,0,0,425,0,425,0,425,0,124,88,42,27,15,4,184,81,15,7,2,5,4,0,39,15,59,0,425,224,9,0,0,1,82,425,8,0,NaN,1,0,0,424,82,2,0,0,0,424,487,127,0,15,0,307,252,0,NaN,NaN,NaN,0,0,0,197,110,0,0,0,0,0,0,1,9,0,214,0,0,0,0,2,50,0,0,0,2,8,181,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,0,12,0,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,26,52,78,0,0,0,234,328,562,5,2,7,37,43,80,NaN,NaN,NaN,0,0,0,204,0,204,0,0,0,0,0,0,44,14,0,0,0,0,0,0,0,0,0,NaN
6,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Janeiro,B3197,"GOVERNADOR VALADARES, MG",HEMOMINAS GOVERNADOR VALADARES ...,'HEMOCENTRO DE BELO HORIZONTE' ...,,Hemocentro Regional,Público,Único serviço,NaN,2118610,"RUA RUA RUI BARBOSA, 149 - CENTRO ...",234,79,361,120,0,0,137,77,302,61,156,61,311,96,284,103,12,5,217,74,366,120,3,19,22,7,2,9,0,1,1,1,0,1,19,15,34,2,0,2,0,0,0,0,0,0,2,2,4,62,64,126,0,0,0,1,594,0,NaN,588,1,588,0,588,7,588,0,588,6,588,3,588,1,0,0,588,0,588,0,588,0,169,100,59,29,9,8,268,120,26,7,10,8,4,2,46,7,87,0,591,277,6,0,0,0,161,588,18,0,NaN,5,0,0,584,21,0,0,0,0,589,830,57,209,325,26,578,510,1,NaN,NaN,NaN,0,0,0,17,17,0,0,0,0,0,0,5,1,1,860,0,0,0,4,0,97,1,0,28,1,2,364,NaN,NaN,NaN,0,0,0,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,37,0,37,0,0,0,0,0,0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,55,33,88,0,0,0,632,255,887,276,73,349,155,72,227,NaN,NaN,NaN,0,0,0,0,2,2,0,0,0,0,0,5,56,79,0,0,0,0,0,0,0,0,0,NaN

In [103]:
hemoprod_hm_deduplicado.to_excel('dados_processados/hemoprod_hm.xlsx', index=False)

## Hemoprod Maranhão

In [106]:
import os
import pandas as pd

dados_brutos_path = 'dados_brutos'

arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_MA.xlsx')
nome_planilha = 'HEMOPROD - MARANHAO'

dicionario_path_ma = ('./dicionario_colunas_269.xlsx')
# dicionario_path_ap = ('./dicionario_colunas_270.xlsx')

dicionario_ma = pd.read_excel(dicionario_path_ma, sheet_name='Sheet1')

# --- 2. Carregue os dados e o dicionário ---
try:
    # Carrega o arquivo de dados
    hemoprod_ma = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)
    print("Arquivo de dados carregado com sucesso.")
    print(f"Número de colunas original: {len(hemoprod_ma.columns)}")

    # Carrega o arquivo de dicionário
    dicionario = pd.read_excel(dicionario_path_ma)
    print("Arquivo de dicionário carregado com sucesso.")

    # --- 3. Extraia a lista de novos nomes ---
    # Pega os valores da coluna 'nome_sql' e converte para uma lista
    novos_nomes = dicionario['nome_sql'].tolist()
    print(f"Número de novos nomes no dicionário: {len(novos_nomes)}")

    # --- 4. Verificação de segurança (MUITO IMPORTANTE) ---
    # Garante que o número de colunas é o mesmo antes de renomear
    if len(hemoprod_ma.columns) == len(novos_nomes):
        print("\nO número de colunas corresponde. Renomeando...")
        
        # --- 5. Substitua os nomes das colunas ---
        # Esta é a linha principal que faz a substituição direta
        hemoprod_ma.columns = novos_nomes
        
        print("Colunas renomeadas com sucesso!")
        
        # --- 6. Verifique o resultado ---
        print("\nInformações do DataFrame com as novas colunas:")
        hemoprod_ma.info()
        
        print("\nAs 5 primeiras linhas com as novas colunas:")
        display(hemoprod_ma.head())

    else:
        # Mensagem de erro se o número de colunas for diferente
        print("\n--- ERRO ---")
        print("A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.")
        print(f"Colunas no arquivo de dados: {len(hemoprod_ma.columns)}")
        print(f"Nomes no dicionário: {len(novos_nomes)}")

except FileNotFoundError as e:
    print(f"\nErro de arquivo não encontrado: {e}")
except KeyError as e:
    print(f"\nErro de coluna não encontrada: {e}. Verifique se a coluna 'nome_sql' existe no seu arquivo de dicionário.")
except Exception as e:
    print(f"\nOcorreu um erro inesperado: {e}")

Arquivo de dados carregado com sucesso.
Número de colunas original: 269
Arquivo de dicionário carregado com sucesso.
Número de novos nomes no dicionário: 269

O número de colunas corresponde. Renomeando...
Colunas renomeadas com sucesso!

Informações do DataFrame com as novas colunas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Columns: 269 entries, id to hemoprod_3_observacoes
dtypes: float64(95), int64(160), object(14)
memory usage: 94.7+ KB

As 5 primeiras linhas com as novas colunas:

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,7,2023-04-06 16:19:00,4,pt-BR,NaN,2zW7HEkDmwFPz8b,2023-04-06 16:06:00,2023-04-06 16:19:00,10.0.1.35,NaN,ORIGINAL,2023,Março,NaN,"São Luís, Maranhão",Fujisan Centro de Hemoterapia e Hematologia do...,FUJISAN CENTRO DE HEMOTERAPIA E HEMATOLOGIA DO...,7871676000957,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,10,0,6,0,0,0,19,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,90,26,0,0,0,0,40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,0,0,0,0,0,28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,4,0,0,0,23,24,47,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
1,8,2023-04-12 15:54:00,4,pt-BR,NaN,2zW7HEkDmwFPz8b,2023-04-12 15:41:00,2023-04-12 15:54:00,10.0.0.186,NaN,ORIGINAL,2023,Janeiro,NaN,"São Luís, Maranhão",Fujisan Centro de Hemoterapia e Hematologia do...,FUJISAN CENTRO DE HEMOTERAPIA E HEMATOLOGIA DO...,7871676000957,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,11,0,2,0,2,0,13,0,1,0,0,0,0,0,2,0,1,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,43,15,0,0,0,0,40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0,0,0,0,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17,12,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
2,9,2023-04-12 16:10:00,4,pt-BR,NaN,2zW7HEkDmwFPz8b,2023-04-12 15:58:00,2023-04-12 16:10:00,10.0.35.138,NaN,ORIGINAL,2023,Fevereiro,NaN,"São Luís, Maranhão",Fujisan Centro de Hemoterapia e Hematologia do...,FUJISAN CENTRO DE HEMOTERAPIA E HEMATOLOGIA DO...,7871676000957,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,8,0,5,0,0,0,17,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,1,0,0,0,0,0,42,11,0,0,0,0,26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,0,0,0,0,0,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,6,0,0,0,30,9,39,0,0,0,6,2,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
3,10,2023-05-08 11:57:00,4,pt-BR,NaN,2zW7HEkDmwFPz8b,2023-05-08 11:49:00,2023-05-08 11:57:00,10.0.51.163,NaN,ORIGINAL,2023,Abril,NaN,"São Luís, Maranhão",Fujisan Centro de Hemoterapia e Hematologia do...,FUJISAN CENTRO DE HEMOTERAPIA E HEMATOLOGIA DO...,7871676000957,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,10,0,3,0,1,0,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,17,0,0,0,0,0,52,23,0,0,0,0,78,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,0,0,0,0,0,35,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,3,5,0,0,0,20,23,43,0,0,0,27,0,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
4,11,2023-06-05 12:01:00,4,pt-BR,NaN,2zW7HEkDmwFPz8b,2023-06-05 11:50:00,2023-06-05 12:01:00,10.0.0.182,NaN,ORIGINAL,2023,Maio,NaN,"São Luís, Maranhão",Fujisan Centro de Hemoterapia e Hematologia do...,FUJISAN CENTRO DE HEMOTERAPIA E HEMATOLOGIA DO...,7871676000957,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,7,0,6,0,0,0,26,0,2,0,1,0,0,0,2,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,1,0,0,0,0,86,19,0,0,0,0,70,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,0,0,0,0,0,24,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,12,30,42,0,0,0,14,16,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN

In [107]:
# --- 2. Defina as colunas para a chave e para ordenação ---
registros_antes = len(hemoprod_ma)
print(f"Total de registros ANTES da remoção de duplicatas: {registros_antes}")
    

colunas_chave = [
        'cnpj', 
        'ano_referencia', 
        'periodo_referencia', 
        'razao_social_nome_fantasia'
    ]

coluna_data = 'data_envio'

# --- 3. Verifique se as colunas necessárias existem ---
colunas_necessarias = colunas_chave + [coluna_data]

if not all(col in hemoprod_ma.columns for col in colunas_necessarias):
    print("\n--- ERRO ---")
    print("Uma ou mais colunas necessárias para a deduplicação não foram encontradas.")
    colunas_faltantes = [col for col in colunas_necessarias if col not in hemoprod_ma.columns]
    print(f"Colunas necessárias: {colunas_necessarias}")
    print(f"Colunas faltantes no DataFrame: {colunas_faltantes}")
else:
    # --- 4. Prepare a coluna de data e ordene os dados ---
    # Converte a coluna 'data_envio' para datetime para garantir a ordenação correta.
    # 'errors='coerce'' transformará datas inválidas em NaT (Not a Time), que são tratadas como nulas.
    hemoprod_ma[coluna_data] = pd.to_datetime(hemoprod_ma[coluna_data], errors='coerce')

    # Ordena o DataFrame. Os registros com data de envio mais recente ficarão por último.
    print(f"\nOrdenando os dados por '{coluna_data}'...")
    hemoprod_ma_ordenado = hemoprod_ma.sort_values(by=coluna_data, ascending=True)

    # --- 5. Identifique e separe os registros duplicados e únicos ---
    # Em vez de usar drop_duplicates() diretamente, vamos usar duplicated()
    # para criar uma máscara booleana.
    # 'keep='last'' marca todas as ocorrências de uma chave como True, EXCETO a última (a mais recente).
    print(f"Identificando duplicatas com cese na chave: {colunas_chave}...")
    mascara_duplicatas = hemoprod_ma_ordenado.duplicated(subset=colunas_chave, keep='last')

    # O DataFrame de removidos conterá todas as linhas marcadas como True
    hemoprod_removidos = hemoprod_ma_ordenado[mascara_duplicatas]
    
    # O DataFrame deduplicado conterá o INVERSO (~) da máscara (linhas marcadas como False)
    hemoprod_ma_deduplicado = hemoprod_ma_ordenado[~mascara_duplicatas]
    
    # Agora podemos contar os registros diretamente dos novos DataFrames
    registros_depois = len(hemoprod_ma_deduplicado)
    registros_removidos = len(hemoprod_removidos) 
    
    # --- 6. Exice o resultado ---
    print("\n--- Processo Concluído ---")
    print(f"Registros removidos: {registros_removidos}")
    print(f"Total de registros DEPOIS da remoção de duplicatas: {registros_depois}")

    # (Opcional) Exibe a amostra dos removidos
    print("\nAmostra dos dados REMOVIDOS (os mais antigos/duplicados):")
    display(hemoprod_removidos.head(10))

    # Você pode continuar a usar o DataFrame 'hemoprod_ce_deduplicado' para suas análises
    print("\nAmostra dos dados únicos (os mais recentes para cada chave):")
    display(hemoprod_ma_deduplicado.head(10))
    
    # Agora você tem o DataFrame 'hemoprod_removidos' salvo

Total de registros ANTES da remoção de duplicatas: 45

Ordenando os dados por 'data_envio'...
Identificando duplicatas com cese na chave: ['cnpj', 'ano_referencia', 'periodo_referencia', 'razao_social_nome_fantasia']...

--- Processo Concluído ---
Registros removidos: 1
Total de registros DEPOIS da remoção de duplicatas: 44

Amostra dos dados REMOVIDOS (os mais antigos/duplicados):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
28,36,2024-06-10 11:01:54,4,pt-BR,1.577533e+09,2zW7HEkDmwFPz8b,2024-06-10 10:49:44,2024-06-10 11:01:54,177.184.128.17,NaN,ORIGINAL,2024,Junho,NaN,"São Luís, Maranhão",Fujisan Centro de Hemoterapia e Hematologia do...,NaN,7871676000957,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,18,0,3,0,0,0,24,0,1,0,0,0,0,0,3,0,0,0,1,0,0,0,1,NaN,NaN,NaN,NaN,NaN,0,0,0,0,10,1,0,0,0,0,77,26,0,0,0,0,83,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,5,0,0,0,0,0,46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,4,0,0,0,38,26,64,0,0,0,15,15,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN

Amostra dos dados únicos (os mais recentes para cada chave):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,7,2023-04-06 16:19:00,4,pt-BR,NaN,2zW7HEkDmwFPz8b,2023-04-06 16:06:00,2023-04-06 16:19:00,10.0.1.35,NaN,ORIGINAL,2023,Março,NaN,"São Luís, Maranhão",Fujisan Centro de Hemoterapia e Hematologia do...,FUJISAN CENTRO DE HEMOTERAPIA E HEMATOLOGIA DO...,7871676000957,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,10,0,6,0,0,0,19,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,90,26,0,0,0,0,40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,0,0,0,0,0,28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,4,0,0,0,23,24,47,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
1,8,2023-04-12 15:54:00,4,pt-BR,NaN,2zW7HEkDmwFPz8b,2023-04-12 15:41:00,2023-04-12 15:54:00,10.0.0.186,NaN,ORIGINAL,2023,Janeiro,NaN,"São Luís, Maranhão",Fujisan Centro de Hemoterapia e Hematologia do...,FUJISAN CENTRO DE HEMOTERAPIA E HEMATOLOGIA DO...,7871676000957,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,11,0,2,0,2,0,13,0,1,0,0,0,0,0,2,0,1,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,43,15,0,0,0,0,40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0,0,0,0,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17,12,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
2,9,2023-04-12 16:10:00,4,pt-BR,NaN,2zW7HEkDmwFPz8b,2023-04-12 15:58:00,2023-04-12 16:10:00,10.0.35.138,NaN,ORIGINAL,2023,Fevereiro,NaN,"São Luís, Maranhão",Fujisan Centro de Hemoterapia e Hematologia do...,FUJISAN CENTRO DE HEMOTERAPIA E HEMATOLOGIA DO...,7871676000957,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,8,0,5,0,0,0,17,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,1,0,0,0,0,0,42,11,0,0,0,0,26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,0,0,0,0,0,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,6,0,0,0,30,9,39,0,0,0,6,2,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
3,10,2023-05-08 11:57:00,4,pt-BR,NaN,2zW7HEkDmwFPz8b,2023-05-08 11:49:00,2023-05-08 11:57:00,10.0.51.163,NaN,ORIGINAL,2023,Abril,NaN,"São Luís, Maranhão",Fujisan Centro de Hemoterapia e Hematologia do...,FUJISAN CENTRO DE HEMOTERAPIA E HEMATOLOGIA DO...,7871676000957,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,10,0,3,0,1,0,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,17,0,0,0,0,0,52,23,0,0,0,0,78,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,0,0,0,0,0,35,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,3,5,0,0,0,20,23,43,0,0,0,27,0,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
4,11,2023-06-05 12:01:00,4,pt-BR,NaN,2zW7HEkDmwFPz8b,2023-06-05 11:50:00,2023-06-05 12:01:00,10.0.0.182,NaN,ORIGINAL,2023,Maio,NaN,"São Luís, Maranhão",Fujisan Centro de Hemoterapia e Hematologia do...,FUJISAN CENTRO DE HEMOTERAPIA E HEMATOLOGIA DO...,7871676000957,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,7,0,6,0,0,0,26,0,2,0,1,0,0,0,2,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,1,0,0,0,0,86,19,0,0,0,0,70,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,0,0,0,0,0,24,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,12,30,42,0,0,0,14,16,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
5,12,2023-07-06 11:13:18,4,pt-BR,1.958977e+09,2zW7HEkDmwFPz8b,2023-07-06 11:04:36,2023-07-06 11:13:18,10.0.0.205,NaN,ORIGINAL,2023,Junho,NaN,"São Luís, Maranhão",Fujisan Centro de Hemoterapia e Hematologia do...,NaN,7871676000957,Agência Transfusional,Privado,Único serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,12,0,3,0,0,0,24,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,68,34,0,0,0,0,40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,0,0,0,0,0,34,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,4,0,0,0,21,21,42,0,0,0,6,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN

In [108]:
hemoprod_ma_deduplicado.to_excel('dados_processados/hemoprod_ma.xlsx', index=False)

## Hemoprod Minas Gerais

In [109]:
import os
import pandas as pd

dados_brutos_path = 'dados_brutos'

arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_MG.xlsx')
nome_planilha = 'HEMOPROD - MINASGERAIS'

dicionario_path_mg = ('./dicionario_colunas_269.xlsx')
# dicionario_path_ap = ('./dicionario_colunas_270.xlsx')

dicionario_mg = pd.read_excel(dicionario_path_mg, sheet_name='Sheet1')

# --- 2. Carregue os dados e o dicionário ---
try:
    # Carrega o arquivo de dados
    hemoprod_mg = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)
    print("Arquivo de dados carregado com sucesso.")
    print(f"Número de colunas original: {len(hemoprod_mg.columns)}")

    # Carrega o arquivo de dicionário
    dicionario = pd.read_excel(dicionario_path_mg)
    print("Arquivo de dicionário carregado com sucesso.")

    # --- 3. Extraia a lista de novos nomes ---
    # Pega os valores da coluna 'nome_sql' e converte para uma lista
    novos_nomes = dicionario['nome_sql'].tolist()
    print(f"Número de novos nomes no dicionário: {len(novos_nomes)}")

    # --- 4. Verificação de segurança (MUITO IMPORTANTE) ---
    # Garante que o número de colunas é o mesmo antes de renomear
    if len(hemoprod_mg.columns) == len(novos_nomes):
        print("\nO número de colunas corresponde. Renomeando...")
        
        # --- 5. Substitua os nomes das colunas ---
        # Esta é a linha principal que faz a substituição direta
        hemoprod_mg.columns = novos_nomes
        
        print("Colunas renomeadas com sucesso!")
        
        # --- 6. Verifique o resultado ---
        print("\nInformações do DataFrame com as novas colunas:")
        hemoprod_mg.info()
        
        print("\nAs 5 primeiras linhas com as novas colunas:")
        display(hemoprod_mg.head())

    else:
        # Mensagem de erro se o número de colunas for diferente
        print("\n--- ERRO ---")
        print("A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.")
        print(f"Colunas no arquivo de dados: {len(hemoprod_mg.columns)}")
        print(f"Nomes no dicionário: {len(novos_nomes)}")

except FileNotFoundError as e:
    print(f"\nErro de arquivo não encontrado: {e}")
except KeyError as e:
    print(f"\nErro de coluna não encontrada: {e}. Verifique se a coluna 'nome_sql' existe no seu arquivo de dicionário.")
except Exception as e:
    print(f"\nOcorreu um erro inesperado: {e}")

Arquivo de dados carregado com sucesso.
Número de colunas original: 270
Arquivo de dicionário carregado com sucesso.
Número de novos nomes no dicionário: 269

--- ERRO ---
A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.
Colunas no arquivo de dados: 270
Nomes no dicionário: 269

In [110]:
arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_CE.xlsx')
nome_planilha = 'Planilha1'
hemoprod_ce1 = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)

colunas_padrao = set(hemoprod_ce1.columns)
colunas_estado = set(hemoprod_mg.columns)

colunas_faltantes = list(colunas_padrao - colunas_estado)

colunas_a_mais = list(colunas_estado - colunas_padrao)

print(f"Número de colunas faltantes: {len(colunas_faltantes)}")
print(f"Colunas faltantes (a serem adicionadas): {colunas_faltantes}")
print("-" * 30)
print(f"Número de colunas a mais: {len(colunas_a_mais)}")
print(f"Colunas a mais (a serem dropadas): {colunas_a_mais}")

Número de colunas faltantes: 0
Colunas faltantes (a serem adicionadas): []
------------------------------
Número de colunas a mais: 1
Colunas a mais (a serem dropadas): ['Município [Outros]']

In [111]:

print("\n--- INICIANDO DROP E ADIÇÃO ---")

# 2.1. DROP das colunas A MAIS restantes
if colunas_a_mais:
    # Observe que COLUNA_ERRADA não está mais aqui
    hemoprod_mg = hemoprod_mg.drop(columns=colunas_a_mais, errors='ignore')
    print(f"Colunas a mais (restantes) removidas: {colunas_a_mais}")
else:
    print("Nenhuma coluna a mais restante para remover.")


# 2.2. ADICIONAR as colunas FALTANTES restantes e preenchê-las com zero (0)
# A coluna COLUNA_CORRETA também não está mais aqui
colunas_de_texto_para_vazias = ['Os dados informados referem-se à um(a):'] # Adicione outras colunas de texto aqui, se houver

for coluna in colunas_faltantes:
    if coluna in colunas_de_texto_para_vazias:
        # Cria a nova coluna preenchida com valor ausente (pd.NA)
        hemoprod_mg[coluna] = pd.NA
    else:
        # Cria a nova coluna preenchida com 0
        hemoprod_mg[coluna] = 0

print(f"Colunas faltantes (restantes) adicionadas: {colunas_faltantes}")


# 3. REORDENAR as colunas do hemoprod_mg na mesma ordem do padrão
ordem_padrao = hemoprod_ce1.columns.tolist()

# Reorganiza as colunas do hemoprod_mg
hemoprod_mg = hemoprod_mg[ordem_padrao]

print("-" * 50)
print("Processo concluído:")
print(f"Total de colunas após o ajuste: {len(hemoprod_mg.columns)}")
print("A ordem das colunas agora corresponde à ordem do hemoprod_ce1.")

--- INICIANDO DROP E ADIÇÃO ---
Colunas a mais (restantes) removidas: ['Município [Outros]']
Colunas faltantes (restantes) adicionadas: []
--------------------------------------------------
Processo concluído:
Total de colunas após o ajuste: 269
A ordem das colunas agora corresponde à ordem do hemoprod_ce1.

In [112]:
 # Carrega o arquivo de dicionário
dicionario = pd.read_excel(dicionario_path_mg)
print("Arquivo de dicionário carregado com sucesso.")

# --- 3. Extraia a lista de novos nomes ---
# Pega os valores da coluna 'nome_sql' e converte para uma lista
novos_nomes = dicionario['nome_sql'].tolist()
print(f"Número de novos nomes no dicionário: {len(novos_nomes)}")

# --- 4. Verificação de segurança (MUITO IMPORTANTE) ---
# Garante que o número de colunas é o mesmo antes de renomear
if len(hemoprod_mg.columns) == len(novos_nomes):
    print("\nO número de colunas corresponde. Renomeando...")
    
    # --- 5. Substitua os nomes das colunas ---
    # Esta é a linha principal que faz a substituição direta
    hemoprod_mg.columns = novos_nomes
    
    print("Colunas renomeadas com sucesso!")
    
    # --- 6. Verifique o resultado ---
    print("\nInformações do DataFrame com as novas colunas:")
    hemoprod_mg.info()
    
    print("\nAs 5 primeiras linhas com as novas colunas:")
    display(hemoprod_mg.head())

else:
    # Mensagem de erro se o número de colunas for diferente
    print("\n--- ERRO ---")
    print("A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.")
    print(f"Colunas no arquivo de dados: {len(hemoprod_mg.columns)}")
    print(f"Nomes no dicionário: {len(novos_nomes)}")

Arquivo de dicionário carregado com sucesso.
Número de novos nomes no dicionário: 269

O número de colunas corresponde. Renomeando...
Colunas renomeadas com sucesso!

Informações do DataFrame com as novas colunas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Columns: 269 entries, id to hemoprod_3_observacoes
dtypes: float64(92), int64(160), object(17)
memory usage: 569.7+ KB

As 5 primeiras linhas com as novas colunas:

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,5,2023-04-14 16:05:33,4,pt-BR,3.992492e+08,IvycpvVQH6KQqkP,2023-04-14 15:05:11,2023-04-14 16:05:33,10.0.113.219,NaN,ORIGINAL,2023,Março,NaN,"Belo Horizonte, Minas Gerais",Vita Hemoterapia Ltda - Vita Hemoterapia,NaN,25463423000179,Unidade de Coleta e Transfusão,Privado,Único serviço,NaN,NaN,NaN,266.0,29.0,1893.0,219.0,1.0,0.0,849.0,149.0,908.0,59.0,403.0,40.0,1131.0,135.0,1029.0,113.0,10.0,0.0,614.0,78.0,1536.0,170.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,31.0,11.0,42.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,102.0,102.0,204.0,0.0,0.0,0.0,0.0,2135.0,25.0,NaN,2157.0,0.0,2157.0,1.0,2157.0,12.0,2157.0,0.0,2157.0,6.0,2157.0,0.0,2157.0,0.0,0.0,0.0,2157.0,6.0,2157.0,0.0,2157.0,1.0,725,880,172,258,55,77,868,962,118,154,30,36,9,15,176,156,336,73,5,51,308,7,0,0,2154.0,2154.0,19.0,0.0,NaN,18,0,0,2098,87,0,0,0,0,2117,19,0,0,0,0,2113,49,0,25,0,0,0,0,0,231,4,0,0,0,0,1,0,17,1,0,1110,0,0,0,0,2,9,0,0,0,0,2,33,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,594,594,0,0,0,21,1702,1723,0,0,0,16,1703,1719,0,43,43,0,0,0,0,121,121,0,21,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1277,16,53,120,3,0,3,0,0,0,1,0.0,0.0,NaN
1,10,2023-04-18 12:22:00,4,pt-BR,NaN,MfTu2yewsNxvB7k,2023-04-18 11:29:00,2023-04-18 12:22:00,10.0.1.35,NaN,ORIGINAL,2022,Janeiro,NaN,"Alfenas, Minas Gerais",Fundação de Ensino e Tecnologia de Alfenas - H...,Hospital Universitário Alzira Velano-Banco de ...,17878554001241,Núcleo de Hemoterapia,Privado-SUS,Único serviço,NaN,NaN,NaN,49.0,10.0,186.0,27.0,0.0,0.0,47.0,17.0,98.0,11.0,90.0,9.0,144.0,13.0,91.0,24.0,0.0,0.0,61.0,19.0,174.0,18.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,3.0,2.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,21.0,31.0,0.0,0.0,0.0,0.0,235.0,0.0,NaN,235.0,0.0,235.0,0.0,235.0,1.0,235.0,0.0,235.0,0.0,235.0,0.0,235.0,0.0,235.0,0.0,235.0,0.0,235.0,0.0,235.0,0.0,82,45,21,13,9,2,84,60,12,8,3,0,1,0,23,5,39,11,0,4,0,0,0,0,235.0,235.0,1.0,0.0,NaN,7,0,0,228,0,0,0,0,0,228,0,0,0,0,0,190,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,7,0,10,160,0,0,0,2,99,14,0,0,0,0,147,20,0,0,0,0,0,0,0,8,0,0,0,0,0,0,0,0,64,64,0,0,0,0,170,170,0,0,0,0,28,28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,193,0,0,0,0,0,0,0,0,0.0,0.0,NaN
2,12,2023-04-18 12:52:00,4,pt-BR,NaN,MfTu2yewsNxvB7k,2023-04-18 12:26:00,2023-04-18 12:52:00,10.0.0.186,NaN,ORIGINAL,2022,Fevereiro,NaN,"Alfenas, Minas Gerais",Fundação de Ensino e Tecnologia de Alfenas - H...,Hospital Universitário Alzira Velano,17878554001241,Núcleo de Hemoterapia,Privado-SUS,Único serviço,NaN,NaN,NaN,50.0,13.0,249.0,68.0,0.0,0.0,68.0,46.0,111.0,13.0,120.0,22.0,191.0,38.0,108.0,43.0,0.0,0.0,82.0,38.0,217.0,43.0,0.0,2.0,2.0,3.0,0.0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,8.0,4.0,12.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.0,36.0,62.0,0.0,2.0,0.0,0.0,297.0,0.0,NaN,297.0,0.0,297.0,0.0,297.0,3.0,297.0,0.0,297.0,0.0,297.0,0.0,297.0,0.0,297.0,0.0,297.0,0.0,297.0,0.0,297.0,0.0,90,36,24,13,9,2,121,58,13,7,4,0,0,2,36,4,53,12,0,1,0,0,0,1,297.0,297.0,3.0,2.0,NaN,21,0,0,276,0,0,0,0,0,276,0,0,0,0,0,187,0,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,21,3,10,382,0,0,0,0,20,14,0,0,0,0,177,14,0,0,0,0,0,0,0,2,15,0,0,0,0,0,0,0,88,88,0,0,0,0,183,183,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,19,0,0,0,0,0,0,0,0,0.0,0.0,NaN
3,17,2023-04-26 12:27:00,4,pt-BR,NaN,MfTu2yewsNxvB7k,2023-04-26 11:49:00,2023-04-26 12:27:00,10.0.52.44,NaN,ORIGINAL,2023,Janeiro,NaN,"Alfenas, Minas Gerais",Fundação de Ensino e Tecnologia de Alfenas - H...,Hospital Universitário Alzira Velano,17878554001241,Núcleo de Hemoterapia,Privado-SUS,Único serviço,NaN,NaN,NaN,48.0,11.0,223.0,37.0,0.0,0.0,57.0,24.0,113.0,13.0,101.0,11.0,170.0,19.0,101.0,29.0,0.0,0.0,68.0,17.0,203.0,31.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,2.0,0.0,0.0,0.0,3.0,2.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,24.0,40.0,0.0,0.0,0.0,0.0,271.0,0.0,NaN,271.0,0.0,271.0,0.0,271.0,1.0,271.0,0.0,271.0,1.0,271.0,0.0,271.0,0.0,0.0,0.0,271.0,0.0,271.0,0.0,271.0,0.0,86,53,22,11,10,3,106,56,10,10,1,2,1,1,35,4,47,17,1,3,0,0,0,3,271.0,271.0,2.0,0.0,NaN,15,0,0,256,0,0,0,0,0,256,0,0,0,0,0,184,0,0,0,0,0,0,0,0,19,0,0,0,0,0,0,0,15,9,9,249,0,0,0,1,113,11,0,0,0,0,161,16,0,0,0,0,0,0,0,0,10,0,0,0,0,0,0,0,121,121,0,0,0,0,179,179,0,0,0,0,8,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,51,74,0,1,0,0,0,0,0,1,0.0,0.0,NaN
4,18,2023-04-26 13:02:01,4,pt-BR,1.780040e+09,MfTu2yewsNxvB7k,2023-04-26 12:32:51,2023-04-26 13:02:01,10.0.52.19,NaN,ORIGINAL,2023,Fevereiro,NaN,"Alfenas, Minas Gerais",Fundação de Ensino e Tecnologia de Alfenas - H...,NaN,17878554001241,Núcleo de Hemoterapia,Privado-SUS,Único serviço,NaN,NaN,NaN,44.0,7.0,242.0,45.0,0.0,0.0,59.0,19.0,124.0,10.0,103.0,23.0,149.0,20.0,137.0,32.0,0.0,0.0,80.0,16.0,206.0,36.0,0.0,0.0,0.0,2.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,30.0,44.0,2.0,0.0,0.0,0.0,284.0,0.0,NaN,284.0,0.0,284.0,0.0,284.0,2.0,284.0,0.0,284.0,0.0,284.0,0.0,284.0,0.0,0.0,0.0,284.0,0.0,284.0,0.0,284.0,0.0,92,35,12,18,4,5,111,55,10,7,5,1,3,3,47,3,65,13,0,0,0,0,0,1,284.0,284.0,2.0,0.0,NaN,11,0,0,273,0,0,0,0,0,273,0,0,0,0,0,193,0,0,0,0,0,0,0,0,23,0,0,0,0,0,1,0,10,1,8,182,0,0,0,1,37,19,0,0,0,0,152,24,0,0,0,0,0,0,1,2,2,0,0,0,0,0,0,0,70,0,0,0,0,0,155,0,0,0,0,0,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,0,0,0,0,0,0,0,0,0.0,0.0,NaN

In [113]:
    # --- 2. Defina as colunas para a chave e para ordenação ---
registros_antes = len(hemoprod_mg)
print(f"Total de registros ANTES da remoção de duplicatas: {registros_antes}")
    

colunas_chave = [
        'cnpj', 
        'ano_referencia', 
        'periodo_referencia', 
        'razao_social_nome_fantasia'
    ]

coluna_data = 'data_envio'

# --- 3. Verifique se as colunas necessárias existem ---
colunas_necessarias = colunas_chave + [coluna_data]

if not all(col in hemoprod_mg.columns for col in colunas_necessarias):
    print("\n--- ERRO ---")
    print("Uma ou mais colunas necessárias para a deduplicação não foram encontradas.")
    colunas_faltantes = [col for col in colunas_necessarias if col not in hemoprod_mg.columns]
    print(f"Colunas necessárias: {colunas_necessarias}")
    print(f"Colunas faltantes no DataFrame: {colunas_faltantes}")
else:
    # --- 4. Prepare a coluna de data e ordene os dados ---
    # Converte a coluna 'data_envio' para datetime para garantir a ordenação correta.
    # 'errors='coerce'' transformará datas inválidas em NaT (Not a Time), que são tratadas como nulas.
    hemoprod_mg[coluna_data] = pd.to_datetime(hemoprod_mg[coluna_data], errors='coerce')

    # Ordena o DataFrame. Os registros com data de envio mais recente ficarão por último.
    print(f"\nOrdenando os dados por '{coluna_data}'...")
    hemoprod_mg_ordenado = hemoprod_mg.sort_values(by=coluna_data, ascending=True)

    # --- 5. Identifique e separe os registros duplicados e únicos ---
    # Em vez de usar drop_duplicates() diretamente, vamos usar duplicated()
    # para criar uma máscara booleana.
    # 'keep='last'' marca todas as ocorrências de uma chave como True, EXCETO a última (a mais recente).
    print(f"Identificando duplicatas com cese na chave: {colunas_chave}...")
    mascara_duplicatas = hemoprod_mg_ordenado.duplicated(subset=colunas_chave, keep='last')

    # O DataFrame de removidos conterá todas as linhas marcadas como True
    hemoprod_removidos = hemoprod_mg_ordenado[mascara_duplicatas]
    
    # O DataFrame deduplicado conterá o INVERSO (~) da máscara (linhas marcadas como False)
    hemoprod_mg_deduplicado = hemoprod_mg_ordenado[~mascara_duplicatas]
    
    # Agora podemos contar os registros diretamente dos novos DataFrames
    registros_depois = len(hemoprod_mg_deduplicado)
    registros_removidos = len(hemoprod_removidos) 
    
    # --- 6. Exice o resultado ---
    print("\n--- Processo Concluído ---")
    print(f"Registros removidos: {registros_removidos}")
    print(f"Total de registros DEPOIS da remoção de duplicatas: {registros_depois}")

    # (Opcional) Exibe a amostra dos removidos
    print("\nAmostra dos dados REMOVIDOS (os mais antigos/duplicados):")
    display(hemoprod_removidos.head(10))

    # Você pode continuar a usar o DataFrame 'hemoprod_ce_deduplicado' para suas análises
    print("\nAmostra dos dados únicos (os mais recentes para cada chave):")
    display(hemoprod_mg_deduplicado.head(10))
    
    # Agora você tem o DataFrame 'hemoprod_removidos' salvo

Total de registros ANTES da remoção de duplicatas: 271

Ordenando os dados por 'data_envio'...
Identificando duplicatas com cese na chave: ['cnpj', 'ano_referencia', 'periodo_referencia', 'razao_social_nome_fantasia']...

--- Processo Concluído ---
Registros removidos: 8
Total de registros DEPOIS da remoção de duplicatas: 263

Amostra dos dados REMOVIDOS (os mais antigos/duplicados):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
85,184,2023-11-20 12:45:37,4,pt-BR,1.974213e+09,GKfOabdaZZsYIgO,2023-11-20 11:59:35,2023-11-20 12:45:37,189.17.52.98,NaN,ORIGINAL,2023,Julho,NaN,"Teófilo Otoni, Minas Gerais",Associação Hospitalar Santa Rosália - Hospital...,NaN,2510490200107,Núcleo de Hemoterapia,Privado-SUS,Rede de serviços,Associação Beneficente Bom Samaritano - Bom Sa...,NaN,NaN,191.0,52.0,211.0,93.0,0.0,0.0,113.0,69.0,221.0,58.0,68.0,18.0,225.0,60.0,177.0,85.0,3.0,2.0,134.0,58.0,265.0,85.0,2.0,30.0,32.0,5.0,2.0,7.0,0.0,1.0,1.0,0.0,0.0,0.0,9.0,4.0,13.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,44.0,47.0,91.0,1.0,15.0,0.0,0.0,286.0,0.0,NaN,386.0,0.0,386.0,0.0,386.0,7.0,386.0,0.0,386.0,6.0,386.0,0.0,386.0,0.0,386.0,0.0,386.0,0.0,386.0,0.0,386.0,0.0,109,169,40,35,11,12,179,276,10,21,7,7,1,1,29,41,47,70,386,562,0,0,4,0,136.0,386.0,0.0,0.0,NaN,386,0,0,51,0,0,0,0,0,386,0,4,0,0,0,365,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,18,4,0,0,335,0,12,12,0,0,0,0,193,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,44,44,0,0,0,4,271,275,0,0,0,0,46,46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,0,0,159,159,0,0,0,0,28,28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,0,0,0,0,0,0,0,0.0,0.0,NaN
138,266,2024-04-08 10:15:29,4,pt-BR,1.448841e+09,43HpQpDjnc0LmIu,2024-04-08 09:50:22,2024-04-08 10:15:29,177.207.187.35,NaN,ORIGINAL,2024,Março,NaN,"Ipatinga, Minas Gerais",Fundação São Francisco Xavier - Hospital Márci...,NaN,19878404000100,Núcleo de Hemoterapia,Privado-SUS,Único serviço,NaN,NaN,NaN,294.0,59.0,377.0,91.0,0.0,0.0,283.0,106.0,188.0,25.0,200.0,19.0,383.0,49.0,288.0,101.0,0.0,1.0,183.0,49.0,488.0,100.0,3.0,35.0,38.0,4.0,0.0,4.0,0.0,8.0,8.0,0.0,0.0,0.0,1.0,3.0,4.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,42.0,53.0,95.0,1.0,11.0,3.0,12.0,644.0,0.0,NaN,644.0,0.0,644.0,0.0,644.0,8.0,644.0,0.0,644.0,4.0,644.0,1.0,644.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,184,184,66,62,21,15,264,272,31,21,12,11,0,1,66,41,109,0,0,3,0,0,0,0,644.0,644.0,13.0,0.0,NaN,0,0,0,64,0,0,0,0,0,644,4,0,0,0,0,644,35,0,0,2,0,0,0,0,56,0,0,0,0,0,0,0,0,0,2,34,0,0,0,0,67,78,0,0,0,0,202,120,0,0,0,0,0,0,0,0,21,0,0,0,0,0,0,0,53,53,0,0,0,31,436,467,0,0,0,6,342,348,0,2,2,0,0,0,0,54,54,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,48,70,23,2,1,1,0,0,0,0,0.0,0.0,"-Campo entradas/recebidas 4 CH, 35 CP, 2CP afé..."
141,271,2024-04-19 10:30:35,4,pt-BR,1.650070e+09,mJUrRJria3Szapo,2024-04-19 09:42:46,2024-04-19 10:30:35,186.248.197.178,NaN,ORIGINAL,2024,Março,NaN,"Nova Lima, Minas Gerais",Biocor Hospital de Doenças Cardiovasculares Lt...,NaN,20294088000109,Núcleo de Hemoterapia,Privado,Único serviço,NaN,NaN,NaN,66.0,0.0,94.0,0.0,0.0,0.0,22.0,0.0,100.0,0.0,38.0,0.0,81.0,0.0,79.0,0.0,0.0,0.0,40.0,0.0,120.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,143.0,17.0,NaN,160.0,0.0,160.0,0.0,160.0,2.0,160.0,0.0,160.0,0.0,160.0,1.0,160.0,0.0,0.0,0.0,160.0,0.0,160.0,0.0,160.0,0.0,42,59,12,20,5,5,0,73,6,5,1,2,1,1,15,12,23,20,0,2,1,0,0,4,22.0,160.0,3.0,0.0,NaN,0,0,0,143,0,0,0,0,0,143,16,0,0,0,0,143,35,0,34,0,0,0,0,0,18,0,0,0,0,0,0,0,0,1,2,76,0,0,0,0,2,4,0,0,0,0,9,5,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,102,102,0,0,0,6,136,142,0,0,0,0,162,162,1,30,31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,120,86,0,0,0,0,0,0,0,0,0.0,0.0,NaN
157,293,2024-06-08 12:16:00,4,pt-BR,NaN,MfTu2yewsNxvB7k,2024-06-08 11:45:00,2024-06-08 12:16:00,189.45.16.78,NaN,ORIGINAL,2024,Maio,NaN,"Alfenas, Minas Gerais",Fundação de Ensino e Tecnologia de Alfenas - H...,Nucleo Hemoterapico Hospital Universitario Alz...,17878554001241,Núcleo de Hemoterapia,Privado-SUS,Único serviço,NaN,NaN,NaN,116.0,25.0,230.0,50.0,0.0,0.0,86.0,35.0,119.0,15.0,141.0,25.0,198.0,28.0,149.0,46.0,0.0,4.0,111.0,27.0,235.0,44.0,0.0,5.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,3.0,8.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,38.0,58.0,1.0,1.0,0.0,0.0,344.0,0.0,NaN,344.0,0.0,344.0,0.0,344.0,0.0,344.0,0.0,344.0,0.0,344.0,0.0,344.0,0.0,0.0,0.0,344.0,0.0,344.0,0.0,344.0,0.0,100,50,19,18,7,3,150,48,13,8,1,0,4,0,50,14,65,0,2,5,73,2,0,3,344.0,344.0,0.0,0.0,NaN,19,0,0,325,0,0,0,0,0,325,0,0,0,0,0,254,0,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,19,2,7,155,0,0,0,0,79,14,0,0,0,0,193,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,74,74,0,0,0,0,162,162,0,0,0,0,62,62,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,46,0,0,0,0,0,0,0,0,0.0,0.0,NaN
166,305,2024-07-08 09:59:32,4,pt-BR,1.814253e+08,MfTu2yewsNxvB7k,2024-07-08 09:24:27,2024-07-08 09:59:32,189.45.16.78,NaN,ORIGINAL,2024,Junho,NaN,"Alfenas, Minas Gerais",Fundação de Ensino e Tecnologia de Alfenas - H...,NaN,17878554001241,Núcleo de Hemoterapia,Privado-SUS,Único serviço,NaN,NaN,NaN,73.0,13.0,207.0,28.0,0.0,0.0,65.0,19.0,100.0,4.0,115.0,18.0,161.0,16.0,119.0,25.0,0.0,0.0,68.0,22.0,212.0,19.0,0.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,4.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,16.0,25.0,0.0,0.0,0.0,0.0,280.0,0.0,NaN,280.0,0.0,280.0,0.0,280.0,2.0,280.0,0.0,280.0,2.0,280.0,0.0,280.0,0.0,280.0,0.0,280.0,0.0,280.0,0.0,280.0,0.0,76,56,18,15,4,4,124,65,10,3,5,2,1,0,42,11,58,0,1,2,59,2,0,2,280.0,280.0,4.0,0.0,NaN,14,0,0,266,0,0,0,0,0,266,0,0,0,0,0,208,0,0,0,0,0,0,0,0,15,0,0,0,0,0,0,0,14,2,2,178,0,0,0,0,109,14,0,0,0,0,160,10,0,0,0,0,0,0,0,7,0,0,0,0,0,0,0,0,88,88,0,0,0,0,180,180,0,0,0,0,42,42,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0,0,0,0,0,0,0,0,0.0,0.0,NaN
215,369,2025-01-20 16:00:29,4,pt-BR,1.209934e+09,VZuYtMoaMM5Nvea,2025-01-20 15:41:01,2025-01-20 16:00:29,192.140.91.31,NaN,ORIGINAL,2024,Dezembro,NaN,"Alfenas, Minas Gerais",Casa de Caridade de Alfenas Nossa Senhora do P...,NaN,16650756000116,Núcleo de Hemoterapia,Privado-SUS,Único serviço,NaN,NaN,NaN,98.0,19.0,269.0,53.0,0.0,0.0,107.0,40.0,140.0,9.0,120.0,23.0,216.0,33.0,151.0,39.0,5.0,0.0,92.0,24.0,270.0,48.0,0.0,5.0,5.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31.0,34.0,65.0,0.0,6.0,0.0,1.0,358.0,9.0,NaN,367.0,0.0,367.0,0.0,367.0,3.0,367.0,0.0,367.0,1.0,367.0,0.0,367.0,0.0,367.0,0.0,367.0,0.0,367.0,0.0,367.0,0.0,101,139,32,17,6,5,166,115,21,19,2,6,2,4,37,22,62,51,1,1,23,4,0,0,107.0,367.0,4.0,2.0,NaN,16,0,0,266,0,0,76,0,0,342,0,0,0,0,0,190,0,0,18,0,0,0,0,0,12,0,0,0,0,0,0,0,16,4,116,174,0,48,58,1,5,15,0,0,0,0,12,3,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,68,68,0,0,0,73,176,249,0,0,0,10,134,144,1,13,14,0,0,0,0,74,74,0,0,0,0,0,0,0,32,32,0,0,0,0,134,134,0,0,0,0,22,22,0,2,2,0,0,0,0,0,0,0,0,0,0,0,5,53,4,1,0,1,0,0,0,0,0.0,0.0,NaN

Amostra dos dados únicos (os mais recentes para cada chave):

,id,data_envio,ultima_pagina,idioma_inicial,semente,codigo_acesso,data_inicio,data_ultima_acao,ip,identificacao_dado,tipo_envio,ano_referencia,periodo_referencia,identificacao_estabelecimento,municipio,razao_social_nome_fantasia,razao_social_nome_fantasia_outros,cnpj,tipo_estabelecimento,natureza_estabelecimento,dados_informados_referem_se,rede_estabelecimento,cnes,endereco,triagem_clinica_total_doacao_espontanea_aptos,triagem_clinica_total_doacao_espontanea_inaptos,triagem_clinica_total_doacao_reposicao_aptos,triagem_clinica_total_doacao_reposicao_inaptos,triagem_clinica_total_doacao_autologa_aptos,triagem_clinica_total_doacao_autologa_inaptos,total_doador_primeira_vez_aptos,total_doador_primeira_vez_inaptos,total_doador_repeticao_aptos,total_doador_repeticao_inaptos,total_doador_esporadico_aptos,total_doador_esporadico_inaptos,total_doador_masculino_aptos,total_doador_masculino_inaptos,total_doador_feminino_aptos,total_doador_feminino_inaptos,total_doador_menor_de_18_anos_aptos,total_doador_menor_de_18_anos_inaptos,total_doador_18_ate_29_anos_aptos,total_doador_18_ate_29_anos_inaptos,total_doador_acima_de_29_anos_aptos,total_doador_acima_de_29_anos_inaptos,total_candidatos_inaptos_anemia_masculino,total_candidatos_inaptos_anemia_feminino,total_candidatos_inaptos_anemia_total,total_candidatos_inaptos_hipertensao_masculino,total_candidatos_inaptos_hipertensao_feminino,total_candidatos_inaptos_hipertensao_total,total_candidatos_inaptos_hipotensao_masculino,total_candidatos_inaptos_hipotensao_feminino,total_candidatos_inaptos_hipotensao_total,total_candidatos_inaptos_alcoolismo_masculino,total_candidatos_inaptos_alcoolismo_feminino,total_candidatos_inaptos_alcoolismo_total,total_candidatos_inaptos_comportamento_risco_dst_masculino,total_candidatos_inaptos_comportamento_risco_dst_feminino,total_candidatos_inaptos_comportamento_risco_dst_total,total_candidatos_inaptos_uso_drogas_masculino,total_candidatos_inaptos_uso_drogas_feminino,total_candidatos_inaptos_uso_drogas_total,total_candidatos_inaptos_hepatite_masculino,total_candidatos_inaptos_hepatite_feminino,total_candidatos_inaptos_hepatite_total,total_candidatos_inaptos_doenca_chagas_masculino,total_candidatos_inaptos_doenca_chagas_feminino,total_candidatos_inaptos_doenca_chagas_total,total_candidatos_inaptos_malaria_masculino,total_candidatos_inaptos_malaria_feminino,total_candidatos_inaptos_malaria_total,total_candidatos_inaptos_outras_masculino,total_candidatos_inaptos_outras_feminino,total_candidatos_inaptos_outras_total,coleta_total_candidatos_desistentes,total_interrupcoes_coleta_dificuldade_puncao_venosa,total_interrupcoes_coleta_reacao_vagal,total_interrupcoes_coleta_outros_motivos,total_coletas_sangue_total,total_coletas_aferese,hemoprod_1_observacoes,exames_triagem_doenca_doenca_chagas_amostras_testadas,exames_triagem_doenca_doenca_chagas_amostras_reagentes,exames_triagem_doenca_hiv_amostras_testadas,exames_triagem_doenca_hiv_amostras_reagentes,exames_triagem_doenca_sifilis_amostras_testadas,`exames_triagem_doenca_sifilis_amostras_reagentes,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_testadas,exames_triagem_doenca_hepatite_b_hbs_ag_amostras_reagentes,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_testadas,exames_triagem_doenca_hepatite_b_anti_hbc_amostras_reagentes,exames_triagem_doenca_hepatite_c_amostras_testadas,exames_triagem_doenca_hepatite_c_amostras_reagentes,exames_triagem_doenca_htlv_i_ii_amostras_testadas,exames_triagem_doenca_htlv_i_ii_amostras_reagentes,exames_triagem_doenca_malaria_amostras_testadas,exames_triagem_doenca_malaria_amostras_reagentes,exames_triagem_doenca_hbv_teste_nat_amostras_testadas,exames_triagem_doenca_hbv_teste_nat_amostras_reagentes,exames_triagem_doenca_hcv_teste_nat_amostras_testadas,exames_triagem_doenca_hcv_teste_nat_amostras_reagentes,exames_triagem_doenca_hiv_teste_nat_amostras_testadas,exames_triagem_doenca_hiv_teste_nat_amostras_reagentes,imunohematologia_a_positivo_doador,imunohematologia_a_positivo_receptor,imunohematologia_b_positivo_doador,imunohematologia_b_positivo_receptor,imunohematologia_ab_positivo_doador,imunohematologia_ab_positivo_receptor,imunohematologia_o_positivo_doador,imunohematologia_o_positivo_receptor,imunohematologia_a_negativo_doador,imunohematologia_a_negativo_receptor,imunohematologia_b_negativo_doador,imunohematologia_b_negativo_receptor,imunohematologia_ab_negativo_doador,imunohematologia_ab_negativo_receptor,imunohematologia_o_negativo_doador,imunohematologia_o_negativo_receptor,imunohematologia_dfraco_doador,imunohematologia_dfraco_receptor,imunohematologia_pesquisa_anticorpo_irregular_positivo_doador,imunohematologia_pesquisa_anticorpo_irregular_positivo_receptor,imunohematologia_fenotipagem_doador,imunohematologia_fenotipagem_receptor,imunohematologia_combs_direto_doador,imunohematologia_combs_direto_receptor,outros_tipos_pesquisa_pesquisa_hbs_doador,inaptidao_triagem_laboratorial_total_bolsas_testadas,inaptidao_triagem_laboratorial_total_bolsas_reagentes_1_ou_mais_marcadores,descarte_bolsas_total_bolsas_descartadas_auto_exclusao,hemoprod_2_observacoes,producao_hemoterapica_entradas_sangue_total_produzidas,producao_hemoterapica_entradas_sangue_total_recebidas,producao_hemoterapica_entradas_sangue_total_devolvidas,producao_hemoterapica_entradas_plasma_fresco_congelado_produzidas,producao_hemoterapica_entradas_plasma_fresco_congelado_recebidas,producao_hemoterapica_entradas_plasma_fresco_congelado_devolvidas,producao_hemoterapica_entradas_plasma_comum_produzidas,producao_hemoterapica_entradas_plasma_comum_recebidas,producao_hemoterapica_entradas_plasma_comum_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_devolvidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_hemacias_sem_buffy_coat_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_devolvidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_produzidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_recebidas,producao_hemoterapica_entradas_concentrado_plaquetas_aferese_devolvidas,producao_hemoterapica_entradas_concentrado_leucocitos_produzidas,producao_hemoterapica_entradas_concentrado_leucocitos_recebidas,producao_hemoterapica_entradas_concentrado_leucocitos_devolvidas,producao_hemoterapica_entradas_crioprecipitado_produzidas,producao_hemoterapica_entradas_crioprecipitado_recebidas,producao_hemoterapica_entradas_crioprecipitado_devolvidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_produzidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_recebidas,producao_hemoterapica_entradas_concentrado_de_plaquetas_sem_buffy_coat_devolvidas,perdas_sangue_total_rompimento_de_bolsa,perdas_sangue_total_validade,perdas_sangue_total_outros_motivos,perdas_plasma_fresco_congelado_rompimento_de_bolsa,perdas_plasma_fresco_congelado_validade,perdas_plasma_fresco_congelado_outros_motivos,perdas_plasma_comum_rompimento_de_bolsa,perdas_plasma_comum_validade,perdas_plasma_comum_outros_motivos,perdas_concentrado_de_hemacias_rompimento_de_bolsa,perdas_concentrado_de_hemacias_validade,perdas_concentrado_de_hemacias_outros_motivos,perdas_concentrado_de_hemacias_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_hemacias_sem_buffy_coat_validade,perdas_concentrado_de_hemacias_sem_buffy_coat_outros_motivos,perdas_concentrado_de_plaquetas_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_validade,perdas_concentrado_de_plaquetas_outros_motivos,perdas_concentrado_de_plaquetas_de_aferese_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_de_aferese_validade,perdas_concentrado_de_plaquetas_de_aferese_outros_motivos,perdas_concentrado_de_leucocitos_rompimento_de_bolsa,perdas_concentrado_de_leucocitos_validade,perdas_concentrado_de_leucocitos_outros_motivos,perdas_crioprecipitado_rompimento_de_bolsa,perdas_crioprecipitado_validade,perdas_crioprecipitado_outros_motivos,perdas_concentrado_de_plaquetas_sem_buffy_coat_rompimento_de_bolsa,perdas_concentrado_de_plaquetas_sem_buffy_coat_validade,perdas_concentrado_de_plaquetas_sem_buffy_coat_outros_motivos,tranfusoes_sangue_total_ambulatorial,tranfusoes_sangue_total_hospitalar,tranfusoes_sangue_total_total,tranfusoes_plasma_fresco_congelado_ambulatorial,tranfusoes_plasma_fresco_congelado_hospitalar,tranfusoes_plasma_fresco_congelado_total,tranfusoes_plasma_comum_ambulatorial,tranfusoes_plasma_comum_hospitalar,tranfusoes_plasma_comum_total,tranfusoes_concentrado_de_hemacias_ambulatorial,tranfusoes_concentrado_de_hemacias_hospitalar,tranfusoes_concentrado_de_hemacias_total,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_hemacias_sem_buffy_coat_total,tranfusoes_concentrado_de_plaquetas_ambulatorial,tranfusoes_concentrado_de_plaquetas_hospitalar,tranfusoes_concentrado_de_plaquetas_total,tranfusoes_concentrado_de_plaquetas_de_aferese_ambulatorial,tranfusoes_concentrado_de_plaquetas_de_aferese_hospitalar,tranfusoes_concentrado_de_plaquetas_de_aferese_total,tranfusoes_concentrado_de_leucocitos_ambulatorial,tranfusoes_concentrado_de_leucocitos_hospitalar,tranfusoes_concentrado_de_leucocitos_total,tranfusoes_crioprecipitado_ambulatorial,tranfusoes_crioprecipitado_hospitalar,tranfusoes_crioprecipitado_total,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_ambulatorial,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_hospitalar,tranfusoes_concentrado_de_plaquetas_sem_buffy_coat_total,distribuicao_para_outros_servicos_sangue_total_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_com_exame_pre_transfusional,distribuicao_para_outros_servicos_sangue_total_total,distribuicao_para_outros_servicos_plasma_fresco_congelado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_fresco_congelado_total,distribuicao_para_outros_servicos_plasma_comum_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_com_exame_pre_transfusional,distribuicao_para_outros_servicos_plasma_comum_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_hemacias_total,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_sem_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_com_exame_pre_transfusi,distribuicao_para_outros_servicos_concentrado_de_hemacias_sem_buffy_coat_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_aferese_total,distribuicao_para_outros_servicos_concentrado_de_leucocitos_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_leucocitos_total,distribuicao_para_outros_servicos_crioprecipitado_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_com_exame_pre_transfusional,distribuicao_para_outros_servicos_crioprecipitado_total,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_sem_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_com_exame_pre_transfusional,distribuicao_para_outros_servicos_concentrado_de_plaquetas_sem_buffy_coat_total,procedimentos_de_modificacao_dos_hemocomponentes_lavagem,procedimentos_de_modificacao_dos_hemocomponentes_irradiacao,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_plaquetas,procedimentos_de_modificacao_dos_hemocomponentes_filtracao_em_concentrado_de_hemacias,procedimentos_de_modificacao_dos_hemocomponentes_fracionamento_pediatrico,reacoes_transfusionais_reacao_febril_nao_hemolitica,reacoes_transfusionais_reacao_hemolitica,reacoes_transfusionais_reacao_alergica,reacoes_transfusionais_choque_bacteriano,reacoes_transfusionais_alteracoes_metabolicas,reacoes_transfusionais_sobrecarga_volemica,reacoes_transfusionais_outras_reacoes,envio_plasma_producao_hemoderivados_plasma_fresco_congelado,envio_plasma_producao_hemoderivados_plasma_comum,hemoprod_3_observacoes
0,5,2023-04-14 16:05:33,4,pt-BR,3.992492e+08,IvycpvVQH6KQqkP,2023-04-14 15:05:11,2023-04-14 16:05:33,10.0.113.219,NaN,ORIGINAL,2023,Março,NaN,"Belo Horizonte, Minas Gerais",Vita Hemoterapia Ltda - Vita Hemoterapia,NaN,25463423000179,Unidade de Coleta e Transfusão,Privado,Único serviço,NaN,NaN,NaN,266.0,29.0,1893.0,219.0,1.0,0.0,849.0,149.0,908.0,59.0,403.0,40.0,1131.0,135.0,1029.0,113.0,10.0,0.0,614.0,78.0,1536.0,170.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,31.0,11.0,42.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,102.0,102.0,204.0,0.0,0.0,0.0,0.0,2135.0,25.0,NaN,2157.0,0.0,2157.0,1.0,2157.0,12.0,2157.0,0.0,2157.0,6.0,2157.0,0.0,2157.0,0.0,0.0,0.0,2157.0,6.0,2157.0,0.0,2157.0,1.0,725,880,172,258,55,77,868,962,118,154,30,36,9,15,176,156,336,73,5,51,308,7,0,0,2154.0,2154.0,19.0,0.0,NaN,18,0,0,2098,87,0,0,0,0,2117,19,0,0,0,0,2113,49,0,25,0,0,0,0,0,231,4,0,0,0,0,1,0,17,1,0,1110,0,0,0,0,2,9,0,0,0,0,2,33,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,594,594,0,0,0,21,1702,1723,0,0,0,16,1703,1719,0,43,43,0,0,0,0,121,121,0,21,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1277,16,53,120,3,0,3,0,0,0,1,0.0,0.0,NaN
1,10,2023-04-18 12:22:00,4,pt-BR,NaN,MfTu2yewsNxvB7k,2023-04-18 11:29:00,2023-04-18 12:22:00,10.0.1.35,NaN,ORIGINAL,2022,Janeiro,NaN,"Alfenas, Minas Gerais",Fundação de Ensino e Tecnologia de Alfenas - H...,Hospital Universitário Alzira Velano-Banco de ...,17878554001241,Núcleo de Hemoterapia,Privado-SUS,Único serviço,NaN,NaN,NaN,49.0,10.0,186.0,27.0,0.0,0.0,47.0,17.0,98.0,11.0,90.0,9.0,144.0,13.0,91.0,24.0,0.0,0.0,61.0,19.0,174.0,18.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,3.0,2.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,21.0,31.0,0.0,0.0,0.0,0.0,235.0,0.0,NaN,235.0,0.0,235.0,0.0,235.0,1.0,235.0,0.0,235.0,0.0,235.0,0.0,235.0,0.0,235.0,0.0,235.0,0.0,235.0,0.0,235.0,0.0,82,45,21,13,9,2,84,60,12,8,3,0,1,0,23,5,39,11,0,4,0,0,0,0,235.0,235.0,1.0,0.0,NaN,7,0,0,228,0,0,0,0,0,228,0,0,0,0,0,190,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,7,0,10,160,0,0,0,2,99,14,0,0,0,0,147,20,0,0,0,0,0,0,0,8,0,0,0,0,0,0,0,0,64,64,0,0,0,0,170,170,0,0,0,0,28,28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,193,0,0,0,0,0,0,0,0,0.0,0.0,NaN
2,12,2023-04-18 12:52:00,4,pt-BR,NaN,MfTu2yewsNxvB7k,2023-04-18 12:26:00,2023-04-18 12:52:00,10.0.0.186,NaN,ORIGINAL,2022,Fevereiro,NaN,"Alfenas, Minas Gerais",Fundação de Ensino e Tecnologia de Alfenas - H...,Hospital Universitário Alzira Velano,17878554001241,Núcleo de Hemoterapia,Privado-SUS,Único serviço,NaN,NaN,NaN,50.0,13.0,249.0,68.0,0.0,0.0,68.0,46.0,111.0,13.0,120.0,22.0,191.0,38.0,108.0,43.0,0.0,0.0,82.0,38.0,217.0,43.0,0.0,2.0,2.0,3.0,0.0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,8.0,4.0,12.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.0,36.0,62.0,0.0,2.0,0.0,0.0,297.0,0.0,NaN,297.0,0.0,297.0,0.0,297.0,3.0,297.0,0.0,297.0,0.0,297.0,0.0,297.0,0.0,297.0,0.0,297.0,0.0,297.0,0.0,297.0,0.0,90,36,24,13,9,2,121,58,13,7,4,0,0,2,36,4,53,12,0,1,0,0,0,1,297.0,297.0,3.0,2.0,NaN,21,0,0,276,0,0,0,0,0,276,0,0,0,0,0,187,0,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,21,3,10,382,0,0,0,0,20,14,0,0,0,0,177,14,0,0,0,0,0,0,0,2,15,0,0,0,0,0,0,0,88,88,0,0,0,0,183,183,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,19,0,0,0,0,0,0,0,0,0.0,0.0,NaN
3,17,2023-04-26 12:27:00,4,pt-BR,NaN,MfTu2yewsNxvB7k,2023-04-26 11:49:00,2023-04-26 12:27:00,10.0.52.44,NaN,ORIGINAL,2023,Janeiro,NaN,"Alfenas, Minas Gerais",Fundação de Ensino e Tecnologia de Alfenas - H...,Hospital Universitário Alzira Velano,17878554001241,Núcleo de Hemoterapia,Privado-SUS,Único serviço,NaN,NaN,NaN,48.0,11.0,223.0,37.0,0.0,0.0,57.0,24.0,113.0,13.0,101.0,11.0,170.0,19.0,101.0,29.0,0.0,0.0,68.0,17.0,203.0,31.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,2.0,0.0,0.0,0.0,3.0,2.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,24.0,40.0,0.0,0.0,0.0,0.0,271.0,0.0,NaN,271.0,0.0,271.0,0.0,271.0,1.0,271.0,0.0,271.0,1.0,271.0,0.0,271.0,0.0,0.0,0.0,271.0,0.0,271.0,0.0,271.0,0.0,86,53,22,11,10,3,106,56,10,10,1,2,1,1,35,4,47,17,1,3,0,0,0,3,271.0,271.0,2.0,0.0,NaN,15,0,0,256,0,0,0,0,0,256,0,0,0,0,0,184,0,0,0,0,0,0,0,0,19,0,0,0,0,0,0,0,15,9,9,249,0,0,0,1,113,11,0,0,0,0,161,16,0,0,0,0,0,0,0,0,10,0,0,0,0,0,0,0,121,121,0,0,0,0,179,179,0,0,0,0,8,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,51,74,0,1,0,0,0,0,0,1,0.0,0.0,NaN
4,18,2023-04-26 13:02:01,4,pt-BR,1.780040e+09,MfTu2yewsNxvB7k,2023-04-26 12:32:51,2023-04-26 13:02:01,10.0.52.19,NaN,ORIGINAL,2023,Fevereiro,NaN,"Alfenas, Minas Gerais",Fundação de Ensino e Tecnologia de Alfenas - H...,NaN,17878554001241,Núcleo de Hemoterapia,Privado-SUS,Único serviço,NaN,NaN,NaN,44.0,7.0,242.0,45.0,0.0,0.0,59.0,19.0,124.0,10.0,103.0,23.0,149.0,20.0,137.0,32.0,0.0,0.0,80.0,16.0,206.0,36.0,0.0,0.0,0.0,2.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,30.0,44.0,2.0,0.0,0.0,0.0,284.0,0.0,NaN,284.0,0.0,284.0,0.0,284.0,2.0,284.0,0.0,284.0,0.0,284.0,0.0,284.0,0.0,0.0,0.0,284.0,0.0,284.0,0.0,284.0,0.0,92,35,12,18,4,5,111,55,10,7,5,1,3,3,47,3,65,13,0,0,0,0,0,1,284.0,284.0,2.0,0.0,NaN,11,0,0,273,0,0,0,0,0,273,0,0,0,0,0,193,0,0,0,0,0,0,0,0,23,0,0,0,0,0,1,0,10,1,8,182,0,0,0,1,37,19,0,0,0,0,152,24,0,0,0,0,0,0,1,2,2,0,0,0,0,0,0,0,70,0,0,0,0,0,155,0,0,0,0,0,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,0,0,0,0,0,0,0,0,0.0,0.0,NaN
5,19,2023-04-26 17:05:53,4,pt-BR,1.061017e+09,mJUrRJria3Szapo,2023-04-26 15:44:37,2023-04-26 17:05:53,10.0.0.30,NaN,ORIGINAL,2023,Março,NaN,"Nova Lima, Minas Gerais",Biocor Hospital de Doenças Cardiovasculares Lt...,NaN,20294088000109,Núcleo de Hemoterapia,Privado,Único serviço,NaN,NaN,NaN,112.0,3.0,66.0,1.0,0.0,0.0,32.0,3.0,91.0,1.0,55.0,0.0,91.0,2.0,87.0,2.0,0.0,0.0,36.0,0.0,142.0,4.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,165.0,13.0,NaN,178.0,0.0,178.0,0.0,178.0,2.0,178.0,0.0,178.0,0.0,178.0,0.0,178.0,0.0,0.0,0.0,178.0,0.0,178.0,0.0,178.0,0.0,49,61,23,21,3,9,68,67,6,14,3,7,2,1,24,19,35,41,178,199,0,0,0,10,32.0,178.0,2.0,0.0,NaN,1,0,0,164,26,0,0,0,0,164,4,0,0,0,0,164,20,0,25,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,76,0,0,0,0,14,2,0,0,0,0,41,4,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,272,272,0,0,0,0,134,134,0,0,0,0,114,114,0,29,29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,98,74,0,0,0,0,0,0,0,0,0.0,0.0,NaN

In [114]:
hemoprod_mg_deduplicado.to_excel('dados_processados/hemoprod_mg.xlsx', index=False)

## Hemoprod Mato Grosso do Sul

In [ ]:
import os
import pandas as pd

dados_brutos_path = 'dados_brutos'

arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_MS.xlsx')
nome_planilha = 'HEMOPROD - MATOGROSSODOSUL'

dicionario_path_ms = ('./dicionario_colunas_270.xlsx')
# dicionario_path_ap = ('./dicionario_colunas_270.xlsx')

dicionario_ms = pd.read_excel(dicionario_path_ms, sheet_name='Sheet1')

# --- 2. Carregue os dados e o dicionário ---
try:
    # Carrega o arquivo de dados
    hemoprod_ms = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)
    print("Arquivo de dados carregado com sucesso.")
    print(f"Número de colunas original: {len(hemoprod_ms.columns)}")

    # Carrega o arquivo de dicionário
    dicionario = pd.read_excel(dicionario_path_ms)
    print("Arquivo de dicionário carregado com sucesso.")

    # --- 3. Extraia a lista de novos nomes ---
    # Pega os valores da coluna 'nome_sql' e converte para uma lista
    novos_nomes = dicionario['nome_sql'].tolist()
    print(f"Número de novos nomes no dicionário: {len(novos_nomes)}")

    # --- 4. Verificação de segurança (MUITO IMPORTANTE) ---
    # Garante que o número de colunas é o mesmo antes de renomear
    if len(hemoprod_ms.columns) == len(novos_nomes):
        print("\nO número de colunas corresponde. Renomeando...")
        
        # --- 5. Substitua os nomes das colunas ---
        # Esta é a linha principal que faz a substituição direta
        hemoprod_ms.columns = novos_nomes
        
        print("Colunas renomeadas com sucesso!")
        
        # --- 6. Verifique o resultado ---
        print("\nInformações do DataFrame com as novas colunas:")
        hemoprod_ms.info()
        
        print("\nAs 5 primeiras linhas com as novas colunas:")
        display(hemoprod_ms.head())

    else:
        # Mensagem de erro se o número de colunas for diferente
        print("\n--- ERRO ---")
        print("A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.")
        print(f"Colunas no arquivo de dados: {len(hemoprod_ms.columns)}")
        print(f"Nomes no dicionário: {len(novos_nomes)}")

except FileNotFoundError as e:
    print(f"\nErro de arquivo não encontrado: {e}")
except KeyError as e:
    print(f"\nErro de coluna não encontrada: {e}. Verifique se a coluna 'nome_sql' existe no seu arquivo de dicionário.")
except Exception as e:
    print(f"\nOcorreu um erro inesperado: {e}")

Arquivo de dados carregado com sucesso.
Número de colunas original: 269
Arquivo de dicionário carregado com sucesso.
Número de novos nomes no dicionário: 270

--- ERRO ---
A renomeação foi cancelada. O número de colunas no arquivo de dados não é igual ao número de nomes no dicionário.
Colunas no arquivo de dados: 269
Nomes no dicionário: 270

In [6]:

arquivo_dados_path = os.path.join(dados_brutos_path, 'Hemoprod_AM.xlsx')
nome_planilha = 'HEMOPROD - AMAZONAS'
hemoprod_ce1 = pd.read_excel(arquivo_dados_path, sheet_name=nome_planilha)

colunas_padrao = set(hemoprod_ce1.columns)
colunas_estado = set(hemoprod_ms.columns)

colunas_faltantes = list(colunas_padrao - colunas_estado)

colunas_a_mais = list(colunas_estado - colunas_padrao)

print(f"Número de colunas faltantes: {len(colunas_faltantes)}")
print(f"Colunas faltantes (a serem adicionadas): {colunas_faltantes}")
print("-" * 30)
print(f"Número de colunas a mais: {len(colunas_a_mais)}")
print(f"Colunas a mais (a serem dropadas): {colunas_a_mais}")

Número de colunas faltantes: 3
Colunas faltantes (a serem adicionadas): ['Os dados informados referem-se à um(a): ', 'Cite os estabelecimentos que compõem a rede  Informe o Tipo de Estabelecimento, o Nome Fantasia\xa0e o Município de localização de cada um. ', 'Ano de referência ']
------------------------------
Número de colunas a mais: 2
Colunas a mais (a serem dropadas): ['Município [Outros]', 'Período de referência [Outros]']

## Analisando o auto exclusao

In [1]:
import pandas as pd
import os

# 1. Definir o caminho do arquivo
parquet_path = "dados_processados/base_nacional.parquet"
coluna_alvo = "descarte_bolsas_total_bolsas_descartadas_auto_exclusao"

# 2. Verificar se o arquivo existe antes de tentar carregar
if not os.path.exists(parquet_path):
    print(f"Erro: Arquivo não encontrado no caminho: {parquet_path}")
else:
    try:
        # 3. Carregar o DataFrame do arquivo Parquet
        # O pandas usa o pyarrow ou fastparquet internamente para ler o .parquet
        df = pd.read_parquet(parquet_path)
        print(f"DataFrame carregado com sucesso. Total de linhas: {len(df)}")
        
        # 4. Verificar se a coluna existe no DataFrame
        if coluna_alvo in df.columns:
            # 5. Calcular a soma da coluna
            total_descarte = df[coluna_alvo].sum()
            
            # 6. Exibir o resultado formatado
            # O f-string com ":," formata o número com separador de milhar
            print("\n--- Resultado ---")
            print(f"Soma total de '{coluna_alvo}':")
            print(f"-> {int(total_descarte):,}")
            
        else:
            print(f"\nErro: A coluna '{coluna_alvo}' não foi encontrada no arquivo Parquet.")
            print(f"Colunas disponíveis: {df.columns.tolist()}")

    except Exception as e:
        print(f"Ocorreu um erro ao carregar o arquivo Parquet: {e}")

DataFrame carregado com sucesso. Total de linhas: 15865

--- Resultado ---
Soma total de 'descarte_bolsas_total_bolsas_descartadas_auto_exclusao':
-> 20,579

In [2]:
import pandas as pd
import os

# 1. Defina o caminho do arquivo Parquet
# Certifique-se de que este caminho está correto em relação ao seu notebook.
parquet_path = "dados_processados/base_nacional.parquet"
coluna_municipio = "municipio"
coluna_descarte = "descarte_bolsas_total_bolsas_descartadas_auto_exclusao"

# 2. Verificar se o arquivo existe e carregar
if not os.path.exists(parquet_path):
    print(f"ERRO: Arquivo não encontrado no caminho: {parquet_path}")
    print("Verifique se o caminho está correto ou se o arquivo foi gerado.")
else:
    try:
        # Carregar o DataFrame
        df = pd.read_parquet(parquet_path)
        print(f"DataFrame carregado com sucesso. Total de linhas: {len(df):,}")

        # 3. Verificar a existência das colunas
        if coluna_municipio in df.columns and coluna_descarte in df.columns:
            
            # 4. Agrupar por Município e somar o total de descartes
            # O .fillna(0) garante que valores nulos não atrapalhem a soma.
            df_analise = (
                df.groupby(coluna_municipio)[coluna_descarte]
                .sum()
                .fillna(0) 
                .sort_values(ascending=False)
            )

            # 5. Selecionar o Top 50
            top_50_municipios = df_analise.head(50)

            # 6. Exibir o resultado
            print("\n--- TOP 50 Municípios por Total de Bolsas Descartadas ---")
            
            # Usando to_frame() e reset_index() para uma exibição formatada
            df_resultado = top_50_municipios.to_frame().reset_index()
            
            # Renomear coluna para clareza
            df_resultado.columns = ["Município", "Total Bolsas Descartadas"]
            
            # Formatação opcional para melhor visualização no notebook
            pd.options.display.float_format = '{:,.0f}'.format
            
            # Exibe a tabela no Jupyter/Pandas
            display(df_resultado)

        else:
            print("\nERRO: Uma ou ambas as colunas necessárias não foram encontradas no DataFrame.")
            print(f"Esperadas: '{coluna_municipio}' e '{coluna_descarte}'")
            
    except Exception as e:
        print(f"Ocorreu um erro ao carregar ou processar o arquivo Parquet: {e}")

DataFrame carregado com sucesso. Total de linhas: 15,865

--- TOP 50 Municípios por Total de Bolsas Descartadas ---

            Município  Total Bolsas Descartadas
0       Não se aplica                     10083
1            Curitiba                      1472
2        Campo Grande                      1003
3             Goiânia                       578
4               Natal                       536
5             Vitória                       491
6         João Pessoa                       445
7              Manaus                       363
8             Maringá                       321
9               Belém                       312
10          Fortaleza                       299
11  Cornélio Procópio                       280
12      Florianópolis                       240
13          Boa Vista                       239
14             Macapá                       216
15             Palmas                       196
16          Tramandaí                       191
17        Porto Velho                       168
18            Lajeado                       168
19          Joinville                       141
20            Pelotas                       135
21            Chapecó                       119
22      Foz do Iguaçu                       115
23           Cascavel                       114
24           Parnaíba                       113
25           Londrina                       110
26       Porto Alegre                       106
27          Apucarana                       103
28             Marabá                        97
29           Blumenau                        96
30           Salvador                        96
31        Três Lagoas                        92
32            Mossoró                        85
33             Cuiabá                        77
34             Gurupi                        75
35          Rio Verde                        69
36       Ponta Grossa                        66
37              Caicó                        64
38            Camaquã                        62
39     Porto Nacional                        56
40           Capanema                        56
41              Lages                        47
42              Juína                        45
43          Castanhal                        45
44            Alfenas                        42
45        Passo Fundo                        38
46           Dourados                        37
47      Caxias do Sul                        30
48     Augustinópolis                        30
49             Recife                        30

In [6]:
import pandas as pd
import os

# 1. Defina o caminho do arquivo Parquet
# Certifique-se de que este caminho está correto em relação ao seu notebook.
parquet_path = "dados_processados/base_nacional.parquet"

# 2. Definir as colunas de análise
coluna_municipio = "municipio"
colunas_de_soma = [
    "total_coletas_sangue_total",
]

# 3. Verificar se o arquivo existe e carregar
if not os.path.exists(parquet_path):
    print(f"ERRO: Arquivo não encontrado no caminho: {parquet_path}")
    print("Verifique se o caminho está correto ou se o arquivo foi gerado.")
else:
    try:
        # Carregar o DataFrame
        # O argumento columns= otimiza a leitura lendo apenas as colunas necessárias + a coluna de agrupamento
        cols_to_load = [coluna_municipio] + colunas_de_soma
        df = pd.read_parquet(parquet_path, columns=cols_to_load)
        print(f"DataFrame carregado com sucesso. Total de linhas: {len(df):,}")

        # 4. Agrupar por Município e somar as colunas
        agg_functions = {col: "sum" for col in colunas_de_soma}
        
        municipio_stats = (
            df.groupby(coluna_municipio)
            .agg(agg_functions)
            .fillna(0) # Trata possíveis valores nulos nas colunas de soma
            .reset_index()
        )

        # 5. Calcular a coluna "Total Coletas" (como no seu código Streamlit)
        municipio_stats["Total Coletas"] = (
            municipio_stats["total_coletas_sangue_total"]
        )
        
        # 6. Ordenar e selecionar o Top 50
        municipio_stats = municipio_stats.sort_values("Total Coletas", ascending=False)
        top_50_municipios = municipio_stats.head(5)

        # 7. Exibir o resultado
        print("\n--- TOP 50 Municípios por Total de Coletas (Sangue Total + Aférese) ---")
        
        # Formatação opcional para melhor visualização dos números no notebook
        pd.options.display.float_format = '{:,.0f}'.format
        
        # Exibe a tabela no Jupyter/Pandas
        display(top_50_municipios)

    except Exception as e:
        print(f"Ocorreu um erro ao carregar ou processar o arquivo Parquet: {e}")

DataFrame carregado com sucesso. Total de linhas: 15,865

--- TOP 50 Municípios por Total de Coletas (Sangue Total + Aférese) ---

         municipio  total_coletas_sangue_total  Total Coletas
234  Não se aplica                     2832656        2832656
112       Curitiba                      427623         427623
140      Fortaleza                      339609         339609
294         Recife                      281227         281227
398        Vitória                      246585         246585